### ISSUE TITLE
Add sorting to Summary page

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#1059]
Suggestion: "for sorting I think you want to have an initial sort order that the form builder can specify + ideally the user can then modify using the usual clicking on column headings etc."

Ideally, multiple levels of sorting would be great.

Moved from http://forge.ow2.org/tracker/index.php?func=detail&aid=311140&group_id=168&atid=350207

**Comment by ebruchez** [comment]
[+1 from customer](https://basecamp.com/1721271/projects/3412232/messages/46504063)

**Comment by FatPanther** [comment]
+1 from me too

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/2016743/messages/638540359#__recording_638542218)

**Comment by avernet** [comment]
We should consider using a component like [Handsontable](https://handsontable.com), which will give us, out-of-the-box, a lot of features we'd like to have on the summary page, including the sorting, column recording, filtering, etc.

**Comment by ebruchez** [comment]
[+1 from user](http://discuss.orbeon.com/Order-the-form-builder-summary-td4663819.html) for sorting the Form Builder Summary page.

**Comment by ebruchez** [comment]
+1 from me today

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/29524853/messages/5672583929)

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/29305475/messages/6659347800)

**Comment by obruchez** [comment]
Some limitations in the current implementation:

- control values will be sorted as strings, even if they're numbers (i.e. "1", "10", "11", "2", "20", "21", etc.)
- HTML control values will be sorted using the HTML markup, so the actual text content will not appear as sorted either in some cases

**Comment by obruchez** [comment]
- [ ] integration in customer branch
- [ ] `SearchTest` update
- [ ] doc

**Comment by obruchez** [comment]
https://doc.orbeon.com/form-runner/api/persistence/search#sorting
