### ISSUE TITLE
oxf.xforms.forward-submission-headers to forward original headers

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#1078]
- we have two set of headers
    1. headers sent by the browser when the form is loaded
    2. headers sent by the browser on the Ajax request
- the current behavior is somewhat inconsistent
    - `xxf:get-header-value()` returns from header set 1
    - `oxf.xforms.forward-submission-headers` forwards from header set 2
- this RFE calls for `oxf.xforms.forward-submission-headers` to forward from header set 1
- this would help in cases where a header can be set on page load (proxy or XHR) but can't be easily set again on Ajax requests

**Comment by ebruchez** [comment]
BTW following #1218, there is only one official property, `oxf.http.forward-headers `. `oxf.xforms.forward-submission-headers` is kept for backward compatibility, and the two sets of headers are combined.

The forwarding code is in [`Connection`](https://github.com/orbeon/orbeon-forms/blob/b2ba6f05cd85b93851fcab3a8a3220b9647c6820/src/main/scala/org/orbeon/oxf/util/Connection.scala#L504), where it checks the request.

**Comment by ebruchez** [comment]
We have as similar issue with the XPath user functions: `xxf:username()`, etc. which are based on the incoming headers, as they call the `ExternalContext`.

**Comment by ebruchez** [comment]
[+1 from customer](https://basecamp.com/1721271/projects/6774292/messages/47184896#comment_329074758)

**Comment by ebruchez** [comment]
Uses of `buildConnectionHeadersLower`:

```
buildConnectionHeadersLowerIfNeeded                   |
  FormRunnerPersistence.readDocument                  | request
    readPublishedForm                                 | request
      ReindexProcessor                                | request
    readFormMetadata                                  | request
      existdb.Permissions.checkPermissions            | request
      CRUD.change/get                                 | request
  FormRunnerPersistenceProxy.proxyEstablishConnection | request
  HttpRequest.request                                 | request [test]
  PDFTemplateProcessor                                | ??? request
    handleImage                                       | ??? request
  Connection.jBuildConnectionHeadersLowerIfNeeded     |
    URIProcessorOutputImpl.readURLToStateIfNeeded     | ??? request
    URLGenerator.openConnection                       | ??? request
    XHTMLToPDFProcessor                               | ??? request
    XFormsModel.loadNonCachedExternalInstance         | XFCD
  XFormsResourceServer.proxyURI                       |
    ... XForms                                        | XFCD
    FileSerializer                                    | ??? request
  SubmissionUtils.openGETConnection                   | XFCD
    processGETConnection                              | XFCD
      SubmissionUtils.readByteArray                   |
        XFormsModelSubmission                         | XFCD
      readTinyTree                                    |
        ... XFormsServerSharedInstancesCache          | XFCD
buildConnectionHeadersLowerWithSOAPIfNeeded           |
  ConnectionTest                                      | request [test]
  BaseSubmission.openLocalConnection                  | XFCD
  EchoSubmission                                      | XFCD
  RegularSubmission                                   | XFCD
```

**Comment by ebruchez** [comment]
One solution would be, at the level of `buildConnectionHeadersLower`, to decide which strategy to use based on the presence of an in-context `XFormsContainingDocument`. If present, pass a function getting headers from it, otherwise a function getting headers from the request. Function signature:

```scala
String ⇒ Option[List[String]]
```

Problem is that with internal requests, a `XFormsContainingDocument` might be in scope right now when it shouldn't be.

Another option would be to pass `String ⇒ Option[List[String]]` down the chain explicitly.

**Comment by ebruchez** [comment]
Next step: create list of scenarios to make sure that we get proper header forwarding from the "sticky" headers in `XFormsContainingDocument `.
