### ISSUE TITLE
Stable API for Form Runner

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#1095]
Right now we call Java/Scala directly. This doesn't make it very clear what is part of a stable API or not.

Initial candidates:

- [x] `fr:mode()`: Form Runner mode
- [x] `fr:is-readonly-mode()`: `fr:mode() = ('view', 'pdf', 'email')`
- [x] `fr:is-design-time()`: whether we are within Form Builder (very useful for XBL components)
- [x] `fr:is-noscript()`
- [x] `fr:app-name()`: Form Runner app
- [x] `fr:form-name()`: Form Runner form- [x] `fr:form-version()`: current form definition version
- [x] `fr:form-version()`: current form definition version
- [x] `fr:document-id()`: Form Runner document id
- [x] `fr:run-process-by-name(process)`
- [x] `fr:run-process(process)`
- [x] `fr:lang()`: current form language
- user information  (implemented as `xxf:` with #2063)
  - [x] `fr:username()`
  - [x] `fr:user-group()`
  - [x] `fr:user-roles()`
- [x] `fr:is-form-data-valid()` (note issue of dependencies)
- [x] `fr:is-form-data-saved()`: whether the data was saved, or is "dirty"

Issue: there is currently no mechanism to add an XPath function library dynamically. We would need such a mechanism, or add the Form Runner library to all XForms pages, which not quite ideal.

**Comment by avernet** [comment]
[+1 from community](http://stackoverflow.com/questions/35928129/can-i-check-if-the-form-is-dirty-in-a-custom-process-or-with-javascript) for `fr:form-data-saved()`

**Comment by ebruchez** [comment]
Steps:

- [ ] figure out how to register the FR function library for Form Runner only
- [ ] implement functions as needed

**Comment by ebruchez** [comment]
So how to provide a function library without the XForms engine depending on it? Options:
 
1. "Push": Some external code, when creating an XFCD, passes an instance of the function library.
2. "Pull": Use a new property, like `xxf:function-library="org.orbeon.oxf.fr.library.FormRunnerFunctionLibrary"`.

The "push" solution doesn't work great currently as the XFCD is created from the general-purpose `XFormsToSomething`. If/when called from an XForms API, as we might have in the future in the browser (#1221), this could work.

The "pull" solution will work better for now, but will require use of reflection to load the function library, so won't work on the client. But there we can switch to a "push" solution.

So voting for "pull" for now.

**Comment by ebruchez** [comment]
The interface could be:

- XForms calls `instance()` method, so 'org.orbeon.oxf.fr.library.FormRunnerFunctionLibrary.instance()'
- must implement `org.orbeon.saxon.functions.FunctionLibrary`

**Comment by ebruchez** [comment]
Created separate issue #2812 for XForms engine configuration.

**Comment by ebruchez** [comment]
[Documented](http://doc.orbeon.com/xforms/xpath/extension-form-runner.html)

**Comment by ebruchez** [comment]
Had put this function but it's unclear what it should do:

- [ ] `fr:is-form-data-from-autosave-draft()`: whether the current data was read from an autosave draft
