### ISSUE TITLE
Summary/Home to show timestamps in a configurable timezone

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#1101]
Right now, the UTC timezone is used. This RFE calls for making that timezone configurable, e.g. "America/Los Angeles" (not an offset).

One step further, not covered by this RFE, would be to allow users to set their timezone, just like they can set their language.

**Comment by ebruchez** [comment]
+1 from customer.

Suggesting adding a Form Runner property to specify the timezone. If it is present and valid, use that, otherwise default to the current behavior.

At some point, there could be a timezone associated with a user profile.

**Comment by ebruchez** [comment]
Using `adjust-dateTime-to-timezone(xs:dateTime(@created))`, which is what we do now, appears to adjust the timezone to the system's default timezone (`-08:00` in my case). Checking, this appears to be [correct per the spec](https://www.w3.org/TR/xpath-functions-31/#func-adjust-dateTime-to-timezone).

Using `adjust-dateTime-to-timezone(xs:dateTime(@created), ())`, the timezone information in the `dateTime`, if any, is simply removed.

My understanding is that `format-dateTime` does not change timezone information at all. It just looks at the components of the `dateTime` that are passed.

**Comment by ebruchez** [comment]
We have a `oxf.fr.default-language` property. I suggest `oxf.fr.default-timezone`.

**Comment by ebruchez** [comment]
[Documented](https://doc.orbeon.com/configuration/properties/form-runner#timezone)

**Comment by ebruchez** [comment]
- [ ] support passing a timezone by name
- [ ] update doc

**Comment by ebruchez** [comment]
I noted in the code review that using offsets would not handle daylight saving. So we decided to use zone ids instead. Those will handle daylight saving. I think that we only need to support zone ids and not offsets. But if we need offsets we can add that in the future.
