### ISSUE TITLE
Rename save and save-draft processes

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#1139]
Right now, our use of the word "draft" in the `save-draft` process is not consistent with its meaning as it relates to the autosave functionality. We should rename:
- rename the `save` process to `save-validate`
- rename the `save-draft` process to `save-no-validate`

**Comment by acspike** [comment]
I recently fell into this very same confusion, though rather than simply making the names less confusing I would rather see the functionality changed to make non-validated drafts a first class citizen as I believe this is a common workflow.

**Comment by ebruchez** [comment]
Still not done as of now.

**Comment by ebruchez** [comment]
- [ ] finalize process name
- [ ] doc

**Comment by ebruchez** [comment]
Suggesting renaming the explicit "Save Draft" to "Save Progress" with a `save-progress` process.

**Comment by ebruchez** [comment]
Check if this regression is due to this change (shouldn't be):

<img width="1001" alt="Screen Shot 2021-05-17 at 3 54 15 PM" src="https://user-images.githubusercontent.com/105769/118566252-7259e180-b728-11eb-8351-7d9306e45481.png">

**Comment by ebruchez** [comment]
[Documented](https://doc.orbeon.com/form-runner/advanced/buttons-and-processes/predefined#predefined-buttons)
