### ISSUE TITLE
Initial values don't work for new repeat iterations

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#1148]
See repro case:

https://gist.github.com/ebruchez/6084856

Fix could be:

- at XForms level (might be subtle)
- at FB level (apply initial value calculation to template too, but how)

Either way it's not trivial.

An easier but partial solution for constant values would be to copy the static default value of the control to the repeat template. In fact this should be done anyway (#2257).

**Comment by avernet** [comment]
[+1 from Twitter](https://twitter.com/CoximusMaximus/status/580355726251540480)

**Comment by ebruchez** [comment]
It would be better to do it at the XForms level.

Right now, we process `xxf:default` expressions:

1. The first time there is a `recalculate` on the model.
2. If the `xf:recalculate` action passes `xxf:defaults="true"`.

The new logic would be that a newly inserted XML subtree into an instance would also receive initial values. The question is: how does the code know this?

We could have an `uninitialized` flag, cleared after a value has been set, or an `initialized` flag, set once a value has been written.

Upon rebuild, we already clear instance data with `InstanceData.clearState`. I think this would argue in favor of the following algorithm:

- upon insert/instance replacement
  - mark all the nodes of the newly inserted tree with `uninitialized`
  - set a model flag called `needsInitialValues`
- upon `rebuild`
  - rebuild doesn't clear the `uninitialized` flag in instance data, but as before clears the other state
- upon `recalculate`
  - if `needsInitialValues` is `true`
    - run default values
    - but only on nodes which have `uninitialized`
    - then clear the `uninitialized` flag on the given nodes in case of success
  -clear `needsInitialValues` and clear all `uninitialized` flags

One question is whether/when to clear the `uninitialized`. If we insert a new XML subtree, should we keep checking, at each recalculate, the `uninitialized` flags? Or do we consider that the `uninitialized` is relevant only until the next `recalculate`? This only has impact if binds can touch nodes after the first `recalculate`, which doesn't happen with Form Builder forms, for example.

**Comment by ebruchez** [comment]
OTOH we need an `xxf:defaults` flag for `xf:insert` and `xf:submission` or `xf:send`, as we don't want to have initial values to run when:

- new form data is posted to the form
- new form data is loaded from the database

Also for backward compatibility, the default might still have to be `xxf:defaults="false"`, and `xf:grid` and `xf:repeater` would use `xxf:defaults="true"`.

**Comment by ebruchez** [comment]
[+1 from customer](https://basecamp.com/1721271/projects/8001401/messages/39936053#comment_289057167)

**Comment by FatPanther** [comment]
+1 from me as well, although our issue would be resolved by having static default values copy to the repeat template, as Erik mentioned in the first comment.

**Comment by ebruchez** [comment]
@FatPanther I agree and I have entered issue #2257 to track the static case. That one should be reasonably easy to do.

**Comment by ebruchez** [comment]
Updating my comment above: it turns out that #2257 is not that easy to do after all.

**Comment by ebruchez** [comment]
Noticing an issue: `fr:grid` implements moving iterations with `xf:delete` then `xf:insert`. But we wouldn't want a move to trigger `xxf:initial` re-evaluation.

**Comment by ebruchez** [comment]
Also need to handle backward compatibility in FB/FR for older forms which don't expect this behavior.

If this is enabled at the form level, see #2239. We would make this the default for new forms, but keep the behavior for existing forms.

If we do it per grid/section, this would be an attribute on the grid/section. FB would now by default put this attribute on new grids/sections, but existing grids/sections would keep the current behavior.
