### ISSUE TITLE
Namespace our version of jQuery

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#1155]
Some sites use their own version of jQuery with potential conflicts of the `$` and `jQuery` definitions.

See http://api.jquery.com/jQuery.noConflict/

Questions:

- What convenient global definition could we use?
- When do we actually need a global definition?

**Comment by avernet** [comment]
- [ ] We would like XBL components, in particular custom ones, to be able to use their own version of jQuery. This means that only calling `$.noConflict(true)` after all the JavaScript is loaded wouldn't work. Instead, we should call `$.noConflict(true)` right away, save the result in a global variable, and in every JavaScript locally initialize `$` using this global value.

**Comment by ajw625** [comment]
I see this is closed with a fix, but there is no milestone. Was this included in 4.8.1?

**Comment by avernet** [comment]
@ajw625 It will be in 4.9. I justed updated the milestone on this issue.
