### ISSUE TITLE
Placeholder lost when control type changes or in repeat

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#1175]
To reproduce, use the example in this [mailing list message](http://goo.gl/GxUJCl). This will be most likely fixed with the changes we are working on now for #1081.

Also the placeholder doesn't show in new repeat iterations.

**Comment by ebruchez** [comment]
This happens in Form Builder's actions. The repeat template is:

```html
<span id="xf-986≡xf-4571≡xf-4651" class="fb-action-option-2-col-span-1 xforms-control xforms-input xforms-incremental">
    <label class="xforms-label xforms-label-appearance-minimal" for="xf-986≡xf-4571≡xf-4651≡xforms-input-1"></label>
    <input id="xf-986≡xf-4571≡xf-4651≡xforms-input-1" type="text" name="xf-986≡xf-4571≡xf-4651≡xforms-input-1" value="" class="xforms-input-input">
    <span class="xforms-alert"></span>
</span>
```

Curiously, there is a `<label>` element with `xforms-label-appearance-minimal`. There probably shouldn't be this element at all.

**Comment by ebruchez** [comment]
Moving this comment from #3238.

See screenshot.

![screen shot 2017-06-05 at 4 02 45 pm](https://cloud.githubusercontent.com/assets/105769/26807070/f9431afe-4a08-11e7-8e27-8b552411b63e.png)

**Comment by ebruchez** [comment]
`placeHolderValueOpt` requires a concrete control, which explains why the template is probably wrong. Although, we need a way to know when copying from the template. What about:

- if the template has a `placeholder` attribute, we know it's either for a label or hint
- wen setting a label or hint value, if the element doesn't exist but the placeholder exists, we know we must update the placeholder

**Comment by ebruchez** [comment]
- [ ] fix template output
- [ ] fix client-side update
- [ ] check fixes Form Builder
- [ ] check fixes `fr:us-phone`
