### ISSUE TITLE
Good-looking upload button

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#1238]
Having a better looking and more compact upload control, cross browsers, would be really good. Chrome/Safari have a selection button, which makes sense. Firefox, up to recently, and IE, have the 1990s-style input field.

But nowadays, with enough CSS and JS hacks, it's possible to do better (like the Gmail and Basecamp uploads, which are pretty nice).

Twitter Bootstrap does not address this, unfortunately.

Requirements:
- must look good and consistent across modern browsers
- must properly scale in Form Runner grids

Also requested by client.

**Comment by ebruchez** [comment]
See also [these examples](https://blueimp.github.io/jQuery-File-Upload/angularjs.html).

**Comment by ebruchez** [comment]
With Bootstrap 3/4, it is very easy to do a basic button, see [this site](https://www.abeautifulsite.net/whipping-file-inputs-into-shape-with-bootstrap-3) and the answer by the same guy on [StackOverflow](https://stackoverflow.com/questions/11235206/twitter-bootstrap-form-file-element-upload-button):

```html
<label class="btn btn-default btn-file">
    Browse <input type="file" style="display: none;">
</label>
```

**Comment by ebruchez** [comment]
This styling also works with our version of Bootstrap. We would need:

- [ ] to modify the markup of `xf:upload`
- [ ] when the file is selected, make sure the button becomes hidden (as it does now)

See also #1011.

**Comment by ebruchez** [comment]
Here the immediate use case is for #3316. The current control looks awful in the grid cell.

**Comment by avernet** [comment]
This is also a localisation issue, since the default button shows a message like "Choose File" using the browser's language, not the current Form Runner language.

[+1 from customer](https://3.basecamp.com/3600924/buckets/1966556/messages/2318328408)

**Comment by ebruchez** [comment]
Two issues I see:

- You can no longer tab to the "Select file" button.
    - Previously you could tab and press space to open the file selector.
- You can no longer drop a file on the upload.
    - This was standard browser behavior, although I don't know if many users know about it.
    - We might be able to restore this by making the control support file drops programmatically.

**Comment by avernet** [comment]
The new button is now again accessible through the keyboard (and has the expected annotations for screen readers), so you can tab to the button, and press enter or space to open the selector. And we can use #1096 to track the implementation of drag & drop.
