### ISSUE TITLE
XForms inspector breaks FB presentation

### ISSUE THREAD

**Issue by evlist** [orbeon/orbeon-forms#1254]
When the XForms inspector  is activated, an instance is displayed above Form Builder's toolbar!
![capture du 2013-09-13 10 31 55](https://f.cloud.github.com/assets/109022/1136864/02eab1ca-1c4f-11e3-8e6a-562b522a81eb.png)

**Comment by avernet** [comment]
[+1 from community](http://discuss.orbeon.com/Inspector-corrupts-builder-screen-td4659826.html)
