### ISSUE TITLE
reCAPTCHA: 

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#1284]
When loading the script from `google.com` (`http://www.google.com/recaptcha/api/js/recaptcha_ajax.js`), the widget shows incorrectly:

![screen shot 2013-09-23 at 11 35 07 am](https://f.cloud.github.com/assets/106961/1194051/eb6b3f64-247e-11e3-9ea9-19b318aa676c.png)

This instead of:

![screen shot 2013-09-23 at 11 33 34 am](https://f.cloud.github.com/assets/106961/1194042/aa14b248-247e-11e3-83b2-263820dadde6.png)

This can be fixed by removing the margin:

![screen shot 2013-09-23 at 11 34 31 am](https://f.cloud.github.com/assets/106961/1194058/00e2074c-247f-11e3-8fc8-a32cd628909b.png)

And the height on the input set by Bootstrap:

![screen shot 2013-09-23 at 11 34 54 am](https://f.cloud.github.com/assets/106961/1194064/0eca2a2e-247f-11e3-99e9-2a5431c72660.png)

This is something we can take care once #1271 is fixed.

**Comment by ebruchez** [comment]
Probably an obsolete bug. Closing.
