### ISSUE TITLE
Annotation control doesn't scale image

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#1312]
Right now it doesn't seem to scale the image, as it was intended to. This was implemented by doing changes to wPaint 1.x (which apparently don't seem to be working anymore). We should try upgrading to [wPaint 2.x](https://github.com/websanova/wPaint), which might now implement this out-of-the-box. [Reported by @ThomasPot](https://twitter.com/ThomasPot/status/385344391646543872).

**Comment by avernet** [comment]
[+ 1 from community](http://discuss.orbeon.com/Annotation-control-doesn-t-scale-image-1312-td4660002.html)

**Comment by ebruchez** [comment]
@avernet Something to consider for 4.10 maybe?

**Comment by open2bizznl** [comment]
Hi,
The (temporary) removal of this control could be a real blocker to upgrade to 4.11
Is there an ETA or milestone when this will be fixed (Wpaint 2)?

**Comment by avernet** [comment]
@open2bizznl If the control works for you as-is, you can add it back to the sidebar very easily. It is just a matter of adding one line to `properties-form-builder.xml`: see 56dd3f024bb76ad6b6d3daa2ad8684d38aa2c564. We haven't removed the component itself, and it will just work for you in 4.11 as it did in the past. Does this make sense?

**Comment by open2bizznl** [comment]
@avernet Thanks for answering. Does one need to build/compile Orbeon from sources if one requires changes in `property-form-builder.xml` Or what does it involve?

Greets, Bob

**Comment by avernet** [comment]
@open2bizznl No need to recompile. The file is inside `WEB-INF/lib/orbeon-resources-private.jar`. The easiest is to extract it from there, do your change, and place the updated version in `WEB-INF/resources/config`, and that version will override the one in the jar.

**Comment by open2bizznl** [comment]
Any plans for this issue in the roadmap? - It's not assigned to a milestone anymore.

**Comment by ebruchez** [comment]
@open2bizznl No current plan. Do you have an urgent need for this fix?

**Comment by open2bizznl** [comment]
@ebruchez Yes indeed, we really would like this control to work as expcected.
What's the policy/procedure to get this on plan?

**Comment by avernet** [comment]
We tentatively add this one to the next milestone.

**Comment by open2bizznl** [comment]
Thanks, you're great.
Really appreciate it!
