### ISSUE TITLE
RFE: Warn if multiple users are working on the same form

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#1332]

**Comment by avernet** [comment]
[+1 from community](http://discuss.orbeon.com/How-to-prevent-multiple-users-from-having-concurrent-access-to-a-form-instance-td4660113.html)

**Comment by ebruchez** [comment]
We have more details on #1067, so closing this one as duplicate.

**Comment by avernet** [comment]
[+1 from customer](http://discuss.orbeon.com/Orbeon-persistence-API-telling-if-a-GET-is-for-view-or-edit-td4661154.html)
