### ISSUE TITLE
Relational persistence: must return empty result if no authorization

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#1383]
See #1382 for details.

Based on the code right now, it seems that this will instead return a SQL error because of the:

```
AND ()
```

Make sure this is done with the new persistence layer code in Scala.

**Comment by avernet** [comment]
On Oracle, the `AND ()` leads to an `ORA-00936`.

[+1 from customer](https://basecamp.com/1721271/projects/5063202/messages/54001872)

**Comment by avernet** [comment]
For a customer, this happened on a system where everything was working earlier. An incorrect change had been made to their SSO, which had as a result that the role header wasn't passed anymore to Orbeon Forms.
