### ISSUE TITLE
Retry properties need to be global

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#1391]
The properties are:
- `oxf.xforms.delay-before-ajax-timeout`
- `oxf.xforms.retry.delay-increment`
- `oxf.xforms.retry.max-delay`

They are used (at least the first two) by the server to determine when it's not worth waiting any longer on the document lock, and the server can safely return an error to the client, who by then is "known" to have closed the connection.

Since the server cannot access the document (it's waiting on a lock on the document), those properties can't be document-specific.

**Comment by ebruchez** [comment]
Checked that this is still the case.
