### ISSUE TITLE
Versioning: summary page must be aware of form versions

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#1435]
Right now it uses the latest form definition to retrieve information about all the forms, some of which might have been created with earlier versions, and thus not have values for some of the fields present in the last form definition.

We could:
1. Make the summary page version-specific, defaulting to the latest version, and allowing another version to be selected. However, splitting data by form version might not make sense to those accessing the summary page, and if there are lots of form versions might force them to go through each version to see all the data.
2. Similar to 1, but instead of having the information for different versions shown on different "pages", they would all be shown on the same page, with one table following the other. However, if there are many versions, this could create a lot of tables, and make the summary page slow to load. Also, grouping the form data by form version might not make sense to users.
3. Showing all the data in one table, as done now, but instead of having separate columns for each one of the fields marked as showing in the summary page, have just one generic column for all those fields, repeat the label of each field in every row (e.g. grayed and smaller above the field value), and combine all the labels/values to display in that field.

**Comment by ebruchez** [comment]
- [ ] read versions
- [ ] set version based on URL parameter if needed
- [ ] dropdown to select version
- [ ] read form definition based on version
- [ ] call search API based on version

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/2010455/messages/1432062827)
