### ISSUE TITLE
Form Builder summary page: show title and description in all languages

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#1459]
This, as we do when editing a form:

- One language selector impacts picks the language used by FR/FB (on the summary page, this would impact all the resources except for the content of the table).
- The other language selector picks the language of the form we're editing (on the summary page, this would impact the language of the form title and description shown in the table).

**Comment by ebruchez** [comment]
RESOLUTION: Form definitions titles/descriptions are not affected by the language selector in the Form Builder Summary page, and we:

- display the value in the first language only
- or display a concatenation of the values when there is more than one

**Comment by ebruchez** [comment]
This will change with work on #649.

@avernet to also check that it works the same way with eXist.

**Comment by ebruchez** [comment]
Seems to work as expected, see screenshot.

![screen shot 2016-07-01 at 2 04 57 pm](https://cloud.githubusercontent.com/assets/105769/16534472/d6cf7528-3f94-11e6-88c3-a99cc3a57ecc.png)
