### ISSUE TITLE
When clicking the PDF button, changes sent in the same Ajax request are not included in the PDF

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#1466]
To reproduce, load the [Bookshelf form](http://localhost:8080/orbeon/fr/orbeon/bookshelf/new), type "a" in the "title" field, tab, type "a" in the "author" field, then click on PDF. Note that the "a" in the "author" field is not shown in the PDF.

This sounds similar #1397, but might be a different problem.

**Comment by ebruchez** [comment]
Closing #3107 as duplicate.

What I wrote about this:

> When you tab out of a modified field, an Ajax request is sent to the server to update the data model. When you click on the PDF button, that goes through a separate path which might reach the model first and so the latest change in the UI is not yet available.

[+1 from customer](https://3.basecamp.com/3600924/buckets/1932446/messages/329479076)

**Comment by ebruchez** [comment]
Keep for 2017.1 for customer.

**Comment by ebruchez** [comment]
Possible next steps:

- Check if evergreen browsers still prevent link navigation upon Ajax response.
- Check if there are newer download APIs in browsers.
- Workaround could be to open a dialog upon PDF button, dialog would  contain link.
- Idea: link would contain `?seq=123`, where this is the seq of the Ajax request, if any, which contains the changes to the fields upon focusing out.
  - Server would check that Ajax request arrived, if not synchronously wait a little bit for that request to be processed.
  - Is it possible, in JS, upon click on link, to update link? Or would we know the sequence id beforehand and update it in the `<a href>`?

**Comment by avernet** [comment]
Inline with the first bullet point in Erik's message, I am checking what browsers prevent a download done from JavaScript running as the result of an Ajax query sent based on an action the user performed. For this, I am using an `xf:trigger` running `xf:submission replace="all"` with a URL that serve a file. The download:

- 💔 Fails with IE8: the browser shows a banner "To help protect your security…"
- 💚 Works with IE9, IE10, IE11, Edge
- 💚 Works with Chrome 58, Firefox 52
- 💚 Works with Safari on iOS 10.2, Chrome on Android 7

Since with 2017.1 we won't support IE8 anymore, we can now "simply" use a `xf:submission replace="all"` to serve the file.
