### ISSUE TITLE
Ability to move controls with drag and drop

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#1479]
In certain cases, maybe most cases, using drag and drop would be faster than cut and paste (which is currently the way to move controls in Form Builder).
## Implementation
- Technical difficulties
  - What happens in the UI between the user performed the D&D and the time the UI is updated?
    - Possible solutions
      - Block the UI just for that cell
        - Could not be enough if the server sends us the full HTML for that section
      - Block the entire UI (e.g. with the current spinner)
      - Any other way?

**Comment by avernet** [comment]
Added a section about the implementation, and technical difficulties.

**Comment by ebruchez** [comment]
I wouldn't want to see the current modal spinner. It's too heavyweight, and the UI would flash constantly.

Ideally, right after the "drop", the builder's response would come quickly (say <= 200 ms), so this wouldn't be a problem as long as we don't flash the UI.

A visual highlight of the drop area should indicate that something is happening. If it takes longer, some additional visual indication would be good. We have a "Loading" indicator, but it doesn't work very well.

As far as preventing further user actions until the drop has completed: is there any user action, in the whole of the builder, which makes sense as the builder UI updates? Maybe if the user clicks on the "Save" button (or other things like that), that action could just be queued as usual?

**Comment by ebruchez** [comment]
[+1 from evaluator](https://mail.google.com/mail/u/0/#inbox/14e7553141c64ab1)

**Comment by avernet** [comment]
When getting to this, we should check if [Dragula](https://github.com/bevacqua/dragula) can help.

**Comment by ebruchez** [comment]
[+1 from customer](https://basecamp.com/1721271/projects/11908529/messages/57428177)

**Comment by ebruchez** [comment]
A few more thoughts on the design.

Where we would like DnD in a first implementation?

- Insert controls/grids/sections from the toolbox to a grid cell.
    - Q: Is this a UI we want?
    - There are other options, such as 1. select tool/objet 2. mouse click places the object (common in graphical tools, with kbd shortcuts for tool selection)
- Move controls between grid cells
    - I think this one is a must have.
- Reorder grids/sections
    - I think this one is a must have.
- Extend cell/control (rowspan).
    - If so we can remove need for extend/collapse arrows.
- Nest/unnest section
- Move grids/sections to other sections

For a good UX:

- need clear indications that a drag action is possible (drag handles upon hover?)
- when dragging, need clear indication of where objects are moved to

Other ideas:

- The client initiates drag without the server's intervention.
- When user drops, then the server is notified of the action.
- This raises the question of what happens just after the drop: is there a delay while the server figures out what to tell the client about the move? How can we make this smooth?

**Comment by ebruchez** [comment]
Unfortunately getting a bit close already to the end of June release for 2016.2. Most likely this one won't cut it.

**Comment by ebruchez** [comment]
Suggestion from [user](https://basecamp.com/1721271/projects/3641011/messages/52147685#comment_430678304): when moving items which are far apart, some other way of moving might be better, such as offering a "move to" menu which allows selecting a destination.

**Comment by ebruchez** [comment]
[+1 from customer](https://mail.google.com/mail/u/0/#inbox/1562652535c246be)

**Comment by ebruchez** [comment]
Just bumped on [Dragula](https://bevacqua.github.io/dragula/) again.

**Comment by avernet** [comment]
Dragula certainly has a good name going for it.

**Comment by avernet** [comment]
Next:

- [ ] Get one case of d&d to happen in Form Builder, at first without information sent to the server.

**Comment by ebruchez** [comment]
Moving given tentative workflow prioritization.

**Comment by ebruchez** [comment]
See also #2461. We now have some experience with drag and drop so we should be able to do this fairly easily.

To address @avernet's initial questions above:

> what happens in the UI between the user performed the D&D and the time the UI is updated

Like for `fb:dnd-repeat` and `fr:tabbable`, we could do this:

- an `xforms-dnd` event is dispatched immediately to the server
- we don't block the UI for now, but we could do so if absolutely needed
- as soon as an Ajax response comes in, we move back the element to its original location in the DOM
- then the Ajax response handles the actual update of the DOM

The idea is that the user shouldn't see too much flickering of the UI event if the server takes, say, a second to respond.

**Comment by avernet** [comment]
#1479 We have now a first working version of this feature implemented. Before we can call it done, however, we want to:

- [ ] In Form Builder's `model.xml`, don't do a copy/cut, then paste, so not to replace what the user might have put in the clipboard.
- [ ] Replace the "anchor" by another icon more evocative of a "move" action.
- [ ] During the D&D, don't show the action icons as part of the "control" we are moving.
- [ ] If possible, when shift is pressed to indicate we're doing a copy, leave the control visible in the source during the D&D.

**Comment by avernet** [comment]
The proper CSS doesn't apply to the control. In Scala.js, we defined the container as `.fr-grid-td`, but the `div` moved, called the "mirror" is the `.fb-hover`, that is: the child of the container. The problem is that the mirror is created as a child of `document.body`, and so the appropriate CSS doesn't apply anymore. Overriding `mirrorContainer` to point to the first actual `.fr-grid-td` in the form solves the CSS selector problem.

**Comment by avernet** [comment]
We don't want to show the "action" icons in the control we're moving. Hiding those icons when inside `.gu-mirror` (block that moves with the mouse cursor) and `.gu-transit` (block that goes to the appropriate container when moving) does the trick.

**Comment by ebruchez** [comment]
Icon hover shows "Delete Control". Also, should the mouse pointer be different upon hover?

<img width="468" alt="screen shot 2017-07-07 at 3 14 15 pm" src="https://user-images.githubusercontent.com/105769/27959296-24391100-6327-11e7-9740-17228b8d4320.png">

**Comment by avernet** [comment]
I’ve done the 2 fixes/changes per the last comment, i.e. having an appropriate tooltip on hover, and more telling mouse pointers before and during D&D.

**Comment by avernet** [comment]
A couple more things to do:

- [ ] Document, and in particular mention how the form author can copy using the shift key
- [ ] When doing a copy, fix flickering of the transit block in the target cell
- [ ] During D&D, the transit block seems to take more vertical space, and the height narrows when after the control is dropped

**Comment by avernet** [comment]
I am closing this, since all the issues and remaining tasks related to this have been done. And of course, we can reopen this issue, or create other issues, in case we find any new problem.

**Comment by avernet** [comment]
Indeed, I'm now also getting what looks to be same issue reported by Erik, that is: the control D&D "not working". I'm looking into it, but somehow changes I do to the source don't seem to have any effect, which doesn't make debugging this easy ;); there must be something I'm overlooking, or something in build that I'm missing. Will go over this with Erik on Wednesday.

**Comment by ebruchez** [comment]
Are you missing a `fastOptJSToExplodedWar`?
