### ISSUE TITLE
Consider moving away from Flying Saucer

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#1498]
The Flying Saucer library sees a few patches here or there, but is not actively maintained, and has not seen a release in a long time.

Some alternatives:
- [wkhtmltopdf](https://code.google.com/p/wkhtmltopdf/)
  - free
  - uses WebKit
  - last release early 2012
  - but github repo active
- Prince (Prince XML)
  - very expensive ($3,800/server)

It seems unlikely that we'll find a JVM-based solution.

**Comment by aninditaghtk** [comment]
Is it safe to use Flying Saucer in current project?

**Comment by avernet** [comment]
@aninditaghtk What do you mean by "safe" and "current project"? Could you provide us with some background for your question?

**Comment by aninditaghtk** [comment]
Hi Alessandro,
Thanks for replying.Currently I am trying to creating a framework to generate pdf from xml using open-sourced tools.My approach is convert xml to html and then convert html to pdf using Flying Saucer.I have seen that Flying Saucer is last updated by google in 2011.So I am thinking will it be safe to use the same or not.Can you please suggest me.

Thanks & Regards,
Anindita

**Comment by ebruchez** [comment]
@aninditaghtk Your question doesn't seem to be related to Orbeon Forms so I don't think we can help much. The bottom line is that it is really up to you. But as mentioned above, see [this repo](https://github.com/danfickle/neoflyingsaucer) which has picked up some development.

**Comment by aninditaghtk** [comment]
Hi Alessandro,
Can flying saucer maven dependency cause memory leak?

Thanks & Regards,
Anindita

**Comment by ebruchez** [comment]
@aninditaghtk In Orbeon Forms we use Flying Saucer and haven't experienced leaks.

**Comment by ebruchez** [comment]
@danfickle's latest developments are now at https://github.com/danfickle/openhtmltopdf.

**Comment by ebruchez** [comment]
`openhtmltopdf` appears to be still under development. We should give it a try. Steps:

- [ ] download artifacts
- [ ] do a basic hookup of the library and run our forms through it to evaluate whether the code is in a usable state

**Comment by ebruchez** [comment]
[PDFreactor](http://www.pdfreactor.com/) would be a commercial alternative worth integrating with.

**Comment by ebruchez** [comment]
See this [reddit question](https://www.reddit.com/r/scala/comments/788ymb/help_need_to_create_pdfs_based_on_html_template/) as well, which mentions [athenapdf](https://github.com/arachnys/athenapdf).

**Comment by ebruchez** [comment]
There has been recent activity on openhtmltopdf for [PDF/UA](https://github.com/danfickle/openhtmltopdf/issues/79) in particular.

**Comment by ebruchez** [comment]
I notice that, independently from openhtmltopdf, Flying Saucer had a few [releases](https://github.com/flyingsaucerproject/flyingsaucer/releases) since our version.

[+1 from customer](https://3.basecamp.com/3600924/buckets/7873395/messages/1657482961#__recording_1661706516) for having support for `nth-child`, which was introduced soon after our version.

**Comment by ebruchez** [comment]
It would be good, as a first step, to integrate openhtmltopdf as a separate renderer in parallel with the current renderer, so we can experiment and compare results.

**Comment by ebruchez** [comment]
See also #4454 which would benefit from SVG support.

**Comment by ebruchez** [comment]
Also [+1 from customer](https://3.basecamp.com/3600924/buckets/2016476/messages/4768207940) in the context of producing accessible PDF files.

**Comment by ebruchez** [comment]
We are now integrating #5342 to use https://github.com/danfickle/openhtmltopdf. This is not an ideal solution but this way at least we benefit from an updated code base and more bug-fixes.

**Comment by ebruchez** [comment]
- [ ] fix cut off right control border in some cases (Controls form)
