### ISSUE TITLE
Liferay 6.2 support

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#1528]

**Comment by ajw625** [comment]
In Liferay 6.2, adding the proxy-portlet to a page initially causes an error. The error message briefly flashes on the screen and then is hidden for some reason. I was able to take a screenshot while it was briefly visible. As the error message recommends, reloading the page makes the error go away. This only seems to occur when the portlet is first added to a page.

Error:
![error adding proxy portlet to page](https://cloud.githubusercontent.com/assets/9143532/6716105/49cde404-cd60-11e4-8a02-8137737e1814.png)

Then it's hidden:
![proxy portlet error hidden](https://cloud.githubusercontent.com/assets/9143532/6716270/78755a5c-cd61-11e4-9a78-8c3694de02f5.png)

**Comment by ebruchez** [comment]
This looks like a [FOUC](https://en.wikipedia.org/wiki/Flash_of_unstyled_content).

**Comment by ajw625** [comment]
It does look like FOUC. I'm not sure why the content ends up hidden. I didn't delve into that too far.

A correction to my last comment: this does not just occur when first adding the portlet to a page. If  I come back to the page after not accessing it for maybe an hour or more this occurs again but is fine after a refresh.

**Comment by ebruchez** [comment]
It might be depending on whether it's in the browser cache and/or the timing of the loading of CSS.

One solution (and I thought we had something like this) might be to have inline style which makes sure that  the content is initially hidden.

**Comment by ebruchez** [comment]
c7a98d59df68c618c07b1cb07105b7cc9ce3cd00 sets `<requires-namespaced-parameters>false</requires-namespaced-parameters>` by default for 4.11.

**Comment by ebruchez** [comment]
So things work in Liferay 6.2, but the CSS is off. Entering #2728 for that.

**Comment by ebruchez** [comment]
With full portlet, while testing for 2016.2 (where 6.2 is still not officially supported), PDF doesn't seem to work with stock 6.2.

**Comment by ebruchez** [comment]
Closing as we officially support Liferay 6.2 now.
