### ISSUE TITLE
Client-side embedding

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#1577]
This would provide a way for users to embed a form created with Form Builder into an existing site.

- [x] Framework-neutral JavaScript API to perform the embedding
    - [x] Implementation of `ORBEON.fr.API.embedForm({ container: HTMLElement, app: String, form: String, action: "new", documentId: string, queryString: string })`
    - [x] Solve error happening when loading the 2nd form, after an initial load
    - [x] Reduce memory leaks (right now we leak a few MB each time a form is loaded)
    - [x] Avoid flickering when form is loaded on Chrome
- [x] Server-side
- [ ] Angular component using the above API, making the integration easier for Angular users, covered by #4617
    - [ ] Make component reusable
    - [ ] Determine where the source for the component should be checked in

For later:

- Handling `xf:submission replace="all"` (see #3141), by just replacing the part of the page in which the form is, would be needed to support the "review" button, which an MVP wouldn't need to support.

Notes:

- Angular support is motivated by customers using that framework, and the popularity of this framework ([2017](https://2017.stateofjs.com/2017/front-end/results/): only second to React, [2018](https://2018.stateofjs.com/front-end-frameworks/overview/): second to React and arguable Vue.js).

**Comment by ebruchez** [comment]
[+1 from customer](https://basecamp.com/1721271/projects/5063202/messages/54175345)

**Comment by ebruchez** [comment]
[+1 from evaluator](https://mail.google.com/mail/u/0/#inbox/1531325bc88cd654)

**Comment by avernet** [comment]
[+1 from customer](https://mail.google.com/mail/u/0/#inbox/154ddf342ce3eb0f)

**Comment by avernet** [comment]
[+1 from customer](https://basecamp.com/1721271/projects/11790080/messages/63110703)

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/1977373/messages/327513843#__recording_327551633)

**Comment by ebruchez** [comment]
See also #2843 regarding Liferay 7's behavior to add/remove `<script>` elements.

**Comment by ebruchez** [comment]
See also Liferay's [Senna.js](https://github.com/liferay/senna.js).

**Comment by ebruchez** [comment]
Renamed. We had mentioned `jQuery.load()`, but that is not the only solution. Check also what `Senna.js` uses.

**Comment by ebruchez** [comment]
Also relevant to Liferay 7's SPA support.

**Comment by avernet** [comment]
I've added a note about supporting Angular, specifically.

[+1 from user](https://stackoverflow.com/questions/50020008/include-orbeon-forms-into-an-angular-application)

**Comment by avernet** [comment]
[+1 from user](https://twitter.com/nellybellyxDxD/status/1164405273638965248)

**Comment by avernet** [comment]
[+1 from user](https://mail.google.com/mail/u/0/#inbox/FMfcgxwDqfGbkWqVrqdlprfPSxVMWCpl), using PHP on the server

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/4224335/messages/2107590428)

**Comment by ebruchez** [comment]
Things to consider:

- provide a clean JavaScript embedding API
- cleanup, including markup, global objects, event listeners
- proxying of resources and Ajax requests
- loading a form
- events for the embedding application
- navigation between Form Runner pages

**Comment by avernet** [comment]
To enable host A (app) to load the form from B (Orbeon Forms), we must:

- On A:
    - Set the `Content-Security-Policy` header to define what the current page can load/run (e.g. with B on `localhost:8081`, to `style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-eval' http://localhost:8081; connect-src 'self' http://localhost:8081`).
    - Pass `withCredentials: true` when doing the XHR request, so cookies are stored.
- On B:
    - Set `Access-Control-Allow-Origin` allowing A to make an XHR to B (e.g. to `http://localhost:8080` if this is where A is).
    - Set `Access-Control-Allow-Credentials: true` to allow the caller to save headers and send them in subsequent requests.

For now, we've decided to require the app and Orbeon Forms to be seen by the browser as being on the same server, requiring proxying if they are not, this for the following reasons:

- The above setup seems to be of same order of complexity as setting up proxying, if needed.
- Browser, in particular Safari, might prevent this from working, as they try to prevent tracking, especially since in our case users will never access Orbeon Forms directly.
- Have the app and Orbeon Forms on different hosts creates session validity problems.
