### ISSUE TITLE
FB: Actions independent from services

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#1610]
It would make sense to have actions which do not require a service, for example:
- copy a control's value to another one upon button click
- insert a grid iteration

**Comment by ebruchez** [comment]
[+1 from from evaluator](https://mail.google.com/mail/u/0/#inbox/14e7553141c64ab1)

**Comment by ebruchez** [comment]
[+1 from customer](https://basecamp.com/1721271/projects/11832548/messages/56218490)

**Comment by ebruchez** [comment]
[+1 from customer](https://mail.google.com/mail/u/0/#inbox/1565803e0542065e)

**Comment by ebruchez** [comment]
From a user perspective, what we need at a minimum is:

- Form Builder UI
    - Do not require selecting a service.
        - Possibly making "Call service" an action, which would also address #397.
    - Add new actions
        - "Set Value" action
        - etc.

The main question is whether it makes sense to do this without addressing #224.

**Comment by ajw625** [comment]
+1 from this customer. My example has two radio button controls. If a specific value is selected for control-1, react to that change and set a "default" value for control-2 (ideally only if a value has not yet been set). This might be a bit more complex than you were intending though.

**Comment by ebruchez** [comment]
This scenario would involve:

- a "React to item selection" trigger
- a way to express a condition
- a `Set Control Value` action

So I would say it is perfectly in line with what we have in mind.

**Comment by ajw625** [comment]
Perfect. Good to hear. Thanks, Erik.

**Comment by avernet** [comment]
[+1 from evaluator](https://mail.google.com/mail/u/0/#inbox/15ac868fdf61f56e)

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/1978677/messages/449563919)

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/1966717/messages/1270490667#__recording_1301863480) for having a button in the middle of the form calling a process.

**Comment by ebruchez** [comment]
The Orbeon Forms 2018.2 [action syntax](https://doc.orbeon.com/form-builder/advanced/services-and-actions/actions-syntax) implements this. We are "just" missing a user interface. So closing this as #1298 covers it.
