### ISSUE TITLE
Ability to hide buttons based on permissions

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#1619]
- Use MySQL for persistence (any relation persistence layer should do).
- Create a form in Form Builder, enable permission as done below.
- Access the new page for form, and hit save twice.
- ⇒ On the second save the persistence layer returns a 403.

![screen shot 2014-03-19 at 12 12 20 pm](https://f.cloud.github.com/assets/106961/2464734/6db02d94-af9a-11e3-991e-33f36b8554cc.png)

We decided that users without the update permissions indeed shouldn't be allowed to update data in the database, even if this is data they "just created". Instead, the "save" button shouldn't be shown to such users. For this we need a mechanism to hide buttons based on users permissions. And this mechanism should be used out-of-the-box to define that the save button is only shown if users have the "update" permission.

**Comment by acspike** [comment]
Hiding the save button based on permission would be nice (as long as it appears long enough for the user to perform the initial save). As a work around is there any way to substitute an alternative message? The database error message could be unnecessarily distressing for a user who has already saved their data once. I was wondering if I could cobble something together using conditionals inside of the save-final process, but I don't know what xpath query might tell me if the data was saved once.

**Comment by avernet** [comment]
About knowing whether the data is saved, see this [answer](https://twitter.com/orbeon/status/565307180392669185).

**Comment by ebruchez** [comment]
[+1 from customer](https://basecamp.com/1721271/projects/5115898/messages/45343437#comment_309082098)

**Comment by ebruchez** [comment]
The current idea is that this will be implemented with the first iteration of the Basic Workflow (#2256).

**Comment by avernet** [comment]
Closing, as this is now covered by #2256.
