### ISSUE TITLE
Prevent duplicate submission for xf:submission replace="all"

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#1726]
- We do this for Ajax requests:
  - We won't perform the same action twice if the same Ajax request is resent.
  - Instead, we just send back the same result to the client.
  - We do this relying on a sequence no kept in sync between server-browser.
- But nothing of the sort happens for `xf:submission replace="all"`:
  - It triggers a "2-pass submission".
  - The 1st pass is an Ajax request, and the browser gets server events.
  - The 2nd pass is a form POST
    - The browser sends the server events.
    - The server runs the submission and returns the HTML to the browser.
  - Currently the 2nd pass can be replayed and the server performs the action again.
- The server could prevent this by
  - Storing the server event in a transient state associated with an id.
  - Returning the id to the browser (instead of encoded events).
  - When running the events, removing them from the transient state.

**Comment by ebruchez** [comment]
Now subsumed by #4386. Closing.
