### ISSUE TITLE
Upgrade to TinyMCE 4

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#1753]
We are using version 3.5.8 and version 4 has been released in June 2013. Also see the [migration guide from 3.x](http://www.tinymce.com/wiki.php/Tutorial:Migration_guide_from_3.x).

**Comment by avernet** [comment]
[+1 from customer](https://basecamp.com/1721271/projects/3641011/messages/51991775)

**Comment by avernet** [comment]
[+1 from customer](http://discuss.orbeon.com/Later-and-commercial-version-of-TinyMCE-td4662298.html)

**Comment by ebruchez** [comment]
Also required fixing #3512.

**Comment by ebruchez** [comment]
And fixing #3473 for Liferay.
