### ISSUE TITLE
We don't catch field changes due to browser autofill

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#1834]
It seems like the browser does not dispatch an event in this case, but we must find a workaround, see [forum thread](http://discuss.orbeon.com/Issue-with-password-autocomplete-td4657279.html).

See also this [StackOverflow question](http://stackoverflow.com/questions/11708092/detecting-browser-autofill), which says the only solution might be "poll at regular interval to see if its filled".

The SO page mentions this [polyfill](https://github.com/tbosch/autofill-event) (by [Tobias Bosch](https://twitter.com/tbosch1009) @tbosch, who seems to work at Google on Angular). I wonder if the check is efficient if you have hundreds or thousands of form fields. We probably would have to do the check not too often. Also, what about fields which may be dynamically added/removed?

See also #1760 and this comment: "This won't be very useful, because browsers don't honor `autocomplete` anymore: see this [forum thread](http://discuss.orbeon.com/Issue-with-password-autocomplete-td4657279.html) and this [Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=956906#c100)."

Maybe consider #1732 as well.

**Comment by ebruchez** [comment]
Is this still releavant?

**Comment by avernet** [comment]
It is working for me with Chrome. So I think we can close this.
