### ISSUE TITLE
FR send: support sending PDF binary

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#1835]
See also #788. Even without multipart, now that the `send` action can be called multiple times, it makes sense to support a `pdf` content token.

**Comment by avernet** [comment]
[+1 from customer](https://basecamp.com/1721271/projects/7915501/messages/39821930)

**Comment by ebruchez** [comment]
This is really needed.

**Comment by ebruchez** [comment]
[+1 from user](http://discuss.orbeon.com/Trouble-accessing-the-PDF-td4661073.html)

**Comment by ebruchez** [comment]
[+1 from customer](https://basecamp.com/1721271/projects/11908529/messages/57428177)

**Comment by ebruchez** [comment]
- [ ] check if URLs stored in `fr-pdf-url-instance` and `fr-tiff-url-instance` are proxied
- [ ] trigger binary submission as needed
- [ ] also support `tiff` content token

**Comment by ebruchez** [comment]
Documented: [`pdf](http://doc.orbeon.com/form-runner/advanced/buttons-and-processes/actions-form-runner.html#sending-a-pdf-binary), [`tiff`](http://doc.orbeon.com/form-runner/advanced/buttons-and-processes/actions-form-runner.html#sending-a-tiff-binary), [`content-type`](http://doc.orbeon.com/form-runner/advanced/buttons-and-processes/actions-form-runner.html#send_parameter_content_type).
