### ISSUE TITLE
Ability to copy/paste between forms

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#1839]
This might not be as hard as it might seem as long as the source and destination are in the same session. We could implement a session-based clipboard storing the XML representation of the control (as we do now but within a single instance of Form Builder only).

This might require a better UI to understand what's currently in the clipboard, so that two instances of Form Builder don't clash too much.

[+1 from customer](https://basecamp.com/1721271/projects/4156697/messages/28885442)

**Comment by avernet** [comment]
[+1 from community](https://stackoverflow.com/questions/45048417/is-there-a-way-to-copy-section-in-orbeon)

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/1966556/messages/1636921611)

**Comment by ebruchez** [comment]
The clipboard still contains XML documents. We should consider a better serialization like we do for undo/redo.

**Comment by avernet** [comment]
[+1 from customer](http://discuss.orbeon.com/Extract-library-section-from-an-existing-form-td4664959.html)

**Comment by ebruchez** [comment]
- Q: Should the clipboard be by default shared within a session?
- A: It might be ok.

**Comment by ebruchez** [comment]
The core of the implementation right now is `writeXcvToClipboard`, which stores an XML document into the clipboard instance. We could serialize that to the session.

One difficulty: in the 2nd form in the same session, the clipboard's paste icon might be empty and disabled (the default initially). We either need to update it regularly, or to let it be enabled at all times.

**Comment by ebruchez** [comment]
So let's say we have two Form Builder instances open in the same browser session.

Questions:

1. Is there only one clipboard in the session, or one local clipboard and one session clipboard?
2. How do we solve the update of the "Paste" icon?
    - In most cases, there won't be any cross-Form Builder instance copy/paste.
    - We could enable it at all times. Right now, it's only enabled when there is at least one clipboard entry. But after that, it's going to be enabled at all times. So it's not a bit deal if it's enabled at all times.

**Comment by ebruchez** [comment]
Reminder that we only have one single entry in the clipboard.

One risk is that you cut an item, then in another Form Builder instance copy an item. That will, arguably unexpectedly, erase the one in the first Form Builder.

So it might make sense to:

- have both a local and a session clipboard
- and/or have a multi-entry clipboard

What we could do:

- have a local clipboard (like now)
- have a separate session clipboard

When we write to the local clipboard, we also write to the session clipboard, using an id that identifies the current Form Builder instance (for example the XForms document id), and maybe some useful information like app name/form name/form title.

We have a separate "Paste from Session" icon, which opens a menu with the list of items in the session clipboard. Selecting one pastes the given item.

Questions for the session clipboard:

- Q: Can you add more than one item for Form Builder session?
     - A: Yes, as we need to support multiple entries anyway.
- Q: How to expire times from the clipboard so it doesn't become infinitely large over time?
    - A: Maybe we can just let it expire with the session, which typically is not infinite?

**Comment by avernet** [comment]
I don't think that having a single clipboard, instead of one clipboard per Form Builder tab, is a problem, and would even argue it is better:

- Having a single clipboard is how things work on the normal OS clipboard, so if anything, it is to have a separate clipboards per tab that should surprise users.
- As far as backward compatibility, I'd be really surprised if many users had a workflow that depended on the clipboard not being shared between tabs, and if that turns out to be the case we can also add "an option" for this later.
- Having 2 ways to paste ("from local clipboard" and "from session clipboard") makes things more complex for users (and for us for creating a clear UI / explain / support).
- This is also what what Google does in Docs, Sheets, etc. (Also, they use the native clipboard, which is an interesting idea. But can we put something that makes sense in context other than Form Builder in the local clipboard?)

**Comment by ebruchez** [comment]
Ok for the single clipboard. But then I think it would be really good to have a multi-level clipboard. (Any OS should have that too, by the way!)

It would be good to be able to use the system clipboard. But:

- I am not sure the browser can read/write to the system clipboard using a custom content-type. Could we use text if not (as XML!)? But then one issue is when pasting we need to check the format.
- Browser support is TBD. Firefox [doesn't seem to support](https://caniuse.com/#search=clipboard) the latest clipboard read/write APIs.

**Comment by ebruchez** [comment]
After discussion with @avernet, we think it's ok to:

1. Have a single clipboard in the session
2. Keep the single item clipboard for now
3. Consider a multi-level clipboard later
4. Not worry about the clipboard API, which is still poor

**Comment by ebruchez** [comment]
[Documented](https://doc.orbeon.com/form-builder/form-editor/cut-copy-paste#copying-and-pasting-between-forms)
