### ISSUE TITLE
Ability to move/reorder grids up/down within/across sections

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#1845]
Curiously, this is not supported right now. It seems like a very basic feature!

See also #635 for other grid-related improvements.

[+1 from customer (private email)](https://mail.google.com/mail/u/0/#inbox/1478aac61dd4491a)

**Comment by ajw625** [comment]
This is definitely something we need. We've found the process rather painful when reordering grids or simply adding a grid at the beginning of a section.

**Comment by ebruchez** [comment]
@ajw625 Agreed. We haven't yet scheduled this enhancement though.

**Comment by avernet** [comment]
[+1 from customer](https://basecamp.com/1721271/projects/8966776/messages/40852998)

**Comment by acspike** [comment]
Adding move triggers is trivial (see #2228), but as with #2226 there is a problem with space. The grid delete trigger is surrounded on all sides. Would it be possible to add a dropdown menu similar to the menu used in repeating grids?

**Comment by ebruchez** [comment]
Ideally, I would like:

- icons for discoverability of the feature
- drag and drop so we can move faster and with more flexibility
- keyboard shortcut to move the current grid (and other objects)

It would be good to have the ability to show more icons without being limited by the space within the grid or grid cell. There could be a "palette" of actions showing outside the boundary of the grid.

**Comment by ebruchez** [comment]
[+1 from evaluator](https://mail.google.com/mail/u/0/#inbox/14e7553141c64ab1)

**Comment by avernet** [comment]
[+1 from customer](https://mail.google.com/mail/u/0/#inbox/14f8b13b1a72edb1)

**Comment by ebruchez** [comment]
+1 from me today. If UI takes a while to implement, maybe can implement keyboard shortcuts first, which is a workaround for beginners, but great for power users (#233).

**Comment by ebruchez** [comment]
Another idea until we get proper DnD: do this via buttons within the Grid Settings dialog.

Currently, there is no such dialog for non-repeated grids, but we should have one, see some steps under #1947.

**Comment by Syncopatico** [comment]
Hi Erik - as per comment elsewhere, for long lists (e.g, where range of move won't fit on screen), a 'move to before/after ...' option may be more usable than drag and drop. BTW - is this still just for grid items witihin Form Builder, or for end-user actions with repeating grid items in Form Runner?

**Comment by ebruchez** [comment]
@Syncopatico Good suggestion. This issue is about Form Builder specifically.

**Comment by ebruchez** [comment]
See also #2461. We now have some experience with drag and drop so we should be able to do this fairly easily.

**Comment by ebruchez** [comment]
The main question is about the UI for this, namely where can you click and grab so it's clear what's happening. Right now, on hover, we show icons, but those are not inserted into the DOM but instead positioned absolutely, on the side. So we probably cannot use that area as handles for Dragula, which I think requires nesting (but need to confirm this).

**Comment by ebruchez** [comment]
Next step:

- [ ] quick try: would naive solution which detects click on grid be usable for a first implementation

**Comment by ebruchez** [comment]
Implemented with arrows for now. Added #4088 for DnD.
