### ISSUE TITLE
Per-app and global permissions configuration

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#1860]
Currently, permissions can only be configured per form, and in Form Builder. We would like to extend that. Proposal:
- do this with JSON properties
- later, we'll have a general UI to update properties

Currently, the XML stored in the form looks like this:

``` xml
<permissions>
    <permission operations="read update">
        <group-member/>
    </permission>
    <permission operations="read update">
        <owner/>
    </permission>
    <permission operations="create"/>
    <permission operations="read update delete">
        <user-role any-of="manager"/>
    </permission>
</permissions>
```

_NOTE: The permissions are top-level in the XML, and have an_ or _meaning. They are designed this way for future extensibility, so that new condition types could be added. For example one could write (don't pay too much attention to the specific condition syntax):_

``` xml
<permission operations="read update">
    <group-member/>
    <condition xpath="//type = 'gaga' and document-age-days() gt 10"/>
</permission>
```

The JSON configuration could look like:
1. the current FB UI, which is easier to understand
2. or like the current XML data, which is more extensible

``` json
[
    {                                  "permissions": "create"                    },
    { "standard-role": "owner",        "permissions": "read update"               },
    { "standard-role": "group-member", "permissions": "read update"               },
    { "user-role":     "manager",      "permissions": "create read update delete" }
]
```

Or:

``` json
[
    { "operations": "read update",        "conditions": [ { "name": "owner" } ]                          },
    { "operations": "read update",        "conditions": [ { "name": "group-member" } ]                   },
    { "operations": "create"                                                                             },
    { "operations": "read update delete", "conditions": [ { "name": "user-role", "any-of": "manager" } ] }
]
```

We would then just need to check properties in `FormRunnerPermissions.authorizedOperationsBasedOnRoles` if the form itself doesn't have permissions.

Property could be:

``` xml
<property as="xs:string"  name="oxf.fr.permissions.*.*">
    [ … ]
</property>
```

**Comment by ebruchez** [comment]
[+1 from evaluator](https://mail.google.com/mail/u/0/#inbox/1556ee2dd8ff9427)

**Comment by ebruchez** [comment]
Permissions are currently checked in `persistence-model.xml`, calling with `xxf:instance('fr-form-metadata')/permissions`:

```xpath
frf:xpathAllAuthorizedOperations()
frf:allAuthorizedOperationsAssumingOwnerGroupMember()
frf:authorizedOperationsBasedOnRoles()
```

All functions are implemented in `FormRunnerPermissions`. They call:

- `allAuthorizedOperations()`
    - calls `authorizedOperationsBasedOnRoles()`
    - also checks `owner` and `group-member`
- `authorizedOperationsBasedOnRoles()`
    - checks roles

In all these cases, when no `permissions` element is provided, we would instead obtain the permissions from properties.

If the format in properties is JSON, it would be good to convert both XML and JSON to a scala representation, so the code checking permissions is not duplicated.

**Comment by ebruchez** [comment]
With #2256, we were planning to have a different representation for permissions when using the workflow feature. So we might have two different initial formats for permissions: the current one and the workflow one (when workflow feature is in use). The idea, in that case, was to "generate workflow config from existing permissions config" in the form definition.

But we also wanted to "strip workflow from metadata column / metadata.xml and only keep short permissions" at runtime, which is what interests us here. Would that "short permissions" format be like the current format, or different?

If think that for now, if we want to implement this issue before #2256, we would just pick a JSON format and convert to the current XML format. If #2256 creates a new "short format", we can adapt. Anyway we will need the ability to keep supporting the current format if we introduce a new one.

**Comment by ebruchez** [comment]
Steps:

- [ ] pick JSON format for use in properties (and maybe, later in form definition)
- [ ] convert from XML / JSON to Scala representation
- [ ] update `FormRunnerPermissions`
    - [ ] convert from XML to Scala when needed
    - [ ] read permissions from properties if no permissions specified in form definition
    - [ ] convert from JSON to Scala when needed
    - [ ] check permissions based on Scala representation

**Comment by ebruchez** [comment]
The format should also support:

- conjunctions of conditions (#2420), even if that's just for future extensibility
- value-based checks

Could you say:

```json
"standard-role": "group-member", "user-role": "manager"
```

Which would translate into "must be group member AND have `manager` role". Disjunctions can be  implemented by adding multiple lines, probably.

For value checks, we could use an array of `name`/`value` objects:

```json
"value-match": [
  {
    "name":  "xh:head/xf:model[@id = 'fr-form-model']/xf:instance[@id = 'fr-form-metadata']/*/application-name",
    "value": "orbeon"
  },
  {
    "name":  "xh:head/xh:head/xf:model[@id = 'fr-form-model']/xf:instance[@id = 'fr-form-metadata']/*/form-name",
    "value": "bookshelf"
  }
]
```

The example above would relate to a Form Builder permission to access `orbeon/bookshelf`.

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/5300917/messages/1619052500)

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/1966556/messages/1970510227#__recording_2118819711) for default permissions

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/7993860/messages/2387911202)

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/23878674/messages/5168267407) in the context of #5397

**Comment by ebruchez** [comment]
I'd suggest that the JSON format follow something close to the current Form Builder UI for permissions. I am not sure if the scenario where we want to enable a conjunction of conditions (#2420) is important or not, or how it relates to the workflow permissions. But a simple format matching what we have now would be something like this:

```json
{
  "anyone": [ "create" ],
  "owner": [ "read", "update" ],
  "group-member": [ "read", "update" ],
  "roles": [
    {
      "role": "orbeon-user",
      "permissions": [ "read", "update", "list" ]
    },
    {
      "role": "orbeon-admin",
      "permissions": [ "read", "update", "delete", "list" ]
    }
  ]
}
```

Or maybe:

```json
{
  "anyone":       { "permissions": [ "create" ] },
  "owner":        { "permissions": [ "read", "update" ] },
  "group-member": { "permissions": [ "read", "update" ] },
  "roles": [
    {
      "role": "orbeon-user",
      "permissions": [ "read", "update", "list" ]
    },
    {
      "role": "orbeon-admin",
      "permissions": [ "read", "update", "delete", "list" ]
    }
  ]
}
```

Or even:

```json
{
  "anyone":         [ "create" ],
  "owner":          [ "read", "update" ],
  "group-member":   [ "read", "update" ],
  "roles": {
    "orbeon-user":  [ "read", "update", "list" ],
    "orbeon-admin": [ "read", "update", "delete", "list" ]
  }
}
```

The last format is the most concise. It's fairly consistent.

I suggest that it's better to split permission tokens in an array, rather than:

- using a space-separated string
- or something more complicated like `{ "read": true, "update": false }`

**Comment by ebruchez** [comment]
[Documented](https://doc.orbeon.com/form-runner/access-control/deployed-forms#per-app-and-global-permissions)
