### ISSUE TITLE
Web site home page: on IE9, video plays to the right of the screenshot

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#1883]
Which means that essentially, the video can't be seen by users on IE9.

![ie9](https://cloud.githubusercontent.com/assets/106961/4158854/58d01a04-3494-11e4-8154-98ee55f85c33.png)

[+1 from user](https://mail.google.com/mail/u/0/#inbox/1483d55c755f4579) (Alex's email)

**Comment by ebruchez** [comment]
This got fixed not long ago. It happened with all versions of IE I think.
