### ISSUE TITLE
Use enum for providers instead of a string

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#1887]
This is done right now in our [test code](https://github.com/orbeon/orbeon-forms/blob/master/src/test/scala/org/orbeon/oxf/fr/persistence/db/Provider.scala), but not in for [CRUD operations](https://github.com/orbeon/orbeon-forms/tree/master/src/main/scala/org/orbeon/oxf/fr/relational/crud).

**Comment by ebruchez** [comment]
@averent I think this is done with 2016.2, correct? If so, I will let you close this issue.

**Comment by avernet** [comment]
Yes, this is done. Closing.
