### ISSUE TITLE
Shouldn't be able to rename nested section from section template

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#1915]
In a library, create a section with a nested repeating section:

![screen shot 2014-09-24 at 4 35 56 pm](https://cloud.githubusercontent.com/assets/106961/4397553/ccc2e0bc-4444-11e4-9fdf-30e1d091a3dd.png)

In a form, add that section template:

![screen shot 2014-09-24 at 4 38 11 pm](https://cloud.githubusercontent.com/assets/106961/4397558/e6ce3402-4444-11e4-919e-32e4735e053b.png)

Rename the section and sub-section:

![screen shot 2014-09-24 at 4 38 27 pm](https://cloud.githubusercontent.com/assets/106961/4397559/ee73f75a-4444-11e4-81dc-0b953eeb73f1.png)

Run the form, and notice how, for the nested section, the original name (S3.1) is used instead of the new one we picked earlier (B):

![screen shot 2014-09-24 at 4 38 34 pm](https://cloud.githubusercontent.com/assets/106961/4397569/0c6ab21c-4445-11e4-8688-51c61365113b.png)

**Comment by ebruchez** [comment]
Check if this is still the case as of 2017.2.
