### ISSUE TITLE
Unify eXist and relational search.xpl, and move to Scala

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#1942]
Right now part of the logic is duplicated between eXist's [`search.xpl`](https://github.com/orbeon/orbeon-forms/blob/master/src/resources/apps/fr/persistence/exist/search.xpl) and the relational [`search.xpl`](https://github.com/orbeon/orbeon-forms/blob/master/src/resources/apps/fr/persistence/relational/search.xpl), e.g. the code dealing with permissions. Also, this code being in XPL and of an increasing complexity, it is harder to debug and maintain, and should be rewritten in Scala.

**Comment by ebruchez** [comment]
This will also be closed with #649, is that right @avernet? If so I am putting the 2016.2 milestone.

**Comment by avernet** [comment]
@ebruchez Not quite: eXist's `search.xpl` will stay as is for 2016.2. It's "only" the `search.xpl` for relational databases that is rewritten in Scala.

**Comment by ebruchez** [comment]
Ok, so removing the milestone.

**Comment by ebruchez** [comment]
Ah, you had removed it already.

**Comment by ebruchez** [comment]
Closing this as eXist support is deprecated.
