### ISSUE TITLE
fr:grid: add enclosing element for non-repeated case

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#1947]
- [x] annotate.xpl: migrate grids
    - [x] non-repeated grids without bind
        - [x] add bind attr
        - [x] create bind
        - [x] migrate data
        - [x] handle simultaneous migration of `<td>` grid
            - maybe do two phases `within-body-migrate-to-12-columns`, then rest? also consider ids
            - don't run migration if not needed
- [x] code to describe data migration
- [x] `dataMaybeMigratedFromEdge` must support 4.0 and 4.8 as destination
- [x] `dataMaybeMigratedToEdge` must support 4.0 and 4.8 as destination
- [x] bug: within repeated section, grid loses its binding
- [x] code to migrate data to/from
    - [x] complete `MigrationOps20191`
       - [x] migrations
       - [x] `MigrationOps20191.adjustPathTo40`
- [x] search for "1947" in source
    - [x] `findContainerNamesForModel`
- [x] settings dialog
  - [x] icon in top-left corner opens dialog
  - [x] ~~need separate delete action, maybe red button in dialog (like for actions)~~
        - We now have a "remove" icon.
  - [x] enable switch between repeated/non-repeated grid
  - [x] support Visibility / Readonly formulas
- [x] modify "insert grid" to insert grid etc. in new format
- [x] check that migrations are properly added when form is published
- [x] `FormDefinition.findIndexedControls`: check if changes are needed depending on provider data format version
- [x] migrate demo forms
    - [x] Bookshelf: update schema too
- [x] update dev support plan hours

See #635 for repeated grid case.

**Comment by ebruchez** [comment]
[+1 from customer](https://basecamp.com/1721271/projects/8001401/messages/51168485)

**Comment by ebruchez** [comment]
Question: should the enclosing element always be added, or just added when needed, that is when the grid has a Visibility or Readonly formula?

**Comment by avernet** [comment]
I would say it should always be added. Just like we always have an element for sections. Plus, it would be strange to have the format change just because a Visibility or Readonly formula is added or removed on a grid.

**Comment by ebruchez** [comment]
I agree that's best. Plus we would do the same we do for repeated grids: keep the database format unchanged, but have the element internally.

**Comment by ebruchez** [comment]
[+1 from customer](https://mail.google.com/mail/u/0/#inbox/15841ceed47fce59)

**Comment by ebruchez** [comment]
+1 from me now working on #3829. As there is no binding on `fr:grid`, we don't get an associated `xforms-enabled` in the correct scope.

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/1966556/messages/1636931029)

This would create a new internal and optional database data format, for example  `2019.1`.

**Comment by ebruchez** [comment]
For the repeated grid case, here is what we do in `annotate.xpl`:

- identify the grids to migrate
- migrate data with `buildGridMigrationMap`/`migrateDataTo`
- migrate repeat templates with `createTemplateContentFromBindName`
- migrate binds by adding an iteration bind in the middle (mostly in XSLT)

Steps for migrating legacy unrepeated grids:

- [ ] legacy non-repeated ("unrepeated") grids
    - [ ] find them (they don't have a `bind`)
    - [ ] add `bind` and `id` (if needed, check) attributes
- [ ] migrate data
- [ ] migrate repeat templates if they contain legacy grids, that's needed
- [ ] identify the location of the new `xf:bind` to insert, insert the bind and move the content into it

Right now, our migration data is a top-level JSON array:

```json
[
  {
    "path": "section-3/section-3-iteration/grid-4",
    "iteration-name": "grid-4-iteration"
  },
  {
    "path": "section-13/grid-6",
    "iteration-name": "grid-6-iteration"
  },
  {
    "path": "section-13/grid-14",
    "iteration-name": "grid-14-iteration"
  },
  {
    "path": "section-8/grid-3",
    "iteration-name": "my-custom-grid-3-iteration"
  },
  {
    "path": "section-23/grid-3",
    "iteration-name": "my-custom-grid-3-iteration"
  }
]
```

This is encapsulated into the following at publish time (`add-migration.xpl`):

```xml
<migration version="4.8.0">...</migration>
```

This means "information to migrate data from the 4.0.0 format to the 4.8.0 format". We might now want:

```xml
<migration version="4.8.0">...</migration>
<migration version="2019.1.0">...</migration>
```

which would mean "information to migrate data from the 4.8.0 format to the 2019.1.0 format".

**Comment by ebruchez** [comment]
The migration information needs to contain, for all unrepeated grids:

- path to containing elements (as grids can be in repeated sections)
- name of element to create
- maybe: position element to create (after other named element)
- name of elements at same level to move into enclosing element

We need to be able to migrate among all formats, as the database or services might be in 4.0.0 or 4.8.0 format. So one or both migrations need to apply.

**Comment by ebruchez** [comment]
The two migrations: 4.0.0 ↔ 4.8.0 ↔ 2019.1.0 are independent since one covers repeated grids and one non-repeated grids, and the migrations cannot be nested.
