### ISSUE TITLE
xxbl:mirror="true" doesn't seem to update inner instance when outer instance is replaced

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#1965]
To reproduce, publish [this form](http://discuss.orbeon.com/file/n4659188/form.xml) in Form Builder, run it, click on open dialog, and upload [this instance](http://discuss.orbeon.com/file/n4659188/data.xml).  The value (42) is visible in in the input outside of the section template, but not for the one inside the section template. (Save, reload, and the value shows.)

**Comment by avernet** [comment]
[+1 from user](https://mail.google.com/mail/u/0/#inbox/151aa35b815fb72b)

**Comment by ebruchez** [comment]
@avernet the original issue doesn't have the required library to reproduce, and the second issue is a private message. I will try to create a reproducible case by just replacing the instance.

**Comment by ebruchez** [comment]
I reproduce with [this form and library](https://gist.github.com/ebruchez/cfce295121ec2aa6e56c).

**Comment by ebruchez** [comment]
`onBindingUpdate()` is not called because section templates don't have a binding.

**Comment by ebruchez** [comment]
Mmh, no it seems to be called after all.

**Comment by ebruchez** [comment]
I verified that:

- the binding of the section template component is updated
- the mirror copies over the new instance content
- the nested input fields re-evaluate to the correct values

However the UI doesn't update.

**Comment by ebruchez** [comment]
It works with `xxf:xpath-analysis="false"`.
