### ISSUE TITLE
XForms JavaScript references jquery's $.browser()

### ISSUE THREAD

**Issue by ajw625** [orbeon/orbeon-forms#1976]
Some of the javascript libraries reference jquery's $.browser function, specifically $.browser.msie:

orbeon-resources-public.jar\ops\javascript\xforms-min.js
orbeon-resources-public.jar\ops\javascript\xforms.js
orbeon-resources-public.jar\ops\javascript\orbeon\xforms\server\AjaxServer-min.js
orbeon-resources-public.jar\ops\javascript\orbeon\xforms\server\AjaxServer.js

This function was removed in jquery 1.9. See this stackoverflow post I found. I had the same error :
http://stackoverflow.com/questions/14923301/uncaught-typeerror-cannot-read-property-msie-of-undefined-jquery-tools

Oddly, this error only showed up when I built a component packaged with jquery 1.9. Once I removed the 1.9 library the error went away.

Still, this should be cleaned up. See the [jQuery 1.9 Upgrade Guide](http://jquery.com/upgrade-guide/1.9/#jquery-browser-removed).

**Comment by avernet** [comment]
The related issues for which we test on IE are #131 and #682. We've changed the code for both instances not to rely on `$.browser`, so we can remove our dependency on jquery-migrate.
