### ISSUE TITLE
"Email Recipient", "Show in Email Subject", and attachments don't work in section templates

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2016]
To reproduce, use the form and library provided by Martin in [this thread](http://discuss.orbeon.com/Marking-field-as-email-recipient-not-working-inside-section-template-td4659258.html).

**Comment by ebruchez** [comment]
[+1 from customer](https://basecamp.com/1721271/projects/4503952/messages/43247832)

**Comment by ebruchez** [comment]
I see two ways of doing this:

1. using the live document to inspect controls and find the ones with a given class
  - this requires that we have an ability to iterate controls and/or find those with a given class, which I don't think we have now so would need to be added
  - then the list of values associated with these controls must be passed to the email service
2. keep things the way they are but inspect section templates XBL

I think option 2 might be easier.
