### ISSUE TITLE
FB: Permissions should not apply to test mode

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2050]
- new form in FB
- enable permissions but do no set any
- Test
- error

The form author should be able to try out the form no matter what permissions are enabled.

**Comment by ebruchez** [comment]
[+1 from customer](https://mail.google.com/mail/u/0/#inbox/14f9a22abf2999c9)

**Comment by avernet** [comment]
[+1 from customer](http://discuss.orbeon.com/Form-quot-test-quot-urls-form-persistence-API-and-401-Not-Authorised-response-td4660989.html)

**Comment by ebruchez** [comment]
Note that we no longer support entering the `test` mode via a GET. So we are in `test` mode only from Form Builder.
