### ISSUE TITLE
Allow modifying section template after insertion (by-copy use)

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2052]
The idea is to be able to modify aspects of the section templates. I see several levels:
1. modify resources: labels, hints, etc.: only 
    - this might require only modifying the section template's resources
2. modify the section template structure: add/remove controls, etc. (#3195)
3. modify the data only (see #2051)
    - this does not require modifying the section template proper

+1 from [StackOverflow](http://stackoverflow.com/questions/27641449/orbeon-forms-section-templates).

**Comment by andrewelkins** [comment]
:+1:

**Comment by ebruchez** [comment]
[+1 from evaluator](https://mail.google.com/mail/u/0/#inbox/15add1be74ff8a4e)

**Comment by ebruchez** [comment]
If we are talking about "by-copy" use as the title says, then this is covered by #3195. Closing and we'll create new issues if we want to address "labels, hints, etc.: only" or "data only" in the future.
