### ISSUE TITLE
Commas not allowed in role/group names

### ISSUE THREAD

**Issue by acspike** [orbeon/orbeon-forms#2059]
Because [comma is used as a role delimiter](https://github.com/orbeon/orbeon-forms/blob/9c261c41bac4babc48f03d7d60aaeeb26190df3a/src/main/scala/org/orbeon/oxf/fr/FormRunnerPermissions.scala#L75), role names (e.g. LDAP Group DNs) which include commas are broken apart and fail to match.

**Comment by ebruchez** [comment]
[Now documented](https://github.com/orbeon/orbeon-forms/wiki/Form-Runner-~-Access-Control-~-Setup)
