### ISSUE TITLE
New functions getting user's roles and group

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2063]
We have `xxf:get-remote-user()` and `xxf:is-user-in-role()` (with the #2062 caveat), but in the context of Form Runner, we should also have a function that returns the user's roles and group, following the Form Runner semantic.

**Comment by ebruchez** [comment]
The following functions are listed in #1095:

- `fr:current-user()`
- `fr:current-group()`
- `fr:current-roles()`

**Comment by ebruchez** [comment]
Exposed as `xxf:` for now:

- `xxf:username()`
- `xxf:user-group()`
- `xxf:user-roles()`

**Comment by acspike** [comment]
Is xxf:username() accessible from theme.xsl ?

**Comment by ebruchez** [comment]
@acspike I haven't tried but yes it should be exposed as `p:username()`.

**Comment by ebruchez** [comment]
[Documented](https://github.com/orbeon/orbeon-forms/wiki/XForms-~-XPath-Function-Library#xxfusername)

**Comment by ebruchez** [comment]
Also exposed as `fr:` following #1095. See [documentation](http://doc.orbeon.com/xforms/xpath/extension-form-runner.html#authentication-functions).
