### ISSUE TITLE
Prevent double submissions

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2068]
Once users have filled out and submitted a form, right now they can hit back in their browser, and submit the form again. Orbeon Forms should, by default, prevent this.

**Comment by avernet** [comment]
[+1 from discuss](http://discuss.orbeon.com/How-to-implement-a-custom-quot-Finish-page-quot-best-td4659431.html)

**Comment by ebruchez** [comment]
Duplicate of #1967, closing.
