### ISSUE TITLE
Structured search can't be used with decimal fields

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2077]
Create a form with a decimal field, mark it as showing in search, publish, open summary page, open the structured search, and notice no search field shows for that decimal control. Also check that the same problem doesn't happen with other controls supported by Form Builder.

**Comment by avernet** [comment]
[+1 from Eric](https://mail.google.com/mail/u/0/#inbox/14b2fd054a8cc9ee) (in Alex's email)

**Comment by ebruchez** [comment]
RESOLUTION: Quick fix by handling `fr:number`. We don't handle search on types well anyway, like dates.

**Comment by ebruchez** [comment]
Also handle `fr:currency` along the way. Here how things look with:

- `xf:input`
- `fr:number`
- `fr:currency`
- `xf:input` with `date`
- `xf:input` with `time`
- `xf:input` with `dateTime`

The `dateTime` is styled too wide. The UI would gain from a revision!

![summary](https://cloud.githubusercontent.com/assets/105769/6721360/a0429518-cd89-11e4-97b2-2deca9ed2744.png)
