### ISSUE TITLE
Two version Orbeon on this same instance Tomcat7

### ISSUE THREAD

**Issue by JDStar** [orbeon/orbeon-forms#2080]
Hi.
I need run two different instances Orbeon - example: orbeon-3.7 and orbeon-4.8.
Under Tomcat7 deploy both version - to different directories:
* /var/lib/tomcat7/webapps/orbeon37/
* /var/lib/tomcat7/webapps/orbeon48/

After this installation - not working any version and java process is 100% utilization CPU.

If install only one of each version - working OK.
Where is my mistakes/error?
What i can install two version Orbeon Forms on one Tomcat7?

**Comment by ebruchez** [comment]
It might be because the JVM is running out of memory. What is the current setting? Try explicitly setting a maximum heap of 1GB or more. For example with this option: `-XmX1g`.

**Comment by JDStar** [comment]
Thanks!
I have 32GB on server and increase memory Tomacat to 4GB - now run OK.
```
JAVA_OPTS="-Djava.awt.headless=true -Dfile.encoding=UTF-8 -server 
-Xms4096m -Xmx4096m -XX:NewSize=512m -XX:MaxNewSize=512m 
-XX:PermSize=512m -XX:MaxPermSize=512m -XX:+DisableExplicitGC"
```
It is OK params?

**Comment by ebruchez** [comment]
I haven't checked the impact of `NewSize` and `MaxNewSize`, but the rest appears ok! Glad it's working for you now.
