### ISSUE TITLE
Wrong value in date/time control when using picker

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2086]
- create form with single "Date and Time" control, publish, /new
- use the date picker icon to select a date
- notice the time field also contains the date
- client sends to the server e.g. `2/2/2015T2/2/201`, which is wrong

**Comment by ebruchez** [comment]
4.7 doesn't have the issue.

**Comment by avernet** [comment]
Had regressed in 4ec537dc599fe637b9562e10592e398118cc55d9.

**Comment by avernet** [comment]
Also cherry picked fix to the 4.8 branches, for inclusion in 4.8.2.
