### ISSUE TITLE
Flat views with PostgreSQL persistence layer use xml datatype for extracted columns

### ISSUE THREAD

**Issue by acspike** [orbeon/orbeon-forms#2089]
Currently the flat view columns are the raw out put of the xpath() call which returns an XML datatype. Ideally appropriate datatypes would be selected (varchar, integer, text, datetime, etc) based upon datatypes in the form design. Perhaps in the meantime an appropriate stop gap would be to cast all columns to a text datatype.

Discussion from [Twitter](https://twitter.com/orbeon/status/563460107233538048)

**Comment by avernet** [comment]
Yes, that sounds reasonable. #2090 was pulled.
