### ISSUE TITLE
xs:gYear validation error

### ISSUE THREAD

**Issue by ewg118** [orbeon/orbeon-forms#2096]
I have come across a validation error for xs:gYear which is fairly unlikely to have been encountered by the average user. According to the ISO 8601 spec, the gYear value '0000' is 1 B.C. The XForms validation accepts the values 0001 (A.D. 1) and -0001 (2 B.C.), but not 0000.

**Comment by avernet** [comment]
Are you sure? From what I'm reading the schema spec about [gYear](http://www.w3.org/TR/2004/REC-xmlschema-2-20041028/datatypes.html#gYear), *The lexical representation for gYear is the reduced (right truncated) lexical representation for dateTime: CCYY*, and there is says *The date and time datatypes described in this recommendation were inspired by [ISO 8601]. '0001' is the lexical representation of the year 1 of the Common Era (1 CE, sometimes written "AD 1" or "1 AD"). There is no year 0, and '0000' is not a valid lexical representation. '-0001' is the lexical representation of the year 1 Before Common Era (1 BCE, sometimes written "1 BC").*

Note they say *inspired by ISO 8601*, so it might indeed be different in ISO 8601.

**Comment by ewg118** [comment]
This is a complicated issue and there is no firm solution. I suppose that if gYear says there is no '0000', then technically the XForms validation scenario functions correctly, even if gYear breaks with ISO8601 and the W3C recommendations I've read elsewhere. This means that mathematically, it will say that 1 B.C. occurred two years before 1 A.D., even though only one year separates them in an actual calendar. Maybe I should raise the issue with the XML schema people, because this is definitely a problem in calculating the age or reign of people born in one era and died in the other.

**Comment by avernet** [comment]
OK, so I'll close this for now.

About computing the difference between 2 dates, I would assume that it is the code in the XPath implementation doing the difference that should be aware of this, and it seems to be the case as running `xs:date('0001-01-01') - xs:date('-0001-01-01')` returns `P366D`.
