### ISSUE TITLE
HTML labels/hints have <br clear="none">

### ISSUE THREAD

**Issue by umwmcomarch** [orbeon/orbeon-forms#2099]
Current version of Orbeon - 4.8 and previous has error in html labels and hints. If we enter html label with html short tags for example "test&lt;br/&gt;test2", Orbeon changes short tags, to open tags without close tags. Created by Orbeon open tag has extra attributtes (clear="none"), which wasn't entered. Moreover from one short tag, Orbeon creates two start tags. If we copy control after that changes, Orbeon on paste add next open tag of short tag - for this example we entered one &lt;br/&gt;, which was changed to two &lt;br clear="none"&gt;, after copy and paste that control we have three &lt;br clear="none"&gt;

**Comment by acspike** [comment]
This was also [mentioned on twitter](https://twitter.com/acspike/status/560527891466047488).

Please see:
- [Use in Orbeon Forms](https://github.com/orbeon/orbeon-forms/blob/tag-release-4.8.1-ce/src/main/java/org/orbeon/oxf/xforms/XFormsUtils.java#L151)
- [TagSoup definition file](https://github.com/jukka/tagsoup/blob/master/src/definitions/html.tssl#L2253)

**Comment by avernet** [comment]
Yes, this sounds like the issue @acspike is referring to. Since we already have "our own" [version of TagSoup](https://github.com/orbeon/tagsoup/commits/master), I'll just change the definition fine accordingly to avoid this, and update the jar in Orbeon Forms.

**Comment by umwmcomarch** [comment]
One problem is 'clear="none"', and the second extra open tags without close tags adding after edit label or copy/paste control.

**Comment by avernet** [comment]
With this change in TagSoup, if you enter `test<br/>test2`, in HTML you'll have `test<br>test2`.

**Comment by acspike** [comment]
Does this also correct the doubling? (<br/> was becoming <br clear="none"><br>)
