### ISSUE TITLE
Dynamic PDF resource filenames lack extension

### ISSUE THREAD

**Issue by acspike** [orbeon/orbeon-forms#2101]
[As discussed on Twitter](https://twitter.com/acspike/status/569877965493956608)

This causes problems on Windows when accessing the pdf-url from the send action because Windows uses the extension as the primary means of determining file types. [A comment in the source code](https://github.com/orbeon/orbeon-forms/blob/master/src/main/scala/org/orbeon/oxf/xforms/processor/XFormsResourceServer.scala#L84) indicates adding extensions as a TODO list item.

**Comment by ebruchez** [comment]
Closing this one as we have #2102.
