### ISSUE TITLE
AVT not interpreted on xh:body

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2103]
Create a form in Form Builder, add `class="{xxf:get-request-parameter('my-param')}"` on the `xh:body`, save, publish, open new, the body has the class `class="orbeon xforms-disable-hint-as-tooltip xforms-disable-alert-as-tooltip {xxf:get-request-parameter('my-param')} yui-skin-sam"`.

**Comment by ebruchez** [comment]
I reproduce the issue, but I don't know the cause yet.

**Comment by acspike** [comment]
When I modify [view.xsl:122](https://github.com/orbeon/orbeon-forms/blob/master/src/resources/apps/fr/components/view.xsl#L122)
```
￼--- a/src/resources/apps/fr/components/view.xsl
+++ b/src/resources/apps/fr/components/view.xsl
@@ -119,7 +119,7 @@
     <xsl:template match="xh:body">
         <xsl:copy>
             <!-- .orbeon is here to scope all Orbeon CSS rules -->
-            <xsl:attribute name="class" select="string-join(('orbeon', concat('xforms-', if ($is-inline-hints) then 'disable' else 'enable', '-hint-as-tooltip'), 'xforms-disable-alert-as-tooltip', @class), ' ')"/>
+            <xsl:attribute name="class" select="string-join(('orbeon', 'test-{1+2}', concat('xforms-', if ($is-inline-hints) then 'disable' else 'enable', '-hint-as-tooltip'), 'xforms-disable-alert-as-tooltip', @class), ' ')"/>
             <xsl:apply-templates select="@* except @class"/>
             <xf:group model="fr-form-model" id="fr-view" class="container{if ($fluid) then '-fluid' else ''} fr-view {{concat('fr-mode-', $fr-mode)}}" xxf:element="div">
                 <xh:div class="popover-container-right"/>
```

Following the execution in the debugger I can see {1+2} evaluated to 3, but, as you know, it never finds its way to the output. Any pointers on where to look further?

**Comment by hgoetzger** [comment]
It's reproducible even without using form builder. In handwritten forms, a simple 

    <xh:body class="{$lang}">

has the same effect, it's not interpreted in the resulting html.

(Glad to see that's an issue, not a problem of the form editor :relaxed:)

**Comment by ebruchez** [comment]
That was an easy one to fix so I just went ahead. The AVT was recognized and computed, but the code handling `<body>` was not processing AVTs.
