### ISSUE TITLE
Repeated grid - problem with value from external node

### ISSUE THREAD

**Issue by g4toor** [orbeon/orbeon-forms#2123]
For the following code I have a problem with setting the values in the control-10 and control-11.
What's wrong in this case?

            
            <xf:instance id="fr-form-instance" xxf:exclude-result-prefixes="#all">
                <form>
                    <section-1>
                        <kompletny>
                            <kod>01 01 01</kod>	
                            <rodzaj>some text 1</rodzaj>
                        </kompletny>
                        <kompletny>
                            <kod>01 01 02</kod>	
                            <rodzaj>some text 2</rodzaj>
                        </kompletny>
                        <control-1/>
                        <grid-6>
                            <grid-6-iteration>
                                <control-8/>
                                <control-9/>
                                <control-10/>
                                <control-11/>
                            </grid-6-iteration>
                        </grid-6>
                        <control-12/>
                    </section-1>
                </form>
            </xf:instance>

            
            <xf:bind id="fr-form-binds" ref="instance('fr-form-instance')">
                <xf:bind id="section-1-bind" name="section-1" ref="section-1">
                    <xf:bind id="control-1-bind" name="control-1" ref="control-1"/>
                    <xf:bind id="grid-6-bind" ref="grid-6" name="grid-6">
                        <xf:bind id="grid-6-iteration-bind" ref="grid-6-iteration" name="grid-6-iteration">
                            <xf:bind id="control-8-bind" ref="control-8" name="control-8"/>
                            <xf:bind id="control-9-bind" ref="control-9" name="control-9" calculate="../control-8"/>
                            <xf:bind id="control-10-bind" ref="control-10" name="control-10"
                                     calculate="//kompletny[kod=../control-8]/kod"/>
                            <xf:bind id="control-11-bind" ref="control-11" name="control-11"
                                     calculate="//kompletny[kod=../control-8]/rodzaj"/>
                        </xf:bind>
                    </xf:bind>
                    <xf:bind id="control-12-bind" ref="control-12" name="control-12"
                             calculate="//kompletny[kod=../control-1]/rodzaj"/>
                </xf:bind>
            </xf:bind>

            
            <xf:instance xxf:readonly="true" id="fr-form-metadata" xxf:exclude-result-prefixes="#all">
                <metadata>
                    <application-name>test</application-name>
                    <form-name>test</form-name>
                    <title xml:lang="en">Untitled Form</title>
                    <description xml:lang="en"/>
                    <singleton>false</singleton>
                </metadata>
            </xf:instance>

            
            <xf:instance id="fr-form-attachments" xxf:exclude-result-prefixes="#all">
                <attachments>
                    <css mediatype="text/css" filename="" size=""/>
                    <pdf mediatype="application/pdf" filename="" size=""/>
                </attachments>
            </xf:instance>

            
            
            <xf:instance id="fr-form-resources" xxf:readonly="false" xxf:exclude-result-prefixes="#all">
                <resources>
                    <resource xml:lang="en">
                        <control-12>
                            <label/>
                            <hint/>
                        </control-12>
                        <control-8>
                            <label/>
                            <hint/>
                        </control-8>
                        <control-9>
                            <label/>
                            <hint/>
                        </control-9>
                        <control-10>
                            <label/>
                            <hint/>
                        </control-10>
                        <control-11>
                            <label/>
                            <hint/>
                        </control-11>
                        <section-1>
                            <label>Untitled Section</label>
                        </section-1>
                        <control-1>
                            <label/>
                            <hint/>
                            <alert/>
                        </control-1>
                    </resource>
                </resources>
            </xf:instance>

            
            <xf:instance id="fr-service-request-instance" xxf:exclude-result-prefixes="#all">
                <request/>
            </xf:instance>

            <xf:instance id="fr-service-response-instance" xxf:exclude-result-prefixes="#all">
                <response/>
            </xf:instance>
            <xf:instance xxf:readonly="true" id="grid-6-template">
                <grid-6-iteration>
                    <control-8/>
                    <control-9/>
                    <control-10/>
                    <control-11/>
                </grid-6-iteration>
            </xf:instance>

        </xf:model>
    </xh:head>
    <xh:body>
        <fr:view>
            <fr:body xmlns:oxf="http://www.orbeon.com/oxf/processors"
                     xmlns:p="http://www.orbeon.com/oxf/pipeline"
                     xmlns:xbl="http://www.w3.org/ns/xbl">
                <fr:section id="section-1-control" bind="section-1-bind">
                    <xf:label ref="$form-resources/section-1/label"/>
                    <fr:grid>
                        <xh:tr>
                            <xh:td>
                                <xf:input id="control-1-control" bind="control-1-bind">
                                    <xf:label ref="$form-resources/control-1/label"/>
                                    <xf:hint ref="$form-resources/control-1/hint"/>
                                    <xf:alert ref="$fr-resources/detail/labels/alert"/>
                                </xf:input>
                            </xh:td>
                            <xh:td/>
                        </xh:tr>
                    </fr:grid>
                    <fr:grid id="grid-6-grid" bind="grid-6-bind" repeat="content" min="1"
                             template="instance('grid-6-template')">
                        <xh:tr>
                            <xh:td>
                                <xf:input id="control-8-control" bind="control-8-bind">
                                    <xf:label ref="$form-resources/control-8/label"/>
                                    <xf:hint ref="$form-resources/control-8/hint"/>
                        
                                    <xf:alert ref="$fr-resources/detail/labels/alert"/>
                                </xf:input>
                            </xh:td>
                            <xh:td>
                                <xf:input id="control-9-control" bind="control-9-bind">
                                    <xf:label ref="$form-resources/control-9/label"/>
                                    <xf:hint ref="$form-resources/control-9/hint"/>
                                    <xf:alert ref="$fr-resources/detail/labels/alert"/>
                        
                        
                                </xf:input>
                            </xh:td>
                            <xh:td>
                                <xf:input id="control-10-control" bind="control-10-bind">
                                    <xf:label ref="$form-resources/control-10/label"/>
                                    <xf:hint ref="$form-resources/control-10/hint"/>
                                    <xf:alert ref="$fr-resources/detail/labels/alert"/>
                        
                        
                                </xf:input>
                            </xh:td>
                            <xh:td>
                                <xf:input id="control-11-control" bind="control-11-bind">
                                    <xf:label ref="$form-resources/control-11/label"/>
                                    <xf:hint ref="$form-resources/control-11/hint"/>
                                    <xf:alert ref="$fr-resources/detail/labels/alert"/>
                        
                        
                                </xf:input>
                            </xh:td>
                        </xh:tr>
                    </fr:grid>
                    <fr:grid>
                        <xh:tr>
                            <xh:td>
                                <xf:input id="control-12-control" bind="control-12-bind">
                                    <xf:label ref="$form-resources/control-12/label"/>
                                    <xf:hint ref="$form-resources/control-12/hint"/>
                                    <xf:alert ref="$fr-resources/detail/labels/alert"/>
                        
                        
                                </xf:input>
                            </xh:td>
                        </xh:tr>
                    </fr:grid>
                </fr:section>
            </fr:body>
        </fr:view>
    </xh:body>

**Comment by avernet** [comment]
What do you mean by "a problem with setting the values"?

- How can we reproduce the problem?
- What behavior to you see?
- What is the behavior you expected?

**Comment by g4toor** [comment]
When I type in control-8 value "01 01 01" in control-10 should appear value with node "//kompletny[kod=../control-8]/kod", in control-11 should appear value with node "//kompletny[kod=../control-8]/rodzaj". I use command "calculate". It works for normal input in section, but does not work with repeated grid.

**Comment by orbeon** [comment]
So, what do you expect to see in control-10? I.e. what value do expect to
see there; what do you expect your XPath expression to return?

(And for my own reference, I have this form locally under
http://localhost:8080/orbeon/fr/orbeon/builder/edit/feb26760bf2400e7cfd353476cbe567ae31408f6
.)

**Comment by g4toor** [comment]
In control-10 value "01 01 01", in control-11 value "some text 1".

**Comment by avernet** [comment]
Got it. This is what I see in the form after having type in control-8 the value "01 01 01":

![screen shot 2015-03-16 at 10 10 59 am](https://cloud.githubusercontent.com/assets/106961/6671766/d539096c-cbc4-11e4-80e7-35106e9f6198.png)

The structure of your data is as follows:

```xml
<form>
    <section-1>
        <kompletny>
            <kod>01 01 01</kod> 
            <rodzaj>some text 1</rodzaj>
        </kompletny>
        <kompletny>
            <kod>01 01 02</kod> 
            <rodzaj>some text 2</rodzaj>
        </kompletny>
        <control-1/>
        <grid-6>
            <grid-6-iteration>
                <control-8/>
                <control-9/>
                <control-10/>
                <control-11/>
            </grid-6-iteration>
        </grid-6>
        <control-12/>
    </section-1>
</form>
```

- `control-10` is calculated as `//kompletny[kod=../control-8]/kod`. This won't match anything, as `control-8` is never a sibling of `kompletny`. You could write: `//kompletny[kod=$control-8]/kod`. This will give you the result you expected. Here `$control-8` refers to the value of that control that is "on the same line", which, I think, is exactly what you want.
- And, same thing for `control-11`: use `//kompletny[kod=$control-8]/rodzaj`.

Closing this, as this isn't a bug. And note that unless you're fairly sure you've hit bug, I'd recommend you post on [the forum](http://discuss.orbeon.com/) instead of the bug base, to keep this space as much as possible focused on verified issues.
