### ISSUE TITLE
FB: Occasionally, when editing a label FB scrolls up and displays the edit box in the wrong place

### ISSUE THREAD

**Issue by ajw625** [orbeon/orbeon-forms#2125]
In the case of this screenshot, I created a new Input Field control at the bottom of a form. When I clicked on the label to edit it, this happened. This occurs intermittently. I haven't discerned a pattern.

I can still enter the label and it works fine. I just have to scroll back down to the bottom of the form.

I am using Chrome and Orbeon 4.8.1.

![image](https://cloud.githubusercontent.com/assets/9143532/6629918/4e6deea8-c8d0-11e4-8d45-a20aa91bfd82.png)

**Comment by avernet** [comment]
Yes, we'll try to fix this quickly, and already have an issue for this: #2093.
