### ISSUE TITLE
Liferay Proxy Portlet - init-param "enable-url-parameters" is backwards

### ISSUE THREAD

**Issue by ajw625** [orbeon/orbeon-forms#2138]
In the portlet.xml, the default is:

    <init-param>
        <name>enable-url-parameters</name>
        <value>false</value>
    </init-param>

With this default setting, "form selection via URL parameters" should not be enabled, but it is.

Changing the value to true disables the feature.

**Comment by ebruchez** [comment]
This was introduced with 8e9c5636ab0ab6952b7fa5f5dec43a5200f24122 for #1850.
