### ISSUE TITLE
Processes: confirm then navigate doesn't wait for confirmation

### ISSUE THREAD

**Issue by evlist** [orbeon/orbeon-forms#2140]
In a process, when `confirm` is followed immediately or not by `navigate` the `confirm`is displayed and closed without waiting for confirmation!

**Comment by ebruchez** [comment]
You must write:

```
confirm
then suspend
then ...
```

The `confirm` action is not synchronous, so the process *must* be suspended right after. Now one question would be: does it ever make sense not to suspend the process after `confirm`? If no, possibly `confirm` should include `suspend`. But we would have to deal with backward compatibility.

**Comment by evlist** [comment]
OK, thanks!
