### ISSUE TITLE
Non localized buttons in confirmation dialogs

### ISSUE THREAD

**Issue by evlist** [orbeon/orbeon-forms#2143]
In this screenshot, FR buttons are (correctly) localized in French but the "No/Yes" buttons in the confirmation dialog are in English:

![Screenshot](https://cloud.githubusercontent.com/assets/109022/6787504/946db142-d193-11e4-83a7-63e3a95d1cf0.png)

**Comment by ebruchez** [comment]
I see a few "TODO: i18n" in the [source](https://github.com/orbeon/orbeon-forms/blob/master/src/resources-packaged/xbl/orbeon/alert-dialog/alert-dialog.xbl).

The bottom line is that it doesn't work because it's not implemented!

**Comment by avernet** [comment]
[+1 from customer](https://basecamp.com/1721271/projects/8811504/messages/40130434)
