### ISSUE TITLE
Publish Dialog Jumps on First Interaction

### ISSUE THREAD

**Issue by acspike** [orbeon/orbeon-forms#2147]
After the fb-publish-dialog is shown on the page the first time a user clicks the publish button, the dialog jumps upward on the page on the very next interaction. This appears to be because when the the first time yuiDialog.center() is called at xforms.js:2445 the inner content of the dialog has not been shown, ie, it is centering an empty dialog with only the title bar. Shortly after this call the inner contents are displayed (I think at ORBEON.xforms.Controls.toggleCase(controlVisibilityChangeId, visible); at AjaxServer.js:1704). The next time yuiDialog.center() is called the dialog jumps into its appropriately central place.

**Comment by avernet** [comment]
Are you talking about those 2 dialogs?

![screen shot 2015-03-26 at 10 47 28 am](https://cloud.githubusercontent.com/assets/106961/6853031/9dffde4c-d3a5-11e4-9052-0a1975978719.png)
![screen shot 2015-03-26 at 10 47 44 am](https://cloud.githubusercontent.com/assets/106961/6853032/9e1de202-d3a5-11e4-8063-c4988a20eb7c.png)

**Comment by acspike** [comment]
I'm talking specifically (and only) about the first one. I thought this might be the same but as the LHHAEditor, but it isn't. I have observed this in both Firefox and Chrome. Happy to offer more detail if needed.

**Comment by avernet** [comment]
Yes, I see that now. Will look into it.

**Comment by ebruchez** [comment]
Upon showing the dialog the first time, we have:

```xml
<xxf:div id="fb-publish-dialog" visibility="visible" constrain="true"/>
```

And then after publish, with the dialog stll visible we have another:

```xml
<xxf:div id="fb-publish-dialog" visibility="visible" constrain="true"/>
```

This seems wrong as well.

**Comment by ebruchez** [comment]
The duplicate `visibility="visible"` comes down to a bug in the diffing.

**Comment by avernet** [comment]
Confirming that Erik's change to the diff algorithm is fixing this. Closing, and will be in 4.9.
