### ISSUE TITLE
New component supporting to capture a "drawn" signature

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2160]
We would implement this leveraging the wPaint library, which we already use for the image annotation component. The component would work on iOS/Android (signing with your finger) and on desktops (using the mouse). On the desktop, it would require IE9, as the canvas, used by wPaint, wasn't available with IE8.

![signature](https://cloud.githubusercontent.com/assets/106961/6986765/56e0a284-d9f5-11e4-95bc-f218bcf0ae3e.png)

[+1 from customer](https://basecamp.com/1721271/projects/5519567)

**Comment by avernet** [comment]
[+1 from community](http://discuss.orbeon.com/Does-Orbeon-Support-Signature-Handwritten-Signature-in-Mobile-Forms-td4660684.html)

**Comment by riteshnarain** [comment]
Is this something that can be done by us on our own or will we need Orbeon to develop this as a core form functionality?

Ritesh

**Comment by riteshnarain** [comment]
Is this something that we can do or will we need Orbeon to add support?

Ritesh

**Comment by ebruchez** [comment]
@riteshnarain It could be done either way. We have some [documentation](http://doc.orbeon.com/xforms/xbl/index.html) on writing XBL components.

**Comment by ebruchez** [comment]
[+1 from customer](https://basecamp.com/1721271/projects/6131438/messages/50691951)

**Comment by avernet** [comment]
Implemented, will be in 4.11 PE.
