### ISSUE TITLE
Double slash in calls to external eXist

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2170]
Setup and external eXist, e.g. on port 9080. Add the following property:

```xml
<property as="xs:anyURI"  name="oxf.fr.persistence.exist.exist-uri"
          value="http://admin:@localhost:9080/exist/rest/db/orbeon/fr"/>
```

In Form Builder create a new form and save. With HTTPScoop notice the request goes to:

```
http://localhost:9080/exist/rest/db/orbeon/fr//orbeon/builder/data/258b39b3595a657a06a47a5d502f8eb673c3cf17/data.xml
```

**Comment by avernet** [comment]
[+1 from community](http://discuss.orbeon.com/Double-slashes-in-eXist-db-interface-td4659741.html)

**Comment by namgang** [comment]
Every slash in an URL is significant, so the outcome depends on undocumented behaviour in eXist-db. /Hakan
