### ISSUE TITLE
Improve performance of DOM updates with large forms

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2174]
When using a large form with lots of required fields, saving the form just after opening it, lots of DOM updates will happen to mark the fields as invalid, and this, on Chrome in particular, can take a noticeable amount of time.

**Comment by avernet** [comment]
Improved by f28b6ba5990cb3409f0a5758b7ba1b6e7cdf412e and (most noteably) 318d988c3db4afa8c295727ce2c8fa3c03cff8cd.

**Comment by ebruchez** [comment]
@avernet to cherry-pick on 4.9 branches.
