### ISSUE TITLE
Recalculation order based on variables dependencies

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2186]
We have #1192, which is a bit more ambitious. This issues is about a simpler scenario: binds created by Form Builder which refer to control values by variables such as `$foo` and `$bar`.

This makes it fairly easy to determine dependencies between nodes and to determine a recalculation order.

Later this can be improved, based on path projection, to also include dependencies based on paths.

**Comment by ebruchez** [comment]
- [ ] unit tests
- [ ] doc

**Comment by ebruchez** [comment]
I found that a customer's form had issues with a circular dependency when this is enabled. I think we need to:

- [ ] check that customer form to make sure it's not a bug in the implementation
- [ ] if we make this he "default" in 4.10, we should make it only for new forms (so in `templates.xml`
- [ ] Form Builder should have an option in Form Settings to control `xpath-analysis` and `analysis.calculate`

**Comment by avernet** [comment]
[+1 from customer](https://basecamp.com/1721271/projects/11627252/messages/54277921)

**Comment by ebruchez** [comment]
+1 from @avernet when doing demo

**Comment by ebruchez** [comment]
Updated list of tasks above.

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/1966555/messages/1041438586)

**Comment by ebruchez** [comment]
What would it take to indicate, in Form Builder, circular dependencies to the user? We need to be able to:

- run the algorithm on the binds
- show the information somewhere

Should it be a specific "inspection" which runs on the form? Or something which is computed at all times?

**Comment by ebruchez** [comment]
[Documented](https://doc.orbeon.com/form-runner/features/automatic-calculations-dependencies)

**Comment by ebruchez** [comment]
Moved remaining tasks to #3798.
