### ISSUE TITLE
frf:sendError(403) just logs the error

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2194]
To reproduce, create a form in Form Builder where anonymous users can only create data. Then, as an anonymous user, access the summary page for that form. You should get a 403, but instead get a page.

The `frf:sendError(403)` in `fr/summary/view.xhtml` is properly thrown, but it is now just logged, most likely due to changes done for #2161.

**Comment by ebruchez** [comment]
Regressed with #2161.
