### ISSUE TITLE
IllegalArgumentException when testing form when cache sizes are set to 1

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2197]
To reproduce, set the following properties:

```xml
<property as="xs:integer" name="oxf.xforms.cache.documents.size"    value="1"/>
<property as="xs:integer" name="oxf.xforms.cache.static-state.size" value="1"/>
```

Restart, create a form in Form Builder, and hit the Test button.

**Comment by ebruchez** [comment]
Curiously, it seems like setting *both* caches to `1` is needed to cause the issue. Setting them to `1` independently is not enough.

**Comment by ebruchez** [comment]
In my case, to reproduce, I must click somewhere in the test iframe after it loads, for example the "Validate" button.

What happens then is that there are 2 Ajax requests dispatched:

1. one with `xxforms-blur` on Form Builder
2. one with `xforms-focus` etc. on the tested form

The first one causes Form Builder to deserialize with an error. I haven't figured out yet why.

**Comment by ebruchez** [comment]
The issue is at:

```scala
val controlScope = scopeForPrefixedId(controlPrefixedId)
```

for `controlPrefixedId == "xf-357"`

**Comment by ebruchez** [comment]
But `xf-357` is present in both the original static state and the new one. It might be that somehow the scope map is not updated properly.

**Comment by ebruchez** [comment]
Doing a dump of `PartXBLAnalysis.prefixedIdToXBLScopeMap` just after `initializeScopes()` in `PartAnalysisImpl`, it turns out that some ids are in fact missing upon restore:

- ids of HTML elements referred to by `for` on AVTs (which shouldn't be there anyway, but don't actively hurt)
- ids of XBL bound elements such as `fr:link-select1`, etc.

This appears to be systematic.

**Comment by ebruchez** [comment]
The issue was due to the addition of a test on `inBody` in `XFormsAnnotator`. Upon restore, `inBody` was never `true`, because the structure is `<static-state>` etc., not `<xhtml:html>` etc.

**Comment by ebruchez** [comment]
Also, the reason both caches need to be set to `1` is that if the doc cache is bigger and the dynamic state remains in memory, the static state does as well, as it is kept by reference even if it expires from cache.

**Comment by ebruchez** [comment]
Had regressed with #1936.
