### ISSUE TITLE
Expose autosize feature in Form Builder

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2211]
The textarea control supports "autosizing" itself based on its content. This is enabled by adding `appearance="xxf:autosize"` on the `<xf:textarea>`. This RFE calls for adding a feature to Form Builder that would allow form authors to enable this feature for any textarea in their form without having to edit the source of the form.

**Comment by ebruchez** [comment]
Seems trivial with the latest XBL changes.
