### ISSUE TITLE
fr:spell-checker causing "assertion failed" in XForms engine

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2213]
To reproduce, load the [spell checker test](http://localhost:8080/orbeon/xforms-sandbox/sample/xbl/orbeon/spell-checker/spell-checker-unittest) and click on a the first *Spell check* button.

[+1 from community](http://discuss.orbeon.com/spellchecker-td4659882.html)

**Comment by ebruchez** [comment]
Now also addressed related #243.
