### ISSUE TITLE
XBL engine to generate span, not label if xxbl:mode="lhha" without xxbl:label-for

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2219]
Right now, when we have `xxbl:mode="lhha"` without `xxbl:label-for`, the XBL engine generates a `<label>` without a `for`, which isn't valid per WCAG2 1.3.1 (A), reported by TotalValidator as E885. Generating a `<span>` will solve that. It will then be the responsibility of the component author to put an `aria-labelledby` in the markup they generate.

(In cases where that markup isn't produced  with JavaScript, we would want the XBL engine to produce an id on the `<span>` with the label, and provide a way to access that id, like a convention or better a function, but this isn't a requirement to solve this issue.)

**Comment by avernet** [comment]
More changes than I initially expected are needed for this one, as the code currently expects to always generate the same HTML element name for an `<xf:label>`, and that element is configurable with the `oxf.xforms.label-element` property. But in this case, we want the name of the element to be different when there is no `xxbl:label-for`. Should we just in that case not honor `oxf.xforms.label-element` and generate a `span`? This seems to somewhat break the configurability of the system.

**Comment by ebruchez** [comment]
@avernet As we discussed, it is ok to force `<xh:span>` in that case, and arguably the `oxf.xforms.label-element` shouldn't even be there.
