### ISSUE TITLE
With eXist, deleted attachments are not deleted from the database

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2230]
For a given document (form data), when an attachment is removed and the data saved, the attachment is still kept in the database, while we could remove it. This is something we can't do (and don't want to do) for relational databases, as we keep the old "version" of the data, and so need to keep the relevant attachment.

**Comment by ebruchez** [comment]
@avernet Didn't you write SQL to address this one too?

**Comment by avernet** [comment]
Yes, we have SQL to [remove old data, and the related attachments](https://github.com/orbeon/orbeon-forms/wiki/Form-Runner-~-Database-~-Purging-old-data) on Oracle; that SQL is a sort of "empty trash". And this issue is for eXist.

**Comment by ebruchez** [comment]
Oh right, this was for eXist and I missed that.

**Comment by ebruchez** [comment]
Closing, see #5770.
