### ISSUE TITLE
New function to know that we are in Form Builder

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2231]
Possible names for that function would be `fr:design-time()` or `fr:in-form-builder()`. As a workaround, right now we can test the app/form name are `orbeon/builder`.

[+1 from community](http://discuss.orbeon.com/xbl-component-quot-am-I-in-the-builder-quot-td4659909.html)

**Comment by avernet** [comment]
[+1 from community](http://stackoverflow.com/questions/33838202/can-the-javascript-attached-to-xbl-control-know-what-mode-the-form-is-in)

**Comment by ebruchez** [comment]
This should very easy to do. The only issue is the function library hookup, see #1095.

**Comment by ebruchez** [comment]
Function `fr:is-design-time()` implemented with #1095 and d9b9ac36e6f5fcfccf240b3b56e730fd4417042c.
