### ISSUE TITLE
Allow initial dialog to be bypassed with app/form name specified on the URL

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2245]
The idea is that a 3rd-party page could link to Form Builder's /new page, providing values for the app/form name, in which case the initial dialog wouldn't need to be shown.

The value of the parameters will be subject to the same restrictions as values for app/form name entered by users, so enabling this by default isn't a security risk and we won't need to protect this feature being a property to-be-enabled.

[+1 from community](http://discuss.orbeon.com/New-form-URL-in-builder-can-I-include-appname-and-formname-td4659960.html)

**Comment by ebruchez** [comment]
In particular, app/name:

- must be valid identifiers as enforced by the dialog
- must satisfy Form Builder permissions restrictions on available app/form/names

**Comment by bwallis42** [comment]
Could you also include the form title as a parameter?

**Comment by ebruchez** [comment]
@bwallis42 That seems reasonable.

**Comment by avernet** [comment]
[+1 from community](http://stackoverflow.com/questions/30590090/retrieve-form-data-id-using-orbeon-api)

**Comment by ebruchez** [comment]
- [ ] check what to do with `fr-singleton`
- [ ] doc new URL parameters are behavior

**Comment by ebruchez** [comment]
[Documented](https://github.com/orbeon/orbeon-forms/wiki/Form-Builder-~-Integration#bypassing-the-new-form-dialog)
