### ISSUE TITLE
Use zebra-striping on home and summary page

### ISSUE THREAD

**Issue by acspike** [orbeon/orbeon-forms#2246]
Because each table row is separated by an invisible:
```
<tr class="xforms-repeat-delimiter"></tr>
```
the visible rows are effectively either all odd or all even. This design renders bootstrap's table-striped class ineffective.

The following styles add back stiped rows:
```
  .orbeon .table-striped tbody > tr:nth-child(n) > td,
  .orbeon .table-striped tbody > tr:nth-child(n) > th {
    background-color: white;
  }
  .orbeon .table-striped tbody > tr:nth-child(4n+2) > td,
  .orbeon .table-striped tbody > tr:nth-child(4n+2) > th {
    background-color: #f9f9f9;
  }
  .orbeon .table-striped tbody > tr:nth-child(4n+3) > td,
  .orbeon .table-striped tbody > tr:nth-child(4n+3) > th {
    background-color: #f9f9f9;
  }
```

Depending on where else table-striped is used in orbeon, it may be better to create a separate class for striping these tables.

**Comment by avernet** [comment]
We only used `.table-striped` on the home page, and, for the reason you mentioned @acspike, it wasn't working. So, instead, I removed the `.table-striped`, and did the zebra-stripping "by hand", using CSS similar to what Bootstrap has for `.table-striped`. Thank you for pointing our attention to this one!

**Comment by acspike** [comment]
Does this stripe the form summary page too? Or is there a reason .table-striped was only used on the home page?

**Comment by ebruchez** [comment]
It doesn't seem to stripe the Summary page. And yes, we should stripe the Summary page too! @avernet ?

**Comment by avernet** [comment]
Yes, we should. I changed the title and reopened the issue.
