### ISSUE TITLE
"Review" makes all the sections accessible in wizard validated mode

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2253]
We need a mechanism not to show the *review* and *save* buttons, unless we are on the last page.

[+1 from community](http://discuss.orbeon.com/new-wizard-validated-mode-review-button-validates-all-sections-td4659973.html)

**Comment by ebruchez** [comment]
[+1 from customer](https://basecamp.com/1721271/projects/3412232/messages/46504063)

**Comment by ebruchez** [comment]
What is the ideal mechanism to achieve this? What we want to say is: "Hide or disable this button until such and such condition is met."

That condition here is transient: it's whether the user has reached (we use `xxf:visited()`) the last page of the wizard. Only the wizard knows the id to check to know whether the last section is visited.

How can we let the button know about this condition? I would think we would want to express that in terms of a function like `fr:wizard-reached-last-page()`.

**Comment by ebruchez** [comment]
[+1 from user](https://mail.google.com/mail/u/0/#inbox/151aa35bfb8f8bba)

**Comment by ebruchez** [comment]
My comment above is not necessarily wrong. We have at least 2 different possibilities:

1. Show the button if all sections have been visited.
2. Show the button *only* when we are on the last page of the wizard.

We already expose publicly the `fr-wizard-prev` and `fr-wizard-next` buttons, which are within the wizard, and make them accessible via `xxf:binding()` so we can have external buttons which are enabled/disabled at the same time.

We could have another such public binding which controls the visibility of a `wizard-submit` button, for example.
