### ISSUE TITLE
Form data includes XML namespace attributes in repeated section iterations

### ISSUE THREAD

**Issue by ajw625** [orbeon/orbeon-forms#2278]
This occurs if a form has a repeated section and the form data has multiple iterations of that section. The XML namespace attributes are not included in the first iteration, but are included in subsequent iterations. See example form data:

    <form>
        <no-repeat-section>
            <dog-name>Rover</dog-name>
            <dog-skills>sit fetch</dog-skills>
        </no-repeat-section>
        <repeated-section>
            <repeated-section-iteration>
                <address-line-1>777 Pacific Blvd</address-line-1>
                <address-line-2/>
                <city>Vancouver</city>
                <province>BC</province>
            </repeated-section-iteration>
            <repeated-section-iteration xmlns:xxi="http://orbeon.org/oxf/xml/xinclude" xmlns:xh="http://www.w3.org/1999/xhtml" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:saxon="http://saxon.sf.net/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xxf="http://orbeon.org/oxf/xml/xforms" xmlns:xbl="http://www.w3.org/ns/xbl" xmlns:fb="http://orbeon.org/oxf/xml/form-builder" xmlns:sql="http://orbeon.org/oxf/xml/sql" xmlns:p="http://www.orbeon.com/oxf/pipeline" xmlns:fr="http://orbeon.org/oxf/xml/form-runner" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xf="http://www.w3.org/2002/xforms" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:exf="http://www.exforms.org/exf/1-0">
                <address-line-1>4545 Pierre-de-Coubertin Avenue</address-line-1>
                <address-line-2/>
                <city>Montreal</city>
                <province>QC</province>
            </repeated-section-iteration>
            <repeated-section-iteration xmlns:xxi="http://orbeon.org/oxf/xml/xinclude" xmlns:xh="http://www.w3.org/1999/xhtml" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:saxon="http://saxon.sf.net/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xxf="http://orbeon.org/oxf/xml/xforms" xmlns:xbl="http://www.w3.org/ns/xbl" xmlns:fb="http://orbeon.org/oxf/xml/form-builder" xmlns:sql="http://orbeon.org/oxf/xml/sql" xmlns:p="http://www.orbeon.com/oxf/pipeline" xmlns:fr="http://orbeon.org/oxf/xml/form-runner" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xf="http://www.w3.org/2002/xforms" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:exf="http://www.exforms.org/exf/1-0">
                <address-line-1>800 Griffiths Way</address-line-1>
                <address-line-2/>
                <city>Vancouver</city>
                <province>BC</province>
            </repeated-section-iteration>
        </repeated-section>
        <section-with-repeated-grid>
            <repeated-grid-1>
                <cat-name>Abbey</cat-name>
                <cat-breed>Abyssinian </cat-breed>
            </repeated-grid-1>
            <repeated-grid-1>
                <cat-breed>Persian</cat-breed>
                <cat-name>Percy</cat-name>
            </repeated-grid-1>
        </section-with-repeated-grid>
        <repeated-section-with-repeated-grid>
            <repeated-section-with-repeated-grid-iteration>
                <first-name>Anthony</first-name>
                <last-name>Hopkins</last-name>
                <repeated-grid-2>
                    <email-address>ahopkins@home.com</email-address>
                    <email-type>home</email-type>
                </repeated-grid-2>
                <repeated-grid-2>
                    <email-address>ahopkins@work.com</email-address>
                    <email-type>work</email-type>
                </repeated-grid-2>
            </repeated-section-with-repeated-grid-iteration>
            <repeated-section-with-repeated-grid-iteration xmlns:xxi="http://orbeon.org/oxf/xml/xinclude" xmlns:xh="http://www.w3.org/1999/xhtml" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:saxon="http://saxon.sf.net/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xxf="http://orbeon.org/oxf/xml/xforms" xmlns:xbl="http://www.w3.org/ns/xbl" xmlns:fb="http://orbeon.org/oxf/xml/form-builder" xmlns:sql="http://orbeon.org/oxf/xml/sql" xmlns:p="http://www.orbeon.com/oxf/pipeline" xmlns:fr="http://orbeon.org/oxf/xml/form-runner" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xf="http://www.w3.org/2002/xforms" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:exf="http://www.exforms.org/exf/1-0">
                <repeated-grid-2>
                    <email-address>bpitt@home.com</email-address>
                    <email-type>home</email-type>
                </repeated-grid-2>
                <repeated-grid-2>
                    <email-address>bpitt@work.com</email-address>
                    <email-type>work</email-type>
                </repeated-grid-2>
                <last-name>Pitt</last-name>
                <first-name>Brad</first-name>
            </repeated-section-with-repeated-grid-iteration>
        </repeated-section-with-repeated-grid>
    </form>

**Comment by ebruchez** [comment]
I reproduce this.

**Comment by ebruchez** [comment]
- [ ] insert `xxf:exclude-result-prefixes="#all"` when creating template
- [ ] `annotate.xpl` must add `xxf:exclude-result-prefixes="#all"` if missing
- [ ] annotate tests must check `xxf:exclude-result-prefixes="#all"` is added
