### ISSUE TITLE
format-multiple.xpl skips certain namespaces

### ISSUE THREAD

**Issue by ahenket** [orbeon/orbeon-forms#2279]
When you call format-multiple.xpl it does not do all namespace declarations in the xml it formats. It skips namespaces that were declared on ancestors. However when you redeclare under a different prefix that also skips useful information:

    <REPC_IN000023NL xmlns="urn:hl7-org:v3">
        <patientID>
            <value root="2.16.840.1.113883.2.4.6.3" extension="999999035"/>
        </patientID>
        <hl7:patientID xmlns:hl7="urn:hl7-org:v3">
            <hl7:value root="2.16.840.1.113883.2.4.6.3" extension="999999035"/>
        </hl7:patientID>
        <patientID>
            <value xsi:type="s0:II" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:s0="urn:hl7-org:v3" root="2.16.840.1.113883.2.4.6.3" extension="999999035"/>
        </patientID>
    </REPC_IN000023NL>

Redeclaring happens for all sorts of reasons in all sorts of engines outside of the span of control of a user. Hence there's no preventing it from happening. What I would like from the formatter is to be as accurate as possible in what's going on.

The offending line in ops/utils/formatting/xml-formatting.xsl is this one:

    <xsl:variable name="namespace-nodes" select="namespace::*[name() != 'xml' and not(. = $current-element/ancestor::*/namespace::*)]"/>

Propose to change to this:

    <xsl:variable name="namespace-nodes" as="item()*">
        <xsl:for-each select="namespace::*[name() != 'xml']">
            <xsl:variable name="namespace-prefix" select="name()"/>
            
            <xsl:copy-of  select=".[not(. = $current-element/ancestor::*/namespace::*[name()=$namespace-prefix])]"/>
        </xsl:for-each>
    </xsl:variable>

**Comment by ebruchez** [comment]
@ahenket Agreed, in general redeclarations should be maintained. Does your suggested change work?

**Comment by ahenket** [comment]
It works when I debug in Oxygen directly. I have no idea how to make a patch for it in Orbeon 4.7 that we run. Because of oxfords:tree we cannot upgrade currently. Assistance in making the right patch appreciated.

**Comment by ebruchez** [comment]
You can patch it locally by placing your modified file under:

    WEB-INF/resources/ops/utils/formatting/xml-formatting.xsl

**Comment by ebruchez** [comment]
And I suppose that `oxfords:tree` is `xxf:tree`? ;)

**Comment by ahenket** [comment]
:-) We all love auto-correct don't we? Back to business: I've created the path ops/utils/formatting and placed xml-formatting.xsl under there, restarted Orbeon 4.7 and can now confirm it works as (I) advertised.

**Comment by ebruchez** [comment]
Great, I'll include this on master.
