### ISSUE TITLE
FR excel import fails to import non string cells

### ISSUE THREAD

**Issue by evlist** [orbeon/orbeon-forms#2294]
Excel cells which are not typed as string are seen as empty by the FR excel feature.

**Comment by evlist** [comment]
The [XSLT instruction](https://github.com/orbeon/orbeon-forms/blob/master/src/resources/apps/fr/import/apply.xpl#L75) to get cell values is currently `<xsl:value-of select="if (exists(@t)) then $strings/*/ms-main:si[xs:integer($v) + 1]/ms-main:t else $v"/>`.

Non string cells do have `@t` attributes, for instance for a number: `<c r="B4" s="0" t="n"><v>8</v></c>` and the formula should be `<xsl:value-of select="if (@t = 's') then $strings/*/ms-main:si[xs:integer($v) + 1]/ms-main:t else $v"/>`.

**Comment by ebruchez** [comment]
Look good, thanks!
