### ISSUE TITLE
Asterisk not turning grey for fields date and dropdown date

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2310]
Required controls, when empty, get the classes `xforms-required` and `xforms-empty`. When a value is provided, `xforms-empty` is removed, and this is used to show a red or grey asterisk.

XBL controls like the fields date and dropdown date with `xxbl:mode="binding value"` do get `xforms-empty`, but that class isn't removed when the value is provided.

Removal of the class is done when the server responds with a `<xxf:control empty="false">` for the given control, but the server doesn't provide this information to the client.

**Comment by ebruchez** [comment]
Reason:

- `XFormsValueComponentControl` does not expose an external value
- but `equalsExternal` compares `getExternalValue`
- therefore `outputAjaxDiff` does not run
- which means that the `empty` value is not updated
