### ISSUE TITLE
Responsive design also kicks in in desktop

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2312]
Maybe not a big issue per se, but some mobile features appear:

- larger font size in controls
- very large buttons at bottom
- also might affect IE 11, not sure if that explains 2nd screenshot below

![responsive](https://cloud.githubusercontent.com/assets/105769/8662420/213fae1c-2974-11e5-9d1f-9a3c583f3f80.png)

![ie11](https://cloud.githubusercontent.com/assets/105769/8662450/825baaa2-2974-11e5-855a-59e0865ae68a.png)

**Comment by avernet** [comment]
Resolutions from discussion with Erik about font too large:

- [ ] Change our current code putting a class if iOS to something more modern
    - [ ] Doubt there is something detecting a zoom on click
    - [ ] Short of that, use detection code for iOS
    - [ ] Use that class to set the size to 16px
- [ ] Consider using similar code to trigger iOS date/time picker, which might solve #2084

**Comment by avernet** [comment]
I'm not seeing the issue shown on the screenshot with IE8. In fact, our responsive stylesheet doesn't seem to have an effect on IE8, as media queries don't [seem be supported by IE before IE9](http://stackoverflow.com/a/7234811/5295). Closing.

![IE8](http://i.imgur.com/Dhy4EM7.png)
