### ISSUE TITLE
Custom PDF Template does not display drop down controls

### ISSUE THREAD

**Issue by cetra3** [orbeon/orbeon-forms#2331]
In PE, drop down control values don't appear to be added in PDF Template forms when attaching a PDF to a form.

Replication as follows:

* Create a form runner form.
* Create a new section called `test`
* Create a dropdown called `test-dropdown`
* With Adobe Professional (or simliar), open a PDF document
* Add a new field (either text field or drop down)
* Name that field `test$test-dropdown`
* Save it and attach to the form
* Create the form, selecting a default value from the drop down.
* View the PDF

To make matters worse, the dropdown is in a repeat field, but it does not work in either a repeat or non-repeat section.

**Comment by ebruchez** [comment]
@cetra3 Thanks, will try to reproduce.

**Comment by yeyan** [comment]
Run into the same issue here. Dropdown control values are completely ignore by PDF template

**Comment by ebruchez** [comment]
Thanks for the reports, I will look into it.
