### ISSUE TITLE
Support for event('response-body') appears to be gone

### ISSUE THREAD

**Issue by ahenket** [orbeon/orbeon-forms#2336]
Using the following statement I used to get the HTTP body in Orbeon 3.9 from the server when there's an error, but in Orbeon 4.7 I get nothing and the message ends at "Body: "

```xml
<xf:submission 
    id="get-user-groups" 
    serialization="none" 
    method="get" 
    resource="http://www.example.org/xxx" 
    replace="instance" 
    instance="user-groups">
    <xf:message ev:event="xforms-submit-error" level="modal">
        A submission error occurred: <xf:output value="event('error-type')"/>;
        Status: <xf:output value="event('response-status-code')"/>;
        URI: <xf:output value="event('resource-uri')"/>;
        Headers: <xf:output value="event('response-headers')"/>;
        Body: <xf:output value="event('response-body')"/>
    </xf:message>
</xf:submission>
```

Any hints? I looked at http://wiki.orbeon.com/forms/doc/developer-guide/xforms-logging#TOC-Development-configuration, but that only hints at logging. This is about telling the user what's up.

It appears to me as if there's a bug in supporting `event('response-body')`. orbeon.log has no info.

**Comment by ebruchez** [comment]
I suspect that this is a bug and that support for `event('response-body')` has regressed. We need to look into it.

**Comment by ebruchez** [comment]
Interestingly, in this particular case, this is an issue specifically due to the use of `xf:output` within an `xf:message`.

**Comment by ebruchez** [comment]
Had probably regressed with 8509dab902b4bd87f7269d50eeb56cb728d10037.
