### ISSUE TITLE
Bootstrap css .orbeon ing class contains illegal declaration

### ISSUE THREAD

**Issue by ahenket** [orbeon/orbeon-forms#2339]
The CSS declaration "width: auto\9;" is illegal and should be replaced with "width: auto;"

**Comment by ebruchez** [comment]
Thanks for reporting, but this is on purpose: it is a common hack for IE 7, 8 and 9, see this [StackOverflow question](http://stackoverflow.com/questions/8004765/css-9-in-width-property).
