### ISSUE TITLE
Image annotation doesn't work

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2342]
- create form with Image Annotation control
- don't attach image statically
- save & publish
- /new
- attach image
- annotate image
- save
- load
- image not annotated

**Comment by avernet** [comment]
@ebruchez Somehow, I can't reproduce this; here is what I do, am I missing anything?

![issue 2342](https://cloud.githubusercontent.com/assets/106961/9415963/a23467fa-47f7-11e5-93de-de865ad01af9.gif)

**Comment by ebruchez** [comment]
@avernet Can't reproduce either, but I notice something different issues now. Will close this one and open new ones.
