### ISSUE TITLE
Hidden fields in PDF documents

### ISSUE THREAD

**Issue by cetra3** [orbeon/orbeon-forms#2389]
More clarification here rather than an issue:

Sometimes we want to include some calculated fields into the PDF form but not have them visible within the web form. (for instance, formatting the full name, the current date, etc..)

When we add these fields as hidden, they do not appear in the resulting PDF Template.

Is this expected behaviour?

**Comment by ebruchez** [comment]
@cetra3 We don't handle hidden fields specifically. Also, we "flatten" the fields (see #1260), so I don't know what would need to be done exactly to handle hidden fields the way you would like to. Either way, this would probably require some work to figure out.

**Comment by cetra3** [comment]
@ebruchez So in your opinion should hidden fields show up in the resulting PDF?  Or is this just a use case that isn't handled at the moment.

We've worked around it by having the calculated fields in their own section on the web form, but it's a bit of an eye sore

**Comment by ebruchez** [comment]
@cetra3 Oh so maybe I didn't understand the original problem. Are you saying you have a *regular* PDF field in the PDF template, but that the field is hidden via a "Visibility" formula in the web form?

**Comment by cetra3** [comment]
@ebruchez Yes that's what I mean

In other words:

* Create a new form with the form builder
* Create a new section named `section`
* Create a new text field named `field` with a default value of `test`
* Use adobe to edit a PDF
* Create a form field of type text with the name `section$field`
* Attach this PDF as the template to the form
* Save, Publish & Run the form and observe that the output PDF has `test` as the output
* Reopen the form
* Change the `field` visibility to false, leaving the default value of `test`
* Save, Publish & Run the form and observe that the output PDF does not have `test`

**Comment by ebruchez** [comment]
@cetra3 What you want do do is make the field visible in PDF mode. Instead of changing the visibility to `false()`, change it to:

```ruby
$fr-mode = 'pdf'
```

**Comment by ebruchez** [comment]
Closing this as I assume that's been answered.

**Comment by cetra3** [comment]
Yes, my apologies for not closing it sooner.  The configuration you have provided works

**Comment by ebruchez** [comment]
Ok great, thanks for confirming @cetra3.
