### ISSUE TITLE
Consider making pages non-cacheable

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2391]
By default, for non-errors, we set the header in `oxf.http.page.cache-headers`, which is `Cache-Control: private, max-age=0; Pragma:`, which is a security risk in the following scenario:

1. Alice is using a shared computer, logs into Orbeon Forms, loads a form with private information, saves it and logs out, and leaves the browser window open.
2. Later, Mallory, on the same computer, hits back a few times and can see the information Alice had loaded. A dialog shows up on top of the form as the Ajax request fails, but Mallory can still see all the private information Alice had entered.

This problem is caught by AppScan (ref: [CWE-525](https://cwe.mitre.org/data/definitions/525.html)).

**Comment by ebruchez** [comment]
I don't see this one as a big deal, given the constraints that the computer is shared and the window is left open!

BTW, see this [SO question](http://stackoverflow.com/questions/49547/making-sure-a-web-page-is-not-cached-across-all-browsers). This comment resonates with  me:

> History mechanisms and caches are different. In particular history mechanisms SHOULD NOT try to show a semantically transparent view of the current state of a resource. Rather, a history mechanism is meant to show exactly what the user saw at the time when the resource was retrieved.

As a browser user, whether the resource is cacheable or not, I would expect the browser back to show me the page exactly as I left it, independently from browser settings.

This said, we have [internal properties](https://github.com/orbeon/orbeon-forms/blob/941eaa0767ea5714520ecd5fa58ccf96dfe23b5f/src/resources-packaged/config/properties-internal.xml#L43) to define the cache headers, so overriding them might do the trick.

**Comment by avernet** [comment]
One question is: if we don't let the browser cache pages, will the mechanism we have to restore page state when navigating the history work?

To test this, I've set `oxf.http.page.cache-headers` to `Cache-Control: no-cache, no-store, must-revalidate; Pragma: no-cache; Expires: 0`, which is the value we currently have for `oxf.http.nocache.cache-headers`, created a form with a checkbox showing an input, loaded a detail page, clicked the box, filled the input, clicked on the summary button, and then hit back. If the input shows with the value, then our restore mechanism works.

Currently, we store the UUID and sequence number in the hidden `$client-state` input. If on load we find something there, we use those values. Below Y means the restore work, N that it doesn't.

| Allow caching | No caching
--- | --- | ---
Chrome 45 | Y | Y
Firefox 38 | Y | N
IE11 | Y | N

It seems that IE and Firefox are not restoring form fields values navigation when the page isn't cacheable, which isn't completely unreasonable. This argues for keeping the pages cacheable, so the restoring mechanism can work across browsers.

**Comment by ebruchez** [comment]
We do have #1802 to use the browser's history mechanism. I wonder if that would be impacted by non-cacheable pages.

**Comment by avernet** [comment]
Since making pages non-cacheable breaks the "back" on IE and Firefox, we resolved *not* to make pages non-cacheable. And of course, should customers have different priorities, they can always set the `oxf.http.page.cache-headers` to `Cache-Control: no-cache, no-store, must-revalidate; Pragma: no-cache; Expires: 0`.
