### ISSUE TITLE
Edit Source no longer works

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2393]
An empty editor shows. Could it be due to the recent focus changes?

**Comment by avernet** [comment]
@ebruchez I'll look into it.

**Comment by avernet** [comment]
@ebruchez I'm not seeing this. Could it have been due to 37c2aecf264c950a33d3036c03ce64f5c1c0de81 / f45f63945ca8048ee2853e667596ec2938430c6e?

**Comment by ebruchez** [comment]
@avernet Yes that was the cause, closing.
