### ISSUE TITLE
Don't show appearance radio in Control Settings when there is only one

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2401]
For instance, the Control Settings for the autocomplete shows the following:

![Control Details](http://i.imgur.com/7oSeES1.png)

In a case like this there is no use in telling users in the Control Settings for the autocomplete that this autocomplete has the appearance of an autocomplete, and that this appearance can't be changed.

**Comment by ebruchez** [comment]
Very easy to do so I went ahead.
