### ISSUE TITLE
Can't edit label for Number/Currency in repeated grid

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2406]
Clicking on the label causes focus on the control, but the editor doesn't appear. Works with 4.10.

![regression-cant-edit-control-label-for-currency](https://cloud.githubusercontent.com/assets/105769/10151713/4312e6b8-65ff-11e5-96f1-a0b69f5fdeaa.png)

**Comment by avernet** [comment]
@ebruchez Maybe related to changes we've done to handle focus on XBL controls, in particular the number fields. You'll let me know.

**Comment by ebruchez** [comment]
@avernet Or maybe due to one of the accessibility change.

**Comment by avernet** [comment]
Hopefully this will be taken care of by @ebruchez fixing #2433.

**Comment by ebruchez** [comment]
Fix for #2433 indeed fixes this, so closing. I am not sure why it worked with 4.10 then.

**Comment by ebruchez** [comment]
And it doesn't work with 4.10.1. So it seems to be a consequence of the fix for #2433.
