### ISSUE TITLE
portlet.xml for proxy-portlet uses <param-name> and <param-value> within <init-param>

### ISSUE THREAD

**Issue by ajw625** [orbeon/orbeon-forms#2418]
For `init-param` some of the parameters use `name` and `value` and some use `param-name` and `param-value` which is incorrect for `http://java.sun.com/xml/ns/portlet/portlet-app_2_0.xsd`. This doesn't appear to be causing any problems but should should be cleaned up.

**Comment by ebruchez** [comment]
@ajw625 Good catch, fixed!

**Comment by ebruchez** [comment]
`web.xml` uses `<param-name>` and `<param-value>`, but `portlet.xml` uses `<name>` and `<value>`.
