### ISSUE TITLE
Calendar in embedded form: id in CSS and DOM don't match

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2423]
As a result, the calendar looks like:

![](http://i.imgur.com/hDvLalt.png)

Instead of:

![](http://i.imgur.com/3F9pKjK.png)

The id used in the CSS is:

![](http://i.imgur.com/bbNFhQg.png)

While in the DOM, it is:

![](http://i.imgur.com/BWPAz0j.png)

Most likely code in [Calendar.coffee](https://github.com/orbeon/orbeon-forms/blob/master/src/resources-packaged/ops/javascript/orbeon/xforms/control/Calendar.coffee) should use a prefixed id when creating the element in the DOM.

**Comment by ebruchez** [comment]
Yes probably that this should work. Alternatively, keep the non-namespaced id but apply the CSS with classes rather than by id.

**Comment by avernet** [comment]
@ebruchez Indeed, using a class is simpler, and this we can keep having just one date picker for the whole page (not that having multiple would be a problem, but just that having one makes more sense). So this is what I did.
