### ISSUE TITLE
"String index out of range: -2" on service call

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2425]
To reproduce the exception, paste [this form](https://gist.github.com/avernet/d282cd08ba280c231063) in Form Builder, test, and change the value in the dropdown. This doesn't happen for me on a verbatim 4.10 PE.

**Comment by ebruchez** [comment]
I am getting an `java.lang.AssertionError`.

**Comment by ebruchez** [comment]
Probably regressed with 90cc8425853fa534cb12ba513d7a4d28a6a778d3.
