### ISSUE TITLE
Embedding API: support Form Builder

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2435]
What's missing:
- CSS/layout issues
- possibly id issues?
- "Test" button requires implementing #2326

**Comment by avernet** [comment]
We've estimated this work to 5 man-days.

**Comment by avernet** [comment]
[+1 from community](http://stackoverflow.com/questions/34988379/logout-from-orbeon-via-rest)

**Comment by avernet** [comment]
[+1 from community](http://discuss.orbeon.com/Is-Form-Builder-supported-in-orbeon-4-10PE-integrated-with-Liferay-td4661146.html)

**Comment by ebruchez** [comment]
Good news is that we no longer use YUI layout since forever ago (October 2012, see 86aa7c9a525d7b971078eda16a343e7ebaaa31f6).

**Comment by ebruchez** [comment]
As is, Form Builder shows pretty nicely when embedding from our demo embedding page. Issues:

- takes the whole viewport (might not/not always be desirable)
- buttons bar at bottom doesn't show or only shows partially 
- "Test" fails with an error (as expected)

**Comment by ebruchez** [comment]
The "Test" button first fails because the iframe is searched by id from JavaScript. Fixing that, the following fails:

```JavaScript
ORBEON.xforms.Document.dispatchEvent("fr-form-model", "fb-show-test-dialog")
```

because it sends the server:

```xml
<xxf:event name="fb-show-test-dialog" source-control-id="-form-model"></xxf:event>
```

We need to fix the `source-control-id`.

**Comment by ebruchez** [comment]
Culprit for that is:

```JavaScript
requestDocumentString.push(' source-control-id="' + event.targetId.substring(ORBEON.xforms.Globals.ns[formID].length) + '"');
```

which removes the namespace no matter what. Here we don't have a namespaced name so it fails.

**Comment by ebruchez** [comment]
Once that is addressed, the server responds with:

```xml
<xxf:submission method="POST" show-progress="false" target="fb-test-iframe"/>
```

Then, as expected, the submission fails at:

    /orbeon-embedding/orbeon//xforms-server-submit

as the embedding code doesn't support that.

There is also the issue of the double `/`.

**Comment by ebruchez** [comment]
Next steps:

- [ ] 
- [ ]

**Comment by ebruchez** [comment]
For [recent customer](https://basecamp.com/1721271/projects/13159770/messages/63670965), Liferay support is not required AFAICT.

**Comment by ebruchez** [comment]
For the layout, it would be good if the `<div class="orbeon-portlet-body">` controlled the outer layout, and then the contents would flow accordingly inside.

Right now, we use `.fb-main`, `.fb-bottom`, etc. with some `position: fixed`, so that has to be changed a bit.

**Comment by ebruchez** [comment]
[Documented](https://doc.orbeon.com/form-runner/link-embed/java-api.html#form-builder-embedding)

**Comment by ebruchez** [comment]
Tried with IE 11 and Edge. Closing.
