### ISSUE TITLE
Form runner create 'new' form button missing

### ISSUE THREAD

**Issue by adamfowleruk** [orbeon/orbeon-forms#2443]
I have created a second version of a form definition and published it to form runner. Now for some reason when viewing my form's summary page in form runner, the 'new' button is missing. When I try to go to the /new url directly, form runner incorrectly opens the first form in the summary list for editing with the new template.

What controls whether the 'new' button appears or not? I cannot find that code in the src repository to check myself.

**Comment by avernet** [comment]
@adamfowleruk What version of Orbeon Forms are you on? The "new" button should be hidden from the summary page if [permissions have been enabled for the form in Form Builder](http://doc.orbeon.com/form-runner/access-control/deployed-forms.html) and the current user doesn't have access to the "create" operation. However, in that scenario, the user should get an "access denied" when loading the /new page for the form. How could we reproduce this issue?

**Comment by adamfowleruk** [comment]
I've discovered if In the summary page I delete the form instance, then the New button reappears, and all is well again. I can create multiple instances of the form thereafter. Very strange.

Permissions are not enabled. It's the previous release from last month, using our custom MarkLogic REST API. (With a default user set in our layer).

For now the problem has gone away. I'm wondering if updating the form definition from our internal development GitHub repo has somehow caused this issue. I'll monitor and report back if it reappears. Closing for now as I cannot provide instructions to recreate it.

**Comment by avernet** [comment]
@adamfowleruk, got it, and of course let us know if you find a way to reproduce this and suspect this is indeed an issue with the product. There are sometimes unexpected ways in which the code can interact with third-party implementations of the persistence API.
