### ISSUE TITLE
Is Nested Grid Possible Using Form Builder?

### ISSUE THREAD

**Issue by hbjadeja** [orbeon/orbeon-forms#2452]
Hi,
I am going through the Form Builder and One of my Requirement is to Use Nested Grid.
I have not found anything specific to that.
If anyone helps me out on this, It will be great help.

Pls. let me know whether its possible or not ? If yes any example is really appreciated.

I have attached sample data view which I wont on form. 

I am looking at similar to InfoPath Nested Grid Controls.

Regards,

Hardik
![sample_data](https://cloud.githubusercontent.com/assets/15263176/11560376/040274b4-99e6-11e5-8569-c83e746ffff1.png)

**Comment by ebruchez** [comment]
There are no nested grids, but you can have repeated sections containing repeated grids. Maybe that could do the trick. See [Repeated sections](http://blog.orbeon.com/2014/01/repeated-sections.html) and [Repeated grids](http://doc.orbeon.com/form-builder/repeated-grids.html).

**Comment by hbjadeja** [comment]
Thanks Eric. One More thing, I have gone through documentation and found that, Grid Can have up to 4 Columns. Is there a way, where we can increase No Of Columns.

**Comment by ebruchez** [comment]
@hbjadeja Yes it is possible with [this property](http://doc.orbeon.com/configuration/properties/form-builder.html#maximum-number-of-columns).
