### ISSUE TITLE
maxOccurs and minOccurs missing from the schema for repeating section iterations

### ISSUE THREAD

**Issue by ajw625** [orbeon/orbeon-forms#2459]
See example schema below. The first two sections contain repeating grids `grid-17` and `grid-3` which have `maxOccurs="unbounded" minOccurs="1"`. `section-9` is a repeating section, so `section-9-iteration` should have them as well. I have also included the form definition.

**Schema:**

    <?xml version="1.0" encoding="utf-8"?>
    <xs:schema xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" xmlns:xf="http://www.w3.org/2002/xforms" xmlns:xs="http://www.w3.org/2001/XMLSchema">
        <xs:element name="form">
        <xs:complexType>
            <xs:all>
            <xs:element name="section-18">
                <xs:complexType>
                <xs:sequence>
                    <xs:element maxOccurs="unbounded" minOccurs="1" name="grid-17">
                    <xs:complexType>
                        <xs:all>
                        <xs:element name="control-19"></xs:element>
                        <xs:element name="control-20"></xs:element>
                        <xs:element name="control-21"></xs:element>
                        <xs:element name="control-22"></xs:element>
                        </xs:all>
                    </xs:complexType>
                    </xs:element>
                </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="section-1">
                <xs:complexType>
                <xs:sequence>
                    <xs:element maxOccurs="unbounded" minOccurs="1" name="grid-3">
                    <xs:complexType>
                        <xs:all>
                        <xs:element name="control-5"></xs:element>
                        <xs:element name="control-6"></xs:element>
                        <xs:element name="control-7"></xs:element>
                        <xs:element name="control-8"></xs:element>
                        <xs:element name="control-9"></xs:element>
                        <xs:element name="control-15"></xs:element>
                        </xs:all>
                    </xs:complexType>
                    </xs:element>
                </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="section-9">
                <xs:complexType>
                <xs:sequence>
                    <xs:element name="section-9-iteration">
                    <xs:complexType>
                        <xs:all>
                        <xs:element name="control-11"></xs:element>
                        <xs:element name="control-12"></xs:element>
                        <xs:element name="control-13"></xs:element>
                        <xs:element name="control-14"></xs:element>
                        <xs:element name="control-23"></xs:element>
                        </xs:all>
                    </xs:complexType>
                    </xs:element>
                </xs:sequence>
                </xs:complexType>
            </xs:element>
            </xs:all>
        </xs:complexType>
        </xs:element>
    </xs:schema>

**Form Definition:**

    <xh:html xmlns:xh="http://www.w3.org/1999/xhtml" xmlns:xf="http://www.w3.org/2002/xforms"
         xmlns:xs="http://www.w3.org/2001/XMLSchema"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns:ev="http://www.w3.org/2001/xml-events"
         xmlns:xi="http://www.w3.org/2001/XInclude"
         xmlns:xxi="http://orbeon.org/oxf/xml/xinclude"
         xmlns:xxf="http://orbeon.org/oxf/xml/xforms"
         xmlns:exf="http://www.exforms.org/exf/1-0"
         xmlns:fr="http://orbeon.org/oxf/xml/form-runner"
         xmlns:saxon="http://saxon.sf.net/"
         xmlns:sql="http://orbeon.org/oxf/xml/sql"
         xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
         xmlns:fb="http://orbeon.org/oxf/xml/form-builder">
        <xh:head>
        <xh:title>Repeat Examples</xh:title>
        <xf:model id="fr-form-model" xxf:expose-xpath-types="true">

            
            <xf:instance id="fr-form-instance" xxf:exclude-result-prefixes="#all">
            <form>
                <section-18>
                <grid-17>
                    <grid-17-iteration>
                    <control-19/>
                    <control-20/>
                    <control-21/>
                    <control-22/>
                    </grid-17-iteration>
                </grid-17>
                </section-18>
                <section-1>
                <grid-3>
                    <grid-3-iteration>
                    <control-5/>
                    <control-6/>
                    <control-7/>
                    <control-8/>
                    <control-9/>
                    <control-15/>
                    </grid-3-iteration>
                </grid-3>
                </section-1>
                <section-9>
                <section-9-iteration>
                    <control-11/>
                    <control-12/>
                    <control-13/>
                    <control-14/>
                    <control-23/>
                </section-9-iteration>
                </section-9>
            </form>
            </xf:instance>

            
            <xf:bind id="fr-form-binds" ref="instance('fr-form-instance')">
            <xf:bind id="section-18-bind" ref="section-18" name="section-18">
                <xf:bind id="grid-17-bind" ref="grid-17" name="grid-17">
                <xf:bind id="grid-17-iteration-bind" ref="grid-17-iteration" name="grid-17-iteration">
                    <xf:bind id="control-19-bind" ref="control-19" name="control-19"/>
                    <xf:bind id="control-20-bind" ref="control-20" name="control-20"/>
                    <xf:bind id="control-21-bind" ref="control-21" name="control-21"/>
                    <xf:bind id="control-22-bind" ref="control-22" name="control-22"/>
                </xf:bind>
                </xf:bind>
            </xf:bind>
            <xf:bind id="section-1-bind" name="section-1" ref="section-1">
                <xf:bind id="grid-3-bind" ref="grid-3" name="grid-3">
                <xf:bind id="grid-3-iteration-bind" ref="grid-3-iteration" name="grid-3-iteration">
                    <xf:bind id="control-5-bind" ref="control-5" name="control-5"/>
                    <xf:bind id="control-6-bind" ref="control-6" name="control-6"/>
                    <xf:bind id="control-7-bind" ref="control-7" name="control-7"/>
                    <xf:bind id="control-8-bind" ref="control-8" name="control-8"/>
                    <xf:bind id="control-9-bind" ref="control-9" name="control-9"/>
                    <xf:bind id="control-15-bind" ref="control-15" name="control-15"/>
                </xf:bind>
                </xf:bind>
            </xf:bind>
            <xf:bind id="section-9-bind" ref="section-9" name="section-9">
                <xf:bind id="section-9-iteration-bind" ref="section-9-iteration"
                     name="section-9-iteration">
                <xf:bind id="control-11-bind" ref="control-11" name="control-11"/>
                <xf:bind id="control-12-bind" ref="control-12" name="control-12"/>
                <xf:bind id="control-13-bind" ref="control-13" name="control-13"/>
                <xf:bind id="control-14-bind" ref="control-14" name="control-14"/>
                <xf:bind id="control-23-bind" ref="control-23" name="control-23"/>
                </xf:bind>
            </xf:bind>
            </xf:bind>

            
            <xf:instance xxf:readonly="true" id="fr-form-metadata" xxf:exclude-result-prefixes="#all">
            <metadata>
                <application-name>test</application-name>
                <form-name>repeating-examples</form-name>
                <title xml:lang="en">Repeat Examples</title>
                <description xml:lang="en"/>
                <singleton>false</singleton>
            </metadata>
            </xf:instance>

            
            <xf:instance id="fr-form-attachments" xxf:exclude-result-prefixes="#all">
            <attachments>
                <css mediatype="text/css" filename="" size=""/>
                <pdf mediatype="application/pdf" filename="" size=""/>
            </attachments>
            </xf:instance>

            
            
            <xf:instance id="fr-form-resources" xxf:readonly="false" xxf:exclude-result-prefixes="#all">
            <resources>
                <resource xml:lang="en">
                <control-19>
                    <label>label</label>
                    <hint/>
                </control-19>
                <control-20>
                    <label>label</label>
                    <hint/>
                </control-20>
                <control-21>
                    <label/>
                    <hint/>
                </control-21>
                <control-22>
                    <label/>
                    <hint/>
                </control-22>
                <control-11>
                    <label/>
                    <hint/>
                </control-11>
                <control-12>
                    <label/>
                    <hint/>
                </control-12>
                <control-13>
                    <label/>
                    <hint/>
                </control-13>
                <control-14>
                    <label/>
                    <hint/>
                </control-14>
                <control-23>
                    <label/>
                    <hint/>
                </control-23>
                <control-5>
                    <label>label</label>
                    <hint/>
                </control-5>
                <control-6>
                    <label>label</label>
                    <hint/>
                </control-6>
                <control-7>
                    <label/>
                    <hint/>
                </control-7>
                <control-8>
                    <label/>
                    <hint/>
                </control-8>
                <control-9>
                    <label/>
                    <hint/>
                </control-9>
                <control-15>
                    <label/>
                    <hint/>
                </control-15>
                <section-1>
                    <label>Multi-line Repeated Grid</label>
                </section-1>
                <section-18>
                    <label>Repeated Grid</label>
                    <help/>
                </section-18>
                <section-9>
                    <label>Repeating Section</label>
                    <help/>
                </section-9>

                </resource>
            </resources>
            </xf:instance>

            
            <xf:instance id="fr-service-request-instance" xxf:exclude-result-prefixes="#all">
            <request/>
            </xf:instance>

            <xf:instance id="fr-service-response-instance" xxf:exclude-result-prefixes="#all">
            <response/>
            </xf:instance>
            <xf:instance xxf:readonly="true" xxf:exclude-result-prefixes="#all" id="grid-3-template">
            <grid-3-iteration>
                <control-5/>
                <control-6/>
                <control-7/>
                <control-8/>
                <control-9/>
                <control-15/>
            </grid-3-iteration>
            </xf:instance>
            <xf:instance xxf:readonly="true" xxf:exclude-result-prefixes="#all" id="section-9-template">
            <section-9-iteration>
                <control-11/>
                <control-12/>
                <control-13/>
                <control-14/>
                <control-23/>
            </section-9-iteration>
            </xf:instance>
            <xf:instance xxf:readonly="true" xxf:exclude-result-prefixes="#all" id="grid-17-template">
            <grid-17-iteration>
                <control-19/>
                <control-20/>
                <control-21/>
                <control-22/>
            </grid-17-iteration>
            </xf:instance>

        </xf:model>
        </xh:head>
        <xh:body>
        <fr:view>
            <fr:body xmlns:xbl="http://www.w3.org/ns/xbl"
                 xmlns:oxf="http://www.orbeon.com/oxf/processors"
                 xmlns:p="http://www.orbeon.com/oxf/pipeline">
            <fr:section id="section-18-control" bind="section-18-bind">
                <xf:label ref="$form-resources/section-18/label"/>
                <fr:grid id="grid-17-grid" bind="grid-17-bind" repeat="content" min="1"
                     template="instance('grid-17-template')">
                <xh:tr>
                    <xh:td>
                    <xf:input id="control-19-control" bind="control-19-bind">
                        <xf:label ref="$form-resources/control-19/label"/>
                        <xf:hint ref="$form-resources/control-19/hint"/>

                        <xf:alert ref="$fr-resources/detail/labels/alert"/>
                    </xf:input>
                    </xh:td>
                    <xh:td>
                    <xf:input id="control-20-control" bind="control-20-bind">
                        <xf:label ref="$form-resources/control-20/label"/>
                        <xf:hint ref="$form-resources/control-20/hint"/>

                        <xf:alert ref="$fr-resources/detail/labels/alert"/>
                    </xf:input>
                    </xh:td>
                    <xh:td>
                    <xf:input id="control-21-control" bind="control-21-bind">
                        <xf:label ref="$form-resources/control-21/label"/>
                        <xf:hint ref="$form-resources/control-21/hint"/>

                        <xf:alert ref="$fr-resources/detail/labels/alert"/>
                    </xf:input>
                    </xh:td>
                    <xh:td>
                    <xf:input id="control-22-control" bind="control-22-bind">
                        <xf:label ref="$form-resources/control-22/label"/>
                        <xf:hint ref="$form-resources/control-22/hint"/>

                        <xf:alert ref="$fr-resources/detail/labels/alert"/>
                    </xf:input>
                    </xh:td>
                </xh:tr>
                </fr:grid>
            </fr:section>
            <fr:section id="section-1-control" bind="section-1-bind">
                <xf:label ref="$form-resources/section-1/label"/>
                <fr:grid id="grid-3-grid" bind="grid-3-bind" repeat="content" min="1"
                     template="instance('grid-3-template')">
                <xh:tr>
                    <xh:td>
                    <xf:input id="control-5-control" bind="control-5-bind">
                        <xf:label ref="$form-resources/control-5/label"/>
                        <xf:hint ref="$form-resources/control-5/hint"/>

                        <xf:alert ref="$fr-resources/detail/labels/alert"/>
                    </xf:input>
                    </xh:td>
                    <xh:td>
                    <xf:input id="control-6-control" bind="control-6-bind">
                        <xf:label ref="$form-resources/control-6/label"/>
                        <xf:hint ref="$form-resources/control-6/hint"/>

                        <xf:alert ref="$fr-resources/detail/labels/alert"/>
                    </xf:input>
                    </xh:td>
                    <xh:td>
                    <xf:input id="control-7-control" bind="control-7-bind">
                        <xf:label ref="$form-resources/control-7/label"/>
                        <xf:hint ref="$form-resources/control-7/hint"/>

                        <xf:alert ref="$fr-resources/detail/labels/alert"/>
                    </xf:input>
                    </xh:td>
                    <xh:td>
                    <xf:input id="control-8-control" bind="control-8-bind">
                        <xf:label ref="$form-resources/control-8/label"/>
                        <xf:hint ref="$form-resources/control-8/hint"/>

                        <xf:alert ref="$fr-resources/detail/labels/alert"/>
                    </xf:input>
                    </xh:td>
                </xh:tr>
                <xh:tr>
                    <xh:td>
                    <xf:input id="control-9-control" bind="control-9-bind">
                        <xf:label ref="$form-resources/control-9/label"/>
                        <xf:hint ref="$form-resources/control-9/hint"/>

                        <xf:alert ref="$fr-resources/detail/labels/alert"/>
                    </xf:input>
                    </xh:td>
                    <xh:td>
                    <xf:input id="control-15-control" bind="control-15-bind">
                        <xf:label ref="$form-resources/control-15/label"/>
                        <xf:hint ref="$form-resources/control-15/hint"/>

                        <xf:alert ref="$fr-resources/detail/labels/alert"/>
                    </xf:input>
                    </xh:td>
                    <xh:td/>
                    <xh:td/>
                </xh:tr>
                </fr:grid>
            </fr:section>
            <fr:section id="section-9-control" bind="section-9-bind" repeat="content"
                    template="instance('section-9-template')">
                <xf:label ref="$form-resources/section-9/label"/>
                <fr:grid>
                <xh:tr>
                    <xh:td>
                    <xf:textarea id="control-11-control" bind="control-11-bind">
                        <xf:label ref="$form-resources/control-11/label"/>
                        <xf:hint ref="$form-resources/control-11/hint"/>

                        <xf:alert ref="$fr-resources/detail/labels/alert"/>
                    </xf:textarea>
                    </xh:td>
                    <xh:td>
                    <xf:textarea id="control-12-control" bind="control-12-bind">
                        <xf:label ref="$form-resources/control-12/label"/>
                        <xf:hint ref="$form-resources/control-12/hint"/>

                        <xf:alert ref="$fr-resources/detail/labels/alert"/>
                    </xf:textarea>
                    </xh:td>
                    <xh:td>
                    <xf:textarea id="control-13-control" bind="control-13-bind">
                        <xf:label ref="$form-resources/control-13/label"/>
                        <xf:hint ref="$form-resources/control-13/hint"/>

                        <xf:alert ref="$fr-resources/detail/labels/alert"/>
                    </xf:textarea>
                    </xh:td>
                    <xh:td>
                    <xf:textarea id="control-14-control" bind="control-14-bind">
                        <xf:label ref="$form-resources/control-14/label"/>
                        <xf:hint ref="$form-resources/control-14/hint"/>

                        <xf:alert ref="$fr-resources/detail/labels/alert"/>
                    </xf:textarea>
                    </xh:td>
                </xh:tr>
                </fr:grid>
                <fr:grid>
                <xh:tr>
                    <xh:td>
                    <xf:textarea id="control-23-control" bind="control-23-bind">
                        <xf:label ref="$form-resources/control-23/label"/>
                        <xf:hint ref="$form-resources/control-23/hint"/>

                        <xf:alert ref="$fr-resources/detail/labels/alert"/>
                    </xf:textarea>
                    </xh:td>
                </xh:tr>
                </fr:grid>
            </fr:section>
            </fr:body>
        </fr:view>
        </xh:body>
    </xh:html>

**Comment by avernet** [comment]
@ajw625 Yes, I reproduced this, and started to look into it.

**Comment by avernet** [comment]
@ajw625 Fixed, you'll let us know if this works for you. And just let us know if you'd like a test build for this.

**Comment by ajw625** [comment]
@avernet Thanks, Alex. Yes, a test build would be great.

**Comment by avernet** [comment]
@ajw625 My apologies for the delay; I had a note somewhere to send you a build, but it fell below the fold. So, here is a [PE build from master](https://drive.google.com/open?id=0B_IAL5I44D2PWEhDMlJINFlyZHc) from January 7. This is just from a snapshot of the code, so don't use this in anything that resembles even remotely to production, but this should allow to check that everything now works as expected, and of course just let us know if you spot any problem.

**Comment by ajw625** [comment]
Thanks, @avernet.

**Comment by ajw625** [comment]
This is closed, but has no milestone. Which release includes it?

**Comment by ebruchez** [comment]
The fix will be in 4.11. I updated the milestone.

**Comment by ajw625** [comment]
Sorry guys. I'm just getting to testing this now with 2016.1.

The fix to the schema appears to be incorrect. Previously the schema included `section-9-iteration` like this:

                <xs:element name="section-9">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="section-9-iteration">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element name="control-11"></xs:element>

I was expecting that maxOccurs and minOccurs would be added to the `section-9-iteration` element. But that element has been removed entirely from the schema. The schema no longer matches the data, which looks like this:

        <section-9>
            <section-9-iteration>
                <control-11>1</control-11>

I've noticed that the use of the `*-iteration` elements is inconsistent. Repeating sections use them, but repeating grids do not.

**Comment by ebruchez** [comment]
I will let @avernet reply with more details, but I notice the code has this comment:

```
// If repeated, skip nested iteration bind so that the schema validates the old data format
// NOTE: This could be made configurable in the future.
```

This comment might be incorrect, in that repeated sections always had the `-iteration` suffix and nesting, and repeated grids only gained this later, and only for form definition which have been converted from the old format or are new. In which case, there is an "internal" format which has the `-iteration` element, while in the database there is no `-iteration` element for backward compatibility.

**Comment by avernet** [comment]
@ajw625 I will be looking at this in more detail, most likely beginning of August, and will make sure to follow up here.

**Comment by ajw625** [comment]
@avernet Have you had a chance to take a look at this? You were saying most likely beginning of August. I'm concerned that this may have gotten lost since this is in the 2016.1 milestone which you have now closed. I noticed there are two other open issues in this milestone.

**Comment by avernet** [comment]
Andrew, we're almost ready to ship 2016.2, but I'll have a quick look at this one before we ship, just to check if we can fix it quickly. I'll follow-up here.

**Comment by ajw625** [comment]
Thanks @avernet . I hope it can be fixed for 2016.2. It's a blocker for us. We can't upgrade without it. If this change were rolled back we would be able to upgrade. But really we need the fix in order to correct several of our bugs.

**Comment by avernet** [comment]
Fixed in https://github.com/orbeon/orbeon-forms-pe/commit/514e5096890348d71ba512f9f6a7dfe41680626f.

**Comment by avernet** [comment]
@ajw625, if you get a chance, you can test this using this [test build](https://drive.google.com/open?id=0B_IAL5I44D2PY1JXYTBMQ0JlbFE), and you'll let us know how this works for you.

**Comment by ajw625** [comment]
Thanks, @avernet . I've got the build and will test as soon as I can.

**Comment by ajw625** [comment]
@avernet Looks good. Thanks much for getting this in!
