### ISSUE TITLE
send action - type attributes present on first section or grid iteration, but not on subsequent iterations

### ISSUE THREAD

**Issue by ajw625** [orbeon/orbeon-forms#2463]
See details below. Notice that `xsi:type="orbeonField"` appears on all field elements in the first grid or section iteration. Also, `xsi:type="orbeonSection"` appears on the first section iteration, but not the rest.

#### Send button test config:

    <property as="xs:string" name="oxf.fr.detail.process.send-to-myservice.*.*">
        set-data-status(status="safe")
        then send(
                  uri="http://posttestserver.com/post.php?dir=vivid_orbeon",
                  content="xml",
                  replace="none"
                 )
        then success-message(message="Save Successful")
        recover error-message(message="Save Failed")
    </property>
    <property as="xs:string" name="oxf.fr.resource.*.*.en.buttons.send-to-myservice" value="Save"/>

    <property as="xs:string"  name="oxf.fr.detail.buttons.*.*">
        send-to-myservice
    </property>

#### Example send output:
[(also available at http://posttestserver.com/data/2015/12/11/vivid_orbeon/13.03.201003444360)](http://posttestserver.com/data/2015/12/11/vivid_orbeon/13.03.201003444360)

	<?xml version="1.0" encoding="UTF-8"?>
	<form>
	  <repeated-grid-section-1 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="orbeonSection">
		<one-line-repeated-grid>
		  <repeat1.control-19 xsi:type="orbeonField">1</repeat1.control-19>
		  <repeat1.control-20 xsi:type="orbeonField">2</repeat1.control-20>
		  <repeat1.control-21 xsi:type="orbeonField">3</repeat1.control-21>
		  <repeat1.control-22 xsi:type="orbeonField">4</repeat1.control-22>
		</one-line-repeated-grid>
		<one-line-repeated-grid>
		  <repeat1.control-19>5</repeat1.control-19>
		  <repeat1.control-20>6</repeat1.control-20>
		  <repeat1.control-21>7</repeat1.control-21>
		  <repeat1.control-22>8</repeat1.control-22>
		</one-line-repeated-grid>
		<one-line-repeated-grid>
		  <repeat1.control-19>9</repeat1.control-19>
		  <repeat1.control-20>10</repeat1.control-20>
		  <repeat1.control-21>11</repeat1.control-21>
		  <repeat1.control-22>12</repeat1.control-22>
		</one-line-repeated-grid>
	  </repeated-grid-section-1>
	  <multi-line-repeated-grid-section-2 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="orbeonSection">
		<multi-line-repeated-grid>
		  <repeat2.control-5 xsi:type="orbeonField">1</repeat2.control-5>
		  <repeat2.control-6 xsi:type="orbeonField">2</repeat2.control-6>
		  <repeat2.control-7 xsi:type="orbeonField">3</repeat2.control-7>
		  <repeat2.control-8 xsi:type="orbeonField">4</repeat2.control-8>
		  <repeat2.control-9 xsi:type="orbeonField">5</repeat2.control-9>
		  <repeat2.control-15 xsi:type="orbeonField">6</repeat2.control-15>
		</multi-line-repeated-grid>
		<multi-line-repeated-grid>
		  <repeat2.control-5>7</repeat2.control-5>
		  <repeat2.control-6>8</repeat2.control-6>
		  <repeat2.control-7>9</repeat2.control-7>
		  <repeat2.control-8>10</repeat2.control-8>
		  <repeat2.control-9>11</repeat2.control-9>
		  <repeat2.control-15>12</repeat2.control-15>
		</multi-line-repeated-grid>
	  </multi-line-repeated-grid-section-2>
	  <repeating-section xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="orbeonSection">
		<repeating-section-iteration xsi:type="orbeonSection">
		  <repeat3.control-11 xsi:type="orbeonField">1</repeat3.control-11>
		  <repeat3.control-12 xsi:type="orbeonField">2</repeat3.control-12>
		  <repeat3.control-13 xsi:type="orbeonField">3</repeat3.control-13>
		  <repeat3.control-14 xsi:type="orbeonField">4</repeat3.control-14>
		  <repeat3.control-23 xsi:type="orbeonField">5</repeat3.control-23>
		</repeating-section-iteration>
		<repeating-section-iteration>
		  <repeat3.control-11>6</repeat3.control-11>
		  <repeat3.control-12>7</repeat3.control-12>
		  <repeat3.control-13>8</repeat3.control-13>
		  <repeat3.control-14>9</repeat3.control-14>
		  <repeat3.control-23>10</repeat3.control-23>
		</repeating-section-iteration>
		<repeating-section-iteration>
		  <repeat3.control-11>11</repeat3.control-11>
		  <repeat3.control-12>12</repeat3.control-12>
		  <repeat3.control-13>13</repeat3.control-13>
		  <repeat3.control-14>14</repeat3.control-14>
		  <repeat3.control-23>15</repeat3.control-23>
		</repeating-section-iteration>
	  </repeating-section>
	</form>

#### Form Definition:

    <xh:html xmlns:xh="http://www.w3.org/1999/xhtml" xmlns:xf="http://www.w3.org/2002/xforms"
             xmlns:xs="http://www.w3.org/2001/XMLSchema"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns:ev="http://www.w3.org/2001/xml-events"
             xmlns:xi="http://www.w3.org/2001/XInclude"
             xmlns:xxi="http://orbeon.org/oxf/xml/xinclude"
             xmlns:xxf="http://orbeon.org/oxf/xml/xforms"
             xmlns:exf="http://www.exforms.org/exf/1-0"
             xmlns:fr="http://orbeon.org/oxf/xml/form-runner"
             xmlns:saxon="http://saxon.sf.net/"
             xmlns:sql="http://orbeon.org/oxf/xml/sql"
             xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
             xmlns:fb="http://orbeon.org/oxf/xml/form-builder">
        <xh:head>
            <xh:title>Repeat Examples</xh:title>
            <xf:model id="fr-form-model" xxf:expose-xpath-types="true">

                
                <xf:instance id="fr-form-instance" xxf:exclude-result-prefixes="#all">
                    <form>
                        <repeated-grid-section-1>
                            <one-line-repeated-grid>
                                <one-line-repeated-grid-iteration>
                                    <repeat1.control-19/>
                                    <repeat1.control-20/>
                                    <repeat1.control-21/>
                                    <repeat1.control-22/>
                                </one-line-repeated-grid-iteration>
                            </one-line-repeated-grid>
                        </repeated-grid-section-1>
                        <multi-line-repeated-grid-section-2>
                            <multi-line-repeated-grid>
                                <multi-line-repeated-grid-iteration>
                                    <repeat2.control-5/>
                                    <repeat2.control-6/>
                                    <repeat2.control-7/>
                                    <repeat2.control-8/>
                                    <repeat2.control-9/>
                                    <repeat2.control-15/>
                                </multi-line-repeated-grid-iteration>
                            </multi-line-repeated-grid>
                        </multi-line-repeated-grid-section-2>
                        <repeating-section>
                            <repeating-section-iteration>
                                <repeat3.control-11/>
                                <repeat3.control-12/>
                                <repeat3.control-13/>
                                <repeat3.control-14/>
                                <repeat3.control-23/>
                            </repeating-section-iteration>
                        </repeating-section>
                    </form>
                </xf:instance>

                
                <xf:bind id="fr-form-binds" ref="instance('fr-form-instance')">
                    <xf:bind id="repeated-grid-section-1-bind" ref="repeated-grid-section-1"
                             name="repeated-grid-section-1">
                        <xf:bind id="one-line-repeated-grid-bind" ref="one-line-repeated-grid"
                                 name="one-line-repeated-grid">
                            <xf:bind id="one-line-repeated-grid-iteration-bind"
                                     ref="one-line-repeated-grid-iteration"
                                     name="one-line-repeated-grid-iteration">
                                <xf:bind id="repeat1.control-19-bind" ref="repeat1.control-19" name="repeat1.control-19"/>
                                <xf:bind id="repeat1.control-20-bind" ref="repeat1.control-20" name="repeat1.control-20"/>
                                <xf:bind id="repeat1.control-21-bind" ref="repeat1.control-21" name="repeat1.control-21"/>
                                <xf:bind id="repeat1.control-22-bind" ref="repeat1.control-22" name="repeat1.control-22"/>
                            </xf:bind>
                        </xf:bind>
                    </xf:bind>
                    <xf:bind id="multi-line-repeated-grid-section-2-bind"
                             name="multi-line-repeated-grid-section-2"
                             ref="multi-line-repeated-grid-section-2">
                        <xf:bind id="multi-line-repeated-grid-bind" ref="multi-line-repeated-grid"
                                 name="multi-line-repeated-grid">
                            <xf:bind id="multi-line-repeated-grid-iteration-bind"
                                     ref="multi-line-repeated-grid-iteration"
                                     name="multi-line-repeated-grid-iteration">
                                <xf:bind id="repeat2.control-5-bind" ref="repeat2.control-5" name="repeat2.control-5"/>
                                <xf:bind id="repeat2.control-6-bind" ref="repeat2.control-6" name="repeat2.control-6"/>
                                <xf:bind id="repeat2.control-7-bind" ref="repeat2.control-7" name="repeat2.control-7"/>
                                <xf:bind id="repeat2.control-8-bind" ref="repeat2.control-8" name="repeat2.control-8"/>
                                <xf:bind id="repeat2.control-9-bind" ref="repeat2.control-9" name="repeat2.control-9"/>
                                <xf:bind id="repeat2.control-15-bind" ref="repeat2.control-15" name="repeat2.control-15"/>
                            </xf:bind>
                        </xf:bind>
                    </xf:bind>
                    <xf:bind id="repeating-section-bind" ref="repeating-section" name="repeating-section">
                        <xf:bind id="repeating-section-iteration-bind" ref="repeating-section-iteration"
                                 name="repeating-section-iteration">
                            <xf:bind id="repeat3.control-11-bind" ref="repeat3.control-11" name="repeat3.control-11"/>
                            <xf:bind id="repeat3.control-12-bind" ref="repeat3.control-12" name="repeat3.control-12"/>
                            <xf:bind id="repeat3.control-13-bind" ref="repeat3.control-13" name="repeat3.control-13"/>
                            <xf:bind id="repeat3.control-14-bind" ref="repeat3.control-14" name="repeat3.control-14"/>
                            <xf:bind id="repeat3.control-23-bind" ref="repeat3.control-23" name="repeat3.control-23"/>
                        </xf:bind>
                    </xf:bind>
                </xf:bind>

                
                <xf:instance xxf:readonly="true" id="fr-form-metadata" xxf:exclude-result-prefixes="#all">
                    <metadata>
                        <application-name>test</application-name>
                        <form-name>repeating-examples</form-name>
                        <title xml:lang="en">Repeat Examples</title>
                        <description xml:lang="en"/>
                        <singleton>false</singleton>
                    </metadata>
                </xf:instance>

                
                <xf:instance id="fr-form-attachments" xxf:exclude-result-prefixes="#all">
                    <attachments>
                        <css mediatype="text/css" filename="" size=""/>
                        <pdf mediatype="application/pdf" filename="" size=""/>
                    </attachments>
                </xf:instance>

                
                
                <xf:instance id="fr-form-resources" xxf:readonly="false" xxf:exclude-result-prefixes="#all">
                    <resources>
                        <resource xml:lang="en">
                            <repeat1.control-19>
                                <label>label</label>
                                <hint/>
                            </repeat1.control-19>
                            <repeat1.control-20>
                                <label>label</label>
                                <hint/>
                            </repeat1.control-20>
                            <repeat1.control-21>
                                <label/>
                                <hint/>
                            </repeat1.control-21>
                            <repeat1.control-22>
                                <label/>
                                <hint/>
                            </repeat1.control-22>
                            <repeat3.control-11>
                                <label/>
                                <hint/>
                            </repeat3.control-11>
                            <repeat3.control-12>
                                <label/>
                                <hint/>
                            </repeat3.control-12>
                            <repeat3.control-13>
                                <label/>
                                <hint/>
                            </repeat3.control-13>
                            <repeat3.control-14>
                                <label/>
                                <hint/>
                            </repeat3.control-14>
                            <repeat3.control-23>
                                <label/>
                                <hint/>
                            </repeat3.control-23>
                            <repeat2.control-5>
                                <label>label</label>
                                <hint/>
                            </repeat2.control-5>
                            <repeat2.control-6>
                                <label>label</label>
                                <hint/>
                            </repeat2.control-6>
                            <repeat2.control-7>
                                <label/>
                                <hint/>
                            </repeat2.control-7>
                            <repeat2.control-8>
                                <label/>
                                <hint/>
                            </repeat2.control-8>
                            <repeat2.control-9>
                                <label/>
                                <hint/>
                            </repeat2.control-9>
                            <repeat2.control-15>
                                <label/>
                                <hint/>
                            </repeat2.control-15>
                            <multi-line-repeated-grid-section-2>
                                <label>Multi-line Repeated Grid</label>
                            </multi-line-repeated-grid-section-2>
                            <repeated-grid-section-1>
                                <label>Repeated Grid</label>
                                <help/>
                            </repeated-grid-section-1>
                            <repeating-section>
                                <label>Repeating Section</label>
                                <help/>
                            </repeating-section>

                        </resource>
                    </resources>
                </xf:instance>

                
                <xf:instance id="fr-service-request-instance" xxf:exclude-result-prefixes="#all">
                    <request/>
                </xf:instance>

                <xf:instance id="fr-service-response-instance" xxf:exclude-result-prefixes="#all">
                    <response/>
                </xf:instance>
                <xf:instance xxf:readonly="true" xxf:exclude-result-prefixes="#all"
                             id="multi-line-repeated-grid-template">
                    <multi-line-repeated-grid-iteration>
                        <repeat2.control-5/>
                        <repeat2.control-6/>
                        <repeat2.control-7/>
                        <repeat2.control-8/>
                        <repeat2.control-9/>
                        <repeat2.control-15/>
                    </multi-line-repeated-grid-iteration>
                </xf:instance>
                <xf:instance xxf:readonly="true" xxf:exclude-result-prefixes="#all"
                             id="repeating-section-template">
                    <repeating-section-iteration>
                        <repeat3.control-11/>
                        <repeat3.control-12/>
                        <repeat3.control-13/>
                        <repeat3.control-14/>
                        <repeat3.control-23/>
                    </repeating-section-iteration>
                </xf:instance>
                <xf:instance xxf:readonly="true" xxf:exclude-result-prefixes="#all"
                             id="one-line-repeated-grid-template">
                    <one-line-repeated-grid-iteration>
                        <repeat1.control-19/>
                        <repeat1.control-20/>
                        <repeat1.control-21/>
                        <repeat1.control-22/>
                    </one-line-repeated-grid-iteration>
                </xf:instance>

            </xf:model>
        </xh:head>
        <xh:body>
            <fr:view>
                <fr:body xmlns:xbl="http://www.w3.org/ns/xbl"
                         xmlns:oxf="http://www.orbeon.com/oxf/processors"
                         xmlns:p="http://www.orbeon.com/oxf/pipeline">
                    <fr:section id="repeated-grid-section-1-control" bind="repeated-grid-section-1-bind">
                        <xf:label ref="$form-resources/repeated-grid-section-1/label"/>
                        <fr:grid id="one-line-repeated-grid-control" bind="one-line-repeated-grid-bind"
                                 repeat="content"
                                 min="1"
                                 template="instance('one-line-repeated-grid-template')">
                            <xh:tr>
                                <xh:td>
                                    <xf:input id="repeat1.control-19-control" bind="repeat1.control-19-bind">
                                        <xf:label ref="$form-resources/repeat1.control-19/label"/>
                                        <xf:hint ref="$form-resources/repeat1.control-19/hint"/>
                                        <xf:alert ref="$fr-resources/detail/labels/alert"/>

                                    </xf:input>
                                </xh:td>
                                <xh:td>
                                    <xf:input id="repeat1.control-20-control" bind="repeat1.control-20-bind">
                                        <xf:label ref="$form-resources/repeat1.control-20/label"/>
                                        <xf:hint ref="$form-resources/repeat1.control-20/hint"/>
                                        <xf:alert ref="$fr-resources/detail/labels/alert"/>

                                    </xf:input>
                                </xh:td>
                                <xh:td>
                                    <xf:input id="repeat1.control-21-control" bind="repeat1.control-21-bind">
                                        <xf:label ref="$form-resources/repeat1.control-21/label"/>
                                        <xf:hint ref="$form-resources/repeat1.control-21/hint"/>
                                        <xf:alert ref="$fr-resources/detail/labels/alert"/>

                                    </xf:input>
                                </xh:td>
                                <xh:td>
                                    <xf:input id="repeat1.control-22-control" bind="repeat1.control-22-bind">
                                        <xf:label ref="$form-resources/repeat1.control-22/label"/>
                                        <xf:hint ref="$form-resources/repeat1.control-22/hint"/>
                                        <xf:alert ref="$fr-resources/detail/labels/alert"/>

                                    </xf:input>
                                </xh:td>
                            </xh:tr>
                        </fr:grid>
                    </fr:section>
                    <fr:section id="multi-line-repeated-grid-section-2-control"
                                bind="multi-line-repeated-grid-section-2-bind">
                        <xf:label ref="$form-resources/multi-line-repeated-grid-section-2/label"/>
                        <fr:grid id="multi-line-repeated-grid-control" bind="multi-line-repeated-grid-bind"
                                 repeat="content"
                                 min="1"
                                 template="instance('multi-line-repeated-grid-template')">
                            <xh:tr>
                                <xh:td>
                                    <xf:input id="repeat2.control-5-control" bind="repeat2.control-5-bind">
                                        <xf:label ref="$form-resources/repeat2.control-5/label"/>
                                        <xf:hint ref="$form-resources/repeat2.control-5/hint"/>
                                        <xf:alert ref="$fr-resources/detail/labels/alert"/>

                                    </xf:input>
                                </xh:td>
                                <xh:td>
                                    <xf:input id="repeat2.control-6-control" bind="repeat2.control-6-bind">
                                        <xf:label ref="$form-resources/repeat2.control-6/label"/>
                                        <xf:hint ref="$form-resources/repeat2.control-6/hint"/>
                                        <xf:alert ref="$fr-resources/detail/labels/alert"/>

                                    </xf:input>
                                </xh:td>
                                <xh:td>
                                    <xf:input id="repeat2.control-7-control" bind="repeat2.control-7-bind">
                                        <xf:label ref="$form-resources/repeat2.control-7/label"/>
                                        <xf:hint ref="$form-resources/repeat2.control-7/hint"/>
                                        <xf:alert ref="$fr-resources/detail/labels/alert"/>

                                    </xf:input>
                                </xh:td>
                                <xh:td>
                                    <xf:input id="repeat2.control-8-control" bind="repeat2.control-8-bind">
                                        <xf:label ref="$form-resources/repeat2.control-8/label"/>
                                        <xf:hint ref="$form-resources/repeat2.control-8/hint"/>
                                        <xf:alert ref="$fr-resources/detail/labels/alert"/>

                                    </xf:input>
                                </xh:td>
                            </xh:tr>
                            <xh:tr>
                                <xh:td>
                                    <xf:input id="repeat2.control-9-control" bind="repeat2.control-9-bind">
                                        <xf:label ref="$form-resources/repeat2.control-9/label"/>
                                        <xf:hint ref="$form-resources/repeat2.control-9/hint"/>
                                        <xf:alert ref="$fr-resources/detail/labels/alert"/>

                                    </xf:input>
                                </xh:td>
                                <xh:td>
                                    <xf:input id="repeat2.control-15-control" bind="repeat2.control-15-bind">
                                        <xf:label ref="$form-resources/repeat2.control-15/label"/>
                                        <xf:hint ref="$form-resources/repeat2.control-15/hint"/>
                                        <xf:alert ref="$fr-resources/detail/labels/alert"/>

                                    </xf:input>
                                </xh:td>
                                <xh:td/>
                                <xh:td/>
                            </xh:tr>
                        </fr:grid>
                    </fr:section>
                    <fr:section id="repeating-section-control" bind="repeating-section-bind" repeat="content"
                                template="instance('repeating-section-template')">
                        <xf:label ref="$form-resources/repeating-section/label"/>
                        <fr:grid>
                            <xh:tr>
                                <xh:td>
                                    <xf:textarea id="repeat3.control-11-control" bind="repeat3.control-11-bind">
                                        <xf:label ref="$form-resources/repeat3.control-11/label"/>
                                        <xf:hint ref="$form-resources/repeat3.control-11/hint"/>
                                        <xf:alert ref="$fr-resources/detail/labels/alert"/>

                                    </xf:textarea>
                                </xh:td>
                                <xh:td>
                                    <xf:textarea id="repeat3.control-12-control" bind="repeat3.control-12-bind">
                                        <xf:label ref="$form-resources/repeat3.control-12/label"/>
                                        <xf:hint ref="$form-resources/repeat3.control-12/hint"/>
                                        <xf:alert ref="$fr-resources/detail/labels/alert"/>

                                    </xf:textarea>
                                </xh:td>
                                <xh:td>
                                    <xf:textarea id="repeat3.control-13-control" bind="repeat3.control-13-bind">
                                        <xf:label ref="$form-resources/repeat3.control-13/label"/>
                                        <xf:hint ref="$form-resources/repeat3.control-13/hint"/>
                                        <xf:alert ref="$fr-resources/detail/labels/alert"/>

                                    </xf:textarea>
                                </xh:td>
                                <xh:td>
                                    <xf:textarea id="repeat3.control-14-control" bind="repeat3.control-14-bind">
                                        <xf:label ref="$form-resources/repeat3.control-14/label"/>
                                        <xf:hint ref="$form-resources/repeat3.control-14/hint"/>
                                        <xf:alert ref="$fr-resources/detail/labels/alert"/>

                                    </xf:textarea>
                                </xh:td>
                            </xh:tr>
                        </fr:grid>
                        <fr:grid>
                            <xh:tr>
                                <xh:td>
                                    <xf:textarea id="repeat3.control-23-control" bind="repeat3.control-23-bind">
                                        <xf:label ref="$form-resources/repeat3.control-23/label"/>
                                        <xf:hint ref="$form-resources/repeat3.control-23/hint"/>
                                        <xf:alert ref="$fr-resources/detail/labels/alert"/>

                                    </xf:textarea>
                                </xh:td>
                            </xh:tr>
                        </fr:grid>
                    </fr:section>
                </fr:body>
            </fr:view>
        </xh:body>
    </xh:html>

**Comment by ebruchez** [comment]
I am not sure I understand where the type `orbeonField` comes from as there is no reference to it in the form definition. Where does it come from?

**Comment by ajw625** [comment]
`orbeonField` and `orbeonSection` are not something I have defined. Those attributes are included by Orbeon as metadata when using the `send` feature.

**Comment by ebruchez** [comment]
@ajw625 Mmh, I don't see which code could add any `xsi:*` attributes, and if I try to send the XML data, I don't get those. Are you sure this is not added by your `http://posttestserver.com/post.php?dir=vivid_orbeon` service?

**Comment by ajw625** [comment]
My mistake. The attributes are not added by `posttestserver.com`. That is not my service. It is a testing service provided for anyone who wants to use it.  But the attributes are added by our component that wraps Orbeon. Closing this.

**Comment by ebruchez** [comment]
Excellent, thanks for confirming!
