### ISSUE TITLE
Supports namespaces in section templates 

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2466]
[+1 from community](http://discuss.orbeon.com/section-template-custom-namespace-error-td4660876.html)

An example  where a namespace is used in a section templates  is mentioned in the thread linked above.

**Comment by ebruchez** [comment]
Error ocurs in [`InstanceMirror`](https://github.com/orbeon/orbeon-forms/blob/6fff6abadbfd7f081c55b0237b92807793b66ffc/src/main/scala/org/orbeon/oxf/xforms/control/controls/InstanceMirror.scala#L269) while evaluating the expression `foo:test[1]`.

**Comment by ebruchez** [comment]
Issue is evaluating expression while defining proper ns mappings. Possible options:

- not using XPath but just navigating `(ns, local)` steps
- using XPath but mapping `ns0`, `ns1`, etc. for each step while creating expression (and could optimize)
