### ISSUE TITLE
Improve behavior of TOC links in wizard validate mode

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2468]
Right now, it seems that the links in the TOC can only be used to navigate back to pages the user already visited, which is inline with what is [documented](http://doc.orbeon.com/form-runner/feature/wizard-view.html). This RFE calls for:

- If the user is allowed to navigate forward to the next page using the "next" button, she should also be able to do so by clicking on the title of that page in TOC.
- If the user isn't allowed to navigate to a certain page, the entry in the TOC for that page shouldn't be a link, but just a label, so users can know before clicking on it that clicking won't navigate to that page. (In addition, we could imagine the styling to be slightly different, e.g. greyed out.)

[+1 from community](http://discuss.orbeon.com/wizard-validate-mode-section-links-in-table-of-contents-td4660884.html)

**Comment by ebruchez** [comment]
Both suggestions make sense to me.

**Comment by avernet** [comment]
When loading existing data (e.g. the same w9 form data), one can *not* navigate to *any* section using links in the TOC, but can navigate using the "next" button. We'll want to make sure that fixing the first bullet point above should takes care of this as well.

**Comment by ebruchez** [comment]
Following @avernet's last comment, entering separate issue #2602.
