### ISSUE TITLE
Function to access the value of a control within a section template

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2471]
Right now we have to use a path, which is error-prone.

Possibly:

```
fr:control-value($name)
fr:control-value($name as xs:string, $scopes as xs:string*)
```

Where `$name` is the control name and `$scopes` is an optional list of scopes to drill down into templates. For example if you have a section template called `my-section-template`:

```
fr:control-value('first-name', 'my-section-template')
```

Question: does this or another function need to be able to also access controls in _enclosing_ section templates? If so how would we do that?

[+1 from customer](https://basecamp.com/1721271/projects/3412232/messages/52315627)

See also #1095.

**Comment by avernet** [comment]
In general, using `$first-name` is quite nice. For section templates, there is the possibility that:

- multiple instances of a section template are used in a form,
- or that a field in the form use the same name as a field in the section template,

so just `$first-name` would beg the question "which first name?". Still, in cases when there is just one, using `$first-name` would is simpler than `fr:control-value('first-name')`. So could we imagine that:

- `$first-name` returns "all first names" when used outside of a section template, but "just the first name in the current section template" if used within the section template (similar to what is done for repeats).
- For cases when you want to address a specific *first name* in a specific section template, `fr:control-value('first-name', 'my-section-template')` would work, but we could maybe use a syntax that would feel less different than `$first-name`, e.g. something like `$my-section-template.first-name`.

**Comment by ebruchez** [comment]
I don't understand what you mean by "all first names"?

Say a formula in your form uses `$first-name`. You test your form and things work. Then you make a totally unrelated change in a section template, and your formula would stop working. That is something that any solution should avoid. I am not sure your proposal would cause this issue.

**Comment by avernet** [comment]
"All first names" refers to all the fields named `first-name`, whether they are in a section template instance, repeat, or "normal" field. Under that "proposal", you could indeed have a form using `$first-name` that works fine, but stops working after a section template is added or changed if that section template has a field named `first-name`. And I agree: even if this doesn't happen often, it is disturbing, and feels like bad design.

So maybe references to names in section templates should always be namespaced. What about supporting a syntax like `$section-name.field-name`, which would feel more inline with the existing syntax (just `$field-name`) used to refer to a field outside of a section template?

**Comment by ebruchez** [comment]
One question that comes to mind is: how would we expose those variables? Currently variables are exposed through named binds. But we don't have such named binds exposed for section templates. So I am not even sure the variables method is possible to implement without major changes.

**Comment by avernet** [comment]
A good question. I was first trying to figure out what would be the best "API" from the point of view of form authors. I.e. is `$section-name.field-name` good for form authors?

Then we can decide whether we want to go for "best, but hard to implement" or "not as good, but easier to implement". Maybe this is something we need to brainstorm about.

**Comment by ebruchez** [comment]
Also, I am still hoping a future "formula editor" will make the point moot: i.e. that we won't care whether we use variables or functions, because that will be exposed to the UI.

Speaking of which, we could even now allow the user to write variables in the UI, and rewrite the expressions to translate variables to functions, if that is better.

**Comment by avernet** [comment]
True.

**Comment by ebruchez** [comment]
[+1 from customer](https://mail.google.com/mail/u/0/#inbox/1562652535c246be)

**Comment by ebruchez** [comment]
Just created and added more general thoughts about binding section template and an enclosing form in #3008.

**Comment by avernet** [comment]
[+1 from user](http://discuss.orbeon.com/Get-initial-value-of-an-another-section-of-a-library-to-do-a-condition-td4664333.html)

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/1966556/messages/1769121996)

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/1966556/messages/2891382857#__recording_2891787767)

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/17077193/messages/3463782520)

**Comment by ebruchez** [comment]
In #5005, we suggest reusing `fr:control-string-value()` for this purpose.

Are we good with using a new 3rd parameter? Its value could be:

1. A library name. What if the same control name appears multiple times in the library? Well, right now this is not possible as the library form enforces that.
2. A section name (the name of the section in the enclosing form).
3. A special name could allow access the other way: from a section template to the global scope. Is this desirable? This is a dependency going in a way we might not like. But we could, for example , pass `_top` or `_form` or something else as 
"scope".

As reminder:

- Section templates cannot, currently, be nested. This means that a library form cannot include a section template from the global library. But this could be added (#1562).
- There are only 2 libraries available to a form at a given time: a global library (`orbeon`, although that could be renamed), and an "app" library. But we could consider, in the future, supporting more libraries.

**Comment by ebruchez** [comment]
[Documented](https://doc.orbeon.com/xforms/xpath/extension-functions/extension-form-runner#fr-control-string-value)
