### ISSUE TITLE
Section expander not showing for section inside repeating section

### ISSUE THREAD

**Issue by ajw625** [orbeon/orbeon-forms#2496]
I have attached a form definition created in Form Builder. It contains a Sites section, which contains an Add Site repeating sub-section, which contains two sub-sub-sections called Add Contact and Copy Contacts. The triangle shaped expander button for these sub-sub-sections is not displaying. I have contfirmed this is a problem in Chrome, IE 11, and Firefox. I also tested this in the Form Builder on orbeon.com to ensure that my local configuration is not a factor. Note that if I click the Test button in Form Builder I am able to see the content of the sections (at the moment it looks a little funny because some fields are hidden based on formulas but they are still taking up space).

Also note that whenever I open this form up in Form Builder, the "Sites", "Permit Over Crown Land", and "Application for Fee Exemption" sections are initially collapsed.

[form_definition_2_technicalInformation.txt](https://github.com/orbeon/orbeon-forms/files/90831/form_definition_2_technicalInformation.txt)

![image](https://cloud.githubusercontent.com/assets/9143532/12334064/c6dacf0e-baac-11e5-9da2-4a252cb6c528.png)

**Comment by avernet** [comment]
I am reproducing this on master, with just a nested section inside a repeating section:

![screen shot 2016-01-14 at 7 45 39 pm](https://cloud.githubusercontent.com/assets/106961/12344908/749007d2-baf7-11e5-8491-ca03003e2fd0.png)

**Comment by avernet** [comment]
@ebruchez [This rule](https://github.com/orbeon/orbeon-forms/blob/tag-release-4.10.2-ce/src/resources-packaged/xbl/orbeon/repeater/repeater.less#L45) overrides the CSS that shows the triangle to expand/collapse sections. It looks like just removing it might solve this, but I imagine it was put there for a reason. Do you remember?

![screen shot 2016-01-14 at 7 57 10 pm](https://cloud.githubusercontent.com/assets/106961/12345062/0bb71d48-baf9-11e5-9113-6536392f2b5d.png)

**Comment by ebruchez** [comment]
@avernet I checked, and I don't know (that was done more than 2 years ago).

**Comment by ajw625** [comment]
Thanks, guys. For now I have overridden `repeater.css` and commented out the rule and that allows me to edit those sub-sub-sections.

    /*
    .orbeon .fr-repeat .fr-repeat-content > .xbl-fr-section > div > h2 > .fr-section-label {
      padding-left: 0;
      background-image: none;
    }
    */

**Comment by avernet** [comment]
I thought that we might have added this for the case section repeat minimal appearance (`oxf.xforms.xbl.fr.section.repeat.appearance.*.*` set to `minimal`), but that doesn't seem to be the case as the problem shows up as well with the minimal appearance, and removing that piece of CSS solves it. So, for now at least, I've removed it, and marked this issue as fixed.

**Comment by ajw625** [comment]
Removing the rule does allow the sections to be expanded. But for some reason whenever I open this form in Form Builder, the last three sections are collapsed:

![image](https://cloud.githubusercontent.com/assets/9143532/12927235/00702df8-cf1c-11e5-9504-2f5759998651.png)

This isn't really a problem for me, since I can just expand it, but I don't think this is the desired behaviour.

**Comment by avernet** [comment]
@ajw625 Are you referring to the form you linked in your first message in this issue? I just pasted the source in a new form, and am seeing all the sections open, including the last 3. (And I don't think that this change to the CSS should have an impact on whether sections are open or closed.)

**Comment by ajw625** [comment]
@avernet Yes, that is the form I am referring to. But I didn't mean to imply that the CSS change caused this issue. The issue was already there in addition to the section expander button being missing. The CSS change fixes the button and allows me to expand the collapsed sections, but still whenever I open the form those sections are collapsed. I just tried pasting the source into a form in FB on orbeon.com and got the same result. I tried it in Chrome, Firefox, and IE 11. I'm not sure why you wouldn't experience the same thing.

**Comment by avernet** [comment]
@ajw625 Got it, I now understand what you meant: those sections are also closed for me in Form Builder, however they are not if you run the form, either using *Test* or by publishing it first. When Form Builder finds what it considers to be a large form, it only shows the first section open, this to improve performance in Form Builder. But you can of course open the section as you wish, and this has no impact on what users will see once your form is published.

**Comment by ajw625** [comment]
@avernet I see. So this is by design, a performance booster. That makes sense. Thanks.
