### ISSUE TITLE
Find workaround in handwritten signature to #2442 unfixable at the moment

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2508]
As far as I can remember, a fix to #2442 was attempted to solve an issue with the signature component. Since we reverted that fix, and solving #2442 seems to be too much work at the moment, we want to check if not having that fix causes a problem to the new signature component, and if it does find a workaround.

**Comment by avernet** [comment]
Fixing #2442 would prevent the server from sending back to the client a value the client just sent to the server. Updating with an identical value was creating a slight blinking, but we are now detecting that case in the JavaScript, and just not doing the update. So I'm not aware of an issue with the handwritten signature component caused by us not fixing #2442. Closing.

**Comment by avernet** [comment]
Reopening. The issue was that if the server sends back to the client a value the client sent to the server, then the client needs to implement a logic to avoid updating the field with a value that is now "obsolete". Imagine:

1. User draws A, client sends A to server, server computes new value of the field as B, sends B to client ⇒ client replaces signature with B. All good.
2. User draws A, client sends A to server, user draws B, server sends A to client ⇒ how can the client know shouldn't replace B, the current value, with A, the value it got from the server?

I don't think we can, at the level of the handwritten signature, reliably determine if an update we get from the server should be applied. For this, we would need some hook in the "AjaxServer" code, e.g. to know when a value was actually sent vs. put in the queue to be sent.

Fixing #2442 would be the most elegant solution. If we can't for 4.11, we could try using an `xf:input` to exchange the value between the client and the server, and the mechanisms we have underlying the `xf:input` might handle this correctly.

**Comment by ebruchez** [comment]
Fixed with #2648. We now have native support for values (`externa-value`) and other lifecycle methods (`javascript-lifecycle`) which solve this problem.
