### ISSUE TITLE
Proxy Portlet: support singleton forms 

### ISSUE THREAD

**Issue by nikyasu** [orbeon/orbeon-forms#2513]
I tried to add a singleton forms with the proxy portlet in liferay.

But when i set "Form Runner page" as "New page", if a forms already exists, the portlet shows this error:

"Orbeon Forms - Page Not Found
We are sorry, but the resource you have requested is not available on this server. "

According to the doc, if a form exist, the portlet should show this forms in edit mode.

(Orbeon Forms 4.10.2 PE with trial license.)

**Comment by ebruchez** [comment]
By "singleton form" I assume you are selecting the "Singleton form" checkbox in Form Settings? Do things work is the "Singleton form" checkbox is not checked?

I suspect that this happens because the server might issue a redirect.

**Comment by ebruchez** [comment]
I reproduce this, and I confirm that Form Runner is returning a 302 code, with `Location`:

```
http://localhost:8080/orbeon/fr/orbeon/issue2513/wsrp_rewrite?
    wsrp-urlType=render&
    wsrp-navigationalState=orbeon.path%3D%252Ffr%252Forbeon%252Fissue2513%252Fedit%252Fc231e1d79efce56189eefe85d738b65a69f999ca/wsrp_rewrite
```

The issue is that we don't properly rewrite the `Location` header and therefore access a URL which doesn't exist.

**Comment by ebruchez** [comment]
Tried to rewrite the `Location` header in [`callService()`](https://github.com/orbeon/orbeon-forms/blob/60f04a10eb381d380c61d050f8a2bc8014dcdc23/src/main/scala/org/orbeon/oxf/fr/embedding/APISupport.scala#L139), but we don't have access to an `EmbeddingContextWithResponse` so cannot do the rewrite there. So we need to figure that out.

**Comment by ebruchez** [comment]
Questions:

- Should the `Location` header sent by Form Runner even be encoded? It refers to a Form Runner URL.
- What about `orbeon.path`? Does it need updating too?

**Comment by ebrost** [comment]
I was unfortunatly able to reproduce the bug. It's a major usability  issue for us as the user has to click once more in a menu to edit or create a singleton form.

**Comment by ebruchez** [comment]
@ebrost It's definitely a bug. It's scheduled to be fixed for the upcoming 4.11.

**Comment by ebruchez** [comment]
Current strategy:

- Form Runner responds with a non-encoded `Location` path
- proxy portlet performs the redirect
    - note that we can't `setRenderParameters()` during a render
    - this argues for the redirect to be handled at the HTTP client level (which is the default)

**Comment by ebruchez** [comment]
Noting that his also fails with the full portlet.
