### ISSUE TITLE
Standard logout page

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2522]
Just like we have a standard login page, for cases when FORM authentication is used, we should also provide a logout page.

- [x] UI – Provide "link" to logout, e.g. `icon-user` (![User icon](https://user-images.githubusercontent.com/106961/39011864-884c5310-43c7-11e8-93b6-a3b58a3d1470.png)), which when clicked shows a drop-down with "Signed in as homer", and an option to logout, similar with what is done by GitHub (see below).
    - Files involved
        - `fr/components/view.xsl`, with its `<fr:user-nav/>`
        - `fr/style/form-runner-orbeon.less`
    - [x] Properties
        ```xml
        <property as="xs:boolean" name="oxf.fr.authentication.user-menu.enable"     value="true"/>
        <property as="xs:string"  name="oxf.fr.authentication.user-menu.uri.login"  value="/fr/login"/>
        <property as="xs:string"  name="oxf.fr.authentication.user-menu.uri.logout" value="/fr/logout"/>
        ```
    - Menu in toolbar
        - [x] Using Flex layout
- [x] New login page
- [x] New logout page, which invalidates the session
    - Invalidating from XForms is dangerous, as the XForms engine assumes we have a valid session
    - So instead, invalidate from XPL, running `oxf:session-invalidator`
    - [x] If accessing `/fr/logout-done` while logged in, redirect to Form Runner home page
- [x] Handle localization in `login.xhtml` and `logout.xhtml`

**Comment by ebruchez** [comment]
[+1 from user](https://mail.google.com/mail/u/0/#inbox/161a3592e3049ffa)

**Comment by ebruchez** [comment]
See also #455.

**Comment by avernet** [comment]
- [ ] UI – Provide "link" to logout, e.g. `icon-user` (![screen shot 2018-04-19 at 11 47 00 am](https://user-images.githubusercontent.com/106961/39011864-884c5310-43c7-11e8-93b6-a3b58a3d1470.png)), which when clicked shows a drop-down with "Signed in as homer", and an option to logout, similar with what is done by GitHub (see below).
- [ ] New boolean property `oxf.fr.authentication.user-menu.show.*.*` – The UI described earlier shows only if a user is logged in and if this property is true.
- [ ] New property `oxf.fr.authentication.user-menu.logout-process.*.*` – Name of the process to run when the user chooses to log out.
- [ ] New action `invalidate-session` and process `logout` that runs this action and takes the user to a logout page.
- [ ] New logout page.

![screen shot 2018-04-19 at 11 45 44 am](https://user-images.githubusercontent.com/106961/39011919-b716e5c0-43c7-11e8-8c6d-e2400bfcaf53.png)

**Comment by avernet** [comment]
Known caveat of the logout page when

**Comment by ebruchez** [comment]
Time to do #1802 to avoid depending on form filling.

**Comment by avernet** [comment]
Code complete, closing. (Of course, we can open issue if we find bugs or missing features during testing.)

**Comment by ebruchez** [comment]
[Documentation is here](https://doc.orbeon.com/form-runner/access-control/login-logout)
