### ISSUE TITLE
Signature not really cleared with "Clear" button

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2525]
- Controls form
- Clear signature
- signature field is now blank
- navigate to Review
- notice signature is still there

**Comment by avernet** [comment]
Fixed in https://github.com/orbeon/orbeon-forms-pe/commit/6c26b72af0d6cf9120fe5115bc5b748b6b4df58a.

**Comment by avernet** [comment]
Minor: remove unnecessary `event` attribute: https://github.com/orbeon/orbeon-forms-pe/commit/90cc6aa554f4cabf06f8f83e8643887eb2f002c2.
