### ISSUE TITLE
"key not found" exception when using <xf:action type="javascript"> instead of <xxf:script>

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2533]
To reproduce, in Form Builder create a form with an handwritten signature, publish, edit `handwritten-signature.xbl` and replace the `<xxf:script>` by `<xf:action type="javascript">`, open the form's /new, click "clear", and you get [the following exception](https://gist.github.com/avernet/409d3387db291524f523).

**Comment by ebruchez** [comment]
Simple answer: when we collect scripts statically, we only look at `xxf:script` elements, not `xf:action[@type = 'javascript']` elements. So we need to fix this.
