### ISSUE TITLE
With XPath analysis, calculations with forward reference to calculated value aren't evaluated

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2541]
To reproduce, with the PE, create a form in Form Builder, with 3 fields `a`, `b`, and `c`, in that order. Have `c` calculated as `$a`, and `b` calculated as `$c`. Enter a value in `a`: it shows in `c`, but not in `b`. Change the value in `a`: it changes in `c`, but there still is nothing in `b` (not even the previous value entered in `a` as is the case with Orbeon Forms CE).

Fixing #2186 should take care of this, but we should check that this behavior doesn't reveal another issue with the XPath dependency engine.

**Comment by ebruchez** [comment]
Fixed by #2186, closing.
