### ISSUE TITLE
datepicker i18n : month in french is not accepted

### ISSUE THREAD

**Issue by ricetrac** [orbeon/orbeon-forms#2568]
Hello,

We use the date-picker on our page with "lang=fr" : it works fine. The display is ok. (formatting and spelling of month).
But when we type a date like "2 mars", there is an javascript error
![copie_erreur_datepicker](https://cloud.githubusercontent.com/assets/1933261/13249413/680f6470-da24-11e5-8aec-71841e7722f5.png)

If we type "2 march", it's ok.

I found in xforms.js, the variable _monthNames which contains the month in English :
`_monthNames: "January February March April May June July August September October November December".split(" "),
`
I think that if I update with month in French, I could type "2 mars".

It could be a good idea to create a parameter for this information.

thank You

**Comment by avernet** [comment]
Indeed, and this is now fixed. When the current language is French, you can now type "2 mars", and the proper data will be shown. This will be in 4.11.

While doing this, I removed the support for "next Tuesday", which wasn't localized, I didn't even know existed, and has an ambiguous meaning for "next".

**Comment by ricetrac** [comment]
Thank You alex.

Julien
