### ISSUE TITLE
Empty Table cells are shown with Invisible fields in a Repeating Grid 

### ISSUE THREAD

**Issue by Nexonic** [orbeon/orbeon-forms#2583]
![image](https://cloud.githubusercontent.com/assets/17457364/13507555/e576a166-e137-11e5-880e-017751ebf45e.png)

1. Create a Repeating Grid
2. Add some fields. Set visibility rule to hide them
3. Empty table cells are shown

**Comment by ebruchez** [comment]
We have a similar issue: #2414.

**Comment by ebruchez** [comment]
Suggesting marking this one as a duplicate.
