### ISSUE TITLE
None.get in MigrationOps.buildGridMigrationMap() on publish 

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2594]
To reproduce, paste and publish the form pasted in [this message](http://discuss.orbeon.com/PDF-generation-unable-to-match-the-relevant-condition-td4661189.html#a4661197).

**Comment by ebruchez** [comment]
I do reproduce this.

**Comment by ebruchez** [comment]
The sample form doesn't follow the Form Runner conventions, in that the control `id` and `bind` attributes are not in sync.

Still, I addressed this particular error by searching the `<fr:bind>` based on the `bind` attribute and not the `id.
