### ISSUE TITLE
Exceptions showing in the console

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2598]
E.g. the `None.get` of #2594, but others do as well.

**Comment by ebruchez** [comment]
Check if there are any `println` in the code. Could it come from there?

**Comment by avernet** [comment]
I just just got this [this exception](https://github.com/orbeon/orbeon-forms/files/183291/a.txt) on the console.

**Comment by ebruchez** [comment]
I don't reproduce the last scenario: I tried to cause an error in the relational search, and the error ends up in the logs as expected.

**Comment by ebruchez** [comment]
Closing for now, reopen if a new occurrence is found.

**Comment by avernet** [comment]
With Tomcat 8, I am getting a `java.sql.SQLException: No suitable driver` in the console if I try to use the Oracle persistence layer without the corresponding `<Resource>` in Tomcat's `server.xml`. Debugging the code, it seems the message is logged when we call `dataSource.getConnection()`, and I suspect Tomcat is logging this. Leaving this as closed, since it seems outside of our control.
