### ISSUE TITLE
Signature has incorrect size in Controls form

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2605]
See screenshot.

![screen shot 2016-03-10 at 11 37 17 am](https://cloud.githubusercontent.com/assets/105769/13711119/be4ad8e2-e771-11e5-98f8-069fff44f097.png)

**Comment by avernet** [comment]
Fixed by https://github.com/orbeon/orbeon-forms-pe/commit/9341a5b1bab32fd217b611038c6755c6f69b5108.
