### ISSUE TITLE
Publish shouldn't save if form author chooses cancel in publish dialog

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2611]
If a form author clicks on publish, then cancels the action in the publish dialog, she most likely expects her action to have no side effect, in particular that Form Builder didn't save data. I.e. saving should happen only when publishing is confirmed in the publish dialog.

**Comment by ebruchez** [comment]
That seemed easy enough, but if we want to go through an intermediary process, we must support #2613 first, which not a trivial extension.

Alternatively, we could decide to bake this in and hardcode the save, which might not be a bad idea.
