### ISSUE TITLE
FB: Support controls other than xf:input for custom settings

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2612]
Currently, the Control Settings dialog only handles `<xf:input>` controls inside `<fb:control-details>`, as [mentioned in the documentation](http://doc.orbeon.com/form-builder/metadata.html#control-metadata-for-the-edit-control-details-dialog).

[+1 from community](http://stackoverflow.com/questions/36015890/is-it-possible-to-have-a-select-in-a-custom-controls-basic-settings)

**Comment by ebruchez** [comment]
I think we might want to consider using `xxf:dynamic` for that. I remember trying in the early days, and there were bugs, but it might work now. Something to try.

**Comment by ebruchez** [comment]
[Documented](http://doc.orbeon.com/form-builder/metadata.html#control-metadata-for-the-control-settings-dialog)
