### ISSUE TITLE
xf:textarea mediatype="text/html" not working on IE11

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2618]
It uses the YUI RTE, which apparently doesn't work with IE11. It does with IE10 and with Edge. We don't want to support YUI RTE going forward, but this is a little bit of a problem since this is the editor we use by default for `<xf:textarea mediatype="text/html">`.

![RTE on IE11](http://i.imgur.com/8ViQesS.png)

**Comment by ebruchez** [comment]
Binding `fr:tinymce` to `xf|textarea[mediatype = 'text/html']` appears to work.

Tasks:

- [ ] update release notes
- [ ] remove native RTE code
- [ ] later: Form Builder should probably switch to using `<xf:textarea>` (see also #2300)
