### ISSUE TITLE
Demo signature is too tall

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2620]
Compare `edit` and `view` modes below.

![edit](https://cloud.githubusercontent.com/assets/105769/13863271/f07cbe46-ec55-11e5-83a9-50611c506360.png)
![view](https://cloud.githubusercontent.com/assets/105769/13863272/f07d2afc-ec55-11e5-9026-deb521764de8.png)

**Comment by avernet** [comment]
Fixed by https://github.com/orbeon/orbeon-forms-pe/commit/2a28c5fce75fb91ba1327364a0c02571aacb1354.
