### ISSUE TITLE
Demo signature goes over line in PDF

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2621]
See screenshot below.

By the way, would there be a way to make the background of the signature transparent by default? I assume this is not the case already?

![pdf](https://cloud.githubusercontent.com/assets/105769/13863302/1a7407cc-ec56-11e5-82b2-7d5b4fa4d6c8.png)

**Comment by avernet** [comment]
Fixed by https://github.com/orbeon/orbeon-forms-pe/commit/6428521aadaba5b310c4245c7adf26c865ad9d54.
