### ISSUE TITLE
Handwritten signature: line doesn't draw under cursor

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2623]
- http://localhost:8080/orbeon/fr/orbeon/controls/new
- Attachments
- try to write on top of existing signature
- notice line doesn't draw under cursor

**Comment by avernet** [comment]
Fixed by https://github.com/orbeon/orbeon-forms-pe/commit/a6dc1045ad3f4aa443b9f2f06dd9323d81ad8fe3.
