### ISSUE TITLE
Summary: awkward line breaks in table

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2645]
See screenshot. This might be a regression.

The Created/Modified columns but also the Application Name column can wrap.

![screen shot 2016-03-23 at 11 25 36 am](https://cloud.githubusercontent.com/assets/105769/13996229/040afbba-f0ea-11e5-8eb3-348edd3a1342.png)

**Comment by ebruchez** [comment]
This is due to the fact that `<xf:output>` produces an HTML `<output>` element, which we format by default to wrap.

If we address #2560, this current issue will go away as the `<xf:output>`s used on the Summary page don't have labels.

**Comment by ebruchez** [comment]
Reverted with 8d51b4c6a81370aa4fe5b8408ba89fa919925d30.

**Comment by ebruchez** [comment]
Fixed with #2560.

**Comment by avernet** [comment]
I'm also adding the *accessibility* tag to this one, since a `<label>` without a `for` is considered to be a problem by some WCAG checkers.
