### ISSUE TITLE
Support automatic setting of value upon xforms-enabled

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2648]
Since #2646, XBL components can have an external value, which means that the server uses `<xxf:value>` to tell the client about the value. This also takes place when the control shows initially.

Ideally, `AjaxServer.js` would just call `setCurrentValue()`, which we now implement for XBL components to, by delegating to the companion JavaScript object.

But that doesn't work, because:

- server first calls `getCurrentValue()`, which returns `undefined`
- fine, we implement that too
- but we can't, because the companion JavaScript object hasn't yet been initialized

When we do things by hand, we initialize the companion JavaScript object using `<xxf:action>` upon `xforms-enabled`. But scripts run control values are set, so that doesn't work.

**Comment by ebruchez** [comment]
Idea: calls of `setCurrentValue()`, etc. must create the instance if needed.

**Comment by ebruchez** [comment]
Once done, update `fr:handwritten-signature` and `fr:code-mirror`.

**Comment by avernet** [comment]
What is the status for this one? Is `updateWithServerValue()` on the companion object now supposed to be automatically called when the XBL has the `external-value` mode?

**Comment by avernet** [comment]
Re-assigning to @ebruchez to implement behavior we discussed when the page loads.

**Comment by ebruchez** [comment]
How things work now:

- JavaScript companion classes register themselves by calling `ORBEON.xforms.XBL.declareClass()`
- `instance()` is called
    - from script explicitly called form XForms
    - upon `ORBEON.xforms.FullUpdate.onFullUpdateDone()`
- some built-in controls (namely `xf|select[appearance ~= compact]`, `xf|select1[appearance ~= compact]`, `xf|range`, and `xxf|dialog`) have built-in JavaScript initialization
    - information about those is under `orbeonInitData.controls`
    - which function to call is hardcoded on the client
    - seems called whether the controls are relevant or not
   - do not pass values (values, if any, have to be stored separately)

It would be good to have a single JavaScript initialization mechanism for both built-in and XBL components. We want to move a few of the built-ins to XBL anyway (#2657, #2658).

Possible steps:

- upon `declareClass()`, map XBL CSS class to JavaScript constructor
- all `xforms.js` functions lazily instantiate `instance()` in case it is not present as `data('xforms-xbl-object')`
- upon page load, XBL controls which have the `external-value` mode and are enabled generate JavaScript initialization (format TBD)
