### ISSUE TITLE
PDF: label and its value to be on the same page

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2656]
See for instance what happens to the selection controls when generating the PDF for the *Form Builder Controls* sample form:

![screen shot 2016-03-28 at 9 50 52 am](https://cloud.githubusercontent.com/assets/106961/14083438/9c74c596-f4ca-11e5-82a9-1b70c922aa36.png)

**Comment by ebruchez** [comment]
This seems to be a regression.

**Comment by ebruchez** [comment]
Fix by reverting #2573. Also add CSS to help group section title with content.

**Comment by ebruchez** [comment]
As of 2019.1, the issue remains with enabling the original fix for #2573. Fields can be cut in half.

<img width="981" alt="Screen Shot 2019-07-31 at 4 54 59 PM" src="https://user-images.githubusercontent.com/105769/62255931-3f5c2780-b3b4-11e9-8aab-02f100c4a4d7.png">
