### ISSUE TITLE
Handwritten signature: quickly through wizard shows mirrored image

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2660]
- Controls form
- quickly click through next arrow in TOC
- notice image signature!

<img width="371" alt="screen shot 2016-03-28 at 9 16 52 pm" src="https://cloud.githubusercontent.com/assets/105769/14097825/72e285d2-f52a-11e5-84cd-9e7516980f6a.png">

**Comment by ebruchez** [comment]
Not sure if due to my latest (local) changes. You don't need to go fast actually:

- navigate to Attachments section
- click on other section
- navigate again to Attachments section

**Comment by avernet** [comment]
Fixed by https://github.com/orbeon/orbeon-forms-pe/commit/1bb9dbcd22864837cf4de321cd1396374651e020.
