### ISSUE TITLE
Clicking on section title to edit truncates title

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2661]
See screenshot. In Form Builder, the label should take the whole width.

<img width="218" alt="screen shot 2016-03-28 at 9 30 17 pm" src="https://cloud.githubusercontent.com/assets/105769/14097995/52f5ba76-f52c-11e5-8415-6a999569a20f.png">

**Comment by ebruchez** [comment]
Also can't edit new section title after adding title.

**Comment by avernet** [comment]
@ebruchez Did you recompile the CoffeeScript? This was a problem, but is now fixed for me.

**Comment by ebruchez** [comment]
That's right. Never mind then. Closing.
