### ISSUE TITLE
Pasted source "ignored" by Form Builder

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2662]
To reproduce, open Form Builder, and paste the content of  `FORM.xml` attached to [this message](https://basecamp.com/1721271/projects/2789956/messages/54672426#comment_393341664). No need to put the global/app library attached to the same message to reproduce the problem. I just checked that this worked with 4.10.2, and as far I can remember this worked as well last time I tried, in the end of February or beginning of  March timeframe.

**Comment by ebruchez** [comment]
I reproduce this. No error in the logs.

**Comment by ebruchez** [comment]
If you paste and then make a change, things work. So it seems that the paste is not taken as a change of value anymore.

**Comment by orbeon** [comment]
But I still think there is something "weird" about that form, as pasting
the source of other forms in general works. For instance, you can try
pasting the other forms attached to the same message.

**Comment by ebruchez** [comment]
Also noticing this with another form, from another user: paste and Apply and nothing happens. But paste, make a change to a string in the source, and Apply, and things work.
