### ISSUE TITLE
FB: Grid cell not tall enough with Firefox

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2663]
See screenshot.

<img width="549" alt="screen shot 2016-03-29 at 9 38 03 pm" src="https://cloud.githubusercontent.com/assets/105769/14132091/9d3c9c2e-f5f6-11e5-9fea-1d7d1dd4e5b9.png">

**Comment by avernet** [comment]
@ebruchez I'm not seeing this at the moment, so this might be due to changes you have on your side. I'm reassigning this to you for now, and feel free to re-assign it to me when when you've pushed those changes.

**Comment by avernet** [comment]
It works with a build created by Travis, closing.
