### ISSUE TITLE
Section help icon not showing when setting help

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2671]
Create a new form in Form Builder, edit the help for the existing section to be `newhelp`, click *Apply* ⇒ the help icon doesn't show to left of the "Untitled Section" label as it should. In the Ajax response, the server isn't telling the client about the new help. Save the form and reload the page ⇒ notice how the help icon now shows, as it should.

**Comment by ebruchez** [comment]
Doesn't seem to be a recent regression: also happens on `demo.orbeon.com`!

**Comment by ebruchez** [comment]
Findings so far:

- changing the section label just causes a change to the label value but no XBL change:
    ```xml
    <xxf:control id="fb≡section-1-control≡xxx" label="My New Title"/>
    ```
- `setControlHelp()` OTOH inserts a new `<xf:help>` under `<fr:section>` which causes an XBL change:
    ```xml
    <xxf:inner-html id="fb≡section-1-control">
    ```

The `<fr:section>` component gets its nested container and shadow tree rebuilt. But I suspect that `<fr:section>` itself doesn't get it's help property updated. So it still "thinks" it doesn't have a help.

**Comment by ebruchez** [comment]
For now considering that a change to a directly-nested XBL component's LHHA is an "unknown" change rather than an XBL change just rebuilding the shadow tree.

**Comment by ebruchez** [comment]
The reason it works for elements other than LHHA (and maybe nested event handlers) is that when we rebuild the shadow tree with `PartXBLAnalysis.updateShadowTree()`, we recreate the `ConcreteBinding` which contains the shadow tree with  `ComponentControl.setBinding()`. This uses the XML element from the *source* of the dynamic form.

However we then call `PartXBLAnalysis.analyzeSubtree()`, which uses `ShadowChildrenBuilder.findRelevantChildrenElements`, which uses the newly-created binding's shadow tree, created from the new source, but as for handlers (`directlyNestedHandlers`) and LHHA (`directlyNestedLHHA`), they are obtained from the XML element initially pointed to by the `ComponentControl`, and that XML element is the *old* XML element from the *static state document*. That static state hasn't been updated to contain, say the new `<xf:help>` element.

There might be a way to address that update, but for now I think we are ok with doing the "unknown" change approach.
