### ISSUE TITLE
Consider using new fancy loading bar at the top of the page

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2678]
E.g. like [this one](http://chieffancypants.github.io/angular-loading-bar/).

**Comment by ebruchez** [comment]
And remove the current "Loading…" indicator.

**Comment by avernet** [comment]
[NProgress](https://github.com/rstacruz/nprogress) looks like a reasonable option, and seems to work nicely with our code.

We could create a property allowing admins to configure what they want to use as a "loading indicator": the "legacy top-right indicator" or the "slim loading bar". However, I'm thinking that the new loading bar is so superior to the legacy indicator that it would be a shame to have to maintain both going forward. So, I suggest that, in 4.11, we switch to the slim loading bar, but keep the code for the legacy indicator, and in a future release, if we don't hear back from customers preferring the legacy indicator, we remove the code for that indicator.

**Comment by avernet** [comment]
Also see #2687, scheduled for the next released, to completely remove code dealing with the legacy loading indicator.
