### ISSUE TITLE
fr:image-annotation doesn't scale image

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2684]
See screenshot. Image is in Form Builder but it doesn't matter whether it's in Form Builder or Form Runner.

![screen shot 2016-04-05 at 10 28 48 am](https://cloud.githubusercontent.com/assets/105769/14291629/3910bf32-fb19-11e5-9b16-8439a74aa6bb.png)

**Comment by avernet** [comment]
Closing as duplicate of #2684.
