### ISSUE TITLE
i18n: Language code zh-Hant and zh-Hans not recognizable

### ISSUE THREAD

**Issue by codingbunny** [orbeon/orbeon-forms#2688]
I am trying to add Chinese support in form builder and form runner. However, I set "xml:lang" in resources.xml according to language.xml, which means "zh-Hant" as traditional Chinese and "zh-Hans" as simplified Chinese. But after I added, the native-name of the language code did not appear at the right corner. I tried all other languages and they all work very well. I guess it is because of the hyphen in the language code. What should I do? Any suggestions will be appreciated, Thank you!

**Comment by ebruchez** [comment]
I reproduce this. It appears to be a bug.

**Comment by codingbunny** [comment]
Thank you for your reply. Then I solved it by changing the language code in language.xml. But it may cause problem for people working on binary build.
