### ISSUE TITLE
Question: Is the language of a form summary page always the same as the language when the form was created?

### ISSUE THREAD

**Issue by codingbunny** [orbeon/orbeon-forms#2697]
Hi,
I am working on version 4.10.
When I use the i18n support of form builder, I found that the language of a form summary page will always keep the same as the language when it was created no matter what the request parameter is.  Which means:
"https://host:port/orbeon/fr/applicationName/formName/summary?fr-language=" not working. The language always keep the same.
I would like to ask whether it is a bug and is there any way I can change it. Thank you very much!

**Comment by codingbunny** [comment]
And "https://host:port/orbeon/fr/applicationName/formName/edit/formID?fr-language=" also not working.

**Comment by ebruchez** [comment]
It seems to work on demo.orbeon.com. Compare:

- http://demo.orbeon.com/orbeon/fr/orbeon/bookshelf/summary?fr-language=en
- http://demo.orbeon.com/orbeon/fr/orbeon/bookshelf/summary?fr-language=fr

**Comment by avernet** [comment]
Closing, as @ebruchez verified it works for him 1 month ago, and we didn't have any comment on this since then.
