### ISSUE TITLE
Form unpublish directly from Form Builder

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#270]
Ideas:
- "Publishing" button from details page
- always make "Publishing" button available
- opens "Publishing" dialog, which does Publish and Unpublish (modify current Publish dialog)
- upon dialog open, load published form metadata, to check whether it's already published ( we have the API since #1054)
- display whether form is published, and at what date
- display buttons
  -  "Save and Publish" if form is not saved
  - "Publish" if form is already saved
  - "Unpublish" if form is already published

Maybe:
- display whether there is data for that form (means running search)
- option to also remove all existing published data (default would be to leave data alone)

Unclear about the following:
- prevent a published form from being renamed (this would create a published form with no form with the same app/form name editable in Form Builder), as [noted by Matthias](http://orbeon-forms-ops-users.24843.n4.nabble.com/Save-as-in-4-1-td4656199.html)
- but, what if there are multiple forms with the same app/name? then renaming one wouldn't be a problem; to avoid this, and prevent other confusions, we could enforce that app/form names should be unique

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/4224335/messages/645764476)

**Comment by avernet** [comment]
- [ ] Changes to the operations drop-down
    - [ ] Change item's labels to start with an uppercase
    - [ ] Move "Unpublish" to Form Builder resources
    - [ ] Move "Operations" to Form Builder resources
- [ ] Other changes in the dialog
    - [ ] On open, focus on "Publish" button

**Comment by avernet** [comment]
[+1 from community](https://stackoverflow.com/questions/45752703/deleting-invisible-unused-input-fields-in-orbeon-form)

**Comment by ebruchez** [comment]
[Documented](https://doc.orbeon.com/form-builder/publishing.html#first-publish) by @avernet.
