### ISSUE TITLE
TIFF button: "No image writer found for image format tiff"

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2717]
Following the steps under *Versioning* in the [test plan](http://doc.orbeon.com/contributors/test-plan.html).

**Comment by ebruchez** [comment]
I don't see this with neither Java 1.7 nor 1.8.

**Comment by ebruchez** [comment]
What was the stack trace?

**Comment by avernet** [comment]
[Here is what I see in the log](https://gist.github.com/avernet/c98b6c69c690d738da2f4335e941b1b6).

**Comment by ebruchez** [comment]
@avernet is reporting that it's happening with Tomcat 6.0.29. I will try that, to see if somehow it is related.

**Comment by ebruchez** [comment]
Good news:

- It fails with a freshly-downloaded Tomcat 6.0.29,
- but works with a freshly-downloaded Tomcat 7.0.68.

I think we can simply recommend using Tomcat 7.

**Comment by ebruchez** [comment]
I [documented](http://doc.orbeon.com/installation/tomcat.html#versions) that TIFF support is not available with Tomcat 6.
