### ISSUE TITLE
Focus on editing control label after inserting a control

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2724]
It' annoying not to be able to type immediately, as that's usually the first thing you want to do after inserting a control.

We used to have this at some point.

**Comment by ebruchez** [comment]
It would be really nice to do this and it should be fairly easy.

**Comment by ebruchez** [comment]
We used to have this a "long time" ago.

**Comment by ebruchez** [comment]
Well, it actually works now, except when adding controls in a multi-row repeated grid.

**Comment by avernet** [comment]
When we add a control, the `<xxf:event-response>` contains a `<xxf:inner-html>` replacing the content of the section and `<xxf:script>` that runs `ORBEON.builder.controlAdded.fire(effectiveId)`. In the case of a control in a repeated grid, the `effectiveId` looks like `fb≡section-1-section≡grid-3-grid≡tmp-7-tmp⊙1`, whether the repeated grid has one (working case) or multiple rows (failing case) per iteration. This is the id of the `fr-grid-td` that contains the control that was just added.

The event handler for `controlAdded` is implemented in `ControlLabelHintTextEditor.scala`. It finds the container element, looks for the control inside that element with `.xforms-control, .xbl-component`. Then if inside an `.fr-repeat`, we have a special behavior to find the label in the header. But with multi-row iterations, the label isn't in the header, so we should only do this when inside a `.fr-repeat-single-row`.
