### ISSUE TITLE
Embedded eXist doesn't start on Tomcat 8

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2729]
eXist outputs `EXistServlet: exist.home=null`, and then tries to read from `/Users/ebruchez/Dropbox/Work/null/exist-conf.xml`.

I found this [eXist commit message](https://sourceforge.net/p/exist/mailman/message/32512077/) which might be the solution. Or, we should upgrade eXist to version 2.2 (see #311).

**Comment by avernet** [comment]
Strangely, I am not getting this on my own machine with Tomcat 8.0.33. But maybe this doesn't matter, since we should anyway upgrade to eXist 2.2.

**Comment by ebruchez** [comment]
Closing, reopen if we see the issue again.
