### ISSUE TITLE
Help not positioned nicely on repeated grid heading 

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2731]
See screenshot from Bookshelf form.

Also noting that the help icon is not very well aligned vertically.

![repeat](https://cloud.githubusercontent.com/assets/105769/14615777/2de856c2-055c-11e6-8710-5f8b32b143dd.png)

**Comment by avernet** [comment]
Still the case in 2016.1.

**Comment by ebruchez** [comment]
@avernet Yes because I just entered this ;)

With 4.10, positioning was different, see screenshot.

![screen shot 2016-04-18 at 12 05 00 pm](https://cloud.githubusercontent.com/assets/105769/14616151/f7613e46-055d-11e6-81af-b0572be926d5.png)
