### ISSUE TITLE
FB: 12-column grid layout

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2738]
The 12-column is standard with Bootstrap (including v4). This could give us a slightly more flexible layout, but we should see how this would translate into Form Builder.

**Comment by ebruchez** [comment]
A possibility would be to always have, for any grid, a 12-column layout.

- With "colspan", controls would use, horizontally, from 1 to 12 cells.
- You would drag the corner of controls to take more cells horizontally or vertically
    - Also: no more down/up arrow for rowspans.
- This covers all our current cases (1, 2, 3 and 4 columns).

Open questions:

- Solution for uses of [`oxf.fb.grid.max-columns `](http://doc.orbeon.com/configuration/properties/form-builder.html#maximum-number-of-columns) to set 5 columns (6 would be no problem).
- Figure out what to do when user inserts / drag a control: how much space taken by default? Would be a pain if you have to resize each control you add?

This would subsume:

- #600: FB: Support colspan
- #1479: Ability to move controls with drag and drop
- #70: Use Bootstrap's grid to implement fr:grid, instead of using tables
- Should also consider #1670: Upgrade to Bootstrap 3

**Comment by coloneltravis** [comment]
Increasing the max. grid columns to Bootstrap's max of 12 would certainly be useful to achieve more accurate placement.  Would there also be options to break down a row into groups of columns to define how the controls would collapse on different device widths? 

An elegant way for the user to specify Bootstrap's responsive columns classes, e.g. col-sm-  col-md- etc.

**Comment by ebruchez** [comment]
@coloneltravis Good suggestions and questions. We'll have to think about these.

Another overarching question is whether we want to tie ourselves to Bootstrap, and if so how much.

**Comment by ebruchez** [comment]
[+1 from customer](https://mail.google.com/mail/u/0/#inbox/1562652535c246be)

**Comment by bwallis42** [comment]
Just want to leave a "me to" note. We already override oxf.fb.grid.max-columns to 6 to accomodate our existing customer forms that have been ported from our older orbeon (3.9) installations.

**Comment by ebruchez** [comment]
@bwallis42 Good to hear!

**Comment by ebruchez** [comment]
Next step: flesh out:

- what exactly we need to do
- whether we can proceed with incremental steps

**Comment by ebruchez** [comment]
One necessary step is to update `fr:grid`:

- Support `colspan` or width, so that a grid row ("desktop" layout) can consist of cells (columns) of varying sizes (from 1 to 12).
- Figure out how this can work with `rowspan`, as that's not supported with Bootstrap (we would still generate an HTML table in this case).
- Decide how to render these columns in "mobile" (phone) mode: all the same width and stacked? Maybe start with a default and add user-configurable options in the future.
- Decide what happens with an existing grid with, say, 4 `<td>` in a row: that should translate to, say, `col-md-3` widths. Does `fr:grid` manage to infer that?

Next steps to flesh out:

- Determine what markup Form Builder must produce in various scenarios.
- Determine Form Builder UX.

**Comment by ebruchez** [comment]
The idea is to expose to the form author that there are, conceptually, 12 columns.

- For an empty grid, we would show an outline (maybe just open hover, maybe always) of the 12 columns.
- If controls/cells are widened, then the outline wouldn't show under those cells (like colspans).
- Adding/dragging a control from the toolbox should take a "natural" width for the control be default, so typically not just column. For example, an input field could take 3-4 columns. This could be configurable per component.
- Q: What happens if you insert, say, with a keyboard shortcut or click, 2+ input fields? They just go next to each other? What if no more space to the right? Make smaller, or next row?

**Comment by ebruchez** [comment]
For Form Builder, we have 2 approaches:

1. work by default on a full 12-cell grid
    - this would generate more HTML markup, not great
1. work by default on a grid with an optimized number of cells
    - so by default, 1 cell spanning 12 cols, or even 0 cell
    - client would display the outline appropriately
    - when inserting with button/click, server will create cells as needed
    - if dragging, client would know where to drop (in those "virtual" cells)

I think the second option might be better, especially as we can now write more/better client-side code.

**Comment by ebruchez** [comment]
This is a separate issue, but some automatic ordering/move functions might be good, like:

- "place all controls in a single/two/three/four column(s)"

**Comment by ebruchez** [comment]
Very rough outline:

![outline](https://cloud.githubusercontent.com/assets/105769/18021508/ac4faa82-6b9c-11e6-80f4-9707d98895c9.jpg)

**Comment by ebruchez** [comment]
Moving as we are considering a workflow feature instead.

**Comment by ebruchez** [comment]
[+1 from evaluator](https://mail.google.com/mail/u/0/#search/from%3Aelca/15add1be74ff8a4e)

**Comment by ebruchez** [comment]
We have to decide on the markup for grids. Right now, we use `<tr>`/`<td>` following the HTML conventions, with `rowspan` (but no `colspan`).

Now we need the ability to specify the width and position of cells. If a row has 1, 2, 3, 4, 6, or 12 cells without a specific width, we could imagine that they split into equal widths (12, 6, 4, 3, or 1).

Otherwise, we need to specify widths on `<td>`s.

**Comment by ebruchez** [comment]
So we have to figure out how to handle existing grids vs. new grids. Right now, we compute a static number of columns based on all `<td>`s present including `colspan`s (which users might have introduced by hand):

```xpath
max(
    for $row in $grid-rows
    return sum(
        for $td in $row/*:td
        return ($td/@colspan[. castable as xs:integer and xs:integer(.) ge 1]/xs:integer(.), 1)[1]
    )
)
```

Questions:

- Can we use/modify this, or do we need some new attribute/other way to indicate the difference between the old and new grids?
- Do we need to migrate old grids in Form Builder to help Form Builder?

**Comment by ebruchez** [comment]
I think we need a way to discriminate. Otherwise this:

```xml
<grid>
    <tr>
        <td/>
        <td/>
    </tr>
    <tr>
        <td colspan="2"/>
    </tr>
</grid>
```

can be interpreted in different ways, see attached.


![2017_08_31_11_00_05](https://user-images.githubusercontent.com/105769/29937844-ba119460-8e3b-11e7-8863-9956b7f8360c.png)

**Comment by ebruchez** [comment]
So let's assume that:

- We have a way to specify the new layout (say `<grid width="12">` or `<grid layout="12-columns">`).
- Form Builder migrates old grids to that layout, except for grids with width 5, 7, 8, 9, 10, 11, or >12.
- `grid.xbl` produces markup for both layouts. 12-col layout is TBD. Right now, we use `<xh:div>` when possible, and tables otherwise. We should proably do the same but skip "holes" in the table if possible, and use appropriate CSS classes, such as `offset-*`.

**Comment by ebruchez** [comment]
Now for the design time:

- Q: How to show an underlay grid to help with positioning, if the grid doesn't include all cells?
  - I can see how this can be all done with Scala.js when hovering. Details TBD.
  - We need to show clearly which area a control takes, as the control itself might not fill an entire cell in all cases.
- UI to resize controls (or the cells the control is in), at least to the right and down.
- Rest TBD.

**Comment by ebruchez** [comment]
Steps:

- [ ] update `grid.xbl`
  - [ ] support reading new layout
  - [ ] output with offsets/colspan/rowspan
- [ ] check if Form Builder can use [CSS grids](https://www.w3.org/TR/css-grid-1/) so we don't have 
to switch between `div`/`td` representations
  - at runtime, use tables for older browsers
- [ ] Form Builder annotate/deannotate
- [ ] TODO

**Comment by ebruchez** [comment]
Playing a little bit with CSS grids.

For row and column spans, we could output `data-fr-row-span="2"`. The benefit of this over a CSS class like `class="fr-row-span-2"` is that it is clearer and clearly splits the name and the value.

On the other hand I am not sure we can avoid duplicating CSS rules per span. Tthe CSS `attr()` function is not implemented in browsers beyond `content`, and `var()` does not work for this use case. So we probably have to write:

```css
.fr-grid-td[data-fr-row-span = '2'] {
    grid-row-end: span 2;
}

.fr-grid-td[data-fr-row-span = '3'] {
    grid-row-end: span 3;
}

.fr-grid-td[data-fr-row-span = '4'] {
    grid-row-end: span 4;
}

.fr-grid-td[data-fr-row-span = '5'] {
    grid-row-end: span 5;
}

etc.

```

For columns, we need 12 - 1 rules, but for rows, in theory it can be unbounded.

**Comment by ebruchez** [comment]
With CSS grids, it seems that we cannot generate enclosing markup for grid rows as we do now. This makes sense given that the layout in rows and columns is controlled entirely via CSS, and can vary with media queries, in particular. So in 12-column mode, `grid.xbl` will not generated `<div>` around rows.

**Comment by ebruchez** [comment]
To clarify we would like to use CSS grids *in Form Builder* So that Form Builder doesn't need to change between `<div>` and table representations when resizing controls/grid items. The alternative would be that Form Builder would have to:

  - update the *markup* on the client as the user resizes the grid item, which would be a lot of work to implement, as currently the markup is generated on the server with `grid.xbl`.
  - or "fake" the resizing, for example showing the resized area as an overlay over the underlying grid, until the user completes the resize; that would also be harder to do, and the visual feedback would not be as good as the proper resizing.

With grids, Form Builder can, as the user drags boundaries, update CSS classes on grid items, and automatically the browser will update its layout.  Only when the user completes the operation is the change committed to the server.

At runtime, we probably cannot switch yet to CSS grids as support is lacking in older browsers, including IE 9/10/11 as well as older mobile browsers. So for those, we will keep outputting tables when using `<div>`s is not possible.

If a grid only has `colspan`s and no `rowspan`s, then we could possibly still use `<div>`s at runtime. 

PDF output requires tables for now as the PDF renderer doesn't support CSS grids.

**Comment by ebruchez** [comment]
At design time, `grid.xbl`:

- generates `<div>`s without markup for grid rows (see above)
- only generates `<div>`s for cells which contain controls
- leaves "holes" where there are no controls
  - so that we don't have an inordinate number of `<div>` generated (which would be 12 per row otherwise)
  - we could fill it with `<div>`s with appropriate spans, but there is probably no point to that
- probably must generate an empty cell for the currently-selected grid cell, even if it doesn't contain a control

Form Builder:

- inserts `<div>`s upon hover to fill the grid so an outline can be shown
- for now, doesn't allow resizing a grid item over cells which already contain controls; those have to be moved first
  - later we can improve on that
  - right now we warn the user upon expanding a cell down to an populated cell
- updates CSS classes on grid items upon resizing them

**Comment by ebruchez** [comment]
Next step:

- [ ] update `grid.xbl` to support output mode using CSS grids
  - [ ] don't output `<tr>`
  - [ ] don't output "holes"
  - [ ] output `data-*` attributes

**Comment by ebruchez** [comment]
Thoughts about refining the 12-column grid *input* format.

We should think about future ability to control, from Form Builder, responsive layouts in more detail. Right now, Form Builder focuses on the wide, desktop mode, and that is fine. However, for narrower modes, like tablet modes, the form author might want to have some control too. The Form Builder UI would be updated to allow updates to the layout in all modes.

As a start, Bootstrap 4 has `xs`, `sm`, `md`, `lg`, and `xl` sizes:

```css
// Extra small devices (portrait phones, less than 576px)
// No media query since this is the default in Bootstrap

// Small devices (landscape phones, 576px and up)
@media (min-width: 576px) { ... }

// Medium devices (tablets, 768px and up)
@media (min-width: 768px) { ... }

// Large devices (desktops, 992px and up)
@media (min-width: 992px) { ... }

// Extra large devices (large desktops, 1200px and up)
@media (min-width: 1200px) { ... }
```

and:

```css
// Extra small devices (portrait phones, less than 576px)
@media (max-width: 575px) { ... }

// Small devices (landscape phones, less than 768px)
@media (max-width: 767px) { ... }

// Medium devices (tablets, less than 992px)
@media (max-width: 991px) { ... }

// Large devices (desktops, less than 1200px)
@media (max-width: 1199px) { ... }

// Extra large devices (large desktops)
// No media query since the extra-large breakpoint has no upper bound on its width
```

With this in mind, in 12-column layout (which would apply to the `md`, `lg`, and `xl` devices (our sections are about 940px), does it make sense to enclose rows in the input format? Maybe not! If we do, the meaning would be "for `md`, `lg`, and `xl` devices".

*NOTE: Bootstrap has rows, not sure why exactly at this point.*

Our grids use `$static-row-pos` (and `$static-col-pos`) to place:

- `can-*` classes on the first row in repeated grids (used by `grid.js`)
- the cells with menu to the left or right in repeated grids
- a class indicating the row/column on *controls*, like `class="fr-grid-1-1 xforms-control xforms-input"`

We can still generate this but we cannot rely on an input `<tr>` if we remove those. And the meaning of a row/column would be again "for `md`, `lg`, and `xl` devices".

**Comment by ebruchez** [comment]
RESOLUTION: We don't place `<tr>`s in the grid input format.

RESOLUTION: Each row added in Form Builder adds a new grid cell, one per row, with a "row start" of the row position. This is necessary so that if the form view is refreshed (section moves, for example), rows added by the user appear correctly. In short, this cannot be transient information.

RESOLUTION: The number of rows is not an attribute on the grid, but inferred from its contained cells and their attributes.

RESOLUTION: We have the following attributes on grid cells: `row-start`, `column-start`, `row-span`, `column-span`.

**Comment by ebruchez** [comment]
First example above is expressed with:

```xml
<grid>
    <c row-start="1" col-start="1" col-span="4"/>
    <c row-start="1" col-start="5" col-span="4"/>
    <c row-start="1" col-start="9" col-span="4"/>
    <c row-start="2" col-start="3" col-span="2"/>
    <c row-start="2" col-start="7" col-span="3"/>
    <c row-start="3" col-start="4" col-span="10"/>
</grid>
```

**Comment by ebruchez** [comment]
Grid migration: don't support nested `<xf:var>` (rarely used) or `<xf:repeat>` (which shouldn't be there really) for now.

**Comment by ebruchez** [comment]
RESOLUTIONS:

- [x] use `x`, `y`, `w`, and `h` instead
- [x] don't place `h="1"` (very common so good default) and `w="1"` (rare, but for consistency)
- [x] don't use prefixes/suffixes for now, we can always add them later as we add support to customize specific device widths

**Comment by ebruchez** [comment]
At runtime, if the source grid is in `<fr:c>` format, we must generate:

- table if there are `rowspan`s
- `<div>`s otherwise (even if there  are `colspan`s

Either way, we must compute:

- the grid height: `max` of `y + h -1`
- the grid width: start with 12, but simplify to 1, 2, 3, 4, or 6 if possible

**Comment by ebruchez** [comment]
- [x] move `Cell` to FR
- [ ] `Cell` must have `Option[Underlying]`
- [ ] FR tests for grid migration

**Comment by ebruchez** [comment]
- [ ] fix Form Builder control insert from toolbox
  - [ ] check `ToolboxOps.insertNewControl()` which calls `ensureEmptyTd()`

**Comment by ebruchez** [comment]
How "td" selection works until now:

- in `fr-form-model`, we have a `selected-cell` variable pointing to `instance('fb-variables')/selected-cell`
- we also have, with `FIXME: Probably remove once all usages are gone`:
  ```xml
  <xf:var
    name="current-td"
    value="id(instance('fb-variables')/selected-cell, instance('fb-form-instance'))"
    as="element()?"/>
  ```
- after inserting a control we call the client with:
  ```javascript
  javascript:ORBEON.Builder.controlAdded.fire('{$effective-id}')
  ```
  where `$effective-id` is:
  ```xpath
  fbf:buildFormBuilderControlEffectiveIdOrEmpty(instance('fb-form-instance'), $selected-cell)
  ```
- `selected-cell` contains the static id of the `td`
- upon form load in Form Builder, we annotate all `*:grid` and `*:td` with `tmp-*-tmp` ids if missing
- we remove them upon `deannotate.xpl`
- in `annotate.xpl`, we add code to listen to `DOMActivate` on grid cells, and set `selected-cell` in response

**Comment by ebruchez** [comment]
RESOLUTION: For now, keep the current mechanism for cell selection.

**Comment by avernet** [comment]
We've discussed an issue we might hit as we're increasingly having code that updates the client before the server tells us to. This can happen for instance with D&D, with the user moving a control from `p1` to `p2` (client sends Ajax request `c1`, server responds with `s1`), and then from `p2` to `p3` (client sends Ajax request `c2`, server responds with `s2`). Say the user does the `p2` to `p3` move before `s1` is received. Then, when `s1` arrives, the UI will momentarily revert back the sate it was in before the `p2` to `p3` move (and finally be "correct" again when `s2` is received).

We had to deal with a specific case of this more general problem with incremental fields, for which we implemented a heuristic (which can't be generalized). I'd like to suggest a more general solution, which will work in all cases, and will allow us to remove the heuristic we have for incremental fields.

The idea is simple: when the client gets a response, if it has events in its request queue (events ready to be sent), it doesn't execute the response, but instead queues it in a newly introduced response queue. It is only when it gets a response, and has nothing in the request queue that it runs everything in the response queue in addition to the current response.

This seems pretty simple, both conceptually, and to implement. I can conceive of cases where the user keeps performing actions fast enough that there are always events in the request queue, and thus the user "never" sees updates to the UI coming from the server. But I can't imagine that this situation can last for very long, either because the user won't keep up, or will just pause waiting for the UI to update.

- [ ] Discuss above algorithm.
- [ ] If we notice the issue described above in practice with D&D and the changes we'll do for the 12-column layout, and no new problem surfaced from our discussion of the algorithm, then consider implementing this algorithm.

**Comment by ebruchez** [comment]
We had a design issue we discussed today regarding "holes" in the grid at *design time*. Specifically, there are two cases where holes appear needed:

- when inserting a row in the middle of the grid, so that the empty row takes space
  - In this case, we can imagine sizing the CSS grid tracks so that the row takes space, but that might require applying `n` CSS rules to size the tracks *and* add a grid height attribute on the grid. So it is not ideal.
- when inserting a row at the end of the grid so that the grid, again at *design time*, takes space.
  - Doing *something* is required, because the user must see the grid's empty row(s) at the bottom, and some kind of persistence of that information at design time is needed because the grids can be regenerated by the server.

So we have this question of whether and when does the grid, at design time, have holes which are actually represented by cells.

A solution consists in creating cells for all the holes in the grid:

- This makes things a bit simpler: you don't have cells in some cases and not in others.
- The holes are, at least at first, only 1 row tall.
- We already have code creating holes for the runtime grid.

Steps:

- [ ] `annotate.xpl` creates holes
  - [ ] when migrating tr/td grids
  - [ ] when showing new format grids
- [ ] `deannotate.xpl` removes holes
- [ ] update operations
  - [ ] expand/shrink
  - [ ] insert new grid / repeated grid / section
  - [ ] insert row
  - [ ] TODO
- [ ] functions for the client
  - [ ] given x/y upon hover, provide operations: cells to update/insert/highlight

**Comment by avernet** [comment]
- [ ] Fix: add a section, move the pointer over the form, and you get a `NoSuchElementException`.
- [ ] Implement: grid icons to send events to the server.
- [ ] Fix: click on *Explanatory Text* in the sidebar, and get a `Cannot read property 'body' of undefined`.

**Comment by avernet** [comment]
- [ ] Get control D&D to work again to an existing empty cell.
- [ ] P2 Fix: when the explanatory text is first added, its width is incorrect.

**Comment by ebruchez** [comment]
Discussing more with @avernet, we are moving towards the following for the MVP:

- It is, in fact, possible for the user to place cells in the grid like before. We show the cell expand/shrink UI for empty cells as well.
- Deleting a control removes the control only, like before.
- When inserting a row below, we create as many cells as were ending on the current row.
- Shrinking the right side of a cell to the left creates a new 1-width cell to the right. This is not ideal but temporary.
- Expanding a cell to the right merges with the cell to the right, provided both cells do not contain a control.

**Comment by avernet** [comment]
- [ ] @ebruchez Support the new event sent to the server on D&D. Event name is `fb-dnd-control`, sent to the control being moved/copied, with the 2 properties: `fb-to-cell` (contains the id of the target cell) and `fb-do-copy` (a boolean indicating whether this is a copy).

**Comment by ebruchez** [comment]
Main steps towards MVP:

- [ ] @ebruchez `fb-grid-delete`
- [ ] @ebruchez `fb-grid-edit-details`
- [ ] design time repeats
  - [ ] @avernet label/hint editor
  - [ ] @avernet show grid row icons
  - [ ] @ebruchez show header row
  - [ ] @ebruchez  show dropdowns 
- [ ] runtime repeats
  - [ ] @ebruchez header border is incorrect (colspans?)

**Comment by avernet** [comment]
- [ ] @ebruchez For repeated grids, in the markup sent to the browser, try to avoid the `<span class="xforms-group">` between the element with `xbl-fr-grid` and the one with `fr-grid`, as it might not be needed.

**Comment by ebruchez** [comment]
Remaining issues:

- [ ] @avernet positioning of cell icons is off just after loading
  - Not sure if it's because of some changes I did.
- [ ] @avernet Hover over repeated grid heading should show grid icons. Now you have to hover specifically over the rows.

**Comment by avernet** [comment]
In some cases, we can end up with the `.fb-row-editor` positioned too low, while the icons inside the editor are positioned properly. We don't care about the position of the container block, and don't position it, so setting an initial `top: 0; left: 0` solves the problem.

![screen shot 2017-10-12 at 4 25 25 pm](https://user-images.githubusercontent.com/106961/31523725-1a62373a-af6a-11e7-82b3-e63d9fde868f.png)

**Comment by avernet** [comment]
- [ ] @avernet HTML labels and hints aren't working in repeated grids:

![screenflow](https://user-images.githubusercontent.com/106961/32083235-18f5ba18-ba76-11e7-8e2b-4bde4685bfdc.gif)

**Comment by avernet** [comment]
To know if the label (or hint) is in HTML, we look for the class `fb-label-is-html` (or `fb-hint-is-html`). The label in the table header current has the class `xforms-mediatype-text-html`. This isn't consistent with the "regular" label inside a control, which doesn't have a `xforms-mediatype-text-html` class. I think it would make sense for all labels to implement the "new technique", and have a `xforms-mediatype-text-html` when appropriate. Then, in `grid.xbl`, we could remove the code that produces the `fb-label-is-html` and `fb-hint-is-html`.

**Comment by avernet** [comment]
- [ ] @avernet Fix control in grid moving when selecting cell on another line.
- [ ] @avernet Click on section title, then other section title: editor for the first section closes, but the editor for the second doesn't open.
- [ ] @avernet Don't show icons when dialog is open.

**Comment by ebruchez** [comment]
Issue of `xf:var` in grids:

- We use this in the permissions dialog.
- Might some other Form Builder dialogs use this?
- Users' forms might use this (manually-edited form definitions).

Options:

- remove support
  - change permissions dialog to do something else
  - have `fr:grid` throw errors when detecting `xf:var`
- keep support
  - Q: What about new grid format with `<fr:c>`? What would the scope be?
  - Q: Only support runtime but not design-time?
  - Q: Do we need to support `xf:group`?
    - Would be *around* `<xh:tr>` and `<xh:td>`
  - Q: Do we need to support `xf:group`?
  - clarify where `xf:var`  is allowed
    - [old comment](https://github.com/orbeon/orbeon-forms/blob/2017.1-ce/form-runner/jvm/src/main/resources/xbl/orbeon/grid/grid.xbl#L682) said "Allow xf:var within xh:tr/xh:td but must add outer scope "
    - `permissions.xbl` uses within `<xh:tr>`, before all `<xh:td>`s

**Comment by ebruchez** [comment]
A few scenarios:

```xml
<!-- Within `<xh:tr>` -->
<fr:grid>
    <xh:tr>
        <xf:var name="foo" value="???"/>
        <xh:td>???</xh:td>
    </xh:tr>
</fr:grid>

<!-- Within `<xh:grid>` -->
<fr:grid>
    <xf:var name="foo" value="???"/>
    <xh:tr>
        <xh:td>???</xh:td>
    </xh:tr>
</fr:grid>

<!-- Within `<xh:tr>` when multiple `<xh:tr>` are present -->
<fr:grid>
    <xh:tr>
        <xf:var name="foo" value="???"/>
        <xh:td>???</xh:td>
    </xh:tr>
    <xh:tr>
        <xf:var name="bar" value="???"/>
        <xh:td>???</xh:td>
    </xh:tr>
</fr:grid>

<!-- Within `<xh:td>` -->
<fr:grid>
    <xh:tr>
        <xh:td>
            <xf:var name="foo" value="???"/>
            ???
        </xh:td>
    </xh:tr>
</fr:grid>

<!-- Using `<fr:c>` -->
<fr:grid>
    <xf:var name="foo" value="???"/>
    <fr:c>???</fr:c>
    <xf:var name="bar" value="???"/>
    <fr:c>???</fr:c>
</fr:grid>
```

**Comment by ebruchez** [comment]
For groups:

```xml
<!-- Group around `<xh:tr>`s -->
<fr:grid>
    <xf:group>
        <xh:tr>
            <xh:td>???</xh:td>
        </xh:tr>
        <xh:tr>
            <xh:td>???</xh:td>
        </xh:tr>
    </xf:group>
</fr:grid>

<!-- Group around `<xh:td>`s -->
<fr:grid>
    <xh:tr>
        <xf:group>
            <xh:td>???</xh:td>
            <xh:td>???</xh:td>
        </xf:group>
    </xh:tr>
</fr:grid>
```

**Comment by ebruchez** [comment]
- Use case for `<xf:var>`
  - scope variables per iteration (like `permissions.xbl` )
- Use case for `<xf:group>`
 - control visibility or rows or individual cells

**Comment by ebruchez** [comment]
One quick solution for variables would be to take all `fr:grid/xf:var | xf:grid/xh:tr/xf:var` and place them in order before all the cells, within `xf:repeat` if the grid is repeated.

This might not work if the input grid is in `tr/td` format and the same variable name is used multiple times. But if all names are different, scoping would work fine.

Failing example:

```xml
<fr:grid>
    <xh:tr>
        <xf:var name="foo" value="???"/>
        <xh:td>use $foo</xh:td>
    </xh:tr>
    <xh:tr>
        <xf:var name="foo" value="???"/>
        <xh:td>use $foo</xh:td>
    </xh:tr>
</fr:grid>
```

A further step would be to keep the relative order of variables and cells.

**Comment by ebruchez** [comment]
For now, supporting `<xf:var>` using the "quick" solution (see above comment).

**Comment by ebruchez** [comment]
Looking at "Also generate `xforms-mediatype-text-html` on LHHA inside the control, when appropriate, as described above.":

- This is meant to match the presence of a `mediatype="text/html"` on the label or hint.
- Looking a the code, we have a funny hierarchy of code to handle HTML:
  - `LHHAAnalysis` has `defaultToHTML` which matches `mediatype="text/html"`
  - passed in 2 places to `XFormsUtils.getElementValue`
  - `XFormsUtils.getElementValue` also receives a `supportsHTML`, which is always true for control LHHA except for the trigger's hint 
  - then we stream HTML out iif `supportsHTML == true` and the LHHA or nested `<xf:output>` elements have an effective `mediatype="text/html"` or there are nested HTML elements
- In theory, all of this can be determined statically, but we don't.
- In the case of Form Builder, we would like the class to appear if there is the `mediatype="text/html"` on the LHHA

**Comment by avernet** [comment]
- [ ] When a button has no label, as is the case just after being added, show a placeholder indicating that the label can be edited in the Control Settings, or a "click here to edit" that opens the Control Settings and set the focus in the text field to edit the label.

**Comment by avernet** [comment]
- [ ] @avernet Create a repeated grid, add a row, and notice how when hovering on a row a "remove" icon is incorrectly shown to left.

**Comment by avernet** [comment]
@ebruchez Would you agree with the "conclusion" in the last bullet point of my previous message?

**Comment by avernet** [comment]
- [ ] @avernet Create a repeated grid, add a row with the "+" icon, delete the first row clicking using the dropdown menu, and this sometimes lead to a JavaScript error.

**Comment by ebruchez** [comment]
@avernet `fb-can-delete-row` now there again.

**Comment by ebruchez** [comment]
[Documented](https://doc.orbeon.com/form-builder/form-area.html#the-12-column-layout)
