### ISSUE TITLE
Refresh button is no longer narrow

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2739]
![refresh button meant to be narrower](https://cloud.githubusercontent.com/assets/105769/14690680/12941530-0702-11e6-80aa-c4ca1b9212da.png)

**Comment by bytesnz** [comment]
Hey @ebruchez, was just wondering if you were going to release a new version of 2016.1 with this fixed in it prior to releasing 2016.2? Cheers.

**Comment by ebruchez** [comment]
@bytesnz We haven't yet decided on the schedule of a 2016.1.1 if any. I think it's unlikely that it will be out before 2016.2 though.
