### ISSUE TITLE
Document versioning

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2755]
Right now we have a general description in a [blog post](http://blog.orbeon.com/2014/02/form-versioning.html), [another blog post](http://blog.orbeon.com/2015/01/choosing-best-versioning-option-when.html) on publish and the choice form authors have to either overwrite or create a new version, buht no general documentation on that feature.

**Comment by ebruchez** [comment]
We do have [documentation](https://doc.orbeon.com/form-runner/features/versioning) now, closing.
