### ISSUE TITLE
Separate deployment: content "cut" with .html

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2775]
To reproduce, deploy [myapp.zip](https://github.com/orbeon/orbeon-forms/files/256147/myapp.zip) along Orbeon Forms. Notice how, with:

- `http://localhost:8080/myapp/xforms/guess.jsp` the "guess the number" example works (first screenshot below).
- `http://localhost:8080/myapp/xforms/guess.html` it doesn't work and only part of the markup is sent to the browser (second screenshot below).

![works](https://cloud.githubusercontent.com/assets/106961/15131969/6da0e2bc-1609-11e6-9e44-9db5c5c97bfa.png)

![cut](https://cloud.githubusercontent.com/assets/106961/15131975/8340b23c-1609-11e6-8e4e-e1113d94cb04.png)

**Comment by avernet** [comment]
[+1 from community](http://discuss.orbeon.com/Orbeon-Initial-Javascript-not-loaded-td4661313.html)

**Comment by ebruchez** [comment]
Curiously, both works for me with Apache Tomcat/7.0.68. @avernet used Tomcat/8.0.33.

**Comment by ebruchez** [comment]
With a stock 2016.1.201604200638-PE release, it works for me with Tomcat 7.0.68, but not Tomcat 8.0.21.

**Comment by ebruchez** [comment]
Findings so far:

- filter is called and renderer outputs the entire HTML
- in `OrbeonXFormsFilter`, `getOrbeonDispatcher().forward()` causes the response to receive all the content
- in fact so far I don't see a difference between the JSP and the HTML case from the filter's point of view
- however, for some reason, in the HTML case, the response doesn't make it to the client entirely

**Comment by ebruchez** [comment]
Making progress by comparing the `CoyoteOutputStream` in both cases:

- the stream gets a `contentLength` of 3166 in the case which doesn't work (that's the size of the input HTML file!)
- this is set at some point during processing of `doFilter()`
- however, our `FilterResponseWrapper` filters calls to `setContentLength()` as well as `setHeader()` and `setIntHeader()`, so it's unclear which piece of code does this!
- calling by hand `setContentLength(-1)` after `doFilter()` makes it work, but it feels a bit hacky

**Comment by ebruchez** [comment]
Attaching the screenshots for reference.

![bad](https://cloud.githubusercontent.com/assets/105769/15583020/a4f97ea0-2328-11e6-8e0a-32b5d9a6632d.png)
![good](https://cloud.githubusercontent.com/assets/105769/15583021/a4fa6f5e-2328-11e6-8ffe-d5d1ef1a6346.png)

**Comment by avernet** [comment]
The `setContentLength(-1)` in the XForms filter is causing an `IndexOutOfBoundsException` with Open Liberty (see #4880), and as of Tomcat 9.0.37 it isn't needed anymore with Tomcat, so I removed it.
