### ISSUE TITLE
Some controls with errors are highlighted with a red border, but not others

### ISSUE THREAD

**Issue by ajw625** [orbeon/orbeon-forms#2776]
For example, Text Fields and Dates have a red border, but Text Areas and Dropdown Menus do not. See screenshot from demo.orbeon.com.

![image](https://cloud.githubusercontent.com/assets/9143532/15156781/7ca098a4-169d-11e6-81b0-5e49d0e3fd25.png)

**Comment by avernet** [comment]
We resolved to remove the red highlight on input fields, as:

- To be consistent, we would need to have a highlight on all form fields, and it isn't clear this can be done nicely for all the controls and on all browsers (think: radio buttons). Even when possible, this makes the CSS more complex.
- The red border doesn't play well with the blue highlight for the current field added by Bootstrap, which can be seen on the above screenshot.
- The red message under the field is a clear enough indication that there is a problem with that field.
