### ISSUE TITLE
Don't use tables for the layout of grids

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2779]
We agree that using literal HTML `<table>` and related elements is not ideal for grids.

Some users have guidelines saying that tables *must not* be used for layout, and that they hurt accessibility. This latter point is debatable ([`role="presentation"`](https://www.w3.org/TR/wai-aria/roles#presentation) can be used), but what is not debatable as of 2016 is that it is possible to achieve the same result without using `<table>` elements. So we should do it.

Impact:

- `fr:grid` must not generate/forward `<table>` and related
- instead, use `<div>` elements with classes
    -  Bootstrap does it this way (even [Bootstrap 4](http://v4-alpha.getbootstrap.com/layout/grid/))
- the CSS for `fr:grid`'s new `<div>`s can use `display: table` etc. as a first step
- we must check that Form Builder doesn't rely on `<table>` and related, and if so make the necessary changes

Related issues:

- Use Bootstrap's grid to implement fr:grid, instead of using tables #70
- FB: Consider if it would make sense to have a 12-column grid layout #2738

**Comment by ebruchez** [comment]
One issue is that of `rowspan`. It's not trivial to express this in CSS. I think that with flexbox we can do it, but support might not be enough everywhere yet.

Options:

- Try to achieve it with CSS anyway.
- If not possible, just generate `<table role="presentation">` for those grids which have `rowspan`.

NOTE: `colspan` is easy to do.

**Comment by avernet** [comment]
It seems we [can't use `colspan` and `rowspan` on arbitrary elements with `display: table-cell`](http://stackoverflow.com/a/15829425/5295). So at this point, the idea would be for the `fr:grid` to produce `span`/`div` when there are no `colspan` or `rowspan`, and to produce a `<table role="presentation">` when there are `colspan` or `rowspan`.

**Comment by ebruchez** [comment]
I had a first look at `grid.xbl` and I don't think this will be too hard to complete. Making this a 2016.2 feature. Local branch `2016-05-13-wip-2779-no-tables`.

**Comment by ebruchez** [comment]
See also the [CSS 2.1 spec](https://www.w3.org/TR/CSS21/tables.html) and in-progress [CSS Table Module Level 3](https://drafts.csswg.org/css-tables-3/).

**Comment by ebruchez** [comment]
I was thinking that one difficulty was that, for repeated grids, we depend on some Bootstrap CSS. So I started looking at that to adapt it to grids without `<table>` elements. On further thought, repeated grids are candidates to be expressed with `<table>`. At least the ones with headings. So for now, we will keep repeated grids as `<table>`.

A case might be made that repeated grids which repeat more than one group of rows should not be `<table>`s. But we can look at that separately. So for now the resolution is to generate `<div>`s only for non-repeated grids which don't have `rowspan`.

**Comment by ebruchez** [comment]
Remaining issues:

- [ ] FB: column arrows don't show
- [ ] FB: row height is too low when cell is empty
- [ ] maybe: should we make `<div class="fr-grid-content">`

**Comment by ebruchez** [comment]
[Documented](http://doc.orbeon.com/form-runner/styling/grids.html)

**Comment by ebruchez** [comment]
Also added `role="presentation"` on `<table>` with `rowspan`.
