### ISSUE TITLE
Repeated grid missing column heading if the field is hidden in the first row

### ISSUE THREAD

**Issue by ajw625** [orbeon/orbeon-forms#2783]
I have a form with a repeating grid of "Activities". The last field/column in the grid, Length (km), has a visibility expression. If visibility does not evaluate to 'true' for the first row, then the column heading will not be displayed. See screenshot below and example form on demo.orbeon.com.

http://demo.orbeon.com/orbeon/fr/orbeon/builder/edit/dba2d972547f193a3e5b2ebcc53f725adbc3311c

![add activity error missing field label](https://cloud.githubusercontent.com/assets/9143532/15304860/a2f35ccc-1b74-11e6-9e47-cf76a9768132.GIF)

**Comment by avernet** [comment]
Indeed, I could also reproduced this with our latest code. Tentatively planning for 2016.2.

**Comment by avernet** [comment]
Simple test case: [scratch.txt](https://github.com/orbeon/orbeon-forms/files/323952/scratch.txt). Notice how the label is missing in the header of the second column because the input in the first row is hidden.

![screen shot 2016-06-20 at 10 27 00 am](https://cloud.githubusercontent.com/assets/106961/16203944/8cd3fcbc-36d1-11e6-9151-b90b3b92b39f.png)

**Comment by avernet** [comment]
In `grid.xbl`, `$control-binding` points to the first element for the control, e.g. `<my-input>`; the declaration "at runtime looks like":

```xml
<xf:var name="control-binding" context="(bind('my-grid-bind'))/*">
    <xxf:value value="." bind="my-input-bind"/>
</xf:var>
```

**Comment by avernet** [comment]
This is a rat's nest.

I was hoping that we could get this to work by, in `grid.xbl`, getting [`control-binding`](https://github.com/orbeon/orbeon-forms/blob/tag-release-2016.1-ce/src/resources-packaged/xbl/orbeon/grid/grid.xbl#L327) to point to all the nodes the control binds to, so we could then use a relevant one in that sequence if the first one is non-relevant. But the way the `bind` work with `xf:var` got in the way (see #2821).

For the label in the table header, we use an `<xf:output>` inside which we copy the `<xf:label>` (and other LHHA) of the control. But we also bind the `<xf:output>` to the node the first control is bound to, and we do this so we can show a star next to the label if the control is required. This is hacky, as it doesn't work if the the repeat is empty, and has side-effects, like the one covered by this issue: hiding the label if the node is non-relevant.

We should find a better way to show the star when the control is required, or not support showing the star on those controls, as it årguably can't be done reliably unless we put some restrictions on the expressions users can write (i.e. users can write an expression where controls on odd rows are required).

For now, I'm removing this from the 2016.2 milestone.

**Comment by ebruchez** [comment]
By the way, we have an RFE #241 to "Support lhha pointing to control inside a repeat".

In the case of this issue #2783, you can solve the issue by binding the `<xf:output>` to an expression which excludes non-relevant nodes. Right now:

    ref="$control-binding, ''"

Maybe change this to:

    ref="$control-binding[xxf:relevant()], ''"
