### ISSUE TITLE
Provide access to Liferay organizations

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2791]
A Liferay user belongs to one or more organizations, and these organizations are in a hierarchy. We would like to provide the ability to:

- pass the user's direct organizations ids and names via headers
- possibly pass the hierarchy of organizations to which the user belongs as well (that is, its ancestor organizations)

Liferay provides an API for this: see [Interface Organization](http://docs.liferay.com/portal/6.2/javadocs/com/liferay/portal/model/Organization.html) and [Interface User](http://docs.liferay.com/portal/6.2/javadocs/com/liferay/portal/model/User.html). We already make use of `User` to provide user details via headers.

**Comment by avernet** [comment]
@ebruchez This looks like a subset of #2792. Do we need a separate issue with this?

**Comment by ebruchez** [comment]
In #2792 we talk about `liferay-organization-owner`. This would be about passing just a user's organization, for example to be used as a group. Not sure that is really a subset.

**Comment by avernet** [comment]
@ebruchez Got it.

**Comment by ebruchez** [comment]
As part of #2792 we implemented passing the full list of user's organizations and their ancestors. Although access control with the "Liferay Organization Owner" and "Liferay Organization Administrator" parametrized roles does not support all organizations, those are available to forms via XPath functions (#2969).
