### ISSUE TITLE
Ability to specify is-manager-of permissions

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2792]
The typical use case is the **expense report approval scenario**, where the manager of the user submitting the ER can view the ER and approve it. So the permission looks like: "can view or approve if manager of user submitting the ER".

The changes described below will allow Orbeon Forms, running with Liferay, to handle the typical use case of an expense report approval scenario, where the manager of the user submitting the ER can view the ER and approve it. This calls for supporting a permission saying "can view or approve if the current user is the manager of the user who submitted the ER".

![screen shot 2016-08-25 at 4 31 34 pm](https://cloud.githubusercontent.com/assets/106961/17989336/6bbee76e-6ae1-11e6-9dcb-2ed064b7a516.png)

Phase 1
- [x] Write MySQL DDL to store organization along data.
- [x] Write Scala code to store organization in table.
- [x] Update REST API to store user's organization.
  - [x] Updates in `CreateUpdateDelete.scala`
  - [x] Tests in `RestApiTest.scala` to pass
- [x] Define data structure (case classes) for parameterized roles.
- [x] Update authorization code (`FormRunnerPermissions`) to take user's organization and role into account.
- [x] Search to take organization into account
  - [x] Get page to load, calling API with correct arguments
  - [x] Update search to SQL query to take organization and parameterized role into account.
- [x] Support for eXist
  - [x] Write Scala code to store organization in eXist.
  - [x] Update search's XQuery to take organization and parameterized role into account.
- [x] Update Form Builder permissions dialog to have dropdown/input for "organization owner" role
  - [x] Add "organization owner" to permissions dialog
  - [x] Only show "organization owner" when property is set
- [x] Update Orbeon Forms Liferay code to pass user's organization and parameterized roles to in headers.

Phase 2
- [x] Port code done for MySQL on other databases
  - [x] Port to PostgreSQL and run tests directly on Travis
  - [x] Support Oracle
  - [x] Support SQL Server
  - [x] Support DB2
- [x] Write documentation
  - [x] Liferay, mentioning this is only supported with the proxy portlet
  - [x] Introduction to the feature
  - [x] Organization names must be unique
  - [x] Organization structure stored as users save data for performance
  - [x] If the structure changes, the database needs to be updated
  - [x] Role can be for another organization the user is in
  - [x] use of `Orbeon-Liferay-User-Credentials` in general (not only orgs) (@ebruchez)
    - [x] username depends on Liferay setting
- [x] Write blog post

**Comment by ebruchez** [comment]
Noting that, at least in some scenarios, storing the owner-group information alongside the data still makes sense.

For example, in the expense report case: use Mary submitted the ER when part of the Engineering group. Even if Mary changes to another group after submitting, it's still the current manager of the Engineering  group who can approve the ER.

**Comment by ebruchez** [comment]
Possibility for a more general mechanism:

- would work at the level of groups (as in owner group/user group)
- the client (e.g. Liferay proxy portlet) would pass mappings ("group role name", groups)
    - "group role name"
        - custom name
        - in Liferay case, we could have "Organization/Group Admin"
        - in other custom cases, we could have "Expense Approver", "Group Manager", etc.
    - "groups"
        - groups names/ids for which the group role name applies
- this is passed by headers
    - format?
    - JSON?
        - `[ { "role-name": "Expense Approver", "groups": [ "group1", "group2" ] }, ... ]`
        - 4K is a reasonable limit, see [SO question](http://stackoverflow.com/questions/686217/maximum-on-http-header-values)
- Form Runner has a new internal header `Orbeon-Group-Roles` with this information
- in Form Builder, you set e.g. "Expense Approver can view data"
- this is passed to the persistence layer
    - when needed, match owner group to list of groups passed

Also, could this be extended to users in addition to groups?

**Comment by ebruchez** [comment]
Tasks:

- [ ] Liferay proxy portlet: generate new headers (maybe configurable)
- [ ] Form Runner: mapping to standard internal header name
- [ ] persistence proxy: prepare information for persistence layer
- [ ] relational persistence: support checking group/user is in provided list(s)
- [ ] Form Builder UI: possibly no change: role check done on passed roles if available, otherwise check group roles
- [ ] automated tests

**Comment by avernet** [comment]
I expanded on the [above notes originally taken by @ebruchez](https://github.com/orbeon/orbeon-forms/issues/2792#issuecomment-220682684) to better reflect how our thinking has evolved after discussing this with the client.

**Comment by avernet** [comment]
Done more editing to the [above "spec"](https://github.com/orbeon/orbeon-forms/issues/2792#issuecomment-220682684), to consistently use the `manager(group = 'west-coast')` syntax, and explain how this could be extended from group to users to handle other use cases we had in mind.

**Comment by avernet** [comment]
The [above description](https://github.com/orbeon/orbeon-forms/issues/2792#issuecomment-220682684) is summarized and better described below.

![screen shot 2016-08-25 at 3 51 28 pm](https://cloud.githubusercontent.com/assets/106961/17988567/f52b56c8-6adb-11e6-8d0e-77a7a2ea5725.png)

**Comment by avernet** [comment]
When list of roles need to be passed around, what serialization do we use? Right now we consider each role to be a string, which is directly the role token. We could keep it this way, and:

1. Use parameterized roles serialized as `manager(group="southern_ca")`, as in the above examples. Non-parameterized roles would stay as they are now, e.g. `clerk`.
2. Use JSON as a format for each role, e.g. `{"name": "clerk"}` and `{"name": "manager", parameters: [{name: "group", "value": "southern_ca"}]}`.

Option 2 has some appeal, as we can avoid spelling out the syntax we're using, however its readability is so degraded that I favor option 1, and should be able to have in a single place Scala code that parses a role into an ADT, and serializes that ADT. Option 1 is also backward compatible, and inline with the syntax we are using when calling actions in processes.

**Comment by avernet** [comment]
**How do we store groups in the database?**

Right now, in the database, we can only have zero or one group per data. For this we use a nullable column. This RFE calls for data to have zero to *n* groups, which means we need to store that information is a separate table. Should we:

1. Have a child table for every table with a `groupname`, i.e. `orbeon_form_data`, `orbeon_form_data_attach`, and `orbeon_i_current`?
2. Have just one `orbeon_groupset` where we store unique combinations of groups, which we can refer from the other 3 tables?

The downside of option 2 is that it might require garbage collection to remove groupset that are not used anymore, and that inserting in `orbeon_form_data` requires a first query to `orbeon_groupset`. The upside is that it requires less tables to be added, less inserts, that populating `orbeon_i_current` is simpler as we can use the same `groupset_id` from `orbeon_form_data`, and I am thus favoring option 2.

**Comment by ebruchez** [comment]
Next step for me:

- [ ] figure out how to obtain Liferay organization information, namely whether the current user is the owner or administrator of organizations

Some [Liferay documentation about Organization Owner/Organization Administrator](https://dev.liferay.com/discover/portal/-/knowledge_base/7-0/roles-and-permissions).

**Comment by avernet** [comment]
Before going ahead with this, we'd like to validate the design discussed above. We're having a concept of group, and having been thinking of mapping Liferay organizations to Orbeon groups. This has at least one downside:

If a user is member of the organizational structure USA > California > San Francisco, per the design described above, for Orbeon Forms that user will end up as a member of the groups USA, California, and San Francisco. If a form author setup permissions on a form so users of the same group can perform certain operations, then all users will be able to perform those operations, as all users are members of the USA group, which means that the "same group" permission feature can't be used at the same time we use an organizational structure.

This case may point to a need to keep the concepts of *organizations* and *groups* distinct in Orbeon Forms as well. This would also make our model more inline with Liferay's.

At this point, we have the following open questions:

- Does Liferay have a concept of permissions given to users of the same group? If so, which group, since in Liferay users can be part of multiple groups?
- What would having groups and organizations look like in Orbeon Forms?

**Comment by avernet** [comment]
Answering the above questions:

- It doesn't look like Liferay has a way to assign permissions to "users who are in the same group as the owner". In Liferay, this would be done with an "implied role", e.g. they have an implied role called "owner". So we can't look at Liferay to figure what "same group as owner" would look like when the user can be part of multiple groups. However, UNIX, again, could be an inspiration here: in UNIX a user can be part of multiple group, but has a primary group, and form data that the user creates, like files on UNIX, get associated with the user's primary group. So I'd suggest we do the same in Orbeon Forms.
- We've already covered groups in the previous point. Organizations would be handled like we were planning to handle groups in the above description.

**Comment by ebruchez** [comment]
@avernet you will close this once you have written your part of the documentation.

**Comment by ebruchez** [comment]
@avernet "Port code done for MySQL on other databases" Is this done?

**Comment by avernet** [comment]
@ebruchez Not all of them. Specifically, we haven't tested this on SQL Server and DB2 yet.

**Comment by avernet** [comment]
We have 3 sets of automated database tests that, respectively, we can run from SBT with:

```
db:testOnly *DDLTest
db:testOnly *OrganizationTest
db:testOnly *RestApiTest
```

Now all tests are passing on Oracle. Next SQL Server.

**Comment by avernet** [comment]
On SQL Server, now `*DDLTest` is passing, as well as `*OrganizationTest`, however `*RestApiTest` is "hanging", in `RestApiTest.permissionsTest`. The code is blocked in `Common.scala`, in `formVersion()` when trying to determine the version used by a form. This is called in `Read.scala` in `get()`, called when reindexing, with the reindexing triggered by a form definition being stored.

In `CreateUpdateDelete.scala` we call the reindexing code passing the connection used to store the new form definition, but `Reindex.scala` uses `FormRunner.readPublishedForm()` read the form, which establishes a new database connection, and could explain the deadlock we're seeing.

Doing a `COMMIT` after writing the form definition and before reindexing solves the problem.

**Comment by avernet** [comment]
Next, and last, DB2.

**Comment by avernet** [comment]
DB2, at least on Linux, [seems](http://stackoverflow.com/questions/12276550/run-create-drop-db2-database-commands-for-a-specific-user-other-than-machine-lo#comment16472228_12276550) to not support creating and dropping databases from SQL (e.g. with `CREATE DATABASE` and `DROP DATABASE`). Since we're running this test by hand, I contemplated the possibility of running everything in the `sample` database, but this won't work as we don't have code to cleanly remove the tables, indexes, etc that we create in the database. For now, I've [asked whether there really is no way to create/drop databases on DB2 JDBC](http://stackoverflow.com/questions/41149829/how-to-create-drop-a-database-on-db2-through-jdbc). If it isn't, we'll have to evaluate what options we have to run those tests on DB2.

**Comment by avernet** [comment]
I am evaluating running DB2 on Docker, using an [Express-C image provided by IBM](https://hub.docker.com/r/ibmcom/db2express-c/), in a way similar to what we are doing for Oracle. A difference here is that I would need to have a special version of `withNewDatabase()` that either:

1. Assumes there is a container running, and does an `exec` to create and drop a database. For this we would need to add an environment variable with the container id. The downside is that creating the database is slow (about a minute).
2. Create an empty `orbeon` database, commit the database, and at the beginning of every test start the container, and stop it at the end. This should be cleaner and much faster.

**Comment by avernet** [comment]
Test are now running locally on DB2, and it wouldn't too hard to do the same on Travis.

**Comment by ebruchez** [comment]
Now documented by @avernet:

- [Organizations](https://doc.orbeon.com/form-runner/access-control/organization.html)
- [Updated headers method](https://doc.orbeon.com/form-runner/access-control/users.html#header-driven-method)
