### ISSUE TITLE
No (Orbeon) focus event in ORBEON.xforms.Events.

### ISSUE THREAD

**Issue by bytesnz** [orbeon/orbeon-forms#2801]
As an Orbeon forms developer, I want to be able to subscribe the the focus event, so that I can run custom javascript on control focus.

There is currently only blurEvent and clickEvent
```javascript
["_findParentXFormsControl", "_findAncestorFocusableControl", "focus", "blurEvent",
"blur", "change", "_isChangingKey", "keydownEvent", "keydown", "keypressEvent",
"keypress", "keyup", "_showToolTip", "mouseover", "mouseout", "clickEvent", "click",
"_resize", "scrollOrResize", "sliderValueChange", "dialogClose", "dialogShow",
"errorShowHideDetails", "errorHideAllDetails", "errorPanelClosed", "errorCloseClicked",
"errorReloadClicked", "dialogMinimalBodyClick", "sendHeartBeatIfNeeded",
"orbeonLoadedEvent", "ajaxResponseProcessedEvent", "errorEvent",
"yuiCalendarCreated"]
```

A focusEvent would be handy so you can handle navigation of the form using the keyboard.

The example use case is using javascript to add/remove a class to the control when it gains/loses focus (a focus class added to controls when in focus could also be a feature request in itself - useful for highlighting what control is in focus [until CSS4 comes out]).

**Comment by ebruchez** [comment]
If this is done entirely on the JavaScript side, you can use jQuery to register your own handlers for focus events. I don't think you need specific Orbeon Forms support for that.

**Comment by bytesnz** [comment]
Was just thinking about the focus event for each element, which you wouldn't be able to use to attach to all fields on form ready as non-visible aren't in the dom, but yes, I can now see a way to do it.

**Comment by ebruchez** [comment]
jQuery's delegated event handlers don't  require the elements to be present at the time the handlers are registered. And it seems they works with `focus`/`blur`, see this [StackOverflow question](http://stackoverflow.com/questions/14496083/how-to-delegate-focus-event).

**Comment by bytesnz** [comment]
Ah. Indeed, yeah, I was going for pure javascript, where focus/blur don't bubble by default (as focusin is not supported by firefox and DOMFocusIn is deprecated in firefox). Can use the useCapture option on addEventListener though. Cheers Eric.

**Comment by ebruchez** [comment]
No problem!
