### ISSUE TITLE
Infrastructure to call a service like search from a test

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2807]
We want to be able to call a service like the persistence search API from a test. This is a service that gets XML from an HTTP POST, and returns XML. Also, the caller should be able to provide credentials (username, group, roles), which will be used by service, of course without being tested. In the short term, we're interested in this mainly to enable use to test the implementation for #649.

(In the future this could be extended to support calling service that support other methods, like GET and PUT, and other inputs/outputs, but this isn't a part of this specific RFE.)

**Comment by ebruchez** [comment]
Done with the new `TestHttpClient`, "which simulates a call to Orbeon Forms without using a servlet. This acts as if the caller is a client making a call to an Orbeon Forms server."

I also added support for directly passing `username`, `group` and `roles`, as in a servlet environment we have a servlet filter which handles those, but that filter is not hooked up here. So we can pass this user information directly.

**Comment by ebruchez** [comment]
Also noting that `FormRunnerSupport` uses `TestHttpClient` now.
