### ISSUE TITLE
Infrastructure for obtaining database connection from service called from test

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2808]
When our service code is called by a test, through the infrastructure provided by #2807, it must be able to establish a connection to the database. If it helps, we can limit this requirement to service code using `RelationalUtils.withConnection()`.

The test code must be able to specify programmatically connection information (driverClassName, username, password, url), as this information will be different depending on the test, for instance each run of o9ur tests typically use a different database.

**Comment by ebruchez** [comment]
[This](https://commons.apache.org/proper/commons-dbcp/guide/jndi-howto.html) might be relevant.

**Comment by ebruchez** [comment]
Example of usage:

```scala
class DatasourceTest extends DocumentTestBase {

  import DataSourceSupport._

  @Test def testConnection(): Unit = {
    withDatasources(List(DatasourceDescriptor(MySQL, Some("orbeon")))) {
      RelationalUtils.withConnection("mysql") { connection ⇒
        println(s"got connection $connection")
      }
    }
  }
}
```
