### ISSUE TITLE
i have any question for orbeon forms/runner

### ISSUE THREAD

**Issue by shixiaochuan** [orbeon/orbeon-forms#2814]
Hello，i'm a raw to software development,and my English is not good，so it is hard for me to read English material. Now, i have some problems.Please help me！Thank you！(my applaction use tom7,and orbeon forms too)
    1:How can i call forms data? And how could my applaction receives data？
      [ Access form data](http://doc.orbeon.com/form-runner/overview/accessing-data.html) in the doc,i see properties-local.xml can be configured  in Send data on submit.But my properties-local.xml is empty.
so,my problems is how can I send data directly to my app.
    2:How do I accept data from my applaction? 
    3:How to set authorization?

 This.is my problems, Thank you very much for your answer.

**Comment by ebruchez** [comment]
Can you please post your question to the [forum](http://discuss.orbeon.com/)? Thanks.
