### ISSUE TITLE
Extend the default number of column to 6

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2817]
Before changing the property value, check for what controls this is a problem (in addition to the date time, or fields date controls), and see if we want to improve how some of those controls are displayed when we have 6 columns.

**Comment by ebruchez** [comment]
See also #2738 for the idea of having a more flexible 12-column layout.

**Comment by ebruchez** [comment]
Possibly, we could also make this a form setting,

**Comment by ebruchez** [comment]
Not relevant since #2738 is implemented.
