### ISSUE TITLE
`fr-<type>-button` class missing from process buttons in 2016.1

### ISSUE THREAD

**Issue by bytesnz** [orbeon/orbeon-forms#2828]
Hello,

The `fr-<type>-button` class seems to have been removed from 2016.1 (compared with 4.10) (see below). These classes were helpful in adding custom formatting to the process buttons.

4.10
```html
<span id="xf-496≡xf-4983⊙1" class="fr-submit-button xforms-trigger-appearance-modal xforms-control xforms-trigger xforms-trigger-appearance-full">
    <button id="xf-496≡xf-4983≡≡c⊙1" type="button" class="btn">Submit</button>
</span>
```

2016.1
```html
<span id="xf-411≡xf-1689⊙1" class="xforms-trigger-appearance-modal xforms-control xforms-trigger xforms-trigger-appearance-full">
    <button id="xf-411≡xf-1689≡≡c⊙1" type="button" class="btn">Submit</button>
</span>
```

**Comment by ebruchez** [comment]
Thanks, and agreed. This was a regression, which is already fixed for the upcoming 2016.2 with #2739. I also cherry-picked the change to the 2016.1 branch.

**Comment by bytesnz** [comment]
Ah. Apologies for duplicating. Cheers Eric.

**Comment by ebruchez** [comment]
No problem at all, there are lots of issues in the tracker! We appreciate good bug reports like yours.
