### ISSUE TITLE
Wizard: support navigating to a specific section via URL

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2848]
Behavior: if in wizard mode, if the URL has a fragment identifier, say `#gaga`, if there is a section named `gaga`, and that section is reachable from the beginning of the wizard by clicking the _next_ button, then that section is shown right away.

[+1 from community](http://stackoverflow.com/questions/38394324/is-there-a-way-navigate-directly-to-a-section-in-an-orbeon-form)

**Comment by avernet** [comment]
[+1 from community](http://discuss.orbeon.com/Linking-to-places-within-a-form-td4661726.html)

**Comment by ebruchez** [comment]
What we need:

- API (via event probably) in wizard to switch to a given page
    - could be by section name and/or by position
        - what about subsections and non-relevant sections (see also #2784)
- must check that navigating to the page is permitted (validated mode)
- client must set fragment when changing page
- client must send event to server when fragment changes
- also handle browser back (if anything particular needed)

See also #2784.

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/2016476/messages/6390506827)

**Comment by ebruchez** [comment]
One thing to be aware of: the URL fragment is never passed to the server, and therefore the page will first load, and then code will check whether a fragment identifier indicates a wizard page to attempt navigation to.

Normally, a fragment identifier indicates a `name` or `id` on the page. The `id`, in our case, might not be initially visible in the case of the wizard.

We do have ids associated with a page, for example:

- non-repeated: `fr-view-component≡date-time-controls-section`
- repeated: `fr-view-component≡detail-section-section≡detail-section-section-repeater≡xf-1181⊙1`

The first one looks ok, but not the second one. In any case, we can interpret the fragment in a different way.

Algorithms:

- navigate forward page by page? or backward if page is back?
- click on TOC if present, or simulate click

**Comment by avernet** [comment]
And: avoid "flashing", i.e. the browser showing the first page, send a request to the server, and upon getting the response showing the desired page.

**Comment by ebruchez** [comment]
Well, it's going to be hard to avoid flashing, since we actually need to do the following:

1. load the page, including the JavaScript
2. detect fragment
3. send event to server
4. show wizard page

Maybe we could, in JavaScript, gray out the form as soon as we detect a URL fragment targeted at a wizard page.

**Comment by avernet** [comment]
I think graying out the form is fine, maybe using the modal loading indicator. This is to avoid the risk that users see the first page, and in case the response takes a while to arrive, start making changes on the first page, or click Next, and while doing so at some point they are "unexpectedly teleported" to another page of the wizard.

**Comment by ebruchez** [comment]
The title of this mentions a fragment id, but we could also use a request parameter. The benefit of that would be to have the ability to let the server load the page on the correct wizard page directly.

**Comment by ebruchez** [comment]
Either way, the wizard needs a server function to navigate to a given section if allowed.

**Comment by ebruchez** [comment]
- [ ] property to enable the feature
- [ ] Q: Do we need a JavaScript API now?

**Comment by ebruchez** [comment]
Quick reminder about how things work with nested sections:

- It is only possible to navigate to a nested section, but not to the enclosing section. If you click on an enclosing section, that navigates to the first nested section.
- With wizard subsection navigation set to `all`, all subsection levels are shown in the TOC, but subsection navigation is limited to the first two levels.

Regarding changing the URL, we could do this by using a variable mirroring the value of `$current-nav-case-id`.

**Comment by ebruchez** [comment]
We probably don't need a Form Builder setting for this, as the default is to enable the feature, and we hope that the feature doesn't need to be disabled. In the rare cases that it should be, the property will be enough.

-[ ] consider renaming property from `allow-initial-url-param` to ???

**Comment by ebruchez** [comment]
[Doc](https://doc.orbeon.com/form-runner/features/wizard-view#page-name-url-parameter)
