### ISSUE TITLE
Index table not updated

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2861]
- using MySQL on RDS, database `orbeon`
- reindex db to make sure I am up to date, no errors
- creating `mysql/name-etc` form with  2 fields: 1 text, 1 number, making them "Show in Search" and "Show in Summary" (did form in `en` and `fr`, BTW)
- new, save
- row appears in summary, but no data shows
- `orbeon_i_control_text` is empty for this data

*NOTE: Save takes 10s of seconds, while read takes only ~2s with remote database.*

**Comment by ebruchez** [comment]
If I reindex the database after that, the values show in the Summary page. So it seems that the index is not updated upon saving.

**Comment by avernet** [comment]
I'm not seeing it. Do you still have the source of the form?

![screen shot 2016-08-05 at 5 25 16 pm](https://cloud.githubusercontent.com/assets/106961/17453504/a26415c4-5b31-11e6-8a84-bf01e10fa8e0.png)

**Comment by ebruchez** [comment]
Here https://gist.github.com/ebruchez/ab7fb7911950012ca7aedea6aaa3a289

**Comment by avernet** [comment]
Still can't reproduce index not updated. Reassigning to Erik to check check if something special is needed to reproduce this.

**Comment by ebruchez** [comment]
Can't reproduce anymore either. Weird.
