### ISSUE TITLE
Run PostgreSQL tests on Travis CI

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2863]
Right now only MySQL is enabled.

Also consider the commercial databases on the PE branch after that.

**Comment by avernet** [comment]
Locally, we can do:

```
createdb orbeon
psql -s orbeon
create user orbeon password '$RDS_PASSWORD';
```

**Comment by avernet** [comment]
When running tests, getting, when locally trying to do a `CREATE DATABASE orbeon_avernet`:

```
org.postgresql.util.PSQLException: ERROR: permission denied to create database
```

**Comment by avernet** [comment]
Granting superuser rights to `orbeon` solves this. I updated the DDL in myg earlier message for this.

**Comment by ebruchez** [comment]
@avernet If this is fixed, can you close it?

**Comment by avernet** [comment]
Yes, we now have the database tests run on Travis CI for MySQL and PostgreSQL. Closing.
