### ISSUE TITLE
Updating data creates new entry in Summary page

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2864]
- with MySQL
- create and save data
- Summary page
- open saved data
- update value (or not)
- save data
- Summary page
- notice two rows

![screen shot 2016-08-05 at 4 20 26 pm](https://cloud.githubusercontent.com/assets/105769/17452859/94267938-5b28-11e6-94f0-93f8663cebf2.png)

**Comment by avernet** [comment]
I am reproducing this one. Good.

![screen shot 2016-08-05 at 5 27 47 pm](https://cloud.githubusercontent.com/assets/106961/17453521/f7affebc-5b31-11e6-9dd8-72480dbc0cfe.png)
