### ISSUE TITLE
Static image broken at runtime

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2871]
With DB2, create a form in Form Builder with a static image, and publish it.

![screen shot 2016-08-10 at 11 19 10 am](https://cloud.githubusercontent.com/assets/106961/17565469/7202d762-5eec-11e6-8d0e-17627e2aee10.png)

Load `/new` and notice the broken image. When the image is loaded, the form version received by the persistence code through the `orbeon-form-definition-version` header is `false`, which is unexpected.

![screen shot 2016-08-10 at 11 21 44 am](https://cloud.githubusercontent.com/assets/106961/17565525/a38f655c-5eec-11e6-948a-7af7b360046e.png)

**Comment by ebruchez** [comment]
Issue was not specific to DB2 by the way. Was due to passing of `Orbeon-Form-Definition-Version` header, where the `fr:form-version()` was incorrectly returning a boolean instead of an integer.
