### ISSUE TITLE
Email mentions only PDF and XML, but TIFF is also attached

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2874]
Now we're also sending a TIFF, but the email body still only mentioned the PDF and XML. It should also mention TIFF when included.

![screen shot 2016-08-10 at 4 32 23 pm](https://cloud.githubusercontent.com/assets/106961/17574694/3fa52cc6-5f18-11e6-948d-591eeb5af89b.png)

**Comment by ebruchez** [comment]
I think it's ok: by default, `attach-tiff` is set to `false`, and we set it to `true` only for the test plan. If you set it to `true` in real life, you will probably write your own email message anyway.

**Comment by avernet** [comment]
@ebruchez Got it, and I agree.
