### ISSUE TITLE
API to publish a form definition

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2876]
[+1 from user](http://discuss.orbeon.com/CRUD-Web-Service-API-Problem-publishing-forms-that-reference-section-template-td4661700.html)

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/1966556/messages/326808857#__recording_357110950)

What would it take to implement this API? Currently, we do the publishing process in:

- `model.xml` as response from `fb-publish-form`
- `home.xhtml` to upgrade form definitions

In both cases, the following is called:

- `deannotate.xpl`
- `add-migration.xpl`
- `add-template-bindings.xpl`
- `fbf:publish($annotated, event('app'), event('form'), event('document'), event('version'))`

`home.xhtml, in addition, first does:

- `annotate.xpl`

The inputs are:

- library for the given app/form
- form definition
- app/form name to publish under
- document id to retrieve form definition attachments and pass as URL parameter upon PUT
- form definition version to publish under, or none

A publish API should obtain the same parameters.

The API would consist in a POST or PUT with:

- XML for the form definition passed
- source document id to retrieve form definition attachments, or none
- form definition version to publish under, or none
- optional parameters
  - source app/form name to retrieve form definition attachments (default: use app/form name in form definition)
  - publish app/form name (default: use app/form name in form definition)

The API implementation would retrieve the library itself.

Steps:

- [ ] implement service
- [ ] Form Builder publish uses service
- [ ] Home page uses service if possible (possible issue: retrieving library many times)

**Comment by ebruchez** [comment]
To consider for customer for 2017.1.

**Comment by ebruchez** [comment]
[+1 from customer](https://mail.google.com/mail/u/0/#drafts/15b5e794aa5189dc)

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/1932446/messages/438098341)

**Comment by ebruchez** [comment]
Example paths:

- `/fr/service/acme/sales/publish`
- `/fr/service/acme/sales/publish/123456`
- `/fr/service/acme/sales/publish?publish-app=acme&publish-form=marketing`

**Comment by ebruchez** [comment]
Issue: we POST at app/form name, but if you have a form definition XML and would like to use that form definition's app/form name, you either have to first look at the content of the form definition and extract the configured app/form name, or the API has to ignore the path's app/form name.

Maybe the path should instead be `/fr/service/publish` and everything else URL parameters.

**Comment by ebruchez** [comment]
Also, we probably don't need to override the published app/form name. Either:

- XML is POSTed and we use the included metadata app/form name
- or we ask the service to read the form definition from orbeon/builder

We could have then two paths:

- `/fr/service/publish`: takes POSTed XML
- and `/fr/service/acme/sales/publish/123456`: retrieves from orbeon/builder

**Comment by ebruchez** [comment]
Also there is no need to support retrieving attachments from Form Builder if the form definition is POSTed.

**Comment by ebruchez** [comment]
[Documented](https://doc.orbeon.com/form-runner/api/other/publish.html)

**Comment by ebruchez** [comment]
For Form Builder to use the API, we must support the ability to POST the XML, while at the same time retrieve the attachments. This is because the XML that is published contains changes compared to the version that is saved to the database, namely:

- the versioning comment
- the `available` flag

**Comment by ebruchez** [comment]
To support the publish API from the Home page, we need to:

- pass username/password
- pass the remote server URL (or some kind of indirection, like by position?)

**Comment by ebruchez** [comment]
Doing automated tests for this would be great, but it requires a running database. This could work along the existing `db:test` suite.

**Comment by ebruchez** [comment]
Wondering whether we should add the following parameters:

- `versioning-comment=...`
- `available=false`

Right now, this is done in `publish-dialog.xml` for those two, and the code to make the form definition available/unavailable is duplicated in `home.xhtml`.
