### ISSUE TITLE
Section/Grid Settings for repeated grid: can uncheck readonly checkbox

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2890]
The *Repeat Content* checkbox shows unchecked after clicking on it, as in the screenshot below, while clicking on a readonly checkbox should have no effect. (The box still shows checked after closing the dialog with *Apply* and reopening the dialog.)

![screen shot 2016-08-16 at 5 08 47 pm](https://cloud.githubusercontent.com/assets/106961/17720155/92a37e4e-63d4-11e6-9498-3d823197b9e9.png)

**Comment by ebruchez** [comment]
Probably not a regression.

In this case, when the dialog shows, it must create the items of the `xf:select[appearance = full]`. When doing so, there is no code to set `disabled` on the HTML `input` elements if the control is readonly.
