### ISSUE TITLE
JavaScript error renaming repeated grid

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2891]
To reproduce, in Form Builder, import [this form](https://github.com/orbeon/orbeon-forms/files/423179/gaga.txt), save it, reload the form, click on the last grid (which is empty), add a repeated grid, click empty grid above the repeated grid that was just added, delete it, got to the properties for the nested grid, change the name, press enter ⇒ the error happens.

**Comment by ebruchez** [comment]
FYI I tried this on master, and the error didn't happen.

**Comment by ebruchez** [comment]
Don't see it with 2016.2 either!

**Comment by avernet** [comment]
When the server tells the client a repeat index changes, the client highlights the corresponding repeat iteration, adding a CSS class where appropriate. If a repeat index changes and it contains a nested repeat, highlighting on that nested repeat will need to change, and this is why the client keeps track of a the repeat hierarchy. This repeat hierarchy is given to the client by the server when the page loads through a `<input type="hidden" name="$repeat-tree">`, but with `<xxf:dynamic>` that hierarchy isn't  static anymore: it can change after the page loads. The server tells the client about a hierarchy change with an `<xxf:load>` calling JavaScript code `ORBEON.xforms.Globals.processRepeatHierarchy(…)`. The error happens since we're processing `<xxf:repeat-indexes>` in the response before we process the `<xxf:load>` (which makes sense).

An "obvious" fix would be to add a new action, `<xxf:repeat-hierarchy>`, and have the server tell the client about a change in the repeat hierarchy with that action. In the sequence of actions, the server would put `<xxf:repeat-hierarchy>` before `<xxf:repeat-indexes>`, since the former is used by the latter. This would also clean things up, avoiding the use of an `<xxf:load>` to call JavaScript code in the client for something that should be part of the client-server protocol.

**Comment by ebruchez** [comment]
For reference updating the repeat hierarchy was done with #1579 in 623c40a69557fcffd1d63302c6053f0144419377.

**Comment by ebruchez** [comment]
Checking where the repeat hierarchy is in use:

- use of `repeatTreeChildToParent`
    - `_renumberIDs`
            - by `endDrag`, which is unused
    - `findRepeatDelimiter`
        - processing `repeat-indexes` in Ajax response
        - `setRepeatIterationRelevance`
            - processing `repeat-iteration` in Ajax response
        - `callUserScript`
            - processing `script` in Ajax response
    - `getClassForRepeatId`
        - processing `repeat-indexes` in Ajax response
- use of `repeatTreeParentToAllChildren`
    - processing `repeat-indexes` in Ajax response

**Comment by ebruchez** [comment]
Created #2892 as a maintenance item to consider avoid storing and updating repeat hierarchy on the client.

**Comment by avernet** [comment]
I am confirming that I am not seeing this issue anymore after 623c40a.

**Comment by ebruchez** [comment]
@avernet should be after fbdbcc04b2698abb98025680d6cc6330b5c9d61e.
