### ISSUE TITLE
Date picker buttons don't work with IE9

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2893]
This might be a regression.

I reproduced this with IE 9.

Curiously, this works with IE 11 and IE 10, even when they are in IE 9 mode.

[+1 from customer](https://basecamp.com/1721271/projects/11150078/messages/59533336)

**Comment by avernet** [comment]
The issue on IE9 was due to a `console.log()` and `console.trace()` leftover by mistake when doing a [fix](https://github.com/orbeon/orbeon-forms/commit/d580b51b5f40cfad877262b89a09d796e5c612d0) to #2570.

**Comment by avernet** [comment]
Since this is a *very* low-risk fix, I cherry-picked it on the 2016.2-ce and 2016.2-pe branches, and we can easily put this on other branches if necessary.

**Comment by ebruchez** [comment]
Cherry-picked on customer branch.

**Comment by ebruchez** [comment]
Also cherry-picked on 2016.1 branches.
