### ISSUE TITLE
SQL Server: error with spaces doing full-text search

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#2913]
If you enter a string such as "abc def ghi", you will get this error:

> Syntax error near 'def' in the full-text search condition 'abc def ghi'

It seems that with SQL server, we must process the search string by adding quotes. See this [SO question](http://stackoverflow.com/questions/9435119/syntax-error-near-of-in-the-full-text-search-condition-control-of).

[+1 from customer](https://mail.google.com/mail/u/0/#inbox/156c60d717802330)

**Comment by avernet** [comment]
Was this with 2016.2? With SQL Server, from what I see in the code, we're now doing `contains(xml, ?)` with the `?` replaced by the string the user typed using a `PreparedStatement`.

**Comment by ebruchez** [comment]
Issue reported with 4.8.2. Did we change the code since then?

**Comment by avernet** [comment]
Search was moved from XPL to Scala in 2016.2, but the SQL itself shouldn't have changed substantially, and I'm able to reproduce this with 2016.2.

**Comment by avernet** [comment]
Fixed in https://github.com/orbeon/orbeon-forms-pe/commit/11b88041fb81954dc2a4b4a15b6250870a48cab1.
