### ISSUE TITLE
Per app/form properties to setup start/end year in the dropdown date control

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#2919]
For instance:

```xml
<property 
    as="xs:string"
    name="oxf.xforms.xbl.fr.dropdown-date.start-year.my-app.*"
    value="1975"/>
```

**Comment by avernet** [comment]
Implemented in https://github.com/orbeon/orbeon-forms/commit/da5bbb5318af56e9bfee36b580949557d227067b.

**Comment by avernet** [comment]
[+1 from customer](https://basecamp.com/1721271/projects/4156697/messages/61463372)

**Comment by ebruchez** [comment]
[Documented](https://doc.orbeon.com/form-runner/component/dropdown-date.html)
