### ISSUE TITLE
Inconsistent behaviour of send process's prune parameter

### ISSUE THREAD

**Issue by ajw625** [orbeon/orbeon-forms#2920]
I have configured a process to send annotated data and then send meta data. It is sending to a test server that someone has helpfullly provided for anyone to use.

Both `send` actions are configured to prune the data so that non-relevant fields are not included. This does not seem to be working consistently though.

```
<property as="xs:string" name="oxf.fr.detail.process.send-to-smartforms.*.*">
    if ("xxf:instance('fr-persistence-instance')/data-status = 'dirty'")
      then
      (
        set-data-status(status="safe")
        then
          send(
                uri="http://posttestserver.com/post.php?dir=vivid_orbeon",
                content="xml",
                method="post",
                replace="none",
                prune="true",
                annotate = "id"
               )
        then
          send(
                uri="http://posttestserver.com/post.php?dir=vivid_orbeon",
                content="metadata",
                replace="none",
                prune="true",
                method="post"
               )
            then success-message(message="Save Successful")
      )
      else nop
    then navigate(uri="javascript:window.SMARTFORMS.orbeonPostSaveNavigation()")
    recover error-message(message="Save Failed")
</property>
<property as="xs:string" name="oxf.fr.resource.*.*.en.buttons.send-to-smartforms" value="Save"/>
```

For example, this field is relevant:
`now_.applicationInformation.informationAboutProposedActivities_.activitiesMineralCoal`
and these fields are not relevant:
`now_.applicationInformation.informationAboutProposedActivities_.activitiesSandGravelQuarry`
`now_.applicationInformation.informationAboutProposedActivities_.activitiesPlacer`

The annotated data includes all three fields. The meta data includes only the `activitiesMineralCoal` and `activitiesPlacer` fields (names shortened for clarity). I did two tests. In the first, only the `activitiesMineralCoal` field had a value and only that field appeared in the meta data. In this second test both the `activitiesMineralCoal` and `activitiesPlacer` fields are included in the meta data. So there is a correlation there.

I've attached the form source and the sent data and meta data.

[form-source.txt](https://github.com/orbeon/orbeon-forms/files/460522/form-source.txt)
[send-data.txt](https://github.com/orbeon/orbeon-forms/files/460524/send-data.txt)
[send-meta.txt](https://github.com/orbeon/orbeon-forms/files/460523/send-meta.txt)

**Comment by ebruchez** [comment]
Thanks @ajw625 I will look into it.

**Comment by ebruchez** [comment]
I suspect that this might be the same issue as #2930.

**Comment by ebruchez** [comment]
@ajw625 We will have a patch for this soon. Please let us know privately if you need it and based on which Orbeon Forms version.

**Comment by ajw625** [comment]
Thanks, @ebruchez. I think it can wait for now.
