### ISSUE TITLE
Use Request Parameter with the custom Persist API

### ISSUE THREAD

**Issue by cetra3** [orbeon/orbeon-forms#2934]
Wondering if it is at all possible to pass request params to the persistence URL as parameters.

I.e say I have a request param `ticket` that is passed through the URL when accessing a form.

I have properties like so:

```
<property as="xs:string"
      name="oxf.fr.persistence.provider.*.*.*"
      value="example"/>

<property as="xs:string"
   name="oxf.fr.persistence.example.uri"
   value="http://localhost:8080/example/service/api/orbeon?ticket={xxf:get-request-parameter('ticket')}" />                    
```

At the moment this complains that the URL is invalid, as it's not converting the `{}` brackets to the request param.

Is it at all possible to pass this through as a parameter?  Or is the alternative to add it as a header?

**Comment by ebruchez** [comment]
The URL for the persistence layer implementation is not a template and cannot contain XPath expressions.

You can try the `query` parameter of the [`save` action](https://doc.orbeon.com/form-runner/advanced/buttons-and-processes/actions-form-runner.html#save). But this will only work when saving and not when reading.

**Comment by cetra3** [comment]
@ebruchez, no worries.  I have used a workaround with cookies that appears to be working.
