### ISSUE TITLE
404 after deleting a draft

### ISSUE THREAD

**Issue by acspike** [orbeon/orbeon-forms#2963]
Submit a form. Open for editing a second time and change a field to create an autosaved draft. Return to the form summary page without saving. Check the draft and delete. Then attempt to access the previously submitted form. 404. 

This is happening with a form embedded in liferay.

**Comment by avernet** [comment]
@acspike Obviously, deleting the draft of a document shouldn't delete the non-draft version. Does it look like this is what is happening here? Do you know if this is happening if you're accessing the form directly, not through Liferay? Also, do you have any permissions defined on the form? And I imagine that your users are authenticated (otherwise they wouldn't have drafts), correct?

**Comment by avernet** [comment]
@acspike Do you have any feedback on my previous comment? If it's indeed an issue, we'd really like to fix this.

**Comment by acspike** [comment]
Sorry. In the database the draft version is marked deleted and the non-draft version is not marked deleted. But the draft version's timestamp is newer (of course). The form shows in the summary. But when clicked 404. If I delete the draft record from the table in the database the form is accessible again.

I did a test today with another form (not through liferay) and had the same experience (seemingly easy to replicate). The form I tested today did have a few permissions (anyone: create; owner: read, update, delete). Yes, authenticated.

**Comment by avernet** [comment]
Indeed, nice catch Aaron. And this looks like a regression caused by changes we had done for 2016.2. I've picked this on our 2016.2-pe branch, to be included in an upcoming 2016.2.2. Aaron, and in the meantime, just let us know if you need a patch for a build you're using.

**Comment by acspike** [comment]
Hit this again today. I guess a patch could be helpful. Or depending on the timetable for 2016.2.2 I could wait.

**Comment by avernet** [comment]
@acspike I'm thinking it might be a good idea for us to do a 2016.2.2 quickly, as we have a number of fairly important fixes in the pipeline. I'll discuss this with Erik and will follow-up here.

**Comment by avernet** [comment]
@acspike We've resolved to release 2016.2.2 with the fixes we have so far on the `2016.2-pe` branch. It should, if everything goes according to plan, happen this week. Does that work for you?

**Comment by acspike** [comment]
Yes, that's great. Thanks.
