### ISSUE TITLE
Process button label property wildcards precedence not working as should

### ISSUE THREAD

**Issue by bytesnz** [orbeon/orbeon-forms#2977]
Orbeon version: Orbeon Forms 2016.2.201608230022 PE

When I set a custom label for the forms in my application, the wildcard value take precedence over the non-wildcard values (https://doc.orbeon.com/configuration/properties/#wildcards-in-properties)

eg
```
  <property as="xs:string" name="oxf.fr.resource.APP.*.en.buttons.submit" value="Submit"/>
  <property as="xs:string" name="oxf.fr.resource.APP.FORMA.en.buttons.submit" value="Place referral/request"/>
  <property as="xs:string" name="oxf.fr.resource.APP.FORMB.en.buttons.submit" value="Submit Completed Form"/>
```

Submit button will always be "Submit" (have tried changing order and commenting out the wildcard to ensure the properties are working for the selected form).

Expected submit to be "Place referral/request" for FORMA, "Submit Completed Form" for FORMB and "Submit" for the other forms in the APP application.

**Comment by avernet** [comment]
@bytesnz The issue is fixed, and will be in the next major release. You'll just let us know if you need a PE patch before that.
