### ISSUE TITLE
Support for datasets in Form Builder and Form Runner

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3014]
This will allow form authors to load data (e.g. from a REST service or SQL query), and have the result stored as a named dataset. The dataset can then be referenced to set initial values, do calculations, validations, and wherever XPath can be used.

It would add:

- In the Actions Editor, another option for what to do with the response: *Save response as dataset*, and a text field to enter the name of the dataset.
- An XPath function to access a dataset: e.g. `fr:dataset('patient-information')`, which works in a way similar to `instance()`.

There are similarities between this RFE and the concept of worksheet #1697, but also some important differences, that warrant, we think, this to be a separate feature:

- Datasets are hierarchical, while worksheets are a set of name/value.
- Datasets are more "free-form" than a worksheet, as their structure isn't known in advance by Form Builder).
- Datasets are read-only, at least initially.

The following features could be done in the future, but are considered to be out-of-scope for this RFE:

- When a static parameter is provided to `fr:dataset()`, check that it matches the name of a dataset defined in an action.
- Support for datasets local to repeats, as we do for itemsets, say when an action runs upon value change of a field in a repeat, for instance to load info about a child when entering the child SSN in a field in a repeat.

Next steps:

- [x] Review RFE with customer

[+1 from customer](https://3.basecamp.com/3600924/buckets/1966555/messages/301803007#__recording_305334151)

**Comment by ebruchez** [comment]
Implementation steps:

- [ ] determine format of the "save to dataset" action representation
- [ ] create Form Builder UI for that action
- [ ] implement action (`actions.xsl`)
  - this must also create one instance per dataset recognized
- [ ] implement XPath function to access a dataset by name
- [ ] unit tests
- [ ] doc

**Comment by ebruchez** [comment]
The format adds:

```xml
<xf:action class="fr-save-to-dataset-action">
```

Implementation in `actions.xsl`
