### ISSUE TITLE
Services dialog for GET service opens with Request Body

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3027]
In Form Builder, paste the source of [this form](https://github.com/orbeon/orbeon-forms/files/635249/scratch_8.txt), save, reload Form Builder, open the dialog for the `country-code-service` HTTP service, and the following shows:

![screen shot 2016-12-06 at 2 46 34 pm](https://cloud.githubusercontent.com/assets/106961/20947168/d17abf10-bbc2-11e6-836e-0bb69a5fb331.png)

Click *cancel*, open the dialog again, and this time it properly shows the URL parameters section, instead of the Request Body text area.

![screen shot 2016-12-06 at 2 48 29 pm](https://cloud.githubusercontent.com/assets/106961/20947223/1420b7a2-bbc3-11e6-96cc-35073c3dfda0.png)

**Comment by ebruchez** [comment]
Check, probably duplicate.

**Comment by avernet** [comment]
Now working for me, closing.
