### ISSUE TITLE
Wizard: option to prevent forward nav even to visited sections

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3029]
Right now ([doc](https://doc.orbeon.com/form-runner/feature/wizard-view.html#validated-mode)), we allow forward validation to the next section if:

1. there are no errors on all preceding pages as well as the current page
2. or if you have already visited the next page

Users would like an option to disallow the second case. So even if a section has already been visited, navigating to it should be disallowed if there are errors in the current (or previous) section.

[+1 from customer](https://mail.google.com/mail/u/0/#inbox/15848879e9ed4c5b) (patch on top of orbeon-4.10.2.201512022157-PE)

**Comment by ebruchez** [comment]
Proposal for option:

```xml
<property
  as="xs:boolean"
  name="oxf.xforms.xbl.fr.wizard.validate-strict.*.*"
  value="true"/>
```
Or, we could keep `validate` and add values to the property:

```xml
<property
  as="xs:string"
  name="oxf.xforms.xbl.fr.wizard.validate.*.*"
  value="false | lax | strict"/>
```

We would still support `true` as synonymous for `lax` for backward compatibility.

**Comment by avernet** [comment]
I prefer the latter. Having 2 boolean properties to choose between 3 options is confusing, and feel like an addon (which it would be).

**Comment by ebruchez** [comment]
Agreed, going with option 2.

**Comment by ebruchez** [comment]
Rules in `strict` mode:

The user can go "Next" if:

- there are no errors in the preceding or current section

The user can click on a top-level section in the TOC if:

- the section is before the current one
- the section is after the current one AND sections before have been visited AND section is not after a section which has errors

There is an issue if the Error Summary shows errors for a section which is after the current one: first we shouldn't show the errors there if the user cannot reach them. Also, if they are in the Error Summary, clicking on them will show the section and bypass the logic.

Should we un-visit sections? At what time?

**Comment by ebruchez** [comment]
For master, also need to think about subsections when enabled.

**Comment by ebruchez** [comment]
[Implemented](https://github.com/orbeon/orbeon-forms-pe/commit/d8579a9035fae5ee0a5ece312a0d15060d266554#diff-64858b7dae680fbdcb8069eb08e5ea3a) on custom 4.10.2 branch for customer.

Will need to port to master.

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/2016723/messages/305437454)
