### ISSUE TITLE
Date and Time control initialized with `current-dateTime()` considered invalid

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3031]
To reproduce, paste [this form](https://github.com/orbeon/orbeon-forms/files/640886/scratch_9.txt) in Form Builder, test, click validate, and see how the date and time field is considered invalid, while it was initialized with `current-dateTime()`.

[+1 from customer](https://3.basecamp.com/3600924/buckets/1966556/messages/307371683)

**Comment by ebruchez** [comment]
Does this need to be backported to earlier releases?

**Comment by avernet** [comment]
I checked to see if this was a regression, but this code has been pretty much unchanged since the beginning, and it looks like we have this component since 2016.1. So yes, this is a candidate to be backported to the 2016.1 and 2016.2 branches.

**Comment by ebruchez** [comment]
Ok I cherry-picked the fix on the 2016.1 and 2016.2 branches.
