### ISSUE TITLE
IE8 unable to load produced by Uglify.js

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3037]
This is happening as Uglify.js generates code of the form: `var a = { for: 'b' }`, without quotes around `for`.

- [x] Can we just change that instance where this code is used? ⇒ Yes, but we're then hitting other problems; see comment below.
- [x] What version of Uglify.js is used by [sbt-uglify](https://github.com/sbt/sbt-uglify)? And can that version generate code that doesn't pose this problem? ⇒ Using version 2.4.13, seems unlikely we're having this problem because of a bug in that version.
- [x] Try changing sbt-uglify to pass `--beautify beautify=false,quote_keys=true` as suggested below.

**Comment by avernet** [comment]
The specific case of `for:` happens in YUI's `dom.js`, in a part of the code only used for browsers < IE8. I tried removed that code, but next we're hitting Uglify.js generating a `class:`, from code in our own code, and this usage seems legitimate. We could change that too, but we're likely to hit other similar problems down the road.

**Comment by avernet** [comment]
I'm wondering if we're not hitting an issue with the version of Uglify.js used by sbt-uglify. I am trying an [online demo](http://demos.forbeslindesay.co.uk/uglify-js/) using version 2.4.12, and it properly adds quotes around `for`. Assuming the sb-uglify we used is based on 1.0.3, then that version [is using](https://github.com/sbt/sbt-uglify/blob/1.0.3/build.sbt) Uglify.js 2.4.13. So if 2.4.12 was "doing the right thing", it is hard to believe that a newer version, 2.4.13, has this problem.

**Comment by avernet** [comment]
Using this [Uglify.js online demo](https://skalman.github.io/UglifyJS-online/) it seems the problem is happening when `quote_keys` is `false`. On the command line, one might be able to set this with `-b quote_keys=true`.

**Comment by avernet** [comment]
I don't see sbt-uglify having keys (?) to configure the `quote_keys`, but since we have a custom version, we could try updating `SbtUglify.scala` to pass `--beautify quote_keys=true`, e.g. adding this to `commonArgs`.

**Comment by avernet** [comment]
I was able to replicate the issue from the command line, and adding the following solves the problem, so hopefully doing this in [`SbtUglify.scala`](https://github.com/sbt/sbt-uglify/blob/master/src/main/scala/com/typesafe/sbt/uglify/SbtUglify.scala) will have the same effect.

    --beautify beautify=false,quote_keys=true

**Comment by avernet** [comment]
Cool!

**Comment by avernet** [comment]
Reopening, as Uglify is compiling `.attributes["class"]` into `.attributes.class`, which causes an error "Expected identifier" on IE8. This is happening with `AjaxServer.js`.

I tried this on the command line, but don't see this problem; from the command line, `.attributes["class"]`is being produced. Could this be due to an option passed by sbt-uglify to Uglify? Next, I'd suggest logging all the options passed, try to reproduce the issue running Uglify directly from the command line with those options, and if you can reproduce the issue in that case, find what option should be changed or removed.

**Comment by avernet** [comment]
Per my last message, re-assigning to Erik.

**Comment by ebruchez** [comment]
From the command-line, with 2.7.5, these options work for me:

uglifyjs --source-map --support-ie8 --compress --mangle -- src/target/web/uglify/build/ops/javascript/orbeon/xforms/server/AjaxServer.js
