### ISSUE TITLE
Missing Oracle and db2 DDL for 2016.3

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3048]
I don't see them here: https://github.com/orbeon/orbeon-forms/tree/master/form-runner/src/main/resources/apps/fr/persistence/relational/ddl

**Comment by avernet** [comment]
I added the missing files in 02c9dc1b63cf3c6073881305d22ee5253dc64298.

**Comment by ebruchez** [comment]
Ok and I pushed the updated [doc](https://doc.orbeon.com/form-runner/persistence/relational-db.html).
