### ISSUE TITLE
fr:error-summary: make entire label + alert a link

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3056]
See local branch `2016-12-22-3056-wip-error-summary-links`.

[+1 from customer](https://3.basecamp.com/3600924/buckets/2016723/messages/316562543)

**Comment by ebruchez** [comment]
In particular must address what to do when the error contains `<ul>`. Current status on branch is not good:

![error-summary](https://cloud.githubusercontent.com/assets/105769/21460998/79065996-c902-11e6-8a6f-bd5b067d727e.png)

**Comment by avernet** [comment]
@ebruchez With this change, how is the case shown in the above screenshot being dealt with?

**Comment by ebruchez** [comment]
It looks about the same, but doesn't have the trailing "-" at the end of the first line. It is styled with a ":" after the label instead.
