### ISSUE TITLE
Image attachment: ability to resize images upon upload

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3061]
[+1 from customer](https://3.basecamp.com/3600924/buckets/2010455/messages/333375505)

**Comment by ebruchez** [comment]
Needs:

- [ ] picking code/library to decode/resize/encode the image
  - needs to support JPG and PNG at least
  - See [this SO question](http://stackoverflow.com/questions/24745147/java-resize-image-without-losing-quality): it seems Java doesn't have any built-in good quality resampling code for downscaling (upscaling seems ok).
  - There is [Morten Nobel's `java-image-scaling`](https://github.com/mortennobel/java-image-scaling) but the repo hasn't seen changes since 2014. And it is supposedly slow.
  - Use Progressive Scaling (see the SO question).
  - Also see [`thumbnailator`](https://github.com/coobird/thumbnailator)
- [ ] figure out configuration
  - globally/form/field level
  - max width/height
  - any other fancy setting?
- [ ] Form Builder UI if needed

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/18358270/messages/3761692261)

**Comment by ebruchez** [comment]
Options:

- https://github.com/coobird/thumbnailator
- JAI
- anything else?

**Comment by ebruchez** [comment]
See also [`xxf:image-metadata()`](https://doc.orbeon.com/xforms/xpath/extension-functions/extension-other#xxf-image-metadata).

**Comment by ebruchez** [comment]
The parameters we can play with are:

- P1
  - max width/height/either dimension in pixels
  - compression quality
  - keep format/force format (to JPG or PNG)
- P2/maybe
  - exact width/height/either dimension?
  - resize to a percentage (for example 50%)
  - rotation
  - crop

**Comment by ebruchez** [comment]
These options are available, as usual:

- on the control
- at the form level
- with properties

Canonical names:

```xml
<fr:image-attachment
    transform-max-width="400"
    transform-max-height="500"
    transform-quality="0.8"
    transform-format="jpeg|png|original"
>
```

**Comment by ebruchez** [comment]
What logic should we apply if one or more of these parameters is present?

- Q: Do we always transform, even if, say, the size is already within bounds?

Tasks:

- [ ] Form Builder UI
- [ ] doc
- [ ] test

**Comment by ebruchez** [comment]
Right now we are using [`thumbnailator`](https://github.com/coobird/thumbnailator) but using that library has some limitations given it's primary aim (which is, well, to produce thumbnails).

First, if the image is smaller, it will scale it up, while the expectation was to scale down only. And in the original use case of "save space by reducing the image size" we are more likely to hit cases where the original is already within the specified dimensions. In which case, we would not want to process it, especially if it's a lossy format like JPEG.

We *could* allow the user to say, for example, something like "force recompression", which could be useful for saving space with a lower compression level. But it's not a primary goal.

There is also the use case where we'd like to force an output format: for example we ask the user for a screenshot, and we'd like to standardize to PNG. Then, if a destination format is specified, but if the image is already in this format, we wouldn't want to decompress/recompress unnecessarily.

If we'd like to know the size in advance of calling `thumbnailator`, we need to read the image ourselves, and know its dimensions. For the image format, we could read the image too, or just look at the mediatype.

So:

- [ ] find the image dimensions first
- [ ] call `thumbnailator` only when needed
