### ISSUE TITLE
IE issue: Cursor always moves to the beginning of a Number field

### ISSUE THREAD

**Issue by ajw625** [orbeon/orbeon-forms#3063]
**Steps to reproduce:**

1. Create a form with a text field and a number field
2. Click the Test button in Form Builder
3. Click in the text field and enter a value
4. Click in the number field and enter a value
5. Click in the text field to the right of the value. The cursor stays to the right of the value.
6. Click in the number field to the right of the value. The cursor moves to the left of the value.

![image](https://cloud.githubusercontent.com/assets/9143532/21736055/cf1730fa-d422-11e6-8cc9-47f816d0a9de.png)

Tested on: http://demo.orbeon.com

I have only reproduced this using IE 11. Chrome and Firefox do not have this issue.

**Comment by avernet** [comment]
I am not sure this can be avoided in all cases, as on focus we set the value of the field to be "formatted for edit" (e.g. if formatted it shows as `1.10`, on focus we'll just have `1.1`), and setting the value can impact the position of the cursor. At least, I've made a change not to set the value if setting it wouldn't have any effect (other than, possibly, changing the position of the cursor).

**Comment by ajw625** [comment]
Thanks, @avernet.
