### ISSUE TITLE
With eXist, when re-publishing, no message about overwrite is shown

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3071]
This is contrary to what is mentioned towards the end of the *Versioning* section of the [test plan](https://doc.orbeon.com/contributors/test-plan.html). IMHO, a warning would be nice, but isn't an absolute must. However, once the form is published,  we shouldn't say it was published as "version 1", since we don't support versioning with eXist.

![screen shot 2017-01-12 at 9 16 55 pm](https://cloud.githubusercontent.com/assets/106961/21919086/7a81a554-d90c-11e6-8295-b1f538c36192.png)

**Comment by ebruchez** [comment]
Confirming this is an issue with 2017.1.

**Comment by ebruchez** [comment]
Still the case with 2018.2.

**Comment by ebruchez** [comment]
Closing, see #5770.
