### ISSUE TITLE
"java:comp is not a subcontext" with WildFly

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3075]
I was able to reproduce this WildFly 10.0.0, PostgreSQL, and Orbeon Forms 2016.3.

[+1 from customer](https://3.basecamp.com/3600924/buckets/1932446/messages/346266768)

**Comment by avernet** [comment]
When we do:

    new InitialContext().lookup("java:comp/env/jdbc")

WildFly fails with:

    Exception: javax.naming.NotContextException
    java:comp is not a subcontext

I imagine this could be either due to:

- a misconfiguration (would need to double check what we have)
- WildFly not supporting code looking up a "intermediary" context, as I am seeing [someone else](https://access.redhat.com/discussions/1573783) having the same problem error doing a `initialContext.lookup("java:comp/env")`

**Comment by avernet** [comment]
The second hypothesis doesn't seem to be true, as doing a direct lookup (see below) produces the same error.

    new InitialContext().lookup(s"java:comp/env/jdbc/$name").asInstanceOf[DataSource]

**Comment by avernet** [comment]
WildFly reporting the driver not to be JDBC compliant is [nothing to worry about](http://stackoverflow.com/questions/27108923/jboss-logs-postgres-driver-is-non-jdbc-compliant):

```
WFLYJCA0005: Deploying non-JDBC-compliant driver class com.mysql.jdbc.Driver (version 5.1)
WFLYJCA0005: Deploying non-JDBC-compliant driver class org.postgresql.Driver (version 9.4)
```

**Comment by avernet** [comment]
The issue is caused by `tyrex-1.0.jar`, which is incorrectly included the in `WEB-INF/lib`. Next:

- [ ] Check that we actually need Tyrex, at all. We most likely need it when running tests, e.g. the new `RestApiTest` that calls services without the need for a server to run. If we need it just for tests, change the `build.sbt` as appropriate.
- [ ] Update the documentation for WildFly per my latest way of doing the configuration.
- [ ] Update the documentation for WildFly to mention the versions I tested this on (10.0 and 10.1).

**Comment by ebruchez** [comment]
Agreed, when cleaning-up our build I wondered if it was actually in use.

**Comment by avernet** [comment]
It turns out we don't rely on Tyrex, even for tests. Instead in the tests, in `DataSourceSupport.scala`, we set the initial context factory to `org.apache.naming.java.javaURLContextFactory`, and `org.apache.naming` comes from our `lib/test/tomcat-7.0.68-catalina.jar`, so, in 7433a79, I removed Tyrex from our `build.sbt`, and also cherry-picked this changed to `2016.3-pe` and `2016.3-ce`.
