### ISSUE TITLE
Attachment control supporting multiple files

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3079]
[+1 from customer](https://mail.google.com/mail/u/0/#inbox/159cce73d0d5c710)

This could be done at the XBL component level, and/or leveraging the `<input multiple>` attribute, which appears to be [well supported now](http://caniuse.com/#search=multiple).

What would the impact be on the background upload/upload server?

**Comment by ebruchez** [comment]
The current workaround is to create a repeated grid containing an attachment control.

**Comment by ebruchez** [comment]
[+1 from user](https://stackoverflow.com/questions/48925198/orbeon-forms-multiple-attachments/48941894#48941894)

**Comment by avernet** [comment]
[+1 from customer](https://mail.google.com/mail/u/0/#inbox/FMfcgxvxBFkHXttnRNXGXDgzQhFHrJfq)

**Comment by egbertr** [comment]
Are there any estimate on when such a feature will be available? Our clients are also calling out strongly for it.

**Comment by ebruchez** [comment]
@egbertr There is [no estimate at this point](https://doc.orbeon.com/faq/resources-support#when-are-you-going-to-fix-implement-my-favorite-issue-feature), sorry.

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/1966556/messages/2470071093)

**Comment by ebruchez** [comment]
If we build this a new component, how would we store the attachments information? Right now, we assume a single enclosing element with attributes, in addition to the URI:

```xml
<my-file filename="" mediatype="" size="">
    /file/uri?and=params
</my-file>
```

- One option would be to store the URLs as space-separated, and not use attributes.
    - Our code which checks for attachments would have to be updated (`collectAttachments`, other?).
- Or we could introduce nested elements.

**Comment by ebruchez** [comment]
- [ ] complete design
- [ ] implement
- [ ] backport to 2019.2 customer branch
- [ ] doc

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/1966718/messages/2507242955)

**Comment by ebruchez** [comment]
At this point, from a data format standpoint, I think the nested `<_>` solution is pretty good. It fits well with the mapping we have in XForms with JSON, which represents an array of values.

So we need to either

- update our existing `fr:attachment` control
- OR create a new "multiple file attachments control"

In its simplest version, the control can use a repeat to handle the multiple attachments with the underlying `<xf:upload>`.

The `collectAttachments` method already checks for nested elements, so we probably don't have to update it.

**Comment by ebruchez** [comment]
Ideas:

- a single upload button is probably enough
- nicely display file name and size when done with an attachment
- quick way to remove an attachment
- can easily add a drop area if we want
- support the `download` attribute configuration
- Q: Does the order of attachment matter?

**Comment by ebruchez** [comment]
I played with also adding a drop target. Things work in that I can detect the file(s) drop, which is good!

From there, the question is how to upload the dropped files. One naive way:

```scala
inputFileElem.asInstanceOf[dom.html.Input].files = ev.dataTransfer.files
```

works on Safari, but not Chrome or Firefox.

**Comment by ebruchez** [comment]
In fact, setting the `.files` works in all 3 browsers, but Safari in addition triggers a change event while the others don't. So we can initiate the upload ourselves.

**Comment by ebruchez** [comment]
With Edge 18, I am getting "Assignment to read-only properties is not allowed in strict mode" upon drop. This appears to be when writing the `.files` property.

<img width="801" alt="edge18" src="https://user-images.githubusercontent.com/105769/82004554-10980080-9618-11ea-8477-725a0eef5738.png">

**Comment by ebruchez** [comment]
With Edge 81 and current dev, I don't seem to be getting drag events.

**Comment by ebruchez** [comment]
With Edge 84 dev on the Mac, the drop works.

**Comment by ebruchez** [comment]
The progress bar is currently XForms native. The server sends progress events at regular intervals. This calls `Upload.progress` on the client, which handles a YUI `ProgressBar`. This uses a `style="width: ..."` to update the bar.

The easiest improvement is probably to replace the YUI progress bar with Bootstrap's.

As part of #2996, we'd also like to make the upload control an XBL component. But we can do this as a second step.

**Comment by ebruchez** [comment]
For constraints, the issue is this. `UploaderServer` calls the document with the `xf:upload` control id to obtain the constraints, first from the `xf:upload`'s bound node, second from form-level settings.

However, the `xf:upload` control is now bound to an internal node. The node containing the constraints is the external node and it is now an enclosing node with nested `<_/>`.

Could we propagate the constraints to the local instance? 

Interestingly enough, we use, for validation, custom MIPs without prefixes: `upload-max-size` and `upload-mediatypes`, so we cannot just write them as custom MIPs in the internal model, as those must not be `NCName`s.

**Comment by ebruchez** [comment]
Found a solution for the constraints.

**Comment by ebruchez** [comment]
Now it would be great if we could minimize the amount of code duplication for the "regular" attachment control.

There are only a few differences between single/multiple that matter:

- binding to the bound node vs. nested `<_/>`
- inserting into the bound node vs. setting the values
- deleting under the bound node vs. clearing the values
- hiding the selection control when an item is already uploaded in single mode
- different instance template (`filename="" mediatype="" size=""`)
- different metadata

I am not sure we can have a single binding, but we might be able to reuse the `xbl:handlers`/`xbl:template`, as we do for `fr:number`/`fr:currency` (although in that case we'd like to move away from that.

It's not an *appearance* difference, and so we can't use the appearance mechanism.

But how could we easily switch between single/multiple as an option?

```xml
<fr:attachment>
```

vs.

```xml
<fr:attachment multiple="true">
```

or:

```xml
<fr:attachment max="???">
```

This said, we not only would need to change the `multiple` or `max` attribute, but also to update/migrate the template in the instance. So maybe as a first step, we don't allow easily switching from one to the other and put this feature under the banner of #2412.

**Comment by ebruchez** [comment]
For explicit item deletion, here is how things work right now with `xf:upload`:

- when writing a blank external value, if there was a non-blank value before, we delete the temporary file immediately
- when writing a non-blank external value, we renamed it to a temp file that expires with the session, but we don't delete the previous temp file if there was one (we should!)

Right now, our custom "x" button just clears the value without coming through the `xf:upload` logic. So it doesn't attempt to delete the temp file immediately. But we should try to do this. However, the `xf:upload` is not bound to the values stored in the array, so we can't just use the `xf:upload`. This said, the logic is fairly simple. We should just expose a function we can call to do this.

**Comment by ebruchez** [comment]
Since we now directly queue multiple events and don't need `.files`, things work with the non-Chromium Edge versions (at least version 18). But they still don't work with IE11 so we disable the drop area for all IE versions.

**Comment by ebruchez** [comment]
Crazy: Safari on iPad doesn't appear to support drag and drop this way. `dataTransfer.files` is there but returns a size of 0. Even though everything is there otherwise.

<img width="1376" alt="Screen Shot 2020-05-27 at 3 14 50 PM" src="https://user-images.githubusercontent.com/105769/83077847-28668000-a02d-11ea-856f-460677ed25f1.png">
