### ISSUE TITLE
Successful response body logged as error

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3082]
With `oxf.xforms.logging.error` set to `submission-error-body` (it is the default), our code towards the end of `SubmitResponseEvent.scala` logs a successful response body as an error. This is confusing, especially as, when dealing with a problem, users tend to pay particular attention to messages logged as `ERROR`.

[+1 from customer](https://3.basecamp.com/3600924/buckets/2016476/messages/357047998)

**Comment by ebruchez** [comment]
Supposing that a non-successful response is one with a non-successful status code. If that's the case, then we can test the status code and log appropriately.
