### ISSUE TITLE
"Duplicate id for XForms element: fr-service-response-instance" when importing form

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3087]
To get the error, in Form Builder paste the source of the form attached to the first message in [this thread](https://3.basecamp.com/3600924/buckets/2016476/messages/329378945), publish, and open the `/new` page.

**Comment by ebruchez** [comment]
Following #1593.

**Comment by ebruchez** [comment]
Two issues:

- [ ] not all instance nodes are removed
- [ ] at runtime, if the published form definition has the instances, we must not add them
