### ISSUE TITLE
Ability to use variables for `min`, `max`, etc.

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#309]
This is a feature that the data-bound select1 calls for. It would allow form authors to easily create linked data-bound select1 control in Form Builder, e.g. (LHHA and table cells removed for clarity):

``` xml
<fr:databound-select1 bind="state-bind"
    resource="/xforms-sandbox/service/zip-states"/>
<fr:databound-select1 bind="city-bind"
    resource="/xforms-sandbox/service/zip-cities?state-abbreviation={$state}"/>
<fr:databound-select1 ref="zip" 
    resource="/xforms-sandbox/service/zip-zips?state-abbreviation={$state}&amp;city={$city}">
```

Without bind names exposed as variables, form authors need to know what the structure of the XML is to refer to the value of another field.

**Comment by avernet** [comment]
[+1 from community](http://stackoverflow.com/questions/31315323/orbeon-link-concat-value-in-href)

**Comment by ebruchez** [comment]
+1 from me as I was writing an example

**Comment by ebruchez** [comment]
See #2910 for a function to access the value of a control.

**Comment by ebruchez** [comment]
In an example, I tried to use `bind('state-bind')`, and it doesn't work, because `databound-select1.xbl` evaluates its itemset in the inner scope. Using `xxf:instance('fr-form-instance')//state` works, but it's cumbersome.

Here again, a Form Runner function would help.

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/1966559/messages/483619263) who hit the use case mentioned [earlier](#issuecomment-42612812) by Erik, and expected to be able to refer to the value of a control when setting the min/max number of iterations in a grid.

**Comment by ebruchez** [comment]
+1 from me for `min` and `max` in repeated grid. Referrring to `$min`/`$max` doesn't work.

**Comment by ebruchez** [comment]
[+1 from user](https://mail.google.com/mail/u/0/#inbox/160eaaff744d4383)

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/7873395/messages/1380610548#__recording_1382786170)

**Comment by ebruchez** [comment]
See also:

- https://github.com/orbeon/orbeon-forms/issues/2910#issuecomment-244559899
- #3772

With #2910 implemented, what would it take to make this work? We would like that:

- the user users variables in `min`, `max`, and other places
- this gets translated to a function call and back to a variable when editing

Q: How can we do this translation? Parsing and rewriting XPath expressions is not hard, but round-tripping to a string expression is not reliably possible with  Saxon. One possibility is to do the rewrite at XBL processing time, at least for `fr:grid` and `fr:section` for `min` and `max`. This is how it's done now:

```xml
<xf:var name="min">
    <xsl:copy-of select="namespace::*"/>
    <xxf:value value="$repeat-context-outer/xxf:evaluate-avt($min-avt)" xxbl:scope="outer"/>
</xf:var>
```

But we should probably use `fr:component-param-value()` instead. Entered and fixed #3795.

So which code should do the rewrite of the expression? Should `fr:component-param-value()`, which translates to `xxf:component-param-value()`, do it? But then what if somebody wants to use a local variable as the parameter name?

Should other Form Runner code do the translation when assembling the form?

- [ ] decide where the translation takes place
- [ ] implement
- [ ] doc

**Comment by ebruchez** [comment]
Another way to look at `min` and `max`, in particular, is like `max-length` and the character counter: it could be expressed as a constraint on the grid. The function would check the constraint and annotate the data. `fr:grid` and `fr:section` would read the annotated data like `fr:character-counter`. Doing this, variables would work naturally without any translation, since the constraint is within binds.

One issue with this is to handle backward-compatibility. `annotate.xpl` could migrate existing forms to use constraints. Form Builder-created forms are unlikely to use expressions which would not run identically in the context of `fr:grid` and in the context of the binds.

**Comment by ebruchez** [comment]
For `fr:databound-select1`, this is another story. I don't think we'd like to set the resource name in a bind constraint, would we?

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/2192969/messages/1917519153) to make variables visible in the view, so we can use them in [templates](https://doc.orbeon.com/form-builder/advanced/template-syntax)

**Comment by avernet** [comment]
[+1 from user](https://stackoverflow.com/questions/61344573/migrate-autocomplete-field-to-dynamic-dropdown) who would like to be able to refer to the value of another field with `$other-field` from the resource URL of a Dynamic dropdown.

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/2016476/messages/2646556535)

**Comment by ebruchez** [comment]
Update from the comments above. We now read the `min` as:

```xpath
(
  xs:integer(
    fr:component-param-value('min')[
      . castable as xs:integer
    ]
  )[. ge 0],
  0
)[1]
```

**Comment by ebruchez** [comment]
Note that the latest +1 from the customer is for `fr:databound-select1`'s `resource` attribute, and the idea is to access a custom variable put in the form definition. This is not exactly something we should be thrilled about, since we'd like variables to represent *control values*, not just custom variables.

**Comment by ebruchez** [comment]
Based on the above, we had two approaches:

1. switch to using constraints in the model
2. rewrite `min` and `max` expressions at runtime

Option 1 is harder because it requires migrating the form definition, etc. Option 2 easier I think. Could we start with option 2 and then switch to option 1 when we have that more general mechanism in place?

OTOH rewriting could take place at runtime. Would it be that hard? Sayou have `min="$foo"`. Rewrite to:

```xpath
constraint="xxf:min-repetitions($foo)"
```

Then read with:

```xpath
xxf:custom-mip($binding, 'min-repetitions')
```

As a reminder, `fr:component-param-value()` evaluates the value as an AVT in the outer context of the component. So I *think* that if we were to use `fr:control-string-value()` (or `fr:control-typed-value()`), things would work in a fairly straightforward way.

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/1966556/messages/2970824793)

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/17077193/messages/3644655062)

They have a case of nested dropdowns, using dynamic dropdowns, so they need in the URL to reference the value of the previous dropdown. When the dropdowns are outside of a repeated grid, they can use the following as a workaround:

    ...?my-parameter={//my-field}

But this doesn't work when the dropdowns are in a repeated grid; in that case, they would need to use a variable (or a function), to leverage our "closest control" resolution algorithm. They could use a path expression, but this would add some complexity and introduce a dependency on the data format.

**Comment by avernet** [comment]
Using `fr:control-string-value()` does works, including in a repeated grid ([sample form](https://github.com/orbeon/orbeon-forms/files/6563727/form.txt)).

https://user-images.githubusercontent.com/106961/120051344-13705400-bfd5-11eb-81ae-9d809bcafa14.mp4

**Comment by ebruchez** [comment]
Great. We should be able to fairly easily replace, at runtime (meaning Form Runner form transformation) to replace variable references in these attributes with function calls.

**Comment by avernet** [comment]
Where / by who would the replacement be done (this is at the level Form Runner so would this be done from `components.xsl` & co)? How do we know which attribute values need to be replaced (some XBL components might have attributes where dollars should be kept)?

**Comment by ebruchez** [comment]
Yes I think `components.xsl` & co. The easiest for now would be to hardcode support for `min` and `max`, even if it's not ideal. There should be a way to declare some XBL attributes as "formula" attributes.

**Comment by avernet** [comment]
Another +1 from user [+1 from user](https://groups.google.com/g/orbeon/c/5kcXt_Pnks8) to be able to use variables in XPath expressions for the template syntax

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/2192969/messages/4339390656)

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/23673855/messages/4548860186) to be able to use variables in the Service Response Actions tab of the Actions Editor dialog

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/23878674/messages/4747429012) for the template syntax, in the context of emails

**Comment by ebruchez** [comment]
`fr:section` and `fr:grid-multiple` parameters:

- `min`
- `max`
- `remove-constraint`

**Comment by ebruchez** [comment]
- [ ] rename upon control rename
- [ ] doc
- [ ] tests

**Comment by ebruchez** [comment]
Other places we'd like this besides `min`/`max`/etc. based on the above:

- [ ] XPath expressions in LHHT templates
- [ ] XPath expressions in email templates (is that the same as the above or do we need special processing?)
- [ ] Service Response Actions tab

Anything else?

**Comment by ebruchez** [comment]
In the model, `$foo` returns an XML node. However with the current implementation, in the view, we use `fr:control-string-value()` which returns a string.

- [ ] double-check that `$foo` returns the node
- [ ] should/could this also be the case in the view, for consistency, in which case we shouldn't use `fr:control-string-value()`
- [ ] also consider whether `$foo` should/could return possibly a sequence
- [ ] doc behavior in both cases!

**Comment by ebruchez** [comment]
So now, in the view, `$foo` also returns a sequence of items, not a string value.

Added a [clarification section](https://doc.orbeon.com/form-builder/formulas#resolution-of-repeated-controls) in the doc about the variable notation and what it does.

**Comment by ebruchez** [comment]
In email templates, "The Form Runner function library is not in scope in this XSLT", and right now we use `saxon:evaluate()`. If we create an expression which contains `frf:controlVariableValue()`, we should be able to evaluate it as there is, in fact, an `XFormsContainingDocument` in scope.

**Comment by ebruchez** [comment]
Updated the [documentation](https://doc.orbeon.com/form-builder/formulas#renaming-of-controls-and-formulas).

**Comment by ebruchez** [comment]
Added [documentation about where formulas can be used](https://doc.orbeon.com/form-builder/formulas#where-you-can-use-variables).
