### ISSUE TITLE
Ability to run an action only when a form isn't new

### ISSUE THREAD

**Issue by bwallis42** [orbeon/orbeon-forms#3097]
Currently in the form builder when defining an action there are two options for the Condition (when it is run). "Run Always" and "Run on Creation Only" corresponding to a value in the if attribute of the xforms-ready event action of "true()" and "$fr-mode='new'".

I find I need more options, in particular "Run on Edit Only" which corresponds to the condition in the if of "$fr-mode='edit'".

I can do this currently in the source editor but it would be nice to have this option in the action dialog in the form builder as well.

Would it be possible to extend the options to include all the modes and maybe even combinations?

i.e. I only want to run the action on fr-mode= new, test and edit (but not when the mode is view, pdf or email)

(I also note that the fr-mode value of test is missing in the documentation at https://doc.orbeon.com/form-builder/formulas-examples.html#check-the-form-runner-mode)

**Comment by ebruchez** [comment]
That seems reasonable and I don't see an immediate drawback to this. Maybe we should have the ability to specify is/is not and specific modes, including "all modes", or maybe list the modes and use checkboxes.

I fixed the doc and added a mention of `test` and the `fr:mode()` function which is preferable to use now.

**Comment by bwallis42** [comment]
I'm sure you would know this already but it is quite easy to match a set of modes in the source.

if="fr:mode()=('new','edit','test')" 

runs the action if the mode is one of those three (this was new for me at least, xsl/xpath is not my strong point).

**Comment by ebruchez** [comment]
Use the opportunity to remove the event names from the resources.

**Comment by ebruchez** [comment]
And also consider not using `xforms-ready`, but dispatching an event such as `fr-run-form-load-action` or similar, so we have control in `persistence-model.xml` on exactly when those actions run. With drafts in particular, `persistence-model.xml` does things upon `xforms-ready` such as showing a dialog, and we should review the order of operations there.

**Comment by ebruchez** [comment]
- [ ] decide UI: checkboxes, how flexible regarding modes?
- [ ] implement
- [ ] remove XPath from the resources for `<event-condition>`
- [ ] review the order of operations with drafts: `persistence-model.xml` does things upon `xforms-ready` such as showing a dialog
- [ ] doc
- [ ] tests
