### ISSUE TITLE
PDF doesn't contain latest field changed

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3107]
What I wrote about this:

> When you tab out of a modified field, an Ajax request is sent to the server to update the data model. When you click on the PDF button, that goes through a separate path which might reach the model first and so the latest change in the UI is not yet available.

[+1 from customer](https://3.basecamp.com/3600924/buckets/1932446/messages/329479076)

**Comment by avernet** [comment]
Sounds like a duplicate of #1466. @ebruchez I'll let you close this or clarify the issue, as appropriate.

**Comment by ebruchez** [comment]
Closing as duplicate of #1466.
