### ISSUE TITLE
Configure PDF filename in email attachment

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3117]
We already have [`oxf.fr.detail.pdf.filename`](https://doc.orbeon.com/configuration/properties/form-runner.html#custom-pdf-filename) to configure a dynamic PDF filename in the URL.

This is about using the same property and/or adding a property to control the PDF name in email attachments. This is done in `email-form.xpl` where we produce a `content-disposition` with `filename="form.pdf"`.

[+1 from customer](https://3.basecamp.com/3600924/buckets/1978393/messages/384956036)

**Comment by FatPanther** [comment]
+1

**Comment by ebruchez** [comment]
Duplicate of #3562 which was implemented in 2018.2. Closing.
