### ISSUE TITLE
Calculated Value field is missing commas for values of a trillion or more

### ISSUE THREAD

**Issue by ajw625** [orbeon/orbeon-forms#3128]
Steps to reproduce:

1. Create a calculated field with Data Type Decimal.
2. Test and ensure that the calculated value has at least 13 digits to the left of the decimal place.

![image](https://cloud.githubusercontent.com/assets/9143532/23144275/5846a2ae-f77b-11e6-9466-95e821ae6de5.png)

**Comment by avernet** [comment]
Andrew, thank you for the bug report.
Also cherry-picked on `2016.3-pe`.

**Comment by ajw625** [comment]
Thanks, Alex. I added those properties to our properties-local.xml and it fixes the issue.

**Comment by avernet** [comment]
Andrew, excellent, and thank you for confirming this works for you.
