### ISSUE TITLE
Load-time ASCII art misaligned

### ISSUE THREAD

**Issue by acspike** [orbeon/orbeon-forms#3129]
https://github.com/orbeon/orbeon-forms/blob/0f8c1dac6e774697d80a89f64cf5ce9c67f0d412/src/main/scala/org/orbeon/oxf/webapp/Orbeon.scala#L34

In the log file the first line occurs on the same line as the log timestamp and is misaligned with the following lines. Starting with a new line would probably fix the issue.

**Comment by ebruchez** [comment]
I added a new line. Hopefully that will help!
