### ISSUE TITLE
"Apply Initial Value Formulas when Adding Iterations" only works if you use the (+)Insert Below link

### ISSUE THREAD

**Issue by ajw625** [orbeon/orbeon-forms#3134]
![image](https://cloud.githubusercontent.com/assets/9143532/23324679/18b848dc-faa4-11e6-844f-0a098dfe52df.png)

![image](https://cloud.githubusercontent.com/assets/9143532/23324607/928534a0-faa3-11e6-9102-d2f5eabbfab4.png)

When adding iterations, you can use any of these options in the screenshot above:
(+) Insert Below
^ Insert Above
v Insert Below

"Apply Initial Value Formulas when Adding Iterations" works fine if you use the first option, but does not work at all for the other two. This is true for both repeating sections and repeating grids.

**Comment by ebruchez** [comment]
Original issue was #1148.
