### ISSUE TITLE
File upload not marked as invalid on upload with Firefox

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3142]
To reproduce:

1. In Form Builder, create a form with a File Attachment control, validated with `. = '' or @mediatype = 'application/pdf'`.
2. Load the `/new` page in Firefox, attach an image, and notice how no error shows, while the error correctly shows if doing this on Chrome.

One difference is that on Chrome, the Ajax request after the file is selected contains a `xxforms-blur`, while on Firefox it doesn't.

[+1 from customer](https://3.basecamp.com/3600924/buckets/2016476/messages/411810024)

**Comment by avernet** [comment]
In `attachment.xbl`, marking the control visited upon `xxforms-upload-done` solves the problem. But we should probably resolved this at the `xf:upload` level, and consider that control to be always visited when a file is uploaded.

**Comment by avernet** [comment]
@ebruchez will check if doing this in our server-side code is a simple enough. If it is, he will remove the fix I did at the level of `attachment.xbl`, and close this issue. If it isn't, we can keep the current fix, and leave this issue for later.

**Comment by ebruchez** [comment]
I thought we would dispatch `xxforms-visited`, but in fact that event is a notification event. However it is easy to do a `visited = true` upon `xxforms-upload-done`, so I did just that.

**Comment by avernet** [comment]
I reproduced the issue with 2017.2, as [reported by customer](https://3.basecamp.com/3600924/buckets/2016476/messages/411810024#__recording_917949042).

**Comment by ebruchez** [comment]
The nested `xf:upload` is still marked as visited upon value change, so this is fine. But the `fr:attachment` component is not. And that information is used by `fr:error-summary`.

We mark controls visited upon `DOMFocusOut` and `xxforms-blur`, but this doesn't seem to happen for `xf:upload`. So the XBL component is not marked as visited.

If we mark the control as visited upon `xforms-value-changed`, then this would fix the problem as `fr:attachment` is a value control. This might cause more controls to be marked as visited, but is this a problem?

**Comment by ebruchez** [comment]
Re-closing and opening #3508.
