### ISSUE TITLE
fr:attachment/fr:image attachment: dispatch upload events

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3144]
[+1 from customer](https://mail.google.com/mail/u/0/#drafts/15a938ef534e5ec4)

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/2016476/messages/422881777)

**Comment by ebruchez** [comment]
It would be good to have a facility to retarget events in our XBL support. Otherwise, we have to dispatch a new event with all the same properties, and that code will need to be updated if new properties are added.

**Comment by ebruchez** [comment]
- [ ] test
- [ ] doc

**Comment by ebruchez** [comment]
Automated tests would be great but we don't yet have a way to test an upload.
