### ISSUE TITLE
Autocomplete: list of suggestions to have adjustable width

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3160]
Currently the text field makes an optimal use of the available horizontal space, but the list of items doesn't.

![screen shot 2017-03-27 at 5 09 26 pm](https://cloud.githubusercontent.com/assets/106961/24383154/2881cbd8-1310-11e7-832e-43ca383ed4a0.png)

**Comment by avernet** [comment]
* `fr-grid-content`
    * `yui-ac` ⇒ proper width
        * `yui-ac-container` ⇒ `position absolute`, `width: 100%`, gets width of `fr-grid-content`, not `yui-ac`
            * `yui-ac-content`

It is unclear to me why the `yui-ac-container` with `width: 100%`, gets its width of `fr-grid-content`, not `yui-ac`. Seems related to the `fr-grid-content` being `display: table-row`, which looks like a hack. Why was this done, and can we avoid it?

**Comment by avernet** [comment]
Better now:

![screen shot 2017-03-29 at 10 05 18 am](https://cloud.githubusercontent.com/assets/106961/24466874/51bbbcd6-1467-11e7-899a-9f2089998d26.png)

**Comment by ebruchez** [comment]
So can this be closed?

**Comment by avernet** [comment]
Yes.
