### ISSUE TITLE
Explanatory text overwrites rich text

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3161]
Steps:

- new form
- insert Formatted Text Area
- enter text in it
- insert Explanatory Text
- type explanation text
- click out
- Formatted Text Area gets text from Explanatory Text

Reproduced with latest code and 2016.3 on demo.

![screen shot 2017-03-30 at 10 04 19 am](https://cloud.githubusercontent.com/assets/105769/24516656/5387ad94-1530-11e7-848e-069e9fa53853.png)

**Comment by avernet** [comment]
Also cherry-picked on `2016.3-pe`.
