### ISSUE TITLE
Top-level listeners re-registered when script reloaded

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3166]
Even if we don't fully support #1577 or #3141, we do have code preventing top-level listeners from being re-registered in case our JavaScript is loaded more than once, but listeners are still re-registered in that case.

To test this, place the content of [this archive](https://github.com/orbeon/orbeon-forms/files/914828/unit-test.zip) in `xforms-hello`, load `/xforms-hello/load`, and check that the counter is only incremented by 1.

**Comment by ebruchez** [comment]
What should happen if the "same" JavaScript code (say xforms.js) is evaluated twice? A global data structure in the JavaScript global context would have a listener pointing to a function in the older JavaScript code, no?

**Comment by avernet** [comment]
Correct, which shouldn't be a problem, if the `xforms.js` is the same. And note that this only applies to top-level listeners.

**Comment by ebruchez** [comment]
Well, it would mean that every time the JavaScript is re-evaluated (so at every navigation) more memory would be used with pointers to duplicate JavaScript code. This would cause leaks.

Wouldn't it be better to deregister/re-register, or to find a way not to load the JavaScript twice?

**Comment by avernet** [comment]
First, this was only done for the top-level listeners. Second, the new listeners in the "new file" are not registered, so this shouldn't cause a leak. Third, I'm wondering if with recent browsers we would need to register listeners at the top level, which, is possible, would allow make sure that the "current" code is used (seems "cleaner"), without the need for users to call any cleanup code (this being said, there might still be some other reason why we might still want or need to have cleanup code).
