### ISSUE TITLE
Test form no longer shows up

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3171]

**Comment by avernet** [comment]
I also had this locally, and the error that seemed relevant in the log was `java.lang.IncompatibleClassChangeError: vtable stub`. Rebuilding (in sbt, doing `clean`, then `package`) solved the problem. Also, I checked that this isn't happening with the Travis build (tried with PE 1124). So closing.

**Comment by ebruchez** [comment]
Yup it works because I fixed it but it's not cherry-picked on the CE master branch yet.
