### ISSUE TITLE
Show in Summary/Show in Search doesn't work within section template

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3173]
[+1 from customer](https://3.basecamp.com/3600924/buckets/1966556/messages/458160543)

**Comment by ebruchez** [comment]
It seems that this was never implemented. When we search for controls in `FormDefinition.findIndexedControls`, we only look under the body.

**Comment by ebruchez** [comment]
So in addition, we need to:

- look under section templates under the head
- find all usages of section templates
- create unique search paths

Don't we have similar code somewhere else?

**Comment by avernet** [comment]
This doesn't sound unlike what we do when producing a schema from a form definition.

**Comment by ebruchez** [comment]
Turns out that's a bit different because that XML Schema generation works on a live document.

But email sending uses [`FormRunnerEmail.searchHoldersForClassUseSectionTemplates`](https://github.com/orbeon/orbeon-forms/blob/0d8fc4e6565f5ff1e305848598a3d7a9474884e1/form-runner/jvm/src/main/scala/org/orbeon/oxf/fr/FormRunnerEmail.scala#L60) and that should be usable.

**Comment by ebruchez** [comment]
What `FormDefinition.findIndexedControls` does:

- find control elements in source (but NOT in section templates yet) with `fr-summary` and/or `fr-search`
- compute `xpath` key
  - find corresponding bind element and build path from that, removing `[@xml:lang = $fb-lang]` when present
    - also use bind to get `type`
  - adjust path when migration information is present and provider store data in 4.0 format
- return `IndexedControl`s

**Comment by ebruchez** [comment]
Related question: do we generate migration data for section templates as well?

**Comment by ebruchez** [comment]
Getting this migration data when publishing the library:

```json
[{ "path": "my-library-section/my-repeated-grid", "iteration-name": "my-repeated-grid-iteration" }]
```

Getting this in the resulting form definition:

```json
[{ "path": "section-4/my-repeated-grid", "iteration-name": "my-repeated-grid-iteration" }]
```

which is right. And `MigrationOps` does have code to handle section templates so this is good.

**Comment by ebruchez** [comment]
- [ ] Form Runner Summary must also get labels from section template resources. Right now, it gets those from the top-level resources.
