### ISSUE TITLE
Values in repeated grid are not shown on the summary page

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3174]
To reproduce, in Form Builder create a form with a repeated grid containing a text field, mark the field as shown on the summary page, open the `/new` page for the form, add a couple of iterations, enter views, save, load the `/summary` page for the form, and notice that the values are not shown in the relevant column.

[+1 from customer](https://3.basecamp.com/3600924/buckets/2016743/messages/475934026)

**Comment by ebruchez** [comment]
The issue is, as @avernet found out, that one path has parentheses around path elements, while the other one doesn't, in `FormDefinition.findIndexedControls`.

**Comment by ebruchez** [comment]
Backported to 2016.3 branch as well.
