### ISSUE TITLE
Repeated grid: option to show a row number

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3189]
The option should be controllable as we probably don't want to show row numbers by default:

- option in grid settings
- maybe option at form level (property + Form Settings)
- global default (property)

Should we use something like `appearance="full fr:row-numbers"` or use a separate attribute? This does control the appearance so possibly that attribute is acceptable?

[+1 from customer](https://3.basecamp.com/3600924/buckets/1979712/messages/301082854#__recording_509241265)

**Comment by ebruchez** [comment]
[+1 from user](https://mail.google.com/mail/u/0/#inbox/15cbd6de7d0eab98)

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/6592477/messages/1043089882#__recording_1961719290)

**Comment by avernet** [comment]
[+1 from customer](http://discuss.orbeon.com/How-in-Orbeon-Forms-in-a-repeted-grid-in-the-No-column-get-the-numbers-1-2-3-etc-td4665273.html)

**Comment by ebruchez** [comment]
+1 from me today

**Comment by ebruchez** [comment]
- [ ] XBL components
- [ ] Form Builder option
- [ ] doc

**Comment by ebruchez** [comment]
[Documented](https://doc.orbeon.com/form-builder/form-editor/repeat-settings#show-repetition-number)
