### ISSUE TITLE
Cannot have multiple deployments on a single HTTPS host due to lack of SNI support

### ISSUE THREAD

**Issue by peter-newman-cta** [orbeon/orbeon-forms#3203]
We have a single host with multiple deployments of Orbeon, running in separate containers for separate customers. These are exposed via HTTPS, using Apache. Each customer has their own domain name and certificate, therefore SNI is required.

We are finding that only one of the Orbeon deployments functions. In the remainder, we get an unspecific error message dialog box on loading the forms runner (/orbeon/fr/). Looking in the server logs turns up errors like:

```
2017-05-23 10:55:28,844 INFO [ajp-bio-26009-exec-10] [org.orbeon.lifecycle] event: {"request": "45", "session": "BEDA78EC8131350AB96872B8CFB30499", "source": "service", "message": "start: handle", "path": "/fr/service/exist/form", "method": "GET"}
2017-05-23 10:55:28,844 INFO [ajp-bio-26009-exec-10] [org.orbeon.oxf.webapp.ProcessorService] /fr/service/exist/form - Received request
2017-05-23 10:51:56,551 ERROR [ajp-bio-26009-exec-4] [org.orbeon.oxf.xforms.processor.XFormsServer] xforms-submit-error - hostname in certificate didn't match: <forms.customer2.com> != <forms.customer1.com> OR <forms.customer1.com> OR <forms.customer1.com>
```

The application for customer 1 works as expected, the others all produce these errors. This suggests that SNI is not supported by whichever library is being used to make internal requests.

As a workaround, we removed the HTTPS, and no longer have any problems with multiple instances on the same host.

**Comment by avernet** [comment]
@peter-newman-cta I doubt this can or should be handled at the web app level, but I might be wrong. You're saying you're using "Apache" are you referring to the HTTP server ("httpd")? Do you have a separate Orbeon Forms web apps for each customer, i.e. a web app handling `forms.customer1.com` and another handling `forms.customer2.com`?

**Comment by peter-newman-cta** [comment]
Yes - each customer has their own domain name and each has a Tomcat 7 instance running Orbeon. All of the domains are hosted on the same machine, so the domain names all resolve to the same IP. 

That machine also runs Apache httpd, with a vhost for each customer domain and a ModJk mount to expose an Orbeon deployment at /orbeon/. The resulting URLs for the apps are thus https://forms.customerN.com/orbeon/.

We find that one of the apps will work, the others are unusable due to the 'hostname in certificate didn't match' error. If customer1's app works fine, customer2 and 3's apps will report a certificate host mismatch between theirs and customer1's domain.

Since the internal requests are also made via http, we see log entries for them in the Apache logs for the app where there is no mismatch:

```
11.22.33.44 - - [23/May/2017:10:55:53 +0000] "POST /orbeon/exist/rest/db/orbeon/fr?app=&form= HTTP/1.1" 200 3582 "-" "-"
```
(11.22.33.44 is the IP of the host machine and the final two blank `-` fields are the referrer and user agent)

However for the other instances, where we get the certificate error, we do not get any entries in the Apache logs, so the connection has failed at an earlier stage. This and the errors for customer2 and 3's domains mentioning customer1, are both evidence for a lack of support for SNI on the client side of the internal requests to be the cause.

It's possible we'll be able to dig a bit deeper into this ourselves in the near future, I'll add more info if/when I get it, of course.

**Comment by peter-newman-cta** [comment]
Hi Alessandro, we think that workaround should work, so we'll bear it in mind for the future, but for now we've just moved Orbeon off HTTPS. 

I'll look into the log output next time I'm in a position to do some debugging.

**Comment by avernet** [comment]
Got it Peter, and thank you for the update. So for now, I will just close this issue, and should you need to come back to this, say, by investigating the `orbeon.log` per the first paragraph of my last message, feel free to post a follow-up here, and we'll take it from there.
