### ISSUE TITLE
Leverage Travis Build Stages

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3204]
Right now, we run 2 jobs in parallel: one for testing and another one to create the build artifact. Both need the code to be compiled. This RFE calls for leveraging the newly introduced [Build Stages](https://blog.travis-ci.com/2017-05-11-introducing-build-stages) to first compile the code, and then, in parallel run the unit tests and create the artifacts.

This won't make the build faster, but is a first step towards splitting the tests job, so, say, tests for each database can run in parallel. The latter isn't covered by this RFE, and we might want to create another RFE for this once we have the basic support for Build Stages in place.

**Comment by ebruchez** [comment]
From July 18, 2018: [Announcing Build Stages GA](https://changelog.travis-ci.com/announcing-build-stages-ga-job-names-and-conditions-v1-as-platform-default-66397).

See [doc](https://docs.travis-ci.com/user/build-stages).

**Comment by avernet** [comment]
We are now running tests for all databases in parallel. They run 6-7 min for MySQL and PostgreSQL to 18 min (the longest) for Oracle. There is maybe still room for optimization (maybe with Oracle?), but at this point we're not planning to switch to Build Stages, and so I am closing this issue.

<img width="944" alt="Screen Shot 2019-09-19 at 9 36 11 AM" src="https://user-images.githubusercontent.com/106961/65263191-ec077b00-dac0-11e9-87fe-574cd3266977.png">
