### ISSUE TITLE
Label appearance `full minimal` hides label in too many cases

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3213]
We should keep the inline label for TinyMCE, the dropdown, the fields and dropdowns date controls, the autocomplete, and Yes/No answer control. This can be tested easily by opening the `orbeon/controls` form in Form Builder, and changing the label appearance in the Form Settings.

**Comment by ebruchez** [comment]
Issues I notice with "Inline" and "Use placeholder":

- character counter field and textarea don't show a lable
- `fr:tinymce`
- `fr:us-phone`
- `fr:number` / `fr:currency`
- `fr:us-state`
- `fr:dropdown-date` / `fr:fields-date`
- `fr:dropdown`
- more

In fact it seems that all XBL components have this problem.

**Comment by ebruchez** [comment]
See #515 which implemented support at the form level.

**Comment by ebruchez** [comment]
So the question is: which controls can support `full minimal`. Right now we have general logic in `object LHHAAnalysis.hasLHHAPlaceholder`. That is called from:

- `XFormsInputControl.placeholderInfo`
  - from `XFormsInputHandler`
  - from `XFormsTextareaHandler`
  - from `XHTMLHeadHandler.gatherJavaScriptInitializations` (only for IE9)
- `XXFormsComponentHandler`
  - introduced for 2017.1 with #3015 but it's unclear why
