### ISSUE TITLE
Custom PDF/TIFF filename doesn't work anymore

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3215]
Try:

```xml
<property
    as="xs:string"
    name="oxf.fr.detail.tiff.filename.a.a"
    value="'abc'"/>

<property
    as="xs:string"
    name="oxf.fr.detail.pdf.filename.a.a"
    value="'abc'"/>
```

Might be following #1466.

**Comment by avernet** [comment]
In the response, we will add the header `Content-Disposition: inline; filename="data.pdf"`. This implies the following changes:

1. We support `<document filename="data.pdf">`, but always generate a `Content-Disposition: attachment`. We'll add a `disposition-type="inline | attachment"` (this is how it is called in [RFC 6266](https://tools.ietf.org/html/rfc6266)), which for backward compatibility defaults to `attachment` when `filename` is present.
2. We need to figure out a way to evaluate the XPath expression in `oxf.fr.detail.pdf|tiff.filename.*.*` in the context of the document.
