### ISSUE TITLE
`Page.getLang` undefined in `Calendar.coffee`

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3220]
To reproduce, create a form with date field, open `/new`, and click on the date field to open the datepicker. This happens because the `Page` is now implemented in Scala, and loaded after `Calendar.coffee`.

**Comment by ebruchez** [comment]
Similar to #3214.

**Comment by avernet** [comment]
Ah, yes, I forgot I had created an issue for this one alreading.
