### ISSUE TITLE
Improve visibility of TOC and error summary options

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3222]
The Wizard TOC and the Error Summary both easily get hidden when scrolling. If space allows, could we make it so that they stay in the viewport?

I thought that GitHub did this for issues but apparently not (or no longer).

[+1 from evaluator](https://mail.google.com/mail/u/0/#drafts/15c54dc6d1bcf1b0)

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/6637356/messages/1024403069)

**Comment by ebruchez** [comment]
Could plain CSS be used to handle the TOC position?

**Comment by ebruchez** [comment]
It looks like [`position: sticky`](https://caniuse.com/#feat=css-sticky) might be what we need, but it's not supported at all with IE. [`position: fixed`](https://caniuse.com/#feat=css-fixed) is.

**Comment by ebruchez** [comment]
There is at least [one polyfill](https://github.com/wilddeer/stickyfill).

**Comment by ebruchez** [comment]
`position: sticky` appears to work with Chrome when applied in the right spot. Next step would be to try a polyfill for other browsers.

**Comment by ebruchez** [comment]
- [ ] try polyfill
- [ ] Safari: need `-webkit-` prefix
- [ ] don't enable on mobile (one-column layout), or TOC moves up/down a little bit

**Comment by avernet** [comment]
@ebruchez mentioned that he added `<xh:div class="fr-toc-inner">` line 422 that he's testing with `.fr-toc-inner { position: sticky; top: 0 }`.

**Comment by avernet** [comment]
Implemented in 747f40e4a08dca9e0156de14af60a644bda2079a. We support this in browsers that properly implement the `position: sticky`, namely Chrome, Firefox, and Edge, but not Safari (as of 11.1) or IE.
