### ISSUE TITLE
Safari mobile: PDF button doesn't show PDF

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3224]
Works with Chrome on iOS. Not sure if it's related to #3219 or if Safari mobile blocks the response.

**Comment by ebruchez** [comment]
Seems to be a regression. Check again after #3219 is fixed.

**Comment by ebruchez** [comment]
Unfortunately, this is still present now that #3219 is fixed.

**Comment by avernet** [comment]
Safari takes an attempt to run a form POST with a `target` as an attempt to open a pop-up, and blocks it. This can be disabled in the Safari settings, in which case Safari still shows:

![screen shot 2017-06-05 at 4 03 16 pm](https://cloud.githubusercontent.com/assets/106961/26807005/9419517a-4a08-11e7-86a6-0f76d7e1cecf.png)

I also don't like sites opening pages in new windows, but this is maybe one of the only cases where I find in acceptable. It is arguable whether this provides enough of a rational to always open the PDF in the current window (users can always hit back in the their browser if they wish to go back to the form), however it seems better to avoid a chance done solely for implementation reasons.

So we resolved to, in JavaScript, on Safari Mobile to ignore the `target` in 2-pass submissions.
