### ISSUE TITLE
fr:number: use round() instead of round-half-to-even()

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3226]
See [discussion on StackOverflow](https://stackoverflow.com/questions/44304839/orbeon-xforms-round-when-formatting-true).

**Comment by ebruchez** [comment]
Possibly, we could backport the Saxon 8.7 `round()` function with a scale to our implementation. It seems fairly easy. Then we can use `round(arg, precision)` from `fr:number`.

**Comment by oikonomopo** [comment]
Any current workaround?

**Comment by ebruchez** [comment]
I cannot think of a workaround. It seems that the solution will require making changes to [`number.xbl`](https://github.com/orbeon/orbeon-forms/blob/fb05c2521c8c8184a71c55b78259f9abbe38e9e7/form-runner/jvm/src/main/resources/xbl/orbeon/number/number.xbl).

**Comment by ebruchez** [comment]
Did this as part of #3453.
