### ISSUE TITLE
Change default for javascript-at-bottom

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3252]
See [Best Practice: Where to include your <script> tags](https://teamtreehouse.com/community/best-practice-where-to-include-your-script-tags).

We should:

- [x] change the default of `oxf.xforms.resources.javascript-at-bottom` to `false`
- [x] add the `defer` attribute to all the scripts we load
- [x] check the proxy portlet's script output as well
- [x] doc
- [x] ~~check things still work with IE9 (or not, see #3380)~~
  - Not doing it since we won't support IE9 anymore.
- [x] ~~consider whether `async` could be used instead~~
  - I don't think we need to look at `async` right now but we can revisit in the future.

**Comment by avernet** [comment]
That comment on IE9 sometimes not executing the `<script defer>` in the right order is a bit worrisome. If we go this route, this calls for us digging into the conditions under which the scripts are not always executed in the right order, as simple testing might not uncover those cases. And hopefully those cases don't apply to us (e.g. if it only happens when scripts are loaded from different servers).

**Comment by ebruchez** [comment]
We are on the verge of not supporting IE9 anymore. But an easy fix would be to sniff for IE9 and not output `defer` in this case.

**Comment by ebruchez** [comment]
According to [this](https://www.netmarketshare.com/browser-market-share.aspx?options=%7B%22filter%22%3A%7B%22%24and%22%3A%5B%7B%22deviceType%22%3A%7B%22%24in%22%3A%5B%22Desktop%2Flaptop%22%5D%7D%7D%5D%7D%2C%22dateLabel%22%3A%22Custom%22%2C%22attributes%22%3A%22share%22%2C%22group%22%3A%22browserVersion%22%2C%22sort%22%3A%7B%22share%22%3A-1%7D%2C%22id%22%3A%22browsersDesktopVersions%22%2C%22dateInterval%22%3A%22Monthly%22%2C%22dateStart%22%3A%222016-05%22%2C%22dateEnd%22%3A%222017-11%22%2C%22plotKeys%22%3A%5B%7B%22browserVersion%22%3A%22Internet%20Explorer%209%22%7D%5D%2C%22segments%22%3A%22-1000%22%7D) IE9 is at around 0.62% market share right now.

![screen shot 2017-12-01 at 2 55 38 pm](https://user-images.githubusercontent.com/105769/33507157-07f8c720-d6a8-11e7-93ee-bb1eb0b2052d.png)
