### ISSUE TITLE
Form Builder sometimes converts HTML entities in labels into unicode characters

### ISSUE THREAD

**Issue by ajw625** [orbeon/orbeon-forms#3263]
I created a form that has several fields with labels that have the HTML checkbox checked. Into each field I've entered the HTML entity `&#x2714;` (heavy checkmark). The checkmark is then displayed in FB, which is fine. But if I look at the source, some of these entities have been converted into unicode characters. I'm guessing this conversion was intended for display only and not to be saved because if I've entered an entity, then that's what I would prefer to be saved in the source.

See screenshots. Tested on demo.orbeon.com.

![image](https://user-images.githubusercontent.com/9143532/27193954-ac21b99c-51b5-11e7-9cf9-b1871f25dab2.png)

![image](https://user-images.githubusercontent.com/9143532/27194109-360d079c-51b6-11e7-8334-c5d60b422a65.png)

**Comment by avernet** [comment]
I have tried to reproduce this, but it seems to work, or at least work the way I expected it to. If I enter `&#x2714;` in a label, the value shows as-is, both in Form Builder and the published form. If I enter the same value, but mark it as HTML, the checkmark shows ( ✔), again both in Form Builder and at runtime. Did you expect a different behavior? Or are you testing something different?

**Comment by ajw625** [comment]
@avernet The issue is not with what gets displayed in Form Builder or at run time. It's that the source is inconsistent. Sometimes it keeps the HTML entity that I entered and sometimes that is converted into a the check mark character itself within the source (as my screenshot of the source shows).

I did a bit more testing and found that this seems only to occur when you make an edit to a label that already has the check mark entity. It's at that point that Form Builder is converting the entity into the check mark character within the source.

For example:

1. Enter `&#x2714;` in a label
2. View the source for that label and you will see `&#x2714;`
3. Edit the label to be "Alex &#x2714;"
4. View the source for that label and you will see "Alex &#x2714;" instead of `Alex &#x2714;`

In most cases this won't be a problem. I only ran into this because I copied and pasted the source into a text editor in order to do some search and replace (renaming a control). The text editor didn't recognize the &#x2714; and converted it to a question mark.

You may decide that this is not an issue and doesn't need to be fixed. I found it a bit odd and confusing though.

**Comment by avernet** [comment]
@ajw625 Got it. And as you suspected, we wouldn't consider this to be a bug. In the XML, you can either have a numeric character reference to a character or the character itself, and they are equivalent. I'll close this one, and thank you for taking the time to write in: when you're seeing something that doesn't sound right, it is always better to double check.

**Comment by ajw625** [comment]
OK. Thanks for the reply, Alex.
