### ISSUE TITLE
Option to rollback data modifications in case of process failure

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3301]
The customer's scenario is:

- attachments are saved successfully
- data is saved successfully
- process continues, for example with a custom `send`, but that fails
- attachment paths are not rolled back

[+1 from customer](https://3.basecamp.com/3600924/buckets/2016476/messages/362080931)

#3084 rolls back attachment paths if the data save fails.

**Comment by ebruchez** [comment]
Options:

1. custom `rollback` action
2. automatic rollback of data if the process fails

A number of side-effecting operations can happen during a process:

- modifications to the form's data:
  - `save` (attachment paths)
  - `xf:setvalue`
  - future: more actions (`xf:insert`, `xf:delete`)
- modifications to the form's metadata:
  - future: workflow `change-stage`
- modification to the runtime state
  - `set-data-status`
- navigation, showing messages
- event dispatches
- save attachments and data to database
- send attachments, data, metadata, PDF to external systems
- email
- and more

Some of those can be rolled back fairly easily:

- modifications to the form's data/metadata
- `set-data-status`

Some of those could be with some work:

- database operations
  - rollback database transaction
  - requires manual transaction start/end on well-defined boundaries:

Some are much harder if not impossible (email, once sent), although you could use a transaction API when calling external systems:

- send, email

So we could handle data/metadata/data status. Should we do this automatically, or require execution of an action in the process?

The problem with doing it automatically is that it changes the existing behavior. So that should probably be enabled explicitly if we provide the feature.

So maybe we start with a `rollback` action. In the future, this action could take parameters, such as `rollback(database = true)`.

**Comment by ebruchez** [comment]
Tasks:

- upon starting an outermost process, save data/metadata/data status
  - internal `transactionStart()`
- `rollback` action
  - restores saved data/metadata/data status
  - internal `transactionRollback()`

Q: Should we have a `commit` action at this point?

**Comment by avernet** [comment]
One difficulty of doing a rollback is that, right now, it isn't the process that it holding a connection (on which it can issue a commit or rollback), but the implementation of the persistence API. The implementation gets a connection from the pool when it is called, and returns it to the pool at the end of the call. If we forget for a second 3rd party implementations of the API, we could imagine some way for the API to "receive" or "return" or a connection, and it would then be the responsibility of the caller to commit it or roll it back. But I am not sure I like this, as it blurs the separation of concerns between the caller of the API and its implementation, and wouldn't support 3rd party implementations. It would seem cleaner to make this part of the persistence API, i.e. when the caller says it doesn't want auto-commit, the API would return a transaction id, which the caller needs to commit/rollback in a subsequent API call.

**Comment by ebruchez** [comment]
So for now, I suggest not handling rolling back database transactions.
