### ISSUE TITLE
Support Liferay DXP GA4

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3314]
Orbeon Forms 2017.1 supports Liferay DXP GA3, but it seems some APIs changed in GA4 leading to a `NoSuchElementException`. I'm marking this for 2017.2, but we should most likely backport this to 2017.1.x.

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/1966556/messages/649246685)

**Comment by ebruchez** [comment]
[+1 from user](http://discuss.orbeon.com/NoSuchElementException-getting-OrganizationLocalServiceUtil-class-td4662819.html)
