### ISSUE TITLE
FB: Allow custom TinyMCE configuration for explanation editor

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3320]
The `fr:tinymce` components allows [overriding the configuration](https://doc.orbeon.com/form-runner/component/rich-text-editor.html), but in Form Builder it is not possible right now as TinyMCE is used directly and the default [`tinymce-config.js`](https://github.com/orbeon/orbeon-forms/blob/c495766a4e2bbb7836b80b70d032e14c8a1baa77/form-runner/jvm/src/main/assets/xbl/orbeon/tinymce/tinymce-config.js) is always used from [`actions.coffee`](https://github.com/orbeon/orbeon-forms/blob/c495766a4e2bbb7836b80b70d032e14c8a1baa77/form-builder/jvm/src/main/assets/forms/orbeon/builder/resources/cell/control-resources-editor/actions.coffee#L78). We could easily add a way to configure which TinyMCE configuration Form Builder should use.

[+1 from user](https://twitter.com/DunsfordMage/status/897411523655720960)

**Comment by avernet** [comment]
We could add a property to configure what config to use with Form Builder, for instance:

```xml
<property
    as="xs:string"
    name="oxf.fb.tinymce.config"
    value=""/>
```

By default, the value would be empty and when initializing the TinyMCE for Form Builder we would use `YAHOO.xbl.fr.Tinymce.DefaultConfig` (as done now), but if set, we would evaluate the value as a JavaScript expression, and use the result as the config.

**Comment by avernet** [comment]
To get the value of a property on the client-side, for XForms properties we rely on a global `opsXFormsProperties` set by the server-side. The client-side part is implemented in `xforms.js`, and this is a mechanism for `oxf.xforms.*` properties, so not something we'll want to use for a Form Builder specific property.
