### ISSUE TITLE
Orbeon dialog is shown in Chrome 59V but not working in Chrome 60V

### ISSUE THREAD

**Issue by tejareddy457** [orbeon/orbeon-forms#3328]
We have orbeon form implemented in project, When we edit an orbeon dialog is opened to enter some values. It was working successfully with Chrome 59.0 version.

Last month Chrome browser has update and it is updated to 60.0 version and the same code for orbeon dialog is not showing.

Request sent to orbeon is successfully and getting the response back but not showing in chrome browser.

Working as expected in Internet Explorer and Chrome 59.0 version.

Could any one please help on this issue .

Thank you in advance

**Comment by ebruchez** [comment]
This is a known issue with versions of Orbeon Forms up to version 4.4.0. See [this discussion](http://discuss.orbeon.com/Chrome-60-breaks-Orbeon-3-9-td4662710.html) for steps.

**Comment by ebruchez** [comment]
Closing as this is solved since January 2014 with Orbeon Forms 4.4.1.
