### ISSUE TITLE
Ability to configure Summary page buttons that run processes

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3347]
For instance, someone might want to run a process that runs the `send` process on the selected form data. Now that #3318 is implemented, doing this is much simpler, as the button just has to call that API and say "run the `send` process on the currently selected data".

[+1 from customer](https://3.basecamp.com/3600924/buckets/2010455/messages/713322605)

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/5300917/messages/2056849105)

**Comment by avernet** [comment]
[+1 from user](http://discuss.orbeon.com/Add-navigation-buttons-to-Summary-td4664788.html)

**Comment by ebruchez** [comment]
Noting that #3318 did get implemented.

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/7993860/messages/6178039850)

**Comment by avernet** [comment]
From #5214, marked as duplicate:

[+1 from user](https://stackoverflow.com/questions/70430719/custom-home-button-in-orbeon-form-builder-summary-page) for configuring the link for the Home button

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/7993860/messages/6358832008)

**Comment by ebruchez** [comment]
For the latest +1, there is no need to run the process on data. Can we split the RFE into two steps:

1. Basic support: add `oxf.fr.detail.process.*.*` properties and run process without data
2. Add support for running in context of selected row data

**Comment by ebruchez** [comment]
`SimpleProcessCommon` currently creates an XPath context, using `formInstance`. We have to see how we handle that. It also accesses `fr-processes-instance` (which might be present in the Summary page?), and possibly more. So we should be ready for a few issues to pop up during implementation.

**Comment by ebruchez** [comment]
@avernet's thoughts:

We can have multiple types of processes on the summary page, in order of complexity:

1. Process like the one Eusebio need, that don't rely on any particular row being selected or any data (e.g. navigate to `/new`)
2. Process that require exactly 1 row being selected, but just need metadata about that row (e.g. navigate to `/edit`)
3. Process that requires 1 or more rows selected, and still just need metadata (e.g. delete)
4. Variations of (ii) and (iii), but that require the actual data, maybe implemented using a background process

Again, for now we only to support 1.

Maybe the process "type" should be indicated somehow (e.g. as part of the property name, or with a separate property)
After doing 1, it would be nice to do 2 and 3 so we can implement the existing buttons with processes

**Comment by ebruchez** [comment]
- [ ] `fr:process-button` currently hardcodes the `oxf.fr.detail.process` property prefix. Use `oxf.fr.summary.process` when in the SUmmary page

**Comment by ebruchez** [comment]
On the detail page, we have a fairly complex system to produce the buttons. It would be good to be able to reuse that. It repeats over:

- `<fr:process-button>`
- `<fr:drop-trigger>`

The Summary page repeats over:

- `<fr:href-button>` (for `'pdf', 'tiff', 'excel-export', 'xml-export'`)
- `<xf:trigger>`

**Comment by ebruchez** [comment]
- [ ] create reusable `fr:buttons-bar` component
    - [ ] basic support to work with detail page
    - [ ] support for `fr:href-button` if needed
    - [ ] figure out how to support dynamically enabling/disabling buttons in Summary page

**Comment by ebruchez** [comment]
We already support showing/hiding and enabling/disabling buttons in the detail page using using XPath. This is evaluated in the context of the data:

```xpath
xxf:instance('fr-form-instance')/xxf:evaluate($enabled-expression)
```

On the Summary page, we have some logic to control the following:

- `home`: no condition
- `print`/`review`
    - `$view-enabled`: `count($documents-selected)  = 1 and $documents-can-view`
- `pdf`/`tiff`/`excel-export`/`xml-export`
    - logic to disable non-PE features
    - enabled: `$view-enabled and $selection-data-or-draft = 'data'`
    - `fr:href-button`
- `test`: not supported
- `delete`
    - `count($documents-selected) != 0 and $documents-can-delete`
- `import
    - `$new-visible`: `$global-operations = ('*', 'create') and not($singleton-limit-reached)`
- `new`
    - `$new-visible`: `$global-operations = ('*', 'create') and not($singleton-limit-reached)`
- `duplicate`
    - more complex logic to enable

**Comment by ebruchez** [comment]
For now, the code supports running processes, but not "on selected data".

- [ ] enter separate bug for acting "on selected data"
- [ ] doc

**Comment by ebruchez** [comment]
[Doc](https://doc.orbeon.com/form-runner/advanced/buttons-and-processes/summary-page-buttons-and-processes#custom-process-configuration)
