### ISSUE TITLE
Method not found on Sierra in dev mode

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3350]
This is because we override `PathMap` and that used to be found before the same class in Saxon. But it seems that with Sierra, the Saxon JAR is found first.

`build.xml` removes `PathMap` from Saxon, but that doesn't run when we do this with sbt. Can we do the same with sbt? We copy JAR files to the `webapp` directory in our own `OrbeonWebappPlugin`, and no filtering happens there. We could add a filter configuration. Or use `webappPostProcess`?

This wouldn't solve the issue of unit tests, but maybe the classpath order is better there?

**Comment by avernet** [comment]
As a temporary workaround, replace `lib/runtime/saxon-9-1-0-8_orbeon_20160615.jar` with the same file from `WEB-INF/lib` inside the [2017.1.1 war](http://www.orbeon.com/download).

**Comment by avernet** [comment]
I temporarily pushed a jar without the classes we override as workaround for this. Once this is fixed, we can reinstate the original jar.

**Comment by ebruchez** [comment]
The root issue is that Saxon comes with an implementation of `PathMap`, but we made changes to that implementation within our own source code rather than within the Saxon source code. We can't just remove `PathMap` from Saxon right now as it is referred to by expressions so Saxon won't compile without it.

Externalizing the implementation and using #3296 would solve the problem better.

In the meanwhile, we *could* decide not to include `PathMap` in the Saxon JAR, but then this would mean that the Saxon JAR couldn't be used independently (which might be fine). Better wait for #3296?

**Comment by ebruchez** [comment]
Currently, our Saxon 9 build [doesn't include `PathMap`](https://github.com/orbeon/saxon/blob/a4626186766667a599ff23da0943b49f05819484/build.sbt#L20) anymore. So we can close this.
