### ISSUE TITLE
For drop-downs populated by Service/Action, enumeration restrictions sometimes exist in the schema

### ISSUE THREAD

**Issue by ajw625** [orbeon/orbeon-forms#3356]
I have two forms (background and personnel). I have simplified them so each has a single section with a single repeating grid. Each grid has one or two drop-down controls that are populated via an HTTP Service and an Action. I am seeing different behaviour when generating the schema for each of these forms. In the background form's schema, the drop-down control has a `<xs:restriction>` with an `<xs:enumeration>`. See schemas below. I have also attached the form definitions.

In the personnel form's schema, neither of the drop-down controls have the restriction. Since we cannot know the enumeration of values at design time, it is correct that the restriction should not be there. I expect Orbeon must have rules specifically preventing the restriction from being included for drop-down controls that are populated by a service. So the question is why is the restriction being included in the background form schema? There must be some difference between these two forms that I'm not seeing.

1. Is this a bug that needs to be fixed? It does seem that way to me.
2. Is there a workaround, a change that I can make to the background form to prevent the restriction from being included? I need this because it is causing errors which make the form unusable.

**Background Form Schema**

    <?xml version="1.0" encoding="utf-8"?>
    <xs:schema xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" xmlns:xf="http://www.w3.org/2002/xforms" xmlns:xs="http://www.w3.org/2001/XMLSchema">
      <xs:element name="form">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="paras.background_.nonArchaeologicalApplications_">
              <xs:complexType>
                <xs:sequence>
                  <xs:element maxOccurs="unbounded" minOccurs="1" name="paras.background_.nonArchaeologicalApplications_.nonnrsosApplications">
                    <xs:complexType>
                      <xs:all>
                        <xs:element name="paras.background_.nonArchaeologicalApplications_.nonnrsosApplications.type">
                          <xs:simpleType>
                            <xs:restriction base="xs:string">
                              <xs:enumeration value="" />
                            </xs:restriction>
                          </xs:simpleType>
                        </xs:element>
                        <xs:element name="paras.background_.nonArchaeologicalApplications_.nonnrsosApplications.applicationID"></xs:element>
                      </xs:all>
                    </xs:complexType>
                  </xs:element>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:schema>

**Personnel Form Schema**

    <?xml version="1.0" encoding="utf-8"?>
    <xs:schema xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" xmlns:xf="http://www.w3.org/2002/xforms" xmlns:xs="http://www.w3.org/2001/XMLSchema">
      <xs:element name="form">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="paras.archaeologicalPersonnel_">
              <xs:complexType>
                <xs:sequence>
                  <xs:element maxOccurs="unbounded" minOccurs="1" name="paras.archaeologicalPersonnel_.cultureAreas">
                    <xs:complexType>
                      <xs:all>
                        <xs:element name="paras.archaeologicalPersonnel_.cultureAreas.area"></xs:element>
                        <xs:element name="paras.archaeologicalPersonnel_.cultureAreas.names"></xs:element>
                      </xs:all>
                    </xs:complexType>
                  </xs:element>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:schema>

[orbeon-drop-down-issue.zip](https://github.com/orbeon/orbeon-forms/files/1392012/orbeon-drop-down-issue.zip)

**Comment by ajw625** [comment]
Also, I tried removing the services and actions from the personnel form and this makes no difference to its schema. I thought that removing them might cause a restriction/enumeration to be included, but it did not.

**Comment by avernet** [comment]
Adding `appearance="dropdown"` on your `<xf:select1>` will solve this problem for you. However looking into this revealed a regression: our code now never generates restrictions with `appearance="dropdown"`. I've created #3362 for that.

**Comment by ajw625** [comment]
Thanks Alex. Adding `appearance="dropdown"` the `<xf:select1>` does solve the problem. I also need to ask:

Some of the drop-downs in our forms are not `<xf:select1>`. They are `<fr:dropdown-select1>`. I don't know why there are two different types or how we ended up with different ones in the source. We have found that adding `appearance="dropdown"` to the `<fr:dropdown-select1>` does not fix the issue, but we can change it to `<xf:select1>` and it works. I guess the bug with schema generation does not exist for `<fr:dropdown-select1>`.

If I add a drop-down to a form, it is a `<fr:dropdown-select1>`. I'm not sure how we ended up with any `<xf:select1>`. I don't know how we ended up with this inconsistency in the source. My guess is that some forms were created before we did our last upgrade of Orbeon and then the you changed the left menu to add  `<fr:dropdown-select1>` instead of `<xf:select1>`. Is that right? We are currently running 2016.2.1.

**Comment by avernet** [comment]
Form Builder used to generate `<fr:dropdown-select1>`, this before Orbeon Forms had a way to bind an XBL control to an appearance. Now `<xf:select1 appearance="dropdown">` is the same as `<fr:dropdown-select1>`, and this is what is being used. So it's possible that with the version you have, you need `<fr:dropdown-select1>` instead of `<xf:select1 appearance="dropdown">`.

**Comment by ajw625** [comment]
OK. Thanks, Alex. `<xf:select1 appearance="dropdown">` seems to work fine with the version we're running so I think we'll stick with that.
