### ISSUE TITLE
Use font awesome to replace all Bootstrap icons

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3369]
Form Builder now uses font awesome, but Form Runner only uses this in some places. Areas to cover:

- [x] grid
- [x] buttons
- [x] pagination (Summary, Home, Wizard)
- [x] Summary page
- [x] Home page
- [x] status icons
- [x] drag and drop "hamburger"

**Comment by avernet** [comment]
Consider using [Nerd Fonts](http://nerdfonts.com), which includes Font Awesome, but also has other fonts, notably those those from [Material Design](https://material.io/tools/icons/).

**Comment by ebruchez** [comment]
And/or consider upgrading to [Font Awesome 5](https://fontawesome.com/how-to-use/upgrading-from-4).
