### ISSUE TITLE
Review use of HTML elements in ControlLabelHintTextEditor

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3409]
This code can definitely not work as the grids use `<div>`s:

```scala
resourceEditorCurrentLabelHint =
    if (repeat.is("*"))
      repeat.find(
        "thead tr th:nth-child(" +
          (container.index() + 1) +
          ") .xforms-label, tbody tr td:nth-child(" +
          (container.index() + 1) +
          ") .xforms-text .xforms-output-output")
    else
      container.find(".xforms-label, .xforms-text .xforms-output-output").first()
```

Following #2738.

**Comment by avernet** [comment]
This is now in `ControlLabelHintTextEditor.scala`, runs when a new control was added attempting to find the label, so we can right away open the editor. And indeed, this isn't working anymore when the control is added to a repeated grid. This issue was already present in 2017.2.

**Comment by avernet** [comment]
Also cherry-picked for `2017.2-pe`.
