### ISSUE TITLE
Form Builder to support leases

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3414]
With Orbeon Forms 2017.2, Orbeon Forms supports document leases. While the mechanism should be the same for Form Builder, we probably need to adapt the UI to Form Builder.

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/2192969/messages/2787351218)

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/7993860/messages/6290497141)

**Comment by obruchez** [comment]
We should not allow read-only mode in Form Builder.

**Comment by avernet** [comment]
> We should not allow read-only mode in Form Builder.

Or at least before #5056 is implemented.

**Comment by obruchez** [comment]
- [ ] doc

**Comment by obruchez** [comment]
See #6353 as well.
