### ISSUE TITLE
Publish dialog doesn't show "Comment" textarea and version override dropdown

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3422]
To reproduce, set `properties-local.xml` to use a relational database, create a form in Form Builder, click the Publish button, and notice how the dialog is missing the comment textarea.

This is done in `dialog-publish.xml` with a `<xf:group ref=".[$versioning-supported]">` around the textarea. Since `$versioning-supported` is true, and the textarea doesn't show even when the predicate is removed, I suspect this might be due to the `xf:group` being inside a `fr:grid`, and something could have changed with the `fr:grid` that breaks this.

**Comment by ebruchez** [comment]
It definitely won't work with `<xf:group>` around `<xh:tr>`. I am moving the groups around `<fr:grid>`s.
