### ISSUE TITLE
Label disappears when clicking quickly

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3449]
From [user](https://mail.google.com/mail/u/0/#inbox/160eaaff744d4383):

> I set a label for a field (like text field) and then click right away on the settings button to set for instance the field as mandatory, the label disappears after I click on the Apply button.

**Comment by avernet** [comment]
I also reproduced this.

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/5085006/messages/895811045)

**Comment by ebruchez** [comment]
This is happening because of the order of events sent by the client:

```xml
<xxf:event name="xxforms-rpc-request" source-control-id="#document">
    <xxf:property name="id">4</xxf:property>
    <xxf:property name="path">org/orbeon/builder/rpc/FormBuilderRpcApi/controlEditDetails</xxf:property>
    <xxf:property name="args">{&quot;controlId&quot;:&quot;fb≡section-1-section≡grid-1-grid≡control-1-control&quot;}</xxf:property>
</xxf:event>
<xxf:event name="xxforms-rpc-request" source-control-id="#document">
    <xxf:property name="id">5</xxf:property>
    <xxf:property name="path">org/orbeon/builder/rpc/FormBuilderRpcApi/controlUpdateLabelOrHintOrText</xxf:property>
    <xxf:property name="args">{&quot;controlId&quot;:&quot;fb≡section-1-section≡grid-1-grid≡control-1-control&quot;,&quot;lhha&quot;:&quot;label&quot;,&quot;value&quot;:&quot;abcwef&quot;,&quot;isHTML&quot;:false}</xxf:property>
</xxf:event>
```

So the first event to be dispatched is the click on the settings icon, and the second one is the update to the label.

Could we just `setTimeout` the click on the Control Settings icon to ensure that any other pending events are processed first? Not sure if that can have any other drawbacks. And even if we do that, couldn't the event still be first in line?
