### ISSUE TITLE
Switch to the Closure compiler to generate source maps

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#345]
Specifically:
1. Use the [Closure compiler](https://developers.google.com/closure/compiler/) instead of the YUI compiler for JavaScript, enabling [source maps](http://www.html5rocks.com/en/tutorials/developertools/sourcemaps/).
2. Allow only the JavaScript to be compiled/combined, leaving CSS as-is, as source maps are not supported for CSS by any compiler as of this writing, including Google's own [Closure stylesheet compiler](http://code.google.com/p/closure-stylesheets/).
3. Add dev-mode property to have the compilation/combination re-done on the server if any of the source files changed.

_Update 2013-04-11_: Loading is now fast with non-combined resources. The main reason to support source maps in combined/minimized code would be to make it easier to find where the error is in the code based on a stack trace sent by a customer. ~~This will allow us to make changes in JavaScript and reload the page much faster, while keeping the file/line info in the Chrome Dev Tools.~~

**Comment by ebruchez** [comment]
We now use UglifyJS to compress JavaScript files, and this produces source maps. Files compiled with less also produce source maps. As noted, not sure how useful that is but I am marking this as closed.
