### ISSUE TITLE
TinyMCE 4 issues with Liferay

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3473]
The upgrade to TinyMCE 4 (#1753) might have broken some "hacks" we had in place to make TinyMCE work with Liferay, and the purpose of this issue is to make sure we thoroughly test TinyMCE with Liferay, and fix potential issues we might find while doing so.

**Comment by ebruchez** [comment]
- [ ] test proxy portlet with Liferay 7 to make sure TinyMCE 4  works

**Comment by ebruchez** [comment]
- [ ] `tinymce.woff` (and `tinymce.ttf`) is not found because accessed at `/web/guest/fonts/tinymce.woff`

**Comment by ebruchez** [comment]
Outside of Liferay, it gets:

```
/e0bf0f75ed7a04a6a4427c41529d66a73ea84ae9/xbl/orbeon/tinymce/js/tinymce/skins/lightgray/fonts/tinymce.woff
```

**Comment by ebruchez** [comment]
The `.woff` file is loaded from CSS:

```
/web/guest/form-runner?p_p_id=orbeonformsproxyportlet_WAR_proxyportlet_INSTANCE_Hwv0RbB7M43X&p_p_lifecycle=2&p_p_state=normal&p_p_mode=view&p_p_cacheability=cacheLevelPage&p_p_resource_id=%2Fe0bf0f75ed7a04a6a4427c41529d66a73ea84ae9%2Fxbl%2Forbeon%2Ftinymce%2Fjs%2Ftinymce/skins/lightgray/skin.min.css
```

The CSS appears loaded dynamically, and its content is not rewritten (`url('fonts/tinymce.woff')  `).

**Comment by ebruchez** [comment]
The CSS is not loaded via `XFormsResourceServer`, which explains why the CSS is not rewritten. Similar issue with #2119.

**Comment by ebruchez** [comment]
It also loads `content.min.css`.

I am not sure how it worked with the previous version of TinyMCE. I don't see a mention of CSS in #258, but in the commits, we have:

```
editor_css: "" // don't let the editor load CSS because that fails in portlets
```

Can we do something similar and just load the CSS of the theme statically?

**Comment by ebruchez** [comment]
Actually, we have a [comment exactly about that](https://github.com/orbeon/orbeon-forms/blob/6fb18a4f75fcdcb6f47205f84ddb54f52a38e3c1/form-runner/jvm/src/main/resources/xbl/orbeon/tinymce/tinymce.xbl#L60) in `tinymce.xbl`.

**Comment by ebruchez** [comment]
Updated [`fr:tinymce` doc](https://doc.orbeon.com/form-runner/component/rich-text-editor)
