### ISSUE TITLE
HTTP Service Editor to show XML converted from JSON

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3474]
When calling a service that returns JSON, that JSON is converted to XML, but it is often hard for form authors to figure what this XML exactly looks like so they can write XPath to extract information from it. To help with that, this RFE calls for the HTTP Service Editor to show that XML document in the Test Result tab either in addition or instead of the JSON.

[+1 from user](http://discuss.orbeon.com/How-to-feed-a-dynamic-dropdown-with-a-rest-service-which-send-application-json-td4663126.html)

**Comment by vicaed** [comment]
Thanks you Alex, for sure it will be very helpful.

**Comment by evlist** [comment]
+1 from customer !

**Comment by evlist** [comment]
An easy enough workaround when you need to see the JSON converted to XML in FB/FR in an HTTP service is to:

1) add a "save to dataset" named (for instance) "json-ds" response action to an action using this service
2) add a textarea with a calculated value set to `xxf:serialize(fr:dataset('json-ds'), 'html')` 

When your action will be executed, the resulting XML document will then be shown in the textarea.

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/5300917/messages/1589514732#__recording_1591349309)

**Comment by ebruchez** [comment]
Suggesting to show the XML transformation of the JSON in the "Test Results" tab of the dialog as well.

**Comment by ebruchez** [comment]
[Documented](https://doc.orbeon.com/form-builder/advanced/services-and-actions/http-services#xml-view-of-JSON-responses)
