### ISSUE TITLE
JavaScript error when using `xf:dialog` inside `xf:repeat`

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3491]
To reproduce the JavaScript error, run the standalone [form.xhtml](https://github.com/orbeon/orbeon-forms/files/1769211/form.txt) and click on the "Insert Element1" button.

[+1 from user](https://stackoverflow.com/questions/49015374/exception-in-client-side-code-when-xxformsdialog-is-within-an-xformsrepeat)

**Comment by ewg118** [comment]
To confirm, is this fix present within Orbeon 2017.2.1?

**Comment by avernet** [comment]
@ewg118 Yes it is in 2017.2.1 PE. On the right hand of the issue, you can see what "project" has been assigned to the issue: for this particular issue, you can see that it has been assigned to the 2017.2.1 and 2018.1 "projects", which (unless we made a mistake!), means it will be in the corresponding builds.
