### ISSUE TITLE
Service / API to produce PDF from data

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3493]
We have user-facing URLs of the form:

```
/fr
  /orbeon
  /bookshelf
  /pdf
  /2ae8a9c1c01feee5cfcd52e06ea2ec53f6e95d5e
  ?fr-language=en
```

But we don't have a service URL for that.  This URL:

```
/fr
  /service
  /orbeon
  /bookshelf
  /pdf
  /2ae8a9c1c01feee5cfcd52e06ea2ec53f6e95d5e
  ?fr-language=en
```

returns an XML document likes this:

```xml
<url>
/xforms-server/dynamic/2f1e0f5b1c659dfe2b260c99e52ea7b423821760
</url>
```

But that too is a user-facing URL and might be protected by a login page or at least the user session.

So we need a different path or a URL parameter designed to obtain the PDF binary directly.

[+1 from customer](https://mail.google.com/mail/u/0/#inbox/161d7ced1600d4cb)

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/7060934/messages/1009190159)

**Comment by avernet** [comment]
[+1 from user](http://discuss.orbeon.com/Appending-form-PDF-using-Orbeon-td4663514.html)

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/7545500/messages/1433685870#__recording_1438463523)

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/2192969/messages/1706558951)

**Comment by ebruchez** [comment]
[+1 from customer](https://mail.google.com/mail/u/0/#inbox/FMfcgxwGDDnSGVxMcBRJQxqHKsvcrkTj)

**Comment by ebruchez** [comment]
Not-so-great workaround:

- call existing PDF service
- call back with JSESSIONID and path to `/xforms-server` returned

But this is more complicated and will create more sessions and temporary files than needed, as this could be stateless.

**Comment by ebruchez** [comment]
Since we have already used the `/pdf/` part of the path to indicate, in fact, "return a stateful PDF URL", what would the service path look like? Options:

- add a URL parameter
    - `result-format=pdf-url|pdf`, with `pdf-url` being the default for backward compatibility
- use a different mode token, for example `/pdf-file/` instead of `/pdf/`

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/16915667/messages/4428263874)

**Comment by ebruchez** [comment]
An alternative would be to use the `/export/` path and `export-format=pdf|tiff`. However, the issue to map this URL to the current `/pdf/` page.

**Comment by ebruchez** [comment]
- `/export/` would be ideal
- `/pdf/` with a URL parameter is easy to implement

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/5085006/messages/6459088638)

**Comment by ebruchez** [comment]
RESOLUTION: Use `/fr/service/$app/$form/export/$document?export=format-pdf|tiff`.

- [ ] consider also `/fr/$app/$form/export/$document?export=format-pdf|tiff`
- [ ] doc

**Comment by ebruchez** [comment]
[Documented](https://doc.orbeon.com/form-runner/api/other-apis/pdf-api)
