### ISSUE TITLE
Copy section settings when inserting section template

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3495]
When inserting a section template, Form Builder creates a new section in the host form and put into that section the content of the selected section from the library. As a consequence, settings for that section, such as whether it is repeated or custom CSS classes, are ignored.

This RFE calls for copying over those properties to the section in the host form. Form authors will be able to change them, but they will be, by default, set as in the library.

**Comment by ebruchez** [comment]
See also #1757.

**Comment by ebruchez** [comment]
We need to consider:

- title and help
- CSS classes
- visibility and readonly formulas
- repeat settings

Upon updating section templates, I wonder if we can avoid showing the user a dialog asking what to do. For example, if the CSS classes are the same on the current form definition section and the section template, we are fine. But if they are different, what to do? Same with the other aspects of the section templates.

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/1966717/messages/1201371197#__recording_1250972333)

**Comment by avernet** [comment]
We should also keep the section name, if possible. For instance, if the section template is named `address`, when inserting it into the form, we should use the name `address`, if that name isn't already used somewhere else in the form. And if already used, we can go for `address-1`, or `address-2`, etc.

[+1 from customer](http://discuss.orbeon.com/Inserting-a-section-template-changes-its-control-name-td4664915.html)

**Comment by ebruchez** [comment]
[+1 from customer](https://mail.google.com/mail/u/0/#inbox/FMfcgzGwJmMRztPBTPszlVxDGsbHfWQf)

**Comment by ebruchez** [comment]
[+1 from customer](https://mail.google.com/mail/u/0/#inbox/FMfcgzGwJmMRztPBTPszlVxDGsbHfWQf)

**Comment by ebruchez** [comment]
One scenario is to have visibility depend on a data from the enclosing form using `//foo = 42`.

**Comment by ebruchez** [comment]
RESOLUTION: Copy values upon insert. User can update those in the enclosing form, and those will not remain synchronized if the library is modified and reloaded.

Q: How to include the pieces of information in the XBL, given that the XBL component is not the `fr:section`, but the content of it?

**Comment by ebruchez** [comment]
- [ ] find solution for metadata
    - new element, like `<section-template>`?
- [ ] `form-to-xbl.xsl` produces metadata
- [ ] Form Builder uses and copies metadata if present
- [ ] doc

**Comment by ebruchez** [comment]
For reference, this was also included on 2023.1.1.
