### ISSUE TITLE
Automatically produce CSS from LESS

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#351]
Subproject of #1585.
- When building, in `build.xml`, produce `.css` from `.less`
  - Right now, the `.less` files are produced in an ad-hoc manner and checked in
- At runtime, compile `.less` to `.css`
  - Do this for combined resources disabled and enabled
    - This makes it easier to debug CSS issues on IE, where we need to use combined resources

**Comment by ebruchez** [comment]
Done in 2016.3.
