### ISSUE TITLE
API to purge old data

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3520]
We have a [manual query](https://doc.orbeon.com/form-runner/persistence/purging-old-data.html), but an API would be much better.

[+1 from customer](https://3.basecamp.com/3600924/buckets/1966718/messages/964223126#__recording_966686762)

**Comment by acspike** [comment]
It would be helpful if the API made it possible to purge not only deleted data, but also superseded data (i.e. old versions for which there is a newer version saved).

**Comment by ebruchez** [comment]
Duplicate of #2886, closing.
