### ISSUE TITLE
Field-level form data encryption in the database

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3525]
- [x] *Encryption at the level of Orbeon Forms* – Encryption and decryption will happen at the level of Orbeon Forms, so the values of the fields marked as "to be encrypted" will never be sent to the database (let alone stored by the database).
- [x] *Form data* – When the value of a field is encrypted, in the form data the containing element will have the attribute `encrypted="true"`.
- [x] *Form Builder UI* – The "Control Settings" dialog will have a checkbox allowing form authors to mark a field for encryption.
- [x] *Persistence proxy* – The Form Runner "front-end" will always see unencrypted data, and it is up to the persistence proxy to encrypt and decrypt data as needed.  When saving data, the persistence proxy will encrypt all fields marked as "to be encrypted" in the form definition before passing the form data to a specific implementation of the persistence API. Conversely, when reading data, it will decrypt all the fields that have the attribute `encrypted="true"`.
- [x] *Form Runner homepage in admin mode* – On this page, admins will be able to select a form definition and trigger data re-encryption for that form. Re-encryption will use the search API to get a list of all the form data, and for each form data, will read it, encrypt or decrypt fields according to the form definition, and if any change is needed, will write the form data back.
* *Limitations* – On summary pages, encrypted fields won't be included in the free text search, and field search for encrypted fields will only be able to do exact matches.
* *Out of scope* – The ability to change a key is out of scope for this request for enhancement.

[+1 from customer](https://3.basecamp.com/3600924/buckets/1966718/messages/964223126#__recording_971644821)

**Comment by acspike** [comment]
+1

**Comment by ebruchez** [comment]
Where is the encryption key/password stored? `properties-local.xml`? A separate file? An API could also be contemplated.

**Comment by ebruchez** [comment]
We also need to consider encryption of existing data in the database. This would be a process accessible probably from the Home page and typically run once only. In addition, it would be nice if you could run a sanity check making sure that the fields that need to be encrypted actually are.

**Comment by avernet** [comment]
Here are few terms used to describe data that customers might want to encrypt:

- Personal information, more often used in the context of US law, which includes:
    - Personally identifiable information (PII)
    - Sensitive personal information (SPI)
- Personal data, more often used in the next of the GDPR

**Comment by avernet** [comment]
1. From the Form Runner home page, admins ask for a given `app/form` to be re-encrypted (for now we won't support re-encrypting `app/*` or `*/*`).
2. Based on the `app/form`, the persistence proxy dispatches the request to the appropriate implementation of the persistence API. Out-of-the-box, for now, we'll implement this only in the relational implementation of the API.
3. The implementation queries the data table to find all the versions of the `app/form` for which we have data. It then iterates over the `app/form/version`.
4. For a given `app/form/version`, it retrieves the form definition, iterates over the corresponding data, and for each runs `FieldEncryption.encryptDataIfNecessary()`, and writes back the result.

**Comment by ebruchez** [comment]
We defer Key management:

> Admins will be able to have different encryption keys per app/form. In the first implementation of this feature, keys will be stored in properties. In the future, we could support using keys from other sources, like a Java key store, or keys retrieved by calling the implementation of an API we provide, e.g. allowing Orbeon Forms to be integrated with a hardware key store.

See also #3631.

**Comment by avernet** [comment]
This is now documented:

- [Main page, for form authors](https://doc.orbeon.com/form-builder/advanced/field-level-encryption)
- [Re-encryption from the Form Runner home page, for admins](https://doc.orbeon.com/form-runner/features/home-page#re-encryption)
