### ISSUE TITLE
Orbeon 2017.1 CE Glassfish 4.1 : FB & FS "Error performing search."

### ISSUE THREAD

**Issue by langholloman** [orbeon/orbeon-forms#3535]
Dropped the 3 Orbeon war files into the Glassfish domain autodeploy directory. The asadmin startserv  ran successfully, and the apps were deployed. The orbeon/home loads correctly. The Form Builder FB Summary is displaying the create new form dialog, select "close" to take the view to the Summary table listing, then the "Error performing search" displays...this is the same for the Form Runner FR also.
I have added the info in the options referenced in the docs at: https://github.com/orbeon/orbeon-forms-doc/blob/master/installation/glassfish.md
This runs smoothly with Tomcat, but the requirement is to run in Glassfish 4.1. Here is the orbeon.log for when the attempting to view the FB Summary screen:
[orbeon.log](https://github.com/orbeon/orbeon-forms/files/1853841/orbeon.log)

**Comment by ebruchez** [comment]
It looks like an issue with connecting to the embedded eXist database. I would setup an [exernal database](https://doc.orbeon.com/form-runner/persistence/relational-db.html) like MySQL, since anyway using the embedding database is for demo purposes only. Then you will avoid that problem.

**Comment by langholloman** [comment]
I attempted using the following and still get the outcome. Can you double check the following for my use of PostgreSQL with the Glassfish server? Here's the configuration/updates I made:
**1.** Driver: Postgresql driver jar (postgresql-42.2.2.jar) is located at: ...glassfish\domains\domain1\lib
**2.** Datasource file located at: glassfish\lib\install\templates\resources\jdbc has the following:
    <resources>
    <jdbc-connection-pool 
        name="postgresql_type4_pool" 
        datasource-classname="org.postgresql.ds.PGSimpleDataSource"
        res-type="javax.sql.DataSource">
        <property name="user" value="postgres"/>
        <property name="password" value="******"/>
        <property name="url" value="jdbc:postgresql://localhost:5432/pg_orbeon?useUnicode=true&amp;characterEncoding=UTF8&amp;socketTimeout=30&amp;tcpKeepAlive=true"/>
    </jdbc-connection-pool>

    <jdbc-resource 
        enabled="true" 
        jndi-name="jdbc/postgresql_type4" 
        object-type="user" 
        pool-name="postgresql_type4_pool"/>
</resources> 

3. The orbeon properties-local.xml located at: glassfish\domains\domain1\applications\orbeon\WEB-INF\resources\config - has the following:
    <property as="xs:string" name="oxf.fr.persistence.provider.*.*.*" value="postgresql"/>

**Comment by ebruchez** [comment]
Do you see the exact same error in the logs?

**Comment by langholloman** [comment]
[orbeon_postgres_glassfish.log](https://github.com/orbeon/orbeon-forms/files/1857506/orbeon_postgres_glassfish.log) - see orbeon log -

**Comment by ebruchez** [comment]
Different error:
```
No object bound to name java:comp/env/jdbc
```
So there is an issue mapping the datasource.

**Comment by langholloman** [comment]
Any suggestions?

**Comment by ebruchez** [comment]
The key is to make sure that a `jdbc/postgresql` datasource is configured and available in GlassFish. We are not GlassFish specialists to say the least, but it seems to be where the problem lies right now.

**Comment by langholloman** [comment]
checking into that now, i'm going to try configuring jdbc postgres through the Glassfish Admin

**Comment by kelderek** [comment]
It seems that is just not the way of glassfish. https://docs.oracle.com/cd/E17952_01/connector-j-5.1-en/connector-j-usagenotes-glassfish-config-jsp.html

What I still don't understand is why uncommenting the DataSource resource-ref in web.xml isn't required for all database/appserver types.

**Comment by ebruchez** [comment]
@kelderek Did you eventually get this figured out?

**Comment by kelderek** [comment]
Since we got it to work in web.xml and sun-web.xml as described in the long post above, we haven't messed with it.  Based on the link I shared earlier, I don't think we are going to be able to get around doing it that way.  I think we can go ahead an close this issue.

**Comment by ebruchez** [comment]
Got it, thanks.
