### ISSUE TITLE
Background progress returns `true` even though process fails

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3546]
To reproduce:

- Add the property below.
- In Form Builder create a form with a field `first-name` marked as required.
- On the `/new` page for that form, enter a first name, save.
- Do a `POST` to `http://localhost:8080/orbeon/fr/service/a/a/edit/123`, where `123` is the document id of the form data.
- ⇒ Note save failed, since the first name is empty (good), however the response contains `<process-success>true</process-success>`, while one would expect `<process-success>false</process-success>`.

```xml
<property as="xs:string" name="oxf.fr.detail.process.after-controls.background.edit.*.*">
    xf:setvalue(ref ="//first-name", value = "''")
    then require-valid
    then save
 </property>
```

[+1 from user](http://discuss.orbeon.com/Embedding-the-Orbeon-Form-td4663214.html)

**Comment by ebruchez** [comment]
The `require-valid` process terminates the top-level process immediately with a `success` if there are validation errors, after running the `recover` block. 

Internally, `require-valid` is only used by `validate-all`, which is used by `validate` (as a synonym), `save-final`, `review`, `send`, `email`, `submit`.

**Comment by ebruchez** [comment]
So it looks like we need the ability for a *sub-process* to return a `failure` value. We have a placeholder for a `failure` action, but it's not implemented, and if it works like `success`, it would short-circuit the entire process all the way to the top.

**Comment by ebruchez** [comment]
When an outer process fails, we log this at error level and try to show an error to the user.

This means that we can't just have `require-valid` terminate the process with an error. We should probably instead:

- have a `failure` (or another name) action which is local
- add a `require-valid-or-fail` subprocess which can return a `failure`
- add a `require-uploads-or-fail` subprocess which can return a `failure`
- change callers
- update doc

**Comment by ebruchez** [comment]
As a workaround, the user can write:

```xml
<property as="xs:string" name="oxf.fr.detail.process.after-controls.background.edit.*.*">
    xf:setvalue(ref ="//current-time", value = "current-dateTime()")
    then validate("error")
    then save
</property>
```

What `require-valid` does in addition is not relevant for background validation.

So I am not sure we really need to change the `require-valid` process at this point.

**Comment by ebruchez** [comment]
In fact we had a similar issue with [this customer](https://3.basecamp.com/3600924/buckets/5085006/messages/888875364#__recording_936856127).

**Comment by ebruchez** [comment]
So we agreed to close this.
