### ISSUE TITLE
Can't navigate to new section showing up in wizard

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3547]
Import [this form](https://github.com/orbeon/orbeon-forms/files/1905921/form.txt) in Form Builder, test or publish, and notice that when selecting "Credit card", the "Credit card" section shows in the sidebar but we can't navigate to that section. Switch to "Bank account" and back to "Credit card", and you can navigate to the section.

**Comment by ebruchez** [comment]
We update section status only upon:

- `xxforms-constraints-changed`
- `xforms-disabled`
- `fr-section-shown` / initial section shown

Here, the section status changes when the value of the control changes. So we should:

- add `xforms-value-changed`
- make sure performance didn't regress with very large form

**Comment by ebruchez** [comment]
Confirming that adding `xforms-value-changed` solves this issue.

**Comment by ebruchez** [comment]
Checked that performance upon load and navigation doesn't appear to be changed with large customer form.
