### ISSUE TITLE
Restore XUpdate processor

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#355]
At least one user is depending on it.

Maybe we can package it as a separate, optional JAR?

Commit which removed it is df2bf34c2810e54fd45ece55ddf465c102d3cb7e.

**Comment by ebruchez** [comment]
@ricetrac I am curious to know whether having XUpdate is still relevant to you or others. It is still present in Orbeon Forms 2018.2.

**Comment by ricetrac** [comment]
Yes we still use it. It's more convenient to update an xml stream, than to use an "XSLT" processor.
"XSLT" is good when you create a new XML feed, but it's more complicated to update just a tag, for example: you have to think about copying all the other tags, and in terms of algorithm, it's more complicated for our developers.
