### ISSUE TITLE
Support serving web fonts in 2017.2 w/Glassfish

### ISSUE THREAD

**Issue by GameDevZach** [orbeon/orbeon-forms#3574]
Is this still supported as shown in issue #3138 ? I'm getting a 404 when attempting to load a font-face from the server using a path like the custom form css path
 `src: url('/forms/assets/fonts/OpenSans-Regular.WOFF') format('woff');`

**Comment by ebruchez** [comment]
Yes it is supported. The issue might be the uppercase extension. Try with a lowercase one to rule out another problem.

**Comment by GameDevZach** [comment]
That was it, thanks.
