### ISSUE TITLE
Issue Connecting orbeon-forms with SQL Server

### ISSUE THREAD

**Issue by wnorales** [orbeon/orbeon-forms#3575]
Hi 
Ive been trying to connect Orbeon-forms with my SQL Database for the past couple of days, however it will not pull down the data from the Database. I know the query is correct. Im running orbeon-forms with Tomcat
<img width="539" alt="capture11" src="https://user-images.githubusercontent.com/10760389/39444958-66e70012-4c87-11e8-96d9-500dfd0d1e9f.PNG">
<img width="300" alt="capture33" src="https://user-images.githubusercontent.com/10760389/39444961-684f8686-4c87-11e8-9044-c9982dd21cb2.PNG">

**Comment by ebruchez** [comment]
First issue I see if that your datasource is named `sqlserver` in Tomcat, and something else in the "Datasource" field. Unless there is a mapping somewhere, this is not going to work.

Also check both Tomcat logs and `orbeon.log` for errors.
