### ISSUE TITLE
Property to disable warning on close when data is dirty

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3584]
Right now the feature is always enabled; this Request for Enhancement calls for adding a property so admins can disable this feature if necessary.

[+1 from user](http://discuss.orbeon.com/Prompt-to-save-form-data-td4663425.html)

**Comment by avernet** [comment]
[+1 from user](https://3.basecamp.com/3600924/buckets/7873395/messages/1371473306#__recording_1374780128)

**Comment by ebruchez** [comment]
To be descriptive, the property name should be something like `oxf.fr.detail.warn-user-on-page-unload-when-data-unsafe`. A bit verbose, maybe?

**Comment by ebruchez** [comment]
- [ ] determine property name
- [ ] doc

**Comment by ebruchez** [comment]
[Documented](https://doc.orbeon.com/configuration/properties/form-runner/form-runner-detail-page#warning-the-user-when-data-is-unsafe)
