### ISSUE TITLE
Home page: ability to delete (unpublish) published form definition

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3597]
Right now, you can only make a form definition unavailable/available again. We would like the ability to actually remove it.

[+1 from customer](https://3.basecamp.com/3600924/buckets/5422190/messages/1082489866)

See also #750.

**Comment by ebruchez** [comment]
Copying comment from duplicate #4154:

Right now Orbeon Forms only supports making forms as unavailable, while in some cases admins might want to completely remove published forms. This could for instance be the case if the forms have been published by mistake, or, more generally, when admins know the forms won't be needed anymore and there is no need to keep them around.

This should be straightforward if we have no data for the forms to delete. If data exists, we might want to warn admins, and maybe offer the option to also delete the corresponding data.

[+1 from user](https://stackoverflow.com/questions/57437460)

**Comment by ebruchez** [comment]
+1 from me today.

If you publish a form definition version by mistake, even by making that version unavailable, you cannot go back to things being as if the form definition hadn't been published. For example `/new` will still try to reach the unavailable version (although it's unclear if this should be considered a bug or not - I was inclined to think so initially).

**Comment by ebruchez** [comment]
Following-up on my comment above I entered #4881.

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/18358270/messages/3857609114)

**Comment by ebruchez** [comment]
+1 from customer today

It might be that the backend is already supporting that, based on what I am seeing in the code.

- [ ] try `DELETE` on the API
- [ ] implement Admin page UI

**Comment by ebruchez** [comment]
Calling `DELETE` appears to work.

**Comment by ebruchez** [comment]
- [ ] doc

**Comment by ebruchez** [comment]
[Documented](https://doc.orbeon.com/form-runner/features/home-page#deleting-published-form-definitions)
