### ISSUE TITLE
Required autocomplete shows error on button click

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3611]
To reproduce, in Form Builder create a form, add an autocomplete, make it required, test, click on the field, click on the button, and notice how an error shows. The same car be reproduced with a fields date control. Marked as regression as it works with the version deployed on `demo.orbeon.com`, but fails with the latest code as of demo.orbeon.com, and also fails with 2017.2.2 PE.

[+1 from customer](https://3.basecamp.com/3600924/buckets/2016476/messages/1098240199)

**Comment by avernet** [comment]
Assigning to @ebruchez.

**Comment by ebruchez** [comment]
Check whether this is due to the fix for #3547, where we now check for `xforms-value-changed`.

**Comment by ebruchez** [comment]
This is due to the fix for #3508 instead: the internal `<xf:input>`, upon `DOMFocusOut`, is marked visited, but so are all its ancestor `XFormsValueComponentControl`, which includes the enclosing `fr:autocomplete`.
