### ISSUE TITLE
TinyMCE doesn't show at runtime

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3612]
Create a form with the Formatted Text Area, publish it, open the `/new` page , and notice the control doesn't show.

[+1 from user](http://discuss.orbeon.com/No-autosave-when-focus-stays-in-the-one-text-field-td4662387.html)

**Comment by avernet** [comment]
- Initialization flow
	- `tinymce.xbl` – `xf:action id="xf-ch"`` runs
	- `tinymce.js` – `init` gets called
- Investigation
	- The JavaScript function corresponding to the `xf-ch` handler
		- Is in `/xforms-server/form/static/123.js` (good)
		- Is never called (bad)
	- The `xf-ch` action does run
		- Reported as running in the `orbeon.log`
		- Changing it into an `<xf:message level="xxf:log-debug">`, we get the message logged properly
	- Problem seems to be that, somehow, even if the action runs, somehow the JavaScript isn't called

Assigning to @ebruchez.

**Comment by ebruchez** [comment]
I don't reproduce this. The control shows for me.

**Comment by ebruchez** [comment]
I tried with the wizard and without.

**Comment by avernet** [comment]
Have you tried with a CI build? I just tested this again this morning, getting the latest PE master build done by Travis, in Form Builder created a ne form, added a Formatted Text Area: it shows in Form Builder, but not when running the form with Test, or publishing and then opening the `/new` page.

**Comment by ebruchez** [comment]
The difference is that I had inline resources enabled locally, while they are not enabled by default. With this I do reproduce the problem.

So the issue is that we call `getServerErrors`, `getScriptsToRun`, `getMessagesToRun`, and `getLoadsToRun` when the dynamic JavaScript is called. However, at the time that happens, the document's `clearClientState` has been called already, so none of those are available.

**Comment by ebruchez** [comment]
Caused by #3565.

**Comment by ebruchez** [comment]
Solution:

- make the "client state" part of the XFCD's initial state
- clear that state *after* the first mutation of state
- make that state serializable

**Comment by ebruchez** [comment]
We already have case classes for that information (adding `Message`), but `StaticScript` is referenced needlessly. Maybe we should just store that state as a string, since the scripts are a string anyway.
