### ISSUE TITLE
Cannot drag cell boundary in repeated grid

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3615]
Compare screenshots below.

<img width="927" alt="out1" src="https://user-images.githubusercontent.com/105769/41183701-f47e8518-6b30-11e8-994f-daf1aa56e73f.png">

<img width="927" alt="out3" src="https://user-images.githubusercontent.com/105769/41183703-f6547ac8-6b30-11e8-9a6e-767a357424d8.png">

**Comment by avernet** [comment]
In `GridWallDnD.scala`, we are doing `frGridBody.css("grid-row-gap")` and expect a result like `6px`, but instead this returns `normal`. Here `frGridBody` points to a `div.fr-grid-body`. The `div.fr-grid-body`, both in the repeated and normal grids, are `display: grid`, but in the normal grid it has a `grid-gap: 1px`, while it doesn't in the repeated grid. Having the `grid-gap` explicitely defined for all cases solves this problem.
