### ISSUE TITLE
Clear doesn't… clear

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3644]
Create a new form in Form Builder, publish it, open the new page, enter something in the field, hit the "Clear" button, confirm, and notice the value isn't cleared.

[+1 from user](http://discuss.orbeon.com/clear-button-in-2018-1-pre-release-td4663640.html)

**Comment by ebruchez** [comment]
Regressed with f5ad21f73d0c5aa3ea2b5e4a992dea9fc1d6d537 for #3211.
