### ISSUE TITLE
Liferay proxy portlet randomly "swallowing" POST requests?

### ISSUE THREAD

**Issue by srinivas-os** [orbeon/orbeon-forms#3647]
Orbeon version 2016.2.1 (PE)

I'm trying to automate Orbeon form load/fill-up/save using JMeter. Basically, I send the same set of HTTP requests as a browser sends when filling up a form, from my script.

When submitting XForms event POST requests (triggered by focus or blur of a form field, for example) to the liferay orbeon proxy portlet, sometimes it doesn't seem to actually send the request to the Orbeon form runner instance. In such cases, I get back a 200 OK from the proxy portlet instance, but with an empty/zero-byte response body (instead of the usual xxf:event-response XML body). But on checking the access log of Orbeon server there's no request received at that time. Any subsequent XForms event request for the same form will return an "unexpected sequence number" error from Form Runner, perhaps further proving that the former request never reached orbeon. The form will also not save.

This is not consistently reproducible and happens without any fixed pattern. I suspected a clustering/LB/session-stickiness issue initially (because it is so random), but it happens with a non-clustered setup as well.

I am not sure if this is enough information for you, but I do not know where to go from here or what else I can add.

**Comment by ebruchez** [comment]
If this issue doesn't happen when end users are accessing the page, I fear that it might be an issue with the JMeter setup and I am not sure what we can do.

**Comment by srinivas-os** [comment]
Thanks @ebruchez. I'm currently analyzing our logs to see if this issue has happened via browser. However, if this had to do with JMeter setup, I'd expect it to occur every time or at least with some discernible pattern. But it is very random and unpredictable, though very frequent. 

In some test runs, it only happens for 1-2 JMeter users and works perfectly for other 10+ users. Sometimes it happens for all JMeter users. Even the form/field for which it happens (i.e. on whose event submission it happens) is not consistent.

**Comment by ebruchez** [comment]
[+1 from original customer](https://3.basecamp.com/3600924/buckets/8287464/messages/1173598227#__recording_1471462057)

**Comment by ebruchez** [comment]
Possible [+1 from customer](https://3.basecamp.com/3600924/buckets/7873395/messages/1743512684), where the original issue appears similar.

**Comment by ebruchez** [comment]
Steps:

1. Option to disable pooling in `ApacheHttpClient` for testing and see if the issue still reproduces when disabled.
1. Implement eviction for case where pool is used.
1. Switch to `PoolingHttpClientConnectionManager` (`PoolingClientConnectionManager` is deprecated).
1. Why does the HTTP client throw `NonRepeatableRequestException`?
1. Consider what to do when an uncaught HTTP client exception is thrown (`ClientProtocolException` caused by `NonRepeatableRequestException`).

**Comment by ebruchez** [comment]
- [ ] Q: Do we need to upgrade to the non-deprecated HttpClient APIs?

**Comment by ebruchez** [comment]
Check the [eviction code](http://hc.apache.org/httpcomponents-client-ga/tutorial/html/connmgmt.html#d5e418).

**Comment by ebruchez** [comment]
- [ ] initial implementation
- [ ] test initial
- [ ] make feature and delays configurable

**Comment by ebruchez** [comment]
[Properties](https://doc.orbeon.com/configuration/properties/general#expired-and-idle-connections) and [parameters](https://doc.orbeon.com/form-runner/link-embed/java-api#http-client-configuration) are documented.
