### ISSUE TITLE
New `date.xbl` that can be used by default in Form Builder

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3657]
Motivation:

- Make the component more modern and easier to extend, for instance adding a placeholder (#3617). To satisfy this requirement, the component will be based off the [bootstrap-datepicker widget](https://bootstrap-datepicker.readthedocs.io/en/latest/).
- Serve as an example for customers who would like to create their own date widget that uses another library (e.g. [WET date picker](https://wet-boew.github.io/wet-boew/demos/datepicker/datepicker-en.html) for projects done by or for the Government of Canada).

Tasks:

- [x] Update value from server
- [x] Show value using proper format, as set by properties
- [x] smart entry (see comment below)
- [x] mobile support (also see comments below)
- [x] update demo forms
    - [x] Controls form
    - [x] DMV-14 form
- [x] P1: support Form Runner language and switching language
- [x] Form Builder: convert date fields to the new one
- [x] consider #3367
- [x] work in repeated grids, depends on #3687 to be done by @ebruchez
- [x] works with automatic PDF
- [x] works with PDF templates (see also #3800)
- test
    - [x]  in repeated grids with inserts
    - [x]  in initially-hidden wizard pages
    - [x] placeholder localization on IE11 and Edge

**Comment by ebruchez** [comment]
Did you start work on this already?

**Comment by ebruchez** [comment]
Ok cool.

**Comment by ebruchez** [comment]
For mobile support, see also #3707. We need a better/reliable way. Can we simply produce the `type="date"` in all cases?

**Comment by avernet** [comment]
In the past we've avoided generating `type="date"` to prevent desktop browsers from trying to show their own datepicker, which goes from "annoying and useless" to "clearly inferior to what JavaScript libraries do", depending on how charitable you are in your assessment.

But browsers have gotten better at this (see [screenshots](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date)), so using the native datepicker, when supported, might not be entirely out of the question anymore.

**Comment by ebruchez** [comment]
That's better. We still have to decide whether we want more native behavior vs. uniform behavior. IE doesn't have support, and Safari desktop doesn't have support either.

**Comment by ebruchez** [comment]
Noticed that clicking on the "add-on" icon doesn't show the calendar. It's a bit unsettling as that's the first thing I tried to do.

**Comment by ebruchez** [comment]
If I enter "9/19", the field reverts to "9/18/2018". We need some level of smart entry support.

**Comment by ebruchez** [comment]
Added to TODOs above to make sure this works with PDF templates in particular (see #3800).

**Comment by ebruchez** [comment]
Latest thinking for handling migration:

- [ ] `annotate-migrate.xsl`: also migrate to `fr:time`
- [ ] add a property to enable "optimal width" for date, etc. controls, true by default
- [ ] template.xml has the property set to `false`
- [ ] set outer CSS class based on property
- [ ] adjust CSS of components
    - [ ] `fr:date`
    - [ ] `fr:time`
    - [ ] `fr:us-phone`
    - [ ] `fr:dateTime`
    - [ ] check old date, time and dateTime appear ok without migration at runtime
