### ISSUE TITLE
Make help more accessible

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3669]
Options:

- make the help icon tabbable, and opening the help dialog accessible
- use the [`aria-details` attribute](https://www.w3.org/TR/wai-aria-1.1/#aria-details)

[+1 from customer](https://3.basecamp.com/3600924/buckets/1977373/messages/1194574584)

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/2192969/messages/3491006780)

**Comment by ebruchez** [comment]
As discussed, making the help tabbable, at least by default, is not a great option. If the `aria-details` option works (which means that it is handled by screen readers), then it's preferable.

We could imagine, for non-impaired and impaired users alike, a keyboard shortcut to open the help when focus is on a control.
