### ISSUE TITLE
Initially non-relevant checkbox doesn't work with IE11

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3677]
This is not always reproducible.

- [+1 from customer](https://3.basecamp.com/3600924/buckets/6794635/messages/1237988939#__recording_1245947552)
- [+1 from customer](https://3.basecamp.com/3600924/buckets/1966555/messages/893281273)
- And I believe we have one more customer who reported that issue.

**Comment by ebruchez** [comment]
Since it isn't always reproducible, one idea was to try to replace the current code which creates a new radio button in JavaScript and rewrite it, say using jQuery, and see if that fixes the issue.

**Comment by ebruchez** [comment]
We tried reproducing this today again with IE11 on Windows 10 and Windows 7 under Liferay. The issue doesn't reproduce, which is consistent with earlier reports.

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/4224335/messages/1436664031#__recording_1436716804)

**Comment by avernet** [comment]
In the last commit I'm trying to make all the updates to the elements we are creating before inserting them in the DOM, trying to get around what seems to be a bug in IE11. We'll see with the customer if this helps.

**Comment by ebruchez** [comment]
Even though this is a tentative fix only, marking as closed. We can enter a new bug or reopen (would this be a good case where reopening makes sense?) if it turns out it is not actually fixed once we get feedback from users.
