### ISSUE TITLE
"Edit" button shows on view page for user without write permission

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3713]
1. Create a new form, enable permissions, allow anyone to create and read.
2. Open the `/new` page, save, go to the summary page, open the data ⇒ it open in view mode.
3. Click on the Edit button ⇒ the field becomes editable. We wouldn't want that Edit button to be present on this page if the user can't edit the data.

This was already the case with 2017.2.2.

**Comment by ebruchez** [comment]
We have some not-entirely-implemented-yet functions to check permissions. When they work correctly, we can use them to control visibility/disabledness (#2834).

**Comment by ebruchez** [comment]
See also #2999.

**Comment by ebruchez** [comment]
With the changes done for #5437, we now properly forward operations during mode changes. This makes the functions implemented with #2834 work correctly, finally! So we can start by hiding the "Edit" button when there are no `update` operation allowed.

This will fix the scenario in this bug, as well as other cases such as when viewing data from the Revision History pane, where we explicitly only enable the `read` operation (#5343).
