### ISSUE TITLE
Edge: grid separations don't show correctly

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3716]
Only one shows, and in the wrong place.

<img width="1262" alt="screen shot 2018-09-05 at 11 52 08 am" src="https://user-images.githubusercontent.com/105769/45115319-5e026180-b104-11e8-9d09-c51c4cd2c392.png">

**Comment by avernet** [comment]
Unfortunately (or fortunately), I am reproducing this one on Edge on VirtualBox as well. (Running Windows 10 in VirtualBox is really pushing the limit of an 8 GB MacBook!)
