### ISSUE TITLE
fr:date: ability to disable/exclude certain dates for selection in calendar

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3721]
Following #3657.

Idea: disable certain dates based on certain dynamic rules, like holidays and weekends.

- days of week could be a specific validation
- expression returning a sequence of dates could be another validation
- Form Builder UI TBD
- how to store this validation at the level of the `validation` attribute or element TBD

[+1 from customer](https://3.basecamp.com/3600924/buckets/1966556/messages/1164833270)

**Comment by ebruchez** [comment]
- [ ] write a `DateSeqValidationFunction` which takes a sequence of `xs:date` as constraint
- [ ] write custom MIP
    - [ ] support writing value other than `String` to node
- [ ] make sure we don't generate CSS classes for MIP values which are not strings (or are too long?)

**Comment by ebruchez** [comment]
For now, we resolve to keep storing `String`s only as custom MIPs, and we write the list of dates as a space-separated list of ISO dates. Entered #3831 to suggest improvements to custom MIPs.

**Comment by ebruchez** [comment]
Right now, the value of the custom MIP shows in the UI, as `excluded-dates-2018-11-29 2018-12-01`, which is wrong (space in the middle) and not useful.

I am thinking that showing custom MIPs in the view should be opt-in. Right now, we use custom MIPs for validation purposes. I don't think we use the MIP CSS classes on the client.

**Comment by ebruchez** [comment]
I was thinking that, since all validation custom MIPs currently don't have a prefix (like `non-negative`, `excluded-dates`) we could at least exclude those from CSS. But we cannot easily tell right now because the MIP name is stored using the prefix following by `-` in the node already. Suggesting to store as name the qualified name instead. This is an internal name anyway. We could switch to using a `QName` later.

**Comment by ebruchez** [comment]
How can we handle the user entering this correct XPath sequence of dates:

```
xs:date('2018-01-01'), current-date()
```

which must be stored as:

```xpath
xxf:excluded-dates((xs:date('2018-01-01'), current-date()))
```

If it is stored as:

```xpath
xxf:excluded-dates(xs:date('2018-01-01'), current-date())
```

then it looks like a two-parameter function, not a one-parameter function with a sequence.

In short, we should add/remove parentheses as needed. Maybe we can *always* add and *always* remove the outer parentheses in the expression.

**Comment by avernet** [comment]
Backporting this to customer `2018.1` branch. We have the following commits marked as being for this issue:

```
* a911cd8 - For #3721: fix handling of outer parens, validate as XPath 2 (3 days ago) <ebruchez>
* 5a1bb4d - For #3721: pass excluded date from MIP to component (3 days ago) <avernet>
* f84473f - For #3721: send list of excluded dates to client and fix JavaScript calls (7 days ago) <ebruchez>
* c64caf2 - For #3721: Form Builder UI (7 days ago) <ebruchez>
* 96ff46f - For #3721: don't output `NCName` custom MIPs to the view (7 days ago) <ebruchez>
* f89aa1a - For #3721: xxf:exclude-dates() validation function (7 days ago) <ebruchez>
* d3f2e1e - For #3721: client-side support for disabled dates (9 weeks ago) <avernet>
```

I cherry-picked the files modified in the 2 `avernet` commits. @ebruchez, I'll let you cherry-pick your 5 commits. Note that the committed version of `date.xbl` and `Date.scala` might already contain changes you've made as part of those 5 commits.
