### ISSUE TITLE
Migrate fr:number, xf:date, and other components to take cell width

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3752]
We don't want components who conceptually have a variable width to, well, have a fixed or maximum width. So we need to migrate them.

- `fr:date` is migrating from `xf:input`
    - → We can change here, and split the grid cell if needed.
- `fr:number` is not migrating
    - → Use Form Builder version.
        - If non-blank, keep as is.
        - Otherwise add CSS class on existing `fr:number` which sets the the max width.
        - Set Form Builder version. (#3751)

**Comment by avernet** [comment]
Has been done recently, as part of the work on #3657, and this also for `fr:time` and `fr:datetime`.
