### ISSUE TITLE
Error summary: errors for readonly fields should be clickable

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3774]
Errors for readonly fields don't show.

- Internally, the Error Summary has all the errors.
- But they don't show for readonly fields even after a `show-relevant-errors`.

[+1 from customer](https://3.basecamp.com/3600924/buckets/5422190/messages/1343540965#__recording_1346343048)

**Comment by avernet** [comment]
Just last week, I tried this on a form with a required, read-only input field, and the error was showing for me on hitting "Save". Are you referring to a different use case?

<img width="959" alt="required" src="https://user-images.githubusercontent.com/106961/46623696-50654080-cae3-11e8-9ba5-b953510041f5.png">

**Comment by ebruchez** [comment]
No, I am trying right now again and it's not working.

**Comment by ebruchez** [comment]
By "no", I mean that I think it;'s the same use case.

**Comment by ebruchez** [comment]
Unclear why it doesn't work right now when `show-relevant-errors` runs. This is meant to make all controls visited, but somehow the readonly input doesn't get marked as visited. I have to check why.

**Comment by ebruchez** [comment]
It works for me right now with 2018.2.3 as well. However, it's not possible to click on the link.

[+1 from customer](https://3.basecamp.com/3600924/buckets/1966716/messages/1931948964) for being able to click on the link.

**Comment by ebruchez** [comment]
A readonly field is currently not keyboard-focusable. So I imagine that the best we can do is show the relevant wizard page and try to get the control in question visible in the viewport.

**Comment by ebruchez** [comment]
Confirmed that this is not a regression.

**Comment by ebruchez** [comment]
This appears to work now, probably since we implemented #3816 with Orbeon Forms 2020.1. So closing this.
