### ISSUE TITLE
Initial value in repeated grid resets when control is moved

### ISSUE THREAD

**Issue by patricsteiner** [orbeon/orbeon-forms#3781]
**Given**
Version 2018.1-ce (I think? the one that is currently deployed on demo.orbeon.com).
A repeated grid with multiple iterations where one control has a different initial value in every iteration.

**When**
The control with the initial value is moved (within the repeated grid)

**Expected**
The initial value of the control stays as it was previously defined in all iterations.

**Actual**
For all iterations, the initial value of the control is set to the value of the control in the first iteration.

**Demo to reproduce**
Use this form https://gist.github.com/patricsteiner/ac953ecfed9bd25348c6dafc161ff3ca

In previous Orbeon versions, this also happened when the control was resized instead of moved.
This is very annoying when you have a big repeated grid with many initial values and want to move things around.

[+1 from customer](https://3.basecamp.com/3600924/buckets/5085006/messages/1369446044)

**Comment by avernet** [comment]
What should I do exactly to reproduce the issue? With your example, initially I have:

<img width="915" alt="screen shot 2018-10-18 at 9 31 11 am" src="https://user-images.githubusercontent.com/106961/47169518-9e82fc80-d2b8-11e8-958b-66ae3ea8001e.png">

If using the dropdown on the first line I select "Move down", I get the following, which seems correct. Should I follow other steps to reproduce the problem you're seeing?

<img width="920" alt="screen shot 2018-10-18 at 9 32 09 am" src="https://user-images.githubusercontent.com/106961/47169571-c3776f80-d2b8-11e8-8531-92f23895b8a9.png">

**Comment by patricsteiner** [comment]
Oh sorry that it wasn't clear, I mean moving the control, not the row:

![image](https://user-images.githubusercontent.com/7628757/47170720-07916100-d307-11e8-9b3e-d01536c78576.png)

**Comment by avernet** [comment]
Got it @patricsteiner, I do reproduce this. Thank you for the details. We'll investigate, and follow-up with you here and/or Basecamp once we have a better understanding of what is going on.

**Comment by ebruchez** [comment]
In `ToolboxOps.controlOrContainerElemToXcv`, called from `ToolboxOps.dndControl`, we have a comment which says `LATER: handle repetitions, for now keep only the first data holder`. So this is obviously part of the problem.

- [ ] update `ToolboxOps.controlOrContainerElemToXcv`
- [ ] update `ToolboxOps.pasteSingleControlFromXcv`

We must handle several cases:

- [ ] move from non-repeated to repeated: only one data holder to copy
- [ ] move from repeated to non-repeated: use first data holder (probably)
- [ ] move from repeated to repeated: match as many iterations as possible, and the rest is blank?

**Comment by ebruchez** [comment]
`insertHolders()` takes a `Seq` for`dataHolders`, but in effect we always pass only one node to it so far.
