### ISSUE TITLE
Embedding: new date picker is not positioned correctly

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3788]
Compare:

<img width="324" alt="screen shot 2018-10-23 at 3 23 37 pm" src="https://user-images.githubusercontent.com/105769/47394412-a3401a00-d6d7-11e8-8c3d-cd1fa790dabb.png">

<img width="346" alt="screen shot 2018-10-23 at 3 22 55 pm" src="https://user-images.githubusercontent.com/105769/47394390-93283a80-d6d7-11e8-8bcd-70206fdb01bc.png">

**Comment by avernet** [comment]
Change done for #3924 fixes this one. Closing.
