### ISSUE TITLE
Embedding: date control is too small

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3789]
<img width="581" alt="screen shot 2018-10-23 at 3 27 47 pm" src="https://user-images.githubusercontent.com/105769/47394574-442ed500-d6d8-11e8-85c4-b6de14ee8bfb.png">

**Comment by avernet** [comment]
This is fine now.

<img width="441" alt="screen shot 2018-12-17 at 12 33 32 pm" src="https://user-images.githubusercontent.com/106961/50113866-fd50ed80-01f7-11e9-8309-ac34da64897e.png">
