### ISSUE TITLE
Phone number field displays incorrectly

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3790]
<img width="291" alt="screen shot 2018-10-23 at 3 29 12 pm" src="https://user-images.githubusercontent.com/105769/47394636-74767380-d6d8-11e8-9497-bad557510eb6.png">

**Comment by ebruchez** [comment]
Still the case.

**Comment by avernet** [comment]
Fixed as part of the changed done for #3684. Also now using Font Awesome for the phone icon (we were already using the Font Awesome in the sidebar).
