### ISSUE TITLE
Support dynamic content in Explanatory Text control

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3802]
As we do since 2018.1 for labels, hints, and help for all controls that support them.

[+1 from user](https://3.basecamp.com/3600924/buckets/7873395/messages/1391988410)

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/7873395/messages/1520034389#__recording_1520185509)

**Comment by ebruchez** [comment]
An additional tab with "Explanation Text" will be introduced. It will work like the existing "Label", "Hint", and "Help Message" tabs in the "Control Details" dialog. The tab must only show when the control supports `<fr:text>`, which means, for now, only `<fr:explanation>`.

**Comment by ebruchez** [comment]
[Documented](https://doc.orbeon.com/form-builder/form-editor/control-settings#explanatory-text)
