### ISSUE TITLE
There should be some space between grids

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3806]
Following #3650.

- Things just don't look good without space, especially with repeated grids.
- Then in Form Builder, it is very hard to tell where a grid stops and the next one starts.

**Comment by avernet** [comment]
- Constraints
    - We want to have a space between grids (called for by this very issue)
    - But if nothing is shown in a grid, then we don’t want the grid to take any space, per #3650
- Margin collapsing
    - Using a margin and relying on margin collapsing seems like the perfect solution
    - However we explain [here](https://github.com/orbeon/orbeon-forms/issues/3650#issuecomment-403924928) why we failed to make this work
