### ISSUE TITLE
Artifact in delete confirmation dialog shows

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3820]
To reproduce, delete an entry from a summary page. It looks like this might be due to the recent change in how we render outputs with a label.

<img width="509" alt="screen shot 2018-11-13 at 9 44 19 am" src="https://user-images.githubusercontent.com/106961/48433579-47900c00-e72c-11e8-852f-01ca8922a764.png">

**Comment by avernet** [comment]
Added missing screenshot to description above.

**Comment by ebruchez** [comment]
I thought I had entered an issue already, but apparently not.
