### ISSUE TITLE
Declarative "synchronize repeated grid/section" action

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3833]
Related to #3803.

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/5085006/messages/1362234678#__recording_1437581523)

**Comment by ebruchez** [comment]
After brainstorming, the "synchronize two repeated entities" use case would be nicely handled by a much more declarative construct. For example:

```xml
<sync left="my-grid-1" right="my-grid-2">
    <map left="my-control-1" right="my-control-2"/>
    <map left="my-control-a" right="my-control-b"/>
</sync>
```

This behaves like an XBL component, except that it is purely a reusable action component used in an `xf:model`. Could we use XBL for this? Maybe in the future. We'd need components which can be instanciated in the model, and can act as event observers. For now, we would implement this in XSLT, making sure there is no id conflict.

The day we add a UI, we'd need to figure out where this fits. This is a more declarative action which doesn't depend on an explicit listener.

**Comment by ebruchez** [comment]
- [ ] finalize action name/format
- [ ] unit tests
- [ ] doc
- [ ] backport for customer

**Comment by avernet** [comment]
[+1 from user](https://stackoverflow.com/questions/53629635/orbeon-access-repeated-grid-items-from-a-different-repeated-grid)

**Comment by ebruchez** [comment]
One thing to be careful about: we must synchronize even if section is non-relevant, for example . So while we can *listen* to events to update the other side, we cannot *dispatch* events to realize it on the other side. For example this means we need to insert repeat iterations directly in the data.

**Comment by ebruchez** [comment]
Latest format:

```xml
<fr:synchronize-repeated-content left="left" right="right" version="2018.2">
    <fr:map left="dropdown" right="dropdown-readonly"/>
    <fr:map left="field"    right="field-readonly"/>
</fr:synchronize-repeated-content>
```

- use names everywhere
- require a format version
- more explicit name

**Comment by ebruchez** [comment]
[Documented `event('index')`](https://doc.orbeon.com/form-runner/component/grid#events)

**Comment by ebruchez** [comment]
[Documented `<fr:synchronize-repeated-content>`](https://doc.orbeon.com/form-builder/advanced/services-and-actions/synchronize-repeated-content)

**Comment by ebruchez** [comment]
Moved P2 to #3848.
