### ISSUE TITLE
MySQL: enabling lease causes errors

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3866]
I am using the latest driver (`mysql-connector-java-5.1.47-bin.jar`) but I am getting this.

```
+----------------------------------------------------------------------------------------------------------------------+
|An Error has Occurred                                                                                                 |
|----------------------------------------------------------------------------------------------------------------------|
|This command is not supported in the prepared statement protocol yet                                                  |
|----------------------------------------------------------------------------------------------------------------------|
```

**Comment by ebruchez** [comment]
This might not be a regression, I am not sure.

**Comment by ebruchez** [comment]
We should have automated tests checking that our SQL passes with all databases.

**Comment by avernet** [comment]
Somehow I can't reproduce this. I was using `mysql-connector-java-8.0.11.jar` against MySQL 5.7, and also tried with `mysql-connector-java-5.1.47.jar`, but the lease seems to work fine for me. Specifically, a user can acquire a lease, another user see the document has already been leased, and the original user can relinquish the lease.

**Comment by avernet** [comment]
I suggest that for now we leave this open for 2018.2.1, and we can discuss this one in the coming weeks to figure out if there really is an issue, or if it is a just a "local configuration issue".

**Comment by avernet** [comment]
Steps to reproduce:

1. Set the properties below
2. In Form Builder, create a form, publish it
3. Open the `/new` page, save
4. Set the header `My-Credentials-Header` to `{ "username" : "hsimpson" }`
5. Clear the `JSESSIONID`
6. Load the form data previously saved

With this, I am getting the following, which is as expected, and doesn't seem to reproduce the issue @ebruchez is seeing.

<img width="960" alt="screen shot 2019-01-25 at 11 47 11 am" src="https://user-images.githubusercontent.com/106961/51769159-20907780-2097-11e9-8bda-7d86c1f93dbd.png">

```xml
<property
    as="xs:string"
    name="oxf.fr.persistence.provider.*.*.*"
    value="mysql"/>
<property
    as="xs:string"
    name="oxf.fr.authentication.method"
    value="header"/>
<property
    as="xs:boolean"
    name="oxf.fr.detail.lease.enabled.*.*"
    value="true"/>
```

**Comment by ebruchez** [comment]
So I did this:

- created new MySQL database with the 2018.2 DDL
- downloaded 2018.2 PE
- setup the properties above
- followed the steps
- still getting the same error

**Comment by ebruchez** [comment]
Maybe @avernet create a new fresh MySQL database?

**Comment by avernet** [comment]
Still unable to reproduce the problem. So, here is how I do the first step "created new MySQL database with the 2018.2 DDL":

1. Start a clean container with MySQL 5.7: `docker run -d -p 3306:3306 -e MYSQL_ALLOW_EMPTY_PASSWORD=yes mysql:5.7 --sql-mode=ALLOW_INVALID_DATES --character-set-server=utf8mb4 --collation-server=utf8mb4_bin`
2. Run `docker ps` to get the container id, then `docker exec -i -t CONTAINER_ID bash`
3. Run the 3 commands in [Setting up users and schema](https://doc.orbeon.com/form-runner/persistence/relational-db#setting-up-users-and-schema)
4. Connect as `orbeon` with `mysql -u orbeon -p`, enter `orbeon` as password, `USE orbeon`, paste the content of [mysql-2018_2.sql](https://github.com/orbeon/orbeon-forms/blob/master/form-runner/jvm/src/main/resources/apps/fr/persistence/relational/ddl/mysql-2018_2.sql), finally `exit` twice
5. Run Tomcat with the `<Resource>` below

@ebruchez You'll let me know if you can reproduce the issue with a clean database created this way.

```
<Resource
    name="jdbc/mysql" driverClassName="com.mysql.jdbc.Driver"
    auth="Container" type="javax.sql.DataSource"
    initialSize="3" maxActive="10" maxIdle="10" maxWait="30000"
    poolPreparedStatements="true" testOnBorrow="true" validationQuery="select 1"
    username="orbeon" password="orbeon"
    url="jdbc:mysql://localhost:3306/orbeon"/>
```

**Comment by avernet** [comment]
I am wondering if this could be caused by the new call to `SHOW VARIABLES LIKE`, in `commonPart.scala`. This should be easy to check, and if the case it will also be easy to change that code to bypass creating a prepared statement. Next step:

- [ ] @ebruchez Check what statement is causing this error

**Comment by ebruchez** [comment]
The error appears to be in the `s"LOCK TABLES $tableName WRITE"` command.

**Comment by ebruchez** [comment]
Replacing the `PreparedStatement` with a good old `Statement` works.

Note that I am using MySQL 5.7.15.

**Comment by ebruchez** [comment]
So I suggest switching to using `createStatement` in this case. This should work with the other databases as well, I hope.
