### ISSUE TITLE
fr:date: entering letters shows the current date

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3877]
This is not desired as if the user make a typo the date will be set anyway.

<img width="294" alt="screen shot 2019-01-02 at 2 52 56 pm" src="https://user-images.githubusercontent.com/105769/50616643-321e9f00-0e9e-11e9-88d7-b82ab2128d09.png">

<img width="148" alt="screen shot 2019-01-02 at 2 52 59 pm" src="https://user-images.githubusercontent.com/105769/50616650-3480f900-0e9e-11e9-8c45-802d4b145c0c.png">

**Comment by avernet** [comment]
I can reproduce this in [their sandbox](https://uxsolutions.github.io/bootstrap-datepicker/) as well, so this isn't specific to our integration. For now I've [posted a question about this](https://groups.google.com/forum/#!topic/bootstrap-datepicker/dimCFqRlZ4Q) in their discussion group.

**Comment by avernet** [comment]
In `Date.xformsGetValue()`, we call the date picker's `getDate()` function, which tries to parse the date "no matter what", and this even when setting `forceParse` to `false` (the default is `true`).

**Comment by avernet** [comment]
- [x] When parsing, don't take `1a/24/2019` to be January 24, 2019 (because of the `a` there in the middle)
- [x] If users enter `gaga` and tabs out, don't set the field value to the current date
- [x] If users enter `gaga` in the field, and open the date picker, don't select the current date
