### ISSUE TITLE
Safari: Test in Form Builder produces "client state not found"

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3900]
This is with the new state handling code only. Works with Chrome and Firefox.

When we test, we do a form submission:

```xml
<xxf:submission method="POST" show-progress="false" target="fb-test-iframe"/>
```

It is as if Safari creates a new history entry in this case, while the other browsers don't. If there is a new history entry, then `findClientState` no longer finds the state after the submission has fired.

**Comment by ebruchez** [comment]
This looks like [this WebKit bug](https://bugs.webkit.org/show_bug.cgi?id=28657) reported 10 years ago.

**Comment by avernet** [comment]
Also reproducing this with the preview of Safari 12.1 (release 73).

**Comment by ebruchez** [comment]
I don't see a way to pass state when doing a `submit()`. Could we do a `history.back()` but only on Safari, or only if doing the `submit()` changes the history (not sure we can detect that)?

**Comment by ebruchez** [comment]
Alternatively, is there another way to handle testing the form? Using an iframe has the benefit of isolation. Using a form POST has the benefit of easily targeting that iframe and handling transient data easily.

**Comment by ebruchez** [comment]
I was wondering if a shadow DOM could be used in instead of an iframe, but that's [not supported with Edge](https://caniuse.com/#feat=shadowdomv1) yet.

Alternatively, keeping an iframe, we could either do a GET in the iframe, or set the iframe content with JavaScript.

**Comment by avernet** [comment]
Luckily for us, it isn't the submission that is creating a new entry in the history, but it was the `contentWindow.location.href = "about:blank"` we were doing to clean the dialog before showing it. (We were doing this so we wouldn't have the output from a previous test show while waiting for the submission to return the new form.) So this was just a matter of finding another way to clear the iframe.
