### ISSUE TITLE
Form Builder always using natural field width

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3901]
Create a new form, add a phone number field (to pick a simple one). Notice how the field width is narrow ("natural") instead of taking the full width. Publish the form, open `/new`: here the field has the fill width as expected. Could it be an issue with our implementation of `FormRunnerFunctionLibrary.FRComponentParam` that doesn't work properly in Form Builder?

**Comment by ebruchez** [comment]
The value evaluated uses the property:

```
<property
    as="xs:string"
    name="oxf.xforms.xbl.fr.us-phone.field-width"
    value="{if (fr:created-with-or-newer('2018.2')) then 'full' else 'natural'}"/>
```

It returns 'natural'. This means that `fr:created-with-or-newer('2018.2')` returned `false()`.

This is the XML metadata as found by `fr:component-param-value('field-width')`:

```
<metadata>
    <application-name>a</application-name>
    <form-name>a</form-name>
    <title xml:lang="en">Untitled Form</title>
    <description xml:lang="en"/>
    <created-with-version>2018.2-SNAPSHOT PE</created-with-version>
    <library-versions>
        <orbeon>1</orbeon>
    </library-versions>
</metadata>
```

It should return `true()`.

However, `fr:created-with-or-newer()` uses a different function to access metadata:

```scala
FormRunner.metadataElemValueOpt(Names.CreatedWithVersion)
```

This finds the *Form Builder* metadata instance at design time, which will be incorrect.

We need to change that to use, instead, like ``fr:component-param-value()`:

```scala
FRComponentParam.findConstantMetadataRootElem()
```
