### ISSUE TITLE
Ability to change "Add Another Repetition" label

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3911]
Often form authors would like to provide a more user-friendly message, say "Add another child".

[+1 from user](http://discuss.orbeon.com/Repeated-Content-Edit-Insert-Below-link-text-td4664349.html)

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/7873395/messages/1713471387)

**Comment by ebruchez** [comment]
Customer would like the ability to set the label independently for each repeated section.

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/10984927/messages/1635931990)

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/7873395/messages/2413982942)

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/18345583/messages/4578774973)

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/23878674/messages/4755672540)

**Comment by ebruchez** [comment]
We already have, in the Section/Grid Settings, a "Repetition Label" tab. The "Add Another Repetition" setting would be similar.

We store the repetition label under the `<fr:section>` as:

```xml
<fr:iteration-label ref="$form-resources/section-1/iteration-label"/>
```

We would add:

```xml
<fr:add-iteration-label ref="$form-resources/section-1/iteration-label"/>
```

**Comment by ebruchez** [comment]
[Documented](https://doc.orbeon.com/form-builder/form-editor/section-settings#custom-add-repetition-label)

**Comment by ebruchez** [comment]
For reference, this was only for repeated sections.
