### ISSUE TITLE
Support encrypting attached files

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3933]
Right now, when an attachment is marked for encryption, the link to the file is encrypted in the form data, but not the file content itself.

[+1 from customer](https://3.basecamp.com/3600924/buckets/2192969/messages/1573943642)

**Comment by avernet** [comment]
Implemented in https://github.com/orbeon/orbeon-forms-pe/commit/ce990bed0ec4c69f07d3be51c245bbe95d06faea.

**Comment by ebruchez** [comment]
- [ ] support `fr:encrypted`
- [ ] review encryption code for efficiency
- [ ] review PE vs. CE changes
- [ ] doc changes to API

**Comment by avernet** [comment]
- [ ] When doing a GET, use `Orbeon-Decrypt: true` instead of `Orbeon-Encrypted-At-Rest: true`

**Comment by avernet** [comment]
The encryption is done in `FieldEncryption.scala`, which is called by the persistance proxy. We get the fields to encrypt as a list of `ControlBindPathHoldersResources`, and for a given field find the corresponding element by building an XPath expression with `fieldToEncrypt.path.map(_.value).mkString("/")`. The problem is that after #1947, `ControlBindPathHoldersResources` contains an additional element for non-repeated grids, but that element isn't present in the data the persistence proxy receives, hence we don't find the element, and encryption doesn't happen. We could fix this by either:

- `ControlBindPathHoldersResources` providing a way to return a path that works on the data sent to the persistence API, a format that can depend on properties. If we can find such a way, this would be simplest thing to do from the perspective of the existing encryption code.
- Move the encryption code so it runs before the data is sent to the proxy. (And conversely do the decryption after receiving the data from the persistence proxy.)

**Comment by avernet** [comment]
In `FieldEncryption.scala`, we get the list of `ControlBindPathHoldersResources` using `FormRunner.searchControlsInFormByClass()`.

**Comment by avernet** [comment]
@ebruchez mentioned that we can maybe use code similar to the one in `findIndexedControls` (in `FormDefinition.scala`).

**Comment by avernet** [comment]
I moved the logic in `findIndexedControls` that was "adapting" the path for a given version of the data format version to `searchControlsInFormByClass`, which now takes an additional parameter of type `DataFormatVersion`.
