### ISSUE TITLE
Minimal repeated section - remove button doesn't work

### ISSUE THREAD

**Issue by mateuszkiec** [orbeon/orbeon-forms#3948]
When we use repeated section with minimal mode like this:

	<property
    		as="xs:string"
    		name="oxf.xforms.xbl.fr.section.appearance.*.*"
    		value="minimal"/>

we cannot remove previously added section. Remove button doesn't work. 
In repeated grid the same mode works like a charm.

Orbeon version: 2018.2.201901010020 CE
Browser: any

As an attachment, I attach an example form.
[form.zip](https://github.com/orbeon/orbeon-forms/files/2865801/form.zip)

**Comment by mateuszkiec** [comment]
In the newest version 2018.2.1.201902072242-CE problem still exist.

**Comment by ebruchez** [comment]
Thanks, I reproduce the issue.

**Comment by ebruchez** [comment]
So @mateuszkiec this is fixed and will be in Orbeon Forms 2018.2.2.
