### ISSUE TITLE
Review orbeon-form-runner.js and orbeon-form-builder.js

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#3953]
They seem to include a very large list of locales. I am not sure where it comes from. Review.

**Comment by ebruchez** [comment]
The Form Builder uncompressed, `fastopt`ed JavaScript file is now 5 MB. Of this, 2.4 MB is locales information. We need to find which code causes this to load and, if possible, reduce that size. We clearly don't need all those locales.

**Comment by ebruchez** [comment]
The optimized version is 1.5 MB, and also contains locale data such as "Andorran pesetas", etc.

Placing a breakpoint on a couple of constructors, I am not getting called, at least immediately, in Form Builder.

**Comment by ebruchez** [comment]
Found the culprit:

```
├─ com.outr:scribe_sjs0.6_2.11:2.7.1
│  ├─ com.outr:perfolation_sjs0.6_2.11:1.0.4
│  │  ├─ com.outr:perfolation-macros_sjs0.6_2.11:1.0.4
│  │  │  ├─ org.scala-js:scalajs-library_2.11:0.6.22 -> 0.6.26
│  │  │  │  └─ org.scala-lang:scala-library:2.11.12 -> 2.11.11
│  │  │  ├─ org.scala-lang:scala-library:2.11.12 -> 2.11.11
│  │  │  └─ org.scala-lang:scala-reflect:2.11.12 -> 2.11.11
│  │  │     └─ org.scala-lang:scala-library:2.11.11
│  │  ├─ io.github.cquiroz:scala-java-locales_sjs0.6_2.11:0.5.4-cldr31
```

**Comment by ebruchez** [comment]
[This commit](https://github.com/outr/perfolation/commit/9ad70046b6283d56b09a3b56a484b3441d5d0922) in `perfolation` seems to be a fix for that, but I don't see a new release after that.

**Comment by ebruchez** [comment]
Asked question here https://github.com/outr/perfolation/pull/11

**Comment by ebruchez** [comment]
So hopefully there will be a new release of perfolation/scribe  which addresses this.

**Comment by darkfrog26** [comment]
Perfolation 1.1.0 is released with this fix.

**Comment by ebruchez** [comment]
With this change:

- `opt` is 817K
- `fastopt`is 3.8 MB
