### ISSUE TITLE
Service should be usable from multiple actions

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#397]
Right now, we restrict 1 service ↔ 1 action.

**Comment by avernet** [comment]
[+1 from community](https://twitter.com/pfiks_robert/status/663499631289044992)

**Comment by ebruchez** [comment]
Added for consideration for 2016.3 pending bug review.

**Comment by ebruchez** [comment]
Pushing as we'll do workflow UI first and then evaluate new actions UI from there.

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/4882960/messages/677469415#__recording_678856582)

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/1966556/messages/685122057)

**Comment by ebruchez** [comment]
Closing, since #3803 implements this. #1298 now covers implementing a UI for the new action format.
