### ISSUE TITLE
New button has no effect

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3970]
With Orbeon Forms 2018.2.2, add the following property to your `properties-local.xml`, load the Bookshelf summary page, click on a line to edit one of the books, click on the New button, and notice that nothing happens.

```xml
<property as="xs:string"  name="oxf.fr.detail.buttons.*.*" value="new"/>
```

**Comment by ebruchez** [comment]
This was probably not a regression. I suspect this was implemented for Form Builder only at first. I have created a more general process.
