### ISSUE TITLE
Improve how long texts are shown by the Formatted Text Area in view and automatic PDF

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3974]
- In view mode, use a  scrollbar, like we do in edit mode.
- In the automatic PDF, wrap the content, so it doesn't show over other controls, and gets cut when arriving at the edge of the page.

[+1 from user](http://discuss.orbeon.com/Pasting-pre-formatted-text-to-formatted-text-control-td4664378.html)

**Comment by ebruchez** [comment]
Input fields and text areas should be fine, I remember we had changed some CSS for that. Here, we have rich text fields.
