### ISSUE TITLE
`ClassFormatException` when starting Tomcat

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#3999]
I have Tomcat 8.0 reporting a "ClassFormatException: Invalid byte tag in constant pool: 20" on `bcpkix-jdk15on-1.61.jar` with Java 8.

**Comment by ebruchez** [comment]
This is happening when Tomcat scans for annotations.

1. The `bc*.jar` libraries for *jdk15on* should NOT have Java 9 bytecode information.
2. We don't need that scan to happen.

**Comment by ebruchez** [comment]
This was also causing an issue with Proguard, which we upgrade to a newer version for that reason.
