### ISSUE TITLE
Proxy portlet and embedding JARs cause class loading error

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#4001]
[+1 from customer](https://3.basecamp.com/3600924/buckets/1966556/messages/1669530234#__recording_1671530237)

**Comment by ebruchez** [comment]
This seems to have happened between 2018.2.1 and 2018.2.2.

**Comment by ebruchez** [comment]
Well, there is a problem, but it seems to happen post 2018.2.2. The 2018.2.2 proxy portlet has `org/orbeon/private/apache/http/HttpRequestInterceptor.class` as expected. There should be no code looking for `org/apache/http/HttpRequestInterceptor`.

**Comment by ebruchez** [comment]
Hoping that #4009 addresses the problem.

**Comment by ebruchez** [comment]
Reproducing this with the embedding JAR as well. So we need a better solution.

**Comment by ebruchez** [comment]
Given that #4009 works, it might just be that our version of jarjar is broken. Next step would be to try version 1.7.2 (https://mvnrepository.com/artifact/org.pantsbuild/jarjar), used in particular by https://github.com/sbt/sbt-assembly/blob/master/build.sbt.

If that doesn't work:

- check the [Ant wrapper](https://github.com/lyubomyr-shaydariv/ant-shade-task) for the [Maven Shade Plugin](https://github.com/apache/maven-shade-plugin)
- consider doing this with Proguard (hard to find how)

NOTE: This is called "shaded dependencies" these days.

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/7873395/messages/1758377219)

**Comment by ebruchez** [comment]
Updated to jarjar 1.7.2. I can build the JAR and WAR files locally without problems this way. I can also deploy them with Liferay 7.0 and via embedding.

**Comment by ebruchez** [comment]
Confirming that with a CI build, the issue is now fixed.
