### ISSUE TITLE
Autosave during upload can cause an error

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#4003]
Form to reproduce the issue: [form.txt](https://github.com/orbeon/orbeon-forms/files/3019649/form.txt).

[+1 from customer](https://3.basecamp.com/3600924/buckets/7314201/messages/1676251769#__recording_1679618868)

**Comment by avernet** [comment]
The message in the log is "instance to submit has at least one pending upload". On autosave, we run the `autosave` process declared in `properties-internal.xml`, which does just a `save(draft = "true")`, hence the error is understandable.

I am trying to reproduce the problem, however, strangely, the autosave during the file upload is working for me. More debugging required.

**Comment by avernet** [comment]
Strangely (?), when I try to reproduce this, the following, in `XFormsModelSubmission.java` returns false:

```java
SubmissionUtils.hasBoundRelevantPendingUploadControls(
    containingDocument, 
    p.refContext().refInstanceOpt()
)
```

**Comment by avernet** [comment]
In the above expression, `p.refContext().refInstanceOpt()` returns `None`. The submission is `fr-create-update-submission` in `universal-submission.xml`, which has a `ref="event('holder')"`, and I imagine that this context isn't tied to an instance.

On a normal save, we call `require-uploads`, which runs `pending-uploads`, which checks that `inScopeContainingDocument.countPendingUploads > 0`, which fails (as it should) when we have a pending upload.

With our latest code things seem to be working:

- The autosave works while the file upload is in progress. If closing the page before the upload is finished and loading the autosaved data, we get the value for all the fields, except the files (and the holders are empty; they don't contain a `file:/` URL).
- The autosave is done again after the file is uploaded.

One possibility is that the customer runs a version of Orbeon Forms where the test for pending uploads during the submission "works", which cause the problem they are seeing. We asked them what version they are running to we can verify this hypothesis by doing a test against that version.

**Comment by ebruchez** [comment]
So there still is a problem with the latest code right? If there is a background upload, `countPendingUploads > 0` should return true.

**Comment by avernet** [comment]
I forgot we already had an issue for this, and consequently created #4012, which is now fixed. So closing this one.
