### ISSUE TITLE
Per-form/global settings for minimal Calculated Value field

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#4008]
Following #4004.

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/7314201/messages/1741346102)

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/2825555/messages/1695824020)

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/5085006/messages/1797170177)

**Comment by ahenket** [comment]
I've managed to circumvent the issue by eliminating xf:label under xf:output elements.

**Comment by ebruchez** [comment]
To recapitulate, following #3804 and #4004. We now (2018.2.3 and 2019.1) have an option in Form Builder. But we'd like an option which is per form.

To render the field without borders, we use `appearance="mimimal"`, which is implemented partially in CSS, but also partially natively to place the `xforms-field` vs. the `xforms-output-output` class.

If the user selected "Calculated Value Without Border" for a given field, it makes sense that this is final. So we are concerned about the case where there is no `minimal` appearance present.

**Comment by ahenket** [comment]
I'm not sure anymore we are talking about the same thing. This fragment causes the issue:

```
    <xforms:output ref="$resources/Is-private" class="padinline" style="margin-left: 5px;">
        <xforms:label ref="$resources/Is-private-hint" class="hidden"/>
        <xforms:help ref="$resources/Is-private-hint"/>
    </xforms:output>
```

Adding appearance="minimal" in either the xforms:output or the xforms:label does not make any difference. Removing the forms:label altogether restores normal behavior.

<img width="666" alt="image" src="https://user-images.githubusercontent.com/5390573/59790086-63b1e800-92cf-11e9-8547-1a2a9c9f9295.png">

**Comment by ebruchez** [comment]
This is probably explained because the `minimal` appearance was introduced with #4004, which was done after Orbeon Forms 2018.2.1 CE. You can see it in action [here](https://demo.orbeon.com/demo/fr/issue/4008/new).

**Comment by ahenket** [comment]
But 2018.2.1 broke xf:output+xf:label for us and there is no CE version after 2018.2.1 yet. Is that bug (can't see it otherwise) still on the list to fix?

**Comment by ebruchez** [comment]
What we call a "calculated field" is an `<xf:output>` with an `<xf:label>`. Most uses of `<xf:output>` are just to produce some content dynamically. But once you add an `<xf:label>` to an `<xf:output>`, conceptually it becomes something different, more like a form field. This is similar to the HTML 5 `<output>` element, which was also designed to show the result of calculations - and which we use in the resulting markup too.

The above is the whole rationale for changing the appearance and behavior of `<xf:output>` with `<xf:label>`  in the first place.

In your case, in the fragement you show above, what is the purpose of the nested `<xforms:label>`? Maybe that `<xforms:label>` shouldn't be there in the first place.

But even with it, the problem for you, in the end, is one of CSS layout, isn't it? If so, a few lines of CSS should be enough to remove the border and background.

**Comment by ahenket** [comment]
We added xforms:label because the nvdl was complaining without it, about xforms:hint/xforms:help. We really don't want to see those labels, hence class=hidden. So given that we should probably just live with the mvdl complaints that impose no real world error in Orbeon. I've already removed xforms:label from all our forms.

As a side note: we also hide almost all (xforms:output|xforms:input|xforms:textarea)/xforms:label by default. Somehow they never render the way we want them to render. They serve a purpose in allowing the error-summary to bind to something, and in preventing nvdl errors, but are otherwise superfluous code.

**Comment by ebruchez** [comment]
> If the user selected "Calculated Value Without Border" for a given field, it makes sense that this is final. So we are concerned about the case where there is no minimal appearance present

For settings at the form level, we have:

- properties
- form-level

For controls like `fr:number`:

- properties
- form-level
- control-level

The recent "Simplified appearance" for sections and grids has:

- properties
- form-level

In fact, it should also be:

- properties
- form-level
- section/grid-level

Now ideally, for the appearance of output, we would also have:

- properties
- form-level
- control level

For controls, we implement the multi-level setting by using the `fr:component-param-value()` function. However, we don't have yet a mechanism to handle appearances this way as they are static.

We could do this by having Form Runner place the appearances at runtime when needed. We already do this, in fact, to handle section/grid appearances via `oxf.xforms.xbl.fr.(section|grid).appearance`.

So we would add something like this and support:

- property `oxf.xforms.xbl.fr.output.appearance`
- form-level
- control-level

Issues:

- at the control level, we don't have default/full/minimal and we only have a checkbox to say minimal
    - Q: Could we create two more XBL entries, one for full, one for default?
- ideally we would support `fr:created-with-or-newer('2018.2')`, but since this has to run in XSLT, we probably cannot do it this way

**Comment by ebruchez** [comment]
Issues:

- In `section-and-grid.xsl` I can try out that logic. It works at runtime, but not at design-time. We need another mechanism to handle the design-time.
- To edit the appearances, we might need a custom editor as we can't use the appearance selector in the form settings. That is, unless we build a general mechanism to pick a default appearance for controls, which might not be a bad idea, except that it's tight for 2019.1.

**Comment by ebruchez** [comment]
For 2019.1, we can do just the first step:

- handle form-level  properties and defaults based on form creation version
- have the appearance selector at the control level for `minimal`, `full`, and default
- push the UI for the setting at the form level to a later version (2019.2)
