### ISSUE TITLE
Can't add a repetition to repeated section after the last one has been removed

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#4018]
To reproduce, create a form in Form Builder, open the section settings to mark the section as repeated and say it has no minimum number of repetitions, delete the first repetition, click "Add Another Repetition" and notice that no repetition is added. The same also happens at runtime.

We want to support repeated section with no iterations, for consistency with grids, but if, in a first step, if we don't support them, the "No minimum" radio should be disabled or not be there at all in the "Section Settings".

[+1 from user](https://3.basecamp.com/3600924/buckets/7873395/messages/1696311351)

**Comment by ebruchez** [comment]
Is this related at all to #4032?

**Comment by avernet** [comment]
I don't know it it is caused by the same underlying issue, but the steps to reproduce seem different: this issue is about the addition failing if the last repeated section has been removed, while for #4032 you need to have additional constraints ("This works if the top-level repeated section only contains a grid. With a nested section, this doesn't work in a simple case.").

**Comment by ebruchez** [comment]
In this case, we are getting a server error first with `assert(_nestedContainerOpt.isEmpty)` in:

```
updateBindings()
createRepeatIterationTree()
recreateNestedContainer()
createNestedContainer()
```

The condition to call `recreateNestedContainer()` is probably incorrect:

```
// Control got created relevant and, in the process, created the static `ConcreteBinding`.
componentControl.isRelevant &&
componentControl.staticControl.hasLazyBinding &&
componentControl.staticControl.bindingOpt.isDefined
```

The comment mirrors the following 2 comments in `BindingUpdater`:

```
// Control just got relevant and, in the process, created the static `ConcreteBinding`.
// Control just got non-relevant and, in the process, deleted the static `ConcreteBinding`.
```

**Comment by ebruchez** [comment]
In this case, we just created the `XFormsComponentControl` with the control factory.  When that happens, `createNestedContainer()` runs at construction. So the container is there, and calling `recreateNestedContainer()` will raise the assert.

Now the question is: do we need to remove `recreateNestedContainer()` altogether, or just add `destroyNestedContainer()` first? Neither seem to make sense.

**Comment by ebruchez** [comment]
@avernet Sorry that was more a question to myself ;)

**Comment by ebruchez** [comment]
Understanding so far:

- `ConcreteBinding` got created during iteration 1
- repeat iteration 2 and associated subtree of concrete controls is created
- component with lazy binding
    - new concrete control in iteration 2 is built through the factory
    - `createNestedContainer()` runs at construction
    - control binding is evaluated
    - `onCreate()` is called
    - `ConcreteBinding` is created if needed
        - in this case, it doesn't need to be created since it was created during iteration 1

Now, if there was no iteration, and `ConcreteBinding` has just been created, do we need `recreateNestedContainer()`, or is the original `createNestedContainer()` sufficient?

The answer is that the call to `createNestedContainer()` in the constructor actually does nothing when the static binding is lazy and empty! So we do need to create the nested container after the static binding got created. Further, `onCreate()` got called, but since there was no nested container, it didn't create the nested models.

**Comment by ebruchez** [comment]
This is similar to #3892 which applied to repeated grids.
