### ISSUE TITLE
Client-side code retrying upload with a GET

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#4040]
We should either:

1. Not retry uploads
    1. At the XForms level, dispatch an appropriate event.
    2. At the Form Runner level, notify users the uploads wasn't done, and that they need to re-attach the file.
2. Ideally, retry the upload as a POST
    1. Can we, technically speaking?
    2. If so, we might first want to explore doing this.

[+1 from customer](https://3.basecamp.com/3600924/buckets/7873395/messages/1743512684)

**Comment by ebruchez** [comment]
I thought the code was explicitly not supposed to retry uploads, but maybe I misremember or there is a bug.

**Comment by avernet** [comment]
With Charles, rewriting the query to `/orbeon/xforms-server/upload` to return a 500, I'm unable to reproduce this problem:

1. The client-side code sends an `<xxf:event name="xxforms-upload-error">` to the server.
2. In `attachment.xbl`, the `xf:upload` gets a `xxforms-upload-error`, and dispatches the same event to the XBL control.
3. Form Runner code shows the following dialog.

<img width="452" alt="Screen Shot 2019-05-01 at 11 47 58 AM" src="https://user-images.githubusercontent.com/106961/57035657-711fef80-6c07-11e9-805f-44ce959db237.png">

Reading the code, I am not seeing anything doing a retry. Closing as can't reproduce.
