### ISSUE TITLE
Metadata and data ids for repeated content don't match

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#4043]
See the example below, where we first have the data and then the metadata:

- Matching ids:
    - Ids on the section (`<family>`) and the non-repeated field (`<head>`)
    - Below, see the blue arrows
- Non-matching ids:
    - Ids on repeated content (`<name>`)
    - Below, see the orange rectangles

<img width="891" alt="Screen Shot 2019-05-02 at 11 53 05 AM" src="https://user-images.githubusercontent.com/106961/57099627-bd376680-6cd1-11e9-9fc3-6517ca8d596a.png">

The `annotate = "id"` gets translated into an `xxf:annotate="id"` on the submission, which is implemented in `annotateWithHashes()` and uses `SubmissionUtils.dataNodeHash()`. On the other hand, when we produce the metadata, it is the `fr-send-submission` that calls `metadata:createFormMetadataDocument()`, which also calls `SubmissionUtils.dataNodeHash()`.

The issue happens because when sending the data, we migrate the data from the `edge` to the `4.0.0` format, so hashes for those migrated nodes are not the same. Consequently, the hashes are always correct if the data is produced with `data-format-version = "edge"`.

**Comment by avernet** [comment]
I was thinking that could maybe fix this by also supporting the `data-format-version` attribute with `content = "metadata"`, and migrating the data appropriately before passing it to `createFormMetadataDocument()`. However, `createFormMetadataDocument()` works on the containing document, which we can't easily "migrate".

So, I suggest that we document that the ids produced by `content = "metadata"` match to the ids produced in the `edge` data.

**Comment by ebruchez** [comment]
We could also make it so that the ids either always reflect something predictable (including all container elements, or none - we choose).

**Comment by avernet** [comment]
For now, I [documented](https://doc.orbeon.com/form-runner/advanced/buttons-and-processes/actions-form-runner/actions-form-runner-send#sending-form-metadata) the current behavior. If requested by a customer, or if we see a need for it, we can create an RFE to have the ids on the data always be the same for elements locally corresponding to the same field, and using those ids in the metadata.
