### ISSUE TITLE
fr:date: commit value upon enter

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#4095]
This is an issue in the Summary page search.

**Comment by ebruchez** [comment]
Also check:

- [ ] `fr:number`
- [ ] `fr:time`

**Comment by ebruchez** [comment]
Also an issue in regular uses of the field.

**Comment by avernet** [comment]
Just like we have `xxbl:mode="focus"`, we might need to add `xxbl:mode="activate"` (name TBD), so the components accepts a `DOMActivate` event.
