### ISSUE TITLE
Allow `fr:date` to be used outside of Form Runner

### ISSUE THREAD

**Issue by ahenket** [orbeon/orbeon-forms#4107]
After #4103 I have been playing some more with fr:date and found it is not ready for use in 2018.2.1 the way I'd like to see it.

I'd like to see it behave similar to xf:input, but:

- The date picker widget never comes up for fr:date
- The input field for fr:date does not seem connected to the instance it references. It does not show what's in it, and if you enter something in the instance from an xf:input field it is not reflected in fr:date either
- If you add an xf:label with appearance=minimal this is rendered in the input field for xf:input, but for fr:date is remains as label to the left of the input field.
- The alert icon does not have the mouse over text for fr:date, the way that it has for xf:input. Hence the user only sees the icon without a hint as to what's going on.

Code that demonstrates all this

```
<xh:html
    xmlns:xh="http://www.w3.org/1999/xhtml"
    xmlns:fr="http://orbeon.org/oxf/xml/form-runner"
    xmlns:xf="http://www.w3.org/2002/xforms"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:xxf="http://orbeon.org/oxf/xml/xforms"
>
    <xh:head>
        <xh:title>Date tester</xh:title>
        <xf:model  xxf:function-library="org.orbeon.oxf.fr.library.FormRunnerFunctionLibrary">
            <xf:instance id="test">
                <date/>
            </xf:instance>
            <xf:bind nodeset="instance('test')" type="xs:date"/>
        </xf:model>
    </xh:head>
    <xh:body>
        <xh:table>
            <xh:tr>
                <xh:td width="100">fr:date</xh:td>
                <xh:td>
                    <fr:date ref="instance('test')">
                        <xf:label appearance="minimal">Test Date</xf:label>
                        <xf:alert ref="'Not a Date'"/>
                    </fr:date>
                </xh:td>
            </xh:tr>
            <xh:tr>
                <xh:td width="100">xf:input</xh:td>
                <xh:td>
                    <xf:input ref="instance('test')">
                        <xf:label appearance="minimal">Test Date</xf:label>
                        <xf:alert ref="'Not a Date'"/>
                    </xf:input>
                </xh:td>
            </xh:tr>
        </xh:table>
    </xh:body>
</xh:html>
```

**Comment by ebruchez** [comment]
So far, `fr:date` was designed and configured for forms that run within Form Runner. For example, it comes with JavaScript which is only loaded when Form Runner is in use. In fact, that might be the main reason it doesn't work at all for you.

Form Runner configures the JavaScript this way. On the main `<xf:model>`:

```xml
xxf:assets.baseline.excludes="/ops/javascript/scalajs/orbeon-xforms.js"
```

Then refers to the Form Runner JavaScript via:

```xml
<xh:script type="text/javascript" src="/apps/fr/resources/scalajs/orbeon-form-runner.js"/>
```

Missing CSS might also be an issue.

**Comment by ahenket** [comment]
There's probably more going on, because those two things did not work, in a sense made it worse for xf:input as not even the tiny thing that could be the widget comes up now.

There's no error or other visual to go on. If you say that I should forget about fr:date in my situation, then that's fine too, but then I need to wait for the xf:input fixes to be released.

**Comment by avernet** [comment]
I've updated this issue's title to reflect that this is about allowing `fr:date` to be used in plain XForms, outside of Form Runner. I've also updated your example, which was missing a namespace declaration for `xs`. And yes, you'll have to either compile Orbeon Forms CE yourself to include the [fix](https://github.com/orbeon/orbeon-forms/commit/c6e08363e577f863508dc673ee31e7a88805fd76) for #4103, or wait for an Orbeon Forms 2018.2.2 CE.

**Comment by avernet** [comment]
We've started taking some steps towards moving `fr:date` at the XForms level, and some things are working already, but definitely need more polishing.

**Comment by avernet** [comment]
Now the example posted at the top of this thread shows as follows:

<img width="281" alt="Screen Shot 2019-06-26 at 5 03 28 PM" src="https://user-images.githubusercontent.com/106961/60223022-54352080-9834-11e9-8556-d1fa0c98b67b.png">

Note:

- You still need to add `xxf:function-library="org.orbeon.oxf.fr.library.FormRunnerFunctionLibrary"` on your first model.
- `appearance="minimal"` on the label has no effect.

**Comment by ahenket** [comment]
I'm assuming that the one size fits all solution in properties-local.xml still holds too. This saves my form about knowing which Orbeon version they are called by

```
<property as="xs:string" name="oxf.xforms.function-library" value="org.orbeon.oxf.fr.library.FormRunnerFunctionLibrary"/>
```

**Comment by avernet** [comment]
Yes, adding `org.orbeon.oxf.fr.library.FormRunnerFunctionLibrary` to `oxf.xforms.function-library` works as well, and indeed is most likely a better way to go.
