### ISSUE TITLE
Add days to a date picker

### ISSUE THREAD

**Issue by danieldotnet** [orbeon/orbeon-forms#4133]
I would like to add 14 days to the selected date, only then should the entry be valid. Specifically: If the selected date is further in the future than +14 days then the entry is valid.
How can I do this in the XPath field (validation)?

**Comment by avernet** [comment]
Hi @danieldotnet, we use this area of the project to keep track of verified bugs and Request for Enhancement. For community support, I would instead encourage your to repost this on [discuss.orbeon.com](http://discuss.orbeon.com).

**Comment by danieldotnet** [comment]
OK, thank you.
