### ISSUE TITLE
Consider deprecating eXist support

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#4141]
We support less features with eXist, and we don't recommend customers use it in production.

Two possibilities for the demos:

- Use an embedded Java SQL database.
- Move more aggressively towards creating Docker VMs, in which case we can just ship with for example  MySQL or PostgreSQL and skip entirely the step of using a special demo database.

**Comment by ykowalewski** [comment]
For me using eXist DB is very helpful. It allows us to install and test different versions of Orbeon Forms in a few steps. If you know what to do you can have working env in a few minutes without installing and configuration any other DB. 
The idea with docker has at least one disadvantage: You need to have installed docker on your computer.

**Comment by ebruchez** [comment]
@ykowalewski Thanks for the feedback. In fact, we have already deprecated eXist since 2019.1 in [the documentation](https://doc.orbeon.com/configuration/advanced/exist-db). We simply don't have the bandwidth to maintain support for it, but until we have a replacement it's going to stay there for demos and quick installs.

**Comment by ebruchez** [comment]
Closing as it is deprecated. See #3321 for Docker-releated ideas.
