### ISSUE TITLE
Second parameter of `xxf:sort()`: string or item?

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#4145]
The [doc](https://doc.orbeon.com/xforms/xpath/extension-functions/extension-xml#xxf-sort) explicitly mentions it must be a string, but in practice ([test case](https://github.com/orbeon/orbeon-forms/files/3456831/view.txt)) it seems that it must be a string, which makes more sense to me, as in general parameters are evaluated before they are passed to functions, and in this case it must be evaluated relative to the result of the first argument. Should the documentation be changed?

**Comment by ebruchez** [comment]
> it must be a string, but […] it must be a string

Seems contradictory. The doc says it must be an `item()`, and the implementation as well. But there is a twist and the doc says "it does not take a plain string but a literal expression".

In fact the second parameter behaves like a "by name" parameter in Scala: it is an expression and re-evaluated in context for each item. This might be contrary to XPath semantic but it works with Saxon. Ideally, with XPath 3, the second parameter should be a function.

**Comment by ebruchez** [comment]
This said, once the expression evaluates for each value to sort, the value is atomized, and used this way for comparison.

**Comment by avernet** [comment]
It seems you're confirming that the documentation is correct. Then the problem is that if I run the following:

    xxf:sort(
        instance(),
        activityDataList/createdOn,
        'text',
        'ascending'
    )"/>

I get the error:

> `A sequence of more than one item is not allowed as the second argument of xxf:sort() (<createdOn/>, <createdOn/>, ...)`

And if I pass the value of the second argument as a string (`'activityDataList/createdOn'`), I don't get any error, but the list isn't sorted. It looks to me that "by name" argument passing isn't happening. Also, I'm not convinced this is the right thing to do as this concept is foreign to XPath.

**Comment by ebruchez** [comment]
Maybe try:

```
(activityDataList/createdOn)[1]
```

We probably can't change this how this function works now. We'd need another function, and again passing a lambda would be the right thing to do.

**Comment by avernet** [comment]
My bad: `xxf:sort()` works as documented, and it is my test that was incorrect. Closing.
