### ISSUE TITLE
Supported liferay version

### ISSUE THREAD

**Issue by srinivas-os** [orbeon/orbeon-forms#4157]
The documentation at https://doc.orbeon.com/form-runner/link-embed#supported-liferay-versions seems to be a little outdated - it does not include the liferay compatibility for most recent Orbeon versions, i.e. 2018.2 and 2019.1.

Which liferay version do these Orbeon versions work with, please?

**Comment by ebruchez** [comment]
Thanks, we have updated the versions supported with 2018.2. Orbeon Forms 2019.1 is not available yet.
