### ISSUE TITLE
Test and support Liferay 7.2

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#4159]
[+1 from customer](https://3.basecamp.com/3600924/buckets/8287464/messages/1994563606#__recording_1996831500)

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/15921610/messages/2441178381)

**Comment by ebruchez** [comment]
After fixing #4468, things work with Liferay 7.2. Still need:

- [ ] test with all built-in examples
- [ ] update the documentation to mention support

Since this does not require big code changes, we can include this with 2019.2.2.
