### ISSUE TITLE
Repeated sections: customizable label for "Add Another Repetition"

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#4166]
This could be similar to #4117.

- Instead of using `<fr:iteration-label>`, we could use `<fr:add-iteration-button-label>`.
- The Form Builder dialog would also just add one more tab for configuring this label.
- `<fr:section>` needs to use `<fr:add-iteration-button-label>` when present.

So it would be fairly simple.

[+1 from customer](https://3.basecamp.com/3600924/buckets/6592477/messages/1043089882#__recording_2022190054)

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/6794635/messages/2022661807)

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/2192969/messages/2047672839#__recording_2050174609)

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/7873395/messages/2077533470)

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/1966556/messages/2881750196)

**Comment by avernet** [comment]
[+1 from user](http://discuss.orbeon.com/Repeating-grids-sections-questions-from-a-novice-td4665738.html)

**Comment by ebruchez** [comment]
This appears to be a duplicate of #3911, which we implemented already.
