### ISSUE TITLE
The "Date" control in Form Builder does not provide a WCAG compliant label

### ISSUE THREAD

**Issue by dropddesigns** [orbeon/orbeon-forms#4194]
To meet WCAG 2.0 success criteria 1.3.1 and 3.3.2, the most common approach is to use label elements to associate text labels with form controls.

Unfortunately, for the "Date" control, the label is output as:
<span class="xforms-label">Label text</span>

In many other input controls, the label is a <label> element and uses the for attribute to reference the ID of the form control.

**Comment by ebruchez** [comment]
The good news is that a fix is fixed already as part of commit b250e46d2fd16dddf062b25b7af155db4df0fb48, which will be included in Orbeon Forms 2019.1. So I am closing this. Thanks for reporting.
