### ISSUE TITLE
Selecting control value in template sometimes leaves blank value

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#4198]
This uses the new dropdown (#1433). It's unclear when exactly it happens but I had it happen a couple of times.

<img width="836" alt="Screen Shot 2019-09-27 at 2 55 43 PM" src="https://user-images.githubusercontent.com/105769/65804488-efd97400-e136-11e9-8f65-dcfef042b424.png">

**Comment by ebruchez** [comment]
Here is an example where it doesn't work: I added a second row, select the value, but it shows as missing and prevents saving the dialog.

<img width="1024" alt="Screen Shot 2019-09-30 at 1 30 22 PM" src="https://user-images.githubusercontent.com/105769/65914595-88b1fe80-e386-11e9-8772-c0d7892cc166.png">

**Comment by avernet** [comment]
It seems that when the selection is made, the server isn't informed that it happened, and thus the server believes that the field is still blank.

**Comment by avernet** [comment]
🎡 Reproduce:

- For a newly created control, open the Control Settings dialog, switch to the Label tab
- Click on the "+" button twice, click on the first dropdown, select `(control-1)`
- Hit the tab key, and the error "Missing value" shows (while we just selected one!)

**Comment by avernet** [comment]
After removing the workaround from `Select1Search.scala`, I don't seem to be able to reproduce this problem, so I am removing this workaround in 2023.1.
