### ISSUE TITLE
Using XForms from Java apps, can't generate PDF or get a review

### ISSUE THREAD

**Issue by fallphenix** [orbeon/orbeon-forms#4217]
I use Orbeon CE for testing, 
i start to deploy **orbeon.war** with external eXist-DB.
Then  i deploy **orbeon-xforms-filter.war** like a Java app with config below : 
`<web-app
    version="2.4"
    xsi:schemaLocation="http://java.sun.com/xml/ns/j2ee http://java.sun.com/xml/ns/j2ee/web-app_2_4.xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="http://java.sun.com/xml/ns/j2ee">
    
    <filter>
        <filter-name>orbeon-xforms-filter</filter-name>
        <filter-class>org.orbeon.oxf.servlet.OrbeonXFormsFilter</filter-class>
        <init-param>
            <param-name>oxf.xforms.renderer.context</param-name>
            <param-value>/orbeon</param-value>
        </init-param>
        <init-param>
            <param-name>oxf.xforms.renderer.default-encoding</param-name>
            <param-value>U9.0.26TF-8</param-value>
        </init-param>
    </filter>

    
    <filter-mapping>
        <filter-name>orbeon-xforms-filter</filter-name>
        <url-pattern>/xforms-jsp/*</url-pattern>
        <dispatcher>REQUEST</dispatcher>
        <dispatcher>FORWARD</dispatcher>
    </filter-mapping>

        
<filter-mapping>
    <filter-name>orbeon-xforms-filter</filter-name>
    <url-pattern>/orbeon/*</url-pattern>
    <dispatcher>REQUEST</dispatcher>
    <dispatcher>FORWARD</dispatcher>
</filter-mapping>

</web-app>
`

I want to test xform when using external Java App : 
Consider the simple form created with form builder (form.xhtml) : 

`<xh:html xmlns:xxf="http://orbeon.org/oxf/xml/xforms" xmlns:xxi="http://orbeon.org/oxf/xml/xinclude" xmlns:saxon="http://saxon.sf.net/" xmlns:fr="http://orbeon.org/oxf/xml/form-runner" xmlns:xf="http://www.w3.org/2002/xforms" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:sql="http://orbeon.org/oxf/xml/sql" xmlns:xh="http://www.w3.org/1999/xhtml" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:exf="http://www.exforms.org/exf/1-0" xmlns:array="http://www.w3.org/2005/xpath-functions/array" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:fb="http://orbeon.org/oxf/xml/form-builder" xmlns:map="http://www.w3.org/2005/xpath-functions/map" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" fr:data-format-version="4.0.0">
    <xh:head>
        <xh:title>Test_Form1</xh:title>
        <xf:model id="fr-form-model" xxf:expose-xpath-types="true" xxf:analysis.calculate="true">

            
            <xf:instance id="fr-form-instance" xxf:exclude-result-prefixes="#all" xxf:index="id">
                <form>
                    <section-1>
                        <control-1/>
                        <control-2/>
                        <control-3/>
                    </section-1>
                </form>
            </xf:instance>

            
            <xf:bind id="fr-form-binds" ref="instance('fr-form-instance')">
                <xf:bind id="section-1-bind" name="section-1" ref="section-1">
                    <xf:bind id="control-1-bind" name="control-1" ref="control-1" xxf:whitespace="trim"/>
                    <xf:bind id="control-2-bind" ref="control-2" name="control-2" xxf:whitespace="trim"/>
                    <xf:bind id="control-3-bind" ref="control-3" name="control-3" type="xf:boolean"/>
                </xf:bind>
            </xf:bind>

            
            <xf:instance id="fr-form-metadata" xxf:readonly="true" xxf:exclude-result-prefixes="#all">
                <metadata>
                    <application-name>Test_Form1</application-name>
                    <form-name>Test_Form1</form-name>
                    <title xml:lang="en">Test_Form1</title>
                    <description xml:lang="en">Test_Form1</description>
                    <created-with-version>2018.2.1.201902072242 CE</created-with-version>
                    
                <updated-with-version>2018.2.1.201902072242 CE</updated-with-version>
                </metadata>
            </xf:instance>

            
            <xf:instance id="fr-form-attachments" xxf:exclude-result-prefixes="#all">
                <attachments/>
            </xf:instance>

            
            <xf:instance xxf:readonly="true" id="fr-form-resources" xxf:exclude-result-prefixes="#all">
                <resources>
                    <resource xml:lang="fr">
                        <section-1>
                            <label>Champ de formulaire</label>
                        </section-1>
                        <control-1>
                            <label>champ1</label>
                            <hint/>
                            <alert/>
                        </control-1>
                        <control-2>
                            <label>champ2</label>
                            <hint/>
                        </control-2>
                        <control-3>
                            <label>Champ de choix</label>
                            <hint/>
                        </control-3>
                    </resource>
                    <resource xml:lang="en">
                        <section-1>
                            <label>Form fields</label>
                        </section-1>
                        <control-1>
                            <label>field1</label>
                            <hint/>
                            <alert/>
                        </control-1>
                        <control-2>
                            <label>field2</label>
                            <hint/>
                        </control-2>
                        <control-3>
                            <label>Field choice</label>
                            <hint/>
                        </control-3>
                    </resource>
                </resources>
            </xf:instance>

        </xf:model>
    </xh:head>
    <xh:body>
        <fr:view>
            <fr:body xmlns:xbl="http://www.w3.org/ns/xbl" xmlns:p="http://www.orbeon.com/oxf/pipeline" xmlns:oxf="http://www.orbeon.com/oxf/processors">
                <fr:section id="section-1-section" bind="section-1-bind">
                    <xf:label ref="$form-resources/section-1/label"/>
                    <fr:grid id="grid-1-grid">
                        <fr:c y="1" x="1" w="6">
                                <xf:input id="control-1-control" bind="control-1-bind">
                                    <xf:label ref="$form-resources/control-1/label"/>
                                    <xf:hint ref="$form-resources/control-1/hint"/>
                                    <xf:alert ref="$fr-resources/detail/labels/alert"/>
                                </xf:input>
                            </fr:c>
                        <fr:c y="1" x="7" w="6">
                            <xf:input id="control-2-control" bind="control-2-bind">
                                <xf:label ref="$form-resources/control-2/label"/>
                                <xf:hint ref="$form-resources/control-2/hint"/>
                        
                                <xf:alert ref="$fr-resources/detail/labels/alert"/>
                            </xf:input>
                        </fr:c>
                        <fr:c x="1" y="2" w="6">
                            <fr:yesno-input xmlns="http://orbeon.org/oxf/xml/form-builder" xmlns:xxbl="http://orbeon.org/oxf/xml/xbl" id="control-3-control" bind="control-3-bind">
                        <xf:label ref="$form-resources/control-3/label"/>
                        <xf:hint ref="$form-resources/control-3/hint"/>
                        
                        <xf:alert ref="$fr-resources/detail/labels/alert"/>
                    </fr:yesno-input>
                        </fr:c>
                        <fr:c x="7" y="2" w="6"/>
                    </fr:grid>
                </fr:section>
            </fr:body>
        </fr:view>
    </xh:body>
</xh:html>`

I put (an rename) this file on tomcat : webapps/orbeon/xforms-jsp/form.jsp.
**1 issue :** Why when access from brower, control buttons are not correclty showing : see screenshort 
![image](https://user-images.githubusercontent.com/2944063/66915227-07a26a80-f008-11e9-8276-8cf71295b2a3.png)
Not that when passing from form builder, all controls are showing correctly : seems like caching.....

2 issue : 
When passing with form builder, PDF and review work fine but when using jsp as viewer i have a 403 error or blank page if allow all http request : 

    <property
  as="xs:string"
  processor-name="oxf:page-flow"
  name="page-public-methods"
  value="GET HEAD POST PUT DELETE"/>

<property
  as="xs:string"
  processor-name="oxf:page-flow"
  name="service-public-methods"
  value="GET HEAD POST PUT DELETE"/>

**Comment by ebruchez** [comment]
To be fair, we haven't tested this mode of operation of Orbeon Forms in a long time, and so it's not surprising that things are not working as expected. We recommend you use the [Java embedding API](https://doc.orbeon.com/form-runner/link-embed/java-api) instead for this purpose.

**Comment by fallphenix** [comment]
Thanks for your  quick response.
I tested the embedding api and it work fine and the two issues are not occured.
However, i have a question about licence : 
Is it possible to  have embedding java api en CE mode ?
I see it is said that   : "It  is said that : "orbeon-embedding.war which ships 
with Orbeon Professional Edition (PE) only" "

Best

**Comment by avernet** [comment]
You read it correctly: the embedding API is a PE-only feature. Feel free to download a PE build and get a trial license from the [download page](https://www.orbeon.com/download), and if you have any problem with that, I'd recommend you post about it on [Discuss](http://discuss.orbeon.com), as we typically only use the issues section on GitHub for verified issues.
