### ISSUE TITLE
Consider migration of fr:autocomplete

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#4242]
We deprecated the "old Autocomplete" control in Orbeon Forms 2019.1. This means that at some point, it might be removed. It'd be nice to have a way to migrate uses of `fr:autocomplete` to the new "with search" controls when possible.

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/2192969/messages/2433501018)
