### ISSUE TITLE
Ability for "new" button on summary page to always use the latest version of the form

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#4244]
This irrelevant of the version selected in the dropdown at the top of the page.

[+1 from customer](https://3.basecamp.com/3600924/buckets/12679874/messages/2150980514)

**Comment by ebruchez** [comment]
[Documentation](https://doc.orbeon.com/configuration/properties/form-runner/form-runner-summary-page#new-button-version-of-the-form)
