### ISSUE TITLE
Support again `<xf:output>` with text content

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#4255]
E.g. `<xf:output>gaga</xf:output>`.

It would be simple enough to, in `XFormsOutputControl.scala` override the `computeValue` defined in `XFormsValueControl.scala` as `boundItemOpt map DataModel.getValue getOrElse (throw new IllegalStateException)` to get the value from `element.getText` if `boundItemOpt` is `None`.

But maybe we want to do this in the static analysis, as done for the LHHA, in `LHHAAnalysis.scala`, which evaluates a `staticValue`, and maybe that LHHA code could be reused.

[+1 from customer](https://3.basecamp.com/3600924/buckets/7545500/messages/2167677241)

**Comment by ebruchez** [comment]
- [ ] check `<xf:output>` within `<xf:message>`
- [ ] handle `mediatype="text/html"`?
- [ ] unit test
