### ISSUE TITLE
Ability to add resources to the baseline

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#4281]
We have the ability remove resources through `xxf:assets.baseline.excludes`, but not add them. This RFE calls for supporting a similar attribute `xxf:assets.baseline.includes` to add files to the baseline. This will allow us to have `scalajs/orbeon-form-runner.js` in the baseline for Form Runner, which will (a) reduce the size of the JavaScript above the baseline as users move from form to form, and (b) allow users of the JavaScript embedding API (#1577) to only include 1 JavaScript file.

**Comment by ebruchez** [comment]
- [x] XForms support
- [ ] Form Runner support

We want to:

- set a baseline (CSS/JS) for Form Runner (all modes/pages) which includes `orbeon-form-runner.js`
- set a baseline (CSS/JS) for the Form Builder detail page *only* which does not include `orbeon-form-runner.js` but includes `orbeon-form-builder.js`

What about:

- `oxf.fr.summary.baseline.updates.*.*`
- `oxf.fr.detail.baseline.updates.*.*`
