### ISSUE TITLE
Review password field status in the toolbox

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#4289]
There is really almost no reason ever to use a password field. It shouldn't be prominently placed at the top of the toolbox alongside common controls. Proposing its own section all the way at the bottom of the toolbox.

**Comment by ebruchez** [comment]
@avernet makes the points that:

1. while it doesn't have any use as a "password" field, as a "secret" field it has some uses
2. we could make this an appearance of an input field, even though in XForms it isn't

For 1, We simply need to rename the control's description in Form Builder. For 2, we can update the XBL binding, however just placing this appearance doesn't cause Form Builder to use the "direct name" `xf:secret` in the form definition source. So we need to do some extra work, such as wrapping the control in XBL.

**Comment by ebruchez** [comment]
Now that the control is named "secret", it's probably ok to keep it in the toolbox even if we allow this as an appearance for a regular input field.

**Comment by acspike** [comment]
Could an appearance be added that provides a disclosure button to allow a user editing the form to temporarily view the value? Would it be possible to use an xpath expression to control the ability to trigger the disclosure button?

**Comment by avernet** [comment]
@acspike Yes, this would make sense, and we've heard about this from other customers before. I've created #5020 to track what you're referring to. And I am closing this as we're good, as noted by @ebruchez [earlier](https://github.com/orbeon/orbeon-forms/issues/4289#issuecomment-567698997), with keeping the Secret control in the toolbox.
