### ISSUE TITLE
XBL companion `destroy` method to be called when switching wizard page

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#4372]
The `destroy` method should be called because:

- A component with `javascript-lifecycle` might want to do its own cleanup (e.g. date control unregistering listener).
- For all components, the XForms engine client-side code needs to remove the companion object from the list of active companion objects it keeps track of.
- This will help us reduce memory leaks with embedding (#1577).

**Comment by ebruchez** [comment]
Currently, `fr|tinymce` doesn't support the `javascript-lifecycle` mode. `destroy()` is only called when that mode is present. So this explains that.

One way to go would be to move this component (and maybe others) to use `javascript-lifecycle`.

**Comment by ebruchez** [comment]
Trying this with the Wizard:

- S1 with a text control
- S2 with an `fr:number` (`control-2`) control (which has `javascript-lifecycle`)
- S1 → S2: `xxf:init` initializes the control
- S2 → S1: nothing is in the response for `control-2`
- S1 → S2: `xxf:init` again
