### ISSUE TITLE
Upgrade to TinyMCE 5

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#4382]
We should also try to use TinyMCE as a module to avoid conflict with embedding apps that may use another version of TinyMCE.

[+1 from customer](https://3.basecamp.com/3600924/buckets/1966555/messages/2241319160#__recording_2265086486)

**Comment by ebruchez** [comment]
#1753 covered the upgrade to TinyMCE 4.

**Comment by ebruchez** [comment]
See [Usage with module loaders](https://www.tiny.cloud/docs/advanced/usage-with-module-loaders/).

**Comment by ebruchez** [comment]
Also keep in mind we might need a backport to 2018.2.

**Comment by avernet** [comment]
- [ ] @avernet Backport to version TBD (is it 2019.2 or 2018.2?)
- [ ] @ebruchez Test with Liferay, fix issues happening with Liferay as necessary
