### ISSUE TITLE
Don't allow server event to be executed more than once

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#4386]
Right now it seems that the client can send server events (`<xxf:event name="xxforms-server-events">`) to the server multiple times, and the server will happily execute them each time, which we shouldn't do and is a potential security risk.

Maybe when the server sends server events to the client, it can store a fingerprint of the server events (or other id) in the dynamic state, when it receives the server events, check if the fingerprint is in the dynamic state, if so remove it and execute the server events, if not discard the server events. Something along those lines would also fix #4385.

**Comment by ebruchez** [comment]
`XFormsServer` produces server events in the following cases:

- 2-pass submissions with `replace="all"` (no delay)
- full portlet loads (no delay)
- delayed events

They are provided:

- during initialization as `rpc.ServerEvent`
    - they are processed right away
    - it appears that these can only be delayed events (no submission/portlet load)
- in an Ajax response as `server-events`
     - events with delay are scheduled right away
     - event, if any, for submission/portlet load is stored and later handled with `submission`
- submission/portlet load events are sent to the server via `$server-events`

Each `xxf:server-events` element in the Ajax response encodes a single event, with the possible exception of the submission/portlet load where both might be present? Unclear if they should be or not.

**Comment by ebruchez** [comment]
For #4385, making the UUID part of the event would be enough. For #4386 we need another piece of data.

Storing extra state on the server is possible but annoying. For example, if each delayed event has an entry on the server, the list of events might increase without bounds if, for some reason, the client doesn't send them back to the server to process and clear them (cases of an attack or a bug). We could garbage-collect them after a delay.

Note that we don't know the sequence number the event will have since there is a delay in sending it and an undetermined number of sequence numbers can happen before that.

**Comment by ebruchez** [comment]
See also "Prevent double submission for xf:submission replace="all" #1726. The server events stored into `$server-events` and submitted alongside the POST should also run only once. Fixing this issue should fix #1726.

**Comment by ebruchez** [comment]
Possible implementation:

- each server event
    - is stored into an XFCD list with an id and expiration time
    - includes that id and UUID
- each incoming sever event
    - is checked for UUID first and rejected if not matching
    - is checked against the list and rejected if not matching, removed from the list if present
- each time a client request arrives, the server events list is garbage-collected based on expiration times

**Comment by ebruchez** [comment]
For `DelayedEvent`, this is what we do now:

- we store them in XFCD (`_delayedEvents`)
- before returning control to the client, we call `processDueDelayedEvents()` which process all dues events only leaves future events in `_delayedEvents`
- remaining events are encoded and sent to the client (init or Ajax response)
- `_delayedEvents` is cleared
- encoded events are sent back to the server as needed

We could have a different way of doing this:

- store all `DelayedEvent`s and submission events in XFCD
     - submission events could be placed first in the queue specially (delay = `None`)
- process due events except `None`
- tell the client ONLY to ping the server after the shortest delay in the remaining events (can be 0) with `xxforms-poll`
- server receives `xxforms-poll` event and starts by processing due events (first submission events)
- processed events are removed from the list
- *NOTE: Events must be serialized to the dynamic state.*

**Comment by ebruchez** [comment]
- [ ] implement
- [ ] modify tests

**Comment by ebruchez** [comment]
Questions that arose discussion with @avernet:

1. Do we care if an event comes in after much longer?

One realistic scenario, besides an attack, is the browser's [bfcache](https://developers.google.com/web/updates/2019/02/back-forward-cache): browsers can pause a page indefinitely, and then resume it. While it's paused, no events are dispatched, no HTTP requests, etc.

So in the the case of a poll event, it might come after minutes, hours, or never. This is probably ok though, and we probably don't need to do anything special at this point.

2. Do we need to gc events?

My worry was that an attacker could keep adding events. But if the events are only added on the server and the client only sees poll events, this cannot happen.

**Comment by ebruchez** [comment]
Since we don't support the full portlet (#3264), we don't need to worry about "full portlet loads".

**Comment by ebruchez** [comment]
`UploaderProcessor` also returns `<xxf:server-events>` containing an `xxforms-upload-done`.

**Comment by ebruchez** [comment]
- [ ] Q: Do we still need the `$server-events` hidden form field?

**Comment by ebruchez** [comment]
- two-pass submission only
    - server issues `xxf:submission` only
    - client submits HTML form (which may or may not navigate in the same browser context)
    - server must check delayed events to process `xxforms-submit`
- delayed events only
    - server issues `xxf:server-events` only OR new `xxf:poll` for earliest event time
    - client must fire poll event after delay
    - server must check delayed events to process available events
- both events
    - allowed

I think this calls for adding `xxf:poll` to the Ajax response.

**Comment by ebruchez** [comment]
Clarify the second-pass submission. Before:

- `XFormsModelSubmission`
    - stops short of performing submission
    - `this.activeSubmissionParameters = p`
    - `containingDocument.setActiveSubmissionFirstPass`
        - stored as `transientState.activeSubmissionFirstPass`
- `XFormsServer` response
    - adds `xxf:server-events` for `xxforms-submit`
    - adds `xxf:submission`
- upon incoming POST on `XFormsServer` request
    - server events are processed first

After:

- `XFormsModelSubmission`
    - stops short of performing submission
    - `containingDocument.addTwoPassSubmitEvent`
        - adds `DelayedEvent` with `time = None``
- `XFormsServer` response
    - __no more server events__ (events are in the delayed events queue`
    - adds `xxf:submission`
    - no `xxforms-poll` for `xxforms-submit`
- upon incoming POST on `XFormsServer` request
    - __no more server events__
    - check pending events with `time = None`
