### ISSUE TITLE
"0 is not an instance of java.lang.Boolean" error when uploading file

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#4405]
This is a side effect of `createDelayedServerEvent` having recently (post-2019.2) been rewritten in Scala.js, and the type of its arguments being checked.

**Comment by ebruchez** [comment]
Isn't this fixed by https://github.com/orbeon/orbeon-forms-pe/commit/c016f2438d2a23b721286bb18b3acf0b8b34f793
