### ISSUE TITLE
form tempate in API contains "grid-1"

### ISSUE THREAD

**Issue by adam00s** [orbeon/orbeon-forms#4412]
Version: orbeon-2019.2.0.201912301747-CE

In form.xhtml data returned by API call to .../fr/service/persistence/crud/$app/$form/form/form.xhtml there is error in template called ```<!-- Main instance -->```, for example:
```
        <form>
          <section-1>
            <grid-1>
              <field-nr-1></field-nr-1>
            </grid-1>
          </section-1>
        </form>
```
real data looks like this:
```
<form xmlns:fr="http://orbeon.org/oxf/xml/form-runner" fr:data-format-version="4.0.0">
  <section-1>
    <field-nr-1>test text</field-nr-1>
  </section-1>
</form>
```
In real data there is no ```grid-1``` node. Form runner don't see data saved in this redundant node.

**Comment by ebruchez** [comment]
This is not a bug. I recommend reading through [Form data](https://doc.orbeon.com/form-runner/api/data-formats/form-data). I hope this helps.

**Comment by adam00s** [comment]
Ok, maybe it needs longer explanation, I am referring to scenario:
1) I have published form definition and I need to integrate orbeon with other system, I want to use orbeon as user configurable way of collecting some data.
2) To do so I need to "remotely" initiate new form instance and have reference to it, so I can redirect user to it, and later get data from this form instance.

So, I read API description and found similar scenario (https://groups.google.com/forum/#!topic/orbeon/sLQcvR3bz-g), I understand that there is no way in API to simply create new form instance and get reference to it. So 
1) I have to get form definition, 
2) interpret it 
3) and PUT with call to /fr/service/persistence/crud/$app/$form/data/$doc/data.xml correct "data xml", 
4) so new instance of form is created. 

In form definition got from /fr/service/persistence/crud/$app/$form/form/form.xhtml I found this ```<!-- Main instance -->``` "templete" of correct data format (I am guessing it is correct template and should work later in Form runner), but there is this "grid-1" node (form definition don't have any "Repeated grids") which mess with Form runner. Data saved by Form runner for this form definition have no "grid-1" node, and if I open form instance saved externally including this "grid-1" node, Form runner don't even show the "field-nr-1" for user to enter data.

Of course, I can filter this "grid-1" node knowing that it should not be there, but maybe in other form definition it should be there, how do I know? For me it looks like a bug.

Maybe I am doing this scenario wrong (and there is a way to instantiate new form instance directly from form definition other then rediracting user browser to /fr/$app/$form/new?form-version=?) or should not use this ```<!-- Main instance -->``` "template" - because it is not mantainted to be "correct" and use other, more complex, data from form.xhtml to preper good form instance?

With best regards.
Adam

**Comment by adam00s** [comment]
I have chacked how it looks for repeating grids:
```
        <form>
          <section-1>
            <grid-1>
              <control-1></control-1>
            </grid-1>
            <grid-2>
              <grid-2-iteration>
                <kolumna-nr></kolumna-nr>
                <kolumna-nazwa></kolumna-nazwa>
                <kolumna-ilosc></kolumna-ilosc>
              </grid-2-iteration>
            </grid-2>

          </section-1>
        </form>
```
So there is a difference in definition, so I can make it work like it is now, but it still looks like a bug :-)

**Comment by ebruchez** [comment]
Got it, but still no bug ;)

The way *not* to go is to try to mess with the data format yourself. That is a sure recipe for disaster, if not right now than in the short-term future when you'll need to upgrade Orbeon Forms.

If what you need to do is create empty/initial data in the database, use the [Run form in the background](https://doc.orbeon.com/form-runner/api/other-apis/run-form-background) API, and associate it with a process that just runs `save`.

**Comment by adam00s** [comment]
Ooo, it looks like what I need, thank you. I will try it. It is sometimes very hard to find how to do what you need in orbeon documentation.

**Comment by ebruchez** [comment]
Understood about the documentation. But feel free to ask questions in our [forum](http://discuss.orbeon.com/) and we'll do our best to answer.
