### ISSUE TITLE
Attachment control: option to omit the "download" link

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#4414]
Possibilities:

- separate option
- appearance

In the future we might want more options:

- show the file size
- show the file type (icon? name?)

See also #2708.

[+1 from customer](https://3.basecamp.com/3600924/buckets/1966556/messages/2395789317)

**Comment by avernet** [comment]
Ideally, this should be "dynamic"so form authors can provide an XPath expression to determine whether the current user can download the file, e.g. based on their role, the workflow stage, or something else.

**Comment by ebruchez** [comment]
We can start with static, and then include dynamic? One issue is that we probably can't use variables yet, see #309.

**Comment by ebruchez** [comment]
Suggesting:

```xml
<fr:attachment download="false">

<fr:image-attachment download="false">
```

I don't think we can go with `appearance` as we don't support dynamic appearances at this time, and it won't be easy to change that.

**Comment by ebruchez** [comment]
- [ ] Form Builder custom editor
- [ ] changes to XBL to use preferences
- [ ] form-level preferences
- [ ] `fr:attachment` and `fr:image-attachment`
- [ ] doc
- [ ] backport
- [ ] any tests?

**Comment by ebruchez** [comment]
I was going to do the `show-size` as well, but that's currently handled natively by the XForms processor. So:

- either I don't do this right now
- or I do this by hiding the native size and showing it separately in the XBL component

**Comment by ebruchez** [comment]
The option no longer shows because we pass an `anyURI` datatype in, but the binding does not depend on that datatype. If we find no match that depends on the datatype, then we should also do a search without the datatype.

**Comment by ebruchez** [comment]
[Documented](https://doc.orbeon.com/form-runner/component/attachment#disallowing-attachment-download)
