### ISSUE TITLE
Possible timing issue with JavaScript loading

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#4416]
I haven't reproduced it yet. But it appears that when the first of our large JavaScript files terminates first, we get a JavaScript error.

We set the 4 main scripts with `defer`.

```html
<script 
    type="text/javascript"
    src="/demo/xforms-server/7e9767a99aeb7f344a3a64cc4d16d194dc1c435f/orbeon-3fd829d169eea2ea2f399c5d2d9f23632862abf5.js"
    defer></script>
<script 
    type="text/javascript"
    src="/demo/xforms-server/7e9767a99aeb7f344a3a64cc4d16d194dc1c435f/orbeon-88e714f3615fd67547b07d02cd1dd2a07b4fcc17.js"
    defer></script>
<script 
    type="text/javascript" 
    class="xforms-standalone-resource" 
    defer
    src="/demo/xforms-server/form/static/395787fd34f746f092fbc7f1cc623d431534d90c.js"></script>
<script
    type="text/javascript" 
    class="xforms-standalone-resource" 
    defer
    src="/demo/xforms-server/form/dynamic/f72a16d0f67c518103a61742f7a607088dcf1894.js"></script>
```

The scripts are:

1. baseline
2. additional
3. static
4. dynamic

In the case that fails, the end of loading order is:

1. static
2. dynamic
3. baseline
4. additional

In the successful cases:

1. static
2. dynamic
3. additional
4. baseline

According to MDN:

> Scripts with the defer attribute will execute in the order in which they appear in the document.

This indicates that the time of termination of a script should not change the execution order.

Next steps:

- [ ] enable HTTP proxy (or use `Thread.sleep()` in the right place) to see if we can reproduce  the issue locally

[+1 from customer](https://3.basecamp.com/3600924/buckets/2016476/messages/2364730619#__recording_2383171554)

**Comment by avernet** [comment]
BTW, I do reproduce this, and for me happens quite frequently.

**Comment by ebruchez** [comment]
@avernet with Safari, I assume?

**Comment by avernet** [comment]
@ebruchez Correct.

**Comment by ebruchez** [comment]
Regarding the facades, I have some local changes to move them to a separate subproject.

**Comment by ebruchez** [comment]
For the facades, see b65a9596170706fe1c58c90e53fb6ef8d7cfdf00 and 555054b4eb9e4e49a9e9aff4b0ee403c19f67068.
