### ISSUE TITLE
Option not to cache user info when using header-based authentication

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#4436]
Currently, we are always caching the user info in the session. This is fine for container-based authentication where a user is tied to a session, but can be a problem with header-based, where headers can be provided by code running outside our web app, or even outside the Java container. For instance:

1. User A logs in (outside of container / Orbeon Forms).
2. A request comes to Orbeon Forms with a header telling us it is from user A, Orbeon Forms create a session and stores this information in the session.
3. User A logs out (again outside of container / Orbeon Forms).
4. User B, with the same browser accesses Orbeon Forms. Orbeon Forms doesn't receive a header telling us this is user A, it might even get a header saying this is user B if user B logged in, but Orbeon Forms has cached that information, and lets user B see all the information and perform all the actions that user A can perform, even after user A logged out.

We'll want to have an option to keep the current behavior for customers who are only sending the header once.

[+1 from customer](https://3.basecamp.com/3600924/buckets/7314201/messages/1917269354)

**Comment by ebruchez** [comment]
This should be quite easy to do.

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/2192969/messages/3074495108)
