### ISSUE TITLE
Ability for emails to include link back to the form

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#4461]
* Right now, we can include a link back to the form by adding to the form a hidden field with the document id, and creating the link with an XPath expression using the value of that field. However, since this is such a common requirements, this request for enhancement calls for adding a "Link back to form" to the drop-down highlighted below.
* Orbeon Forms might be able to guess the URL of the server, but it won't always be right, so we should also add a property for admins to specify that URL.

[+1 from user](https://3.basecamp.com/3600924/buckets/14497875/messages/2413677090)

<img width="784" alt="Screen Shot 2020-03-09 at 2 05 00 PM" src="https://user-images.githubusercontent.com/106961/76257586-33b8c500-620f-11ea-80c8-a6e7aecb5feb.png">

**Comment by ebruchez** [comment]
- [ ] define and add "external application path" property
- [ ] add options to dropdown
    - [ ] link to edit
    - [ ] link to view
    - [ ] link to new
    - [ ] link to summary
    - [ ] link to home

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/16100056/messages/2550404248)

**Comment by ebruchez** [comment]
Suggesting property name:

    oxf.fr.external-base-url

**Comment by ebruchez** [comment]
Q: If we use a reference to a template parameter that is inserted in an `href` when the template is in HTML, do we need to escape that URL?

A: The URLs that we produce probably don't have any characters that need escaping. The external base URL, specified by property, probably won't have any either. So we should be fine in this case.

**Comment by ebruchez** [comment]
There is the case of the proxy portlet and embedding. In this case, what should we do? Should we use the current container type (servlet, portlet, embedding) and produce a link accordingly?

For portlet, we already have [specified](https://doc.orbeon.com/form-runner/link-embed/liferay-proxy-portlet#enabling-form-selection-via-url-parameters) parameter names: `orbeon-app`, `orbeon-form`, `orbeon-document`, and `orbeon-page`. We are missing, it turns out, an `orbeon-form-version`.

**Comment by ebruchez** [comment]
In the "Email Settings" dialog, the HTML editor's link dialog doesn't allow entering values in the fields. But with the JavaScript console, I don't seem them readonly or disabled! If I force readonly or disabled, they change the background color. So Something else is preventing those from working. Same with Chrome and Firefox.

**Comment by ebruchez** [comment]
Confirming it's a JavaScript event handler that blocks this for some reason.

**Comment by ebruchez** [comment]
The HTML editor link is working now, for some reason!

**Comment by ebruchez** [comment]
[Doc on links](https://doc.orbeon.com/form-builder/advanced/template-syntax#links)
