### ISSUE TITLE
Dynamic Dropdown Control with service search - errors after clearing value

### ISSUE THREAD

**Issue by mateuszkiec** [orbeon/orbeon-forms#4463]
Orbeon Forms version: 2019.2.0 CE

Error is in dynamic dropdown control. To reproduce error:
- dropdown has to be configured like: "With search": yes, "Service performs search": yes
- Choose any value in field, then cancel value with cross.
- Value disappears (on GUI) but still remains in internal structure. You can see it in calculated value and on validation rules.

You can check the error out using “User” / “Value of field User” controls in this form (as a attachment).

The second problem is in generating PDF based on form. Whenever we correctly fill the dynamic dropdown field (with configuration like in current form) value is not populated to generated PDF.

[orbeon_dynamic_dropdown_error.zip](https://github.com/orbeon/orbeon-forms/files/4312237/orbeon_dynamic_dropdown_error.zip)

**Comment by mateuszkiec** [comment]
I verified your commit. First part of issue was successfully resolved. But the second problem in generation PDF still exists. The same problem is when we use Review option - field is empty.

**Comment by avernet** [comment]
@mateuszkiec, thank you for confirming that the issue when clearing the drop-down is indeed fixed. And yes, I am still working on the PDF issue; I will post an update here when it is taken care of.

**Comment by avernet** [comment]
@mateuszkiec, and the other issue happening with the PDF is now fixed as well.
