### ISSUE TITLE
Uploading a file of zero bytes causes an error

### ISSUE THREAD

**Issue by VirtualSatai** [orbeon/orbeon-forms#4466]
If you upload an empty file to an upload control, it will give a database error:
![image](https://user-images.githubusercontent.com/1919650/76430957-3b17d400-63b1-11ea-9b58-7de4be2f3758.png)

**Comment by VirtualSatai** [comment]
Seems to be related to #2289 which is closed.

**Comment by ebruchez** [comment]
I reproduce this. I am getting the following error:

```
xforms-submit-error - /Users/ebruchez/Google Drive/Work/apache-tomcat-9.0.19/temp/xforms_upload_14750032030631765402.tmp (No such file or directory)
```

**Comment by ebruchez** [comment]
[Possible +1 from customer](https://3.basecamp.com/3600924/buckets/2192969/messages/2847498994)

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/2016476/messages/2882527902#__recording_2890207287)

**Comment by ebruchez** [comment]
- [ ] fix
- [ ] try with 1 byte file
- [ ] backport to customer

**Comment by ebruchez** [comment]
The problem is that we don't create a temporary file if we don't write to the `DiskFileItem`'s `OutputStream`.

**Comment by ebruchez** [comment]
With eXist, there is an additional problem. I am not sure we want to fix that.
