### ISSUE TITLE
Repeated grid shows line in the middle of the header

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#4471]
<img width="922" alt="Screen Shot 2020-03-18 at 10 32 48 AM" src="https://user-images.githubusercontent.com/105769/76989614-e1a92b00-6903-11ea-8ae6-884463e311d1.png">

**Comment by avernet** [comment]
Fixed by 5243524bf5da1c643418a5b064c8ba5409c664ae, due to typo in changes to CSS done for #4134.

**Comment by ebruchez** [comment]
Oops!
