### ISSUE TITLE
Structure search on summary page to support multiple selection controls

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#4479]
Currently we support searching through single-selection controls, but not multiple selection controls.

[+1 from user](https://3.basecamp.com/3600924/buckets/14497875/messages/2536841714)

**Comment by avernet** [comment]
Adding basic support to `fr/summary/view.xhtml` gives the following, which works, modulo cosmetic aspects. For single-selection controls, we always show a dropdown. What should we do for multiple-selection? We don't like lists (shown in the screenshot below), radios can take too much space, so maybe we should go for scrollable checkboxes.

<img width="957" alt="Screen Shot 2020-03-29 at 10 49 45 PM" src="https://user-images.githubusercontent.com/106961/77879675-c4336580-720f-11ea-9b62-9fdd452f2dce.png">

- [ ] Validate approach
- [ ] Switch to scrollable checkboxes
- [ ] Cosmetics: align to the top, vertical bars to all have the same height

**Comment by ebruchez** [comment]
See also #3371.

**Comment by avernet** [comment]
Since eXist support is [deprecated since 2019.1](https://doc.orbeon.com/configuration/advanced/exist-db), we won't be implementing the support for structured searches of multiple selection controls on eXist. However, we'll support it for all relational databases.
