### ISSUE TITLE
Reflow/responsive repeated grids on devices with narrow screens

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#4491]
We already do this for non-repeated grids, and this RFE calls for also supporting reflow on repeated grids.

[+1 from user](http://discuss.orbeon.com/Dynamically-filter-dropdown-list-based-on-other-dropdown-value-td4665072.html)

**Comment by ebruchez** [comment]
The main issue is that for repeated grids that have an external label, we probably need to repeat the labels when in responsive mode. Right now we use `aria-labelledby` and the label is not repeated. So we might have to output the label anyway, and hide it in wide mode but show it in narrow mode.

**Comment by ebruchez** [comment]
+1 from customer

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/2016476/messages/4403335830)

**Comment by avernet** [comment]
Some thoughts on how we could improve the situation just with CSS (and then we could decide whether we want to improve it further by changing the markup we send to the browser):

- We could keep the button showing the dropdown menu, but should:
    - Make sure the menu is usable on mobile
    - Put it on its own row, acting a sort of separator between iterations
        - An alternative would be to keep it on its own column and make it "rowspan" to cover the vertical space for all the rows corresponding to the current iteration, but that doesn't seem possible without changing the markup
- In the `<thead>`, hide the labels (we still need to keep the "+" to cover the case where we have no iterations, in which case users can't use one of the button to create the first iteration)

![grafik](https://user-images.githubusercontent.com/106961/144800231-cf20faa6-c997-4ee7-8d27-b750ccdecf9b.png)

**Comment by ebruchez** [comment]
I note that for repeated grids over multiple rows, which don't have external labels and headings, responsive is good now.

**Comment by ebruchez** [comment]
In order to responsively show a local label or a heading label, we need to output both and hide one or the other via CSS.

This probably means we need to implement #4758 or a variation thereof. With this, we would keep the local label and in addition have the external label.

**Comment by ebruchez** [comment]
- [ ] implement #4758
- [ ] `grid-multiple.xbl` keeps the local label
- [ ] CSS must hide/show appropriate label

Current code that filters local LHH:

https://github.com/orbeon/orbeon-forms/blob/e4bec8f7afd7a99672bfd9ec817730118a5a3617/form-runner/jvm/src/main/resources/xbl/orbeon/grid-common/grid-common.xsl#L264-L269_

**Comment by ebruchez** [comment]
In this case, if we go for the two labels (one internal, and in the cell, and the other one external, in the header), we actually will have the same label value in both cases.

Right now, attaching more than one label, for example one external and one internal, works partially:

- the external label shows, and shows its value
- the internal label shows, and shows its value
- however, statically, only the second label is attached to the form control, because we use a `Map[LHHA, LHHAAnalysis]`

This means that there is no `labelledby` generated on the `<input>` field. However, is this a problem, since we do have the internal label anyway?

**Comment by ebruchez** [comment]
My conclusion so far is that it is not a problem. Therefore, we do not need to implement #4758, and we can focus on the rest.

**Comment by ebruchez** [comment]
Remaining tasks

- [ ] fix full repeated grid borders
    - [ ] with table
    - [ ] with CSS grids
- [ ] TODO

**Comment by ebruchez** [comment]
One more thing to check, see list above.
