### ISSUE TITLE
Readonly attachment doesn't show button as readonly

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#4494]
Following #1238.
<img width="137" alt="Screen Shot 2020-04-09 at 4 46 51 PM" src="https://user-images.githubusercontent.com/105769/78949881-e33cbd80-7a81-11ea-8441-9c40114220e7.png">

**Comment by ebruchez** [comment]
And if you click on the button, the file selector comes.

**Comment by avernet** [comment]
For a regular button, we have `<button disabled class="btn">`. In our case, we have a `<label class="btn btn-file" for="[pointing to the input id]" role="button" tabindex="0">`. We should:

- Have a `disabled` on the `label`: even if not used by the browser, it is used by the Bootstrap CSS to show the button as greyed out.
- Remove the `tabindex="0"`, so we can't focus on that "button", as is the case for disabled buttons.
- The `<input type="file">` should have a `disabled` attribute.

**Comment by avernet** [comment]
For the first bullet above, Bootstrap supports a `disabled` class, in addition to a `disabled` attribute, which sounds better to be since `disabled` is [not expected on a `<label>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled).
