### ISSUE TITLE
Missing `fr:relevant="false"`

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#4519]
The attribute appears to be missing on data saved in the database for non-relevant elements.

[+1 from customer](https://3.basecamp.com/3600924/buckets/1966556/messages/2618140128)

**Comment by ebruchez** [comment]
In `trySaveAttachmentsAndData`, `putWithAttachments` starts by calling `migrate`, which is `maybeMigrateData` and then `MigrationSupport.migrateDataWithFormMetadataMigrations`, which calls `migrateDataInPlace`. It's during that last call that the instance data, which contains relevance information, disappears.

**Comment by ebruchez** [comment]
It comes down to the `insert()` function which clears instance data.

The migration from 4.8 to 4.0 only migrates repeated grids, while the migration from 2019.1 to 4.8 migrates regular grids too, which means all controls. This might explain while we we didn't notice this with only the first migrations, but now the issue has become evident.

The solution probably consists in telling `insert()` not to remove instance data in this case.

**Comment by ebruchez** [comment]
- [] unit tests

**Comment by ebruchez** [comment]
In this case, we call `migrateDataFrom`, which should be called really `migrateDataDown`. The relevance needs to be reserved only when migrating data "down", as the internal format is always the newest (highest). So we don't need to update `migrateDataTo`.
