### ISSUE TITLE
Improve choices for Calculated Values appearances

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#4531]
Currently, we have:

<img width="250" alt="Screen Shot 2020-05-07 at 4 04 58 PM" src="https://user-images.githubusercontent.com/106961/81352938-a06c0680-907c-11ea-92c0-2286080bcb6f.png">

What the first option corresponds to isn't clear, without looking at what the code does. It is selected when we have no `appearance` in the source of the form, in which case the appearance is determined based on the version of Orbeon Forms that was used to create the form.

This issue calls for our code that "upgrades" the form definition when opened in Form Builder to always add an `appearance` when it is missing, following the same algorithm, and in the UI to only keep the "With Border" and "Without Border" radio buttons.

**Comment by ebruchez** [comment]
The runtime `view.xsl` has:

```xslt
<xsl:variable
    xmlns:version="java:org.orbeon.oxf.common.Version"
    name="calculated-value-appearance"
    as="xs:string"
    select="
        (
            (: Consider this a pseudo-XBL component called `fr:calculated-value` :)
            $fr-form-metadata/xbl/fr:calculated-value/@appearance[normalize-space()],
            p:property(string-join(('oxf.xforms.xbl.fr.calculated-value.appearance', $app, $form), '.'))[normalize-space()],
            for $created-version in $fr-form-metadata/created-with-version[normalize-space()]/normalize-space()
                return
                    if (version:compare($created-version, '2018.2') ge 0) then
                        'full'
                    else
                        'minimal',
            'minimal'
        )[1]"/>
```

Note that this actually depends on a property `oxf.xforms.xbl.fr.calculated-value.appearance`, unlike what we had discussed with @avernet earlier. So we can't just use it in Form Builder.

The property by default is:

```xml
<!-- Blank string means `if (fr:created-with-or-newer('2018.2')) then 'full' else 'minimal'`. But we cannot
     actually use that expression, since the logic runs in XSLT. So that behavior is implicit. -->
<property as="xs:string"  name="oxf.xforms.xbl.fr.calculated-value.appearance.*.*"          value=""/>
```

And in `section-and-grid.xsl`, at runtime, we use `$calculated-value-appearance` and for all:

```xpath2
xh:body//xf:output[exists(xf:label) and empty(@appearance)] |
  xbl:binding/xbl:template//fr:section[exists(xf:label) and empty(@appearance)]
```

we add an appearance attribute (except if `$calculated-value-appearance = 'full'`, which is the default).

**Comment by ebruchez** [comment]
The reason we can't use simply `fr:component-param-value()` is that `appearance` must be statically-determined.

We could implement the calculated values control as an XBL component (and we should, in fact), but we can't call `fr:component-param-value()` from the XBL template transformation either, in particular in XSLT, because that function requires the XForms containing document's context to run. In theory, it, or another function, could maybe be used. What we would need:

- the component's context to determine the bound node's attributes
    - this is available from XSLT
- searches the metadata instance dynamically
   - this would require something new
- searches properties
    - this is available from XSLT

So it's not immediately workable, and I think our only solution right now is to rename the first Calculated Value to "Default" or "From Default", where that means, in order:

- from form settings (as usual)
- from properties (as usual)
- from form creation version (special for this case)

**Comment by ebruchez** [comment]
Interestingly, while the code checks the form metadata instance for the form-level default, we don't have a UI for that part. We are not using a custom editor here, but the built-in appearance selection of Form Builder.

Also, we don't generally have a UI for form-level appearance preferences. Discussing with @avernet, it might make sense to have a general mechanism for that. For example. you'd want to say you want, by default, all forms to have dropdowns with search.

Another issue we have is this:

1. We'd like ideally the selection to say:
    - "Use default"
    - "With border"
    - "Without border"
2. But these labels are also used in the toolbox.
    - Right now, we use the first one, so we can't just say "Use default". We need to say "Calculated value".

We could change the label of the first one to say just "Use default". But then, it's weird from a control metadata perspective.

Or, could we add, optionally, a separate appearance label in the control metadata? For example under `<appearance-name>`? This would solve that. If that's missing, just use the `<display-name>`.

~~Could we use, in the meanwhile, a custom editor to change the appearance?~~

**Comment by ebruchez** [comment]
New UI:

<img width="169" alt="Screen Shot 2020-05-08 at 5 44 23 PM" src="https://user-images.githubusercontent.com/105769/81459210-9bc65180-9153-11ea-8a02-f56a0bfddd76.png">
