### ISSUE TITLE
On publish, can't select version number previously published as unavailable

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#4532]
For instance, here I published version 1, then 2, then 2 as unavailable. Then when publishing, I can select to publish over version 2, as soon in the screenshot below. Is this a regression?

<img width="502" alt="Screen Shot 2020-05-07 at 5 30 50 PM" src="https://user-images.githubusercontent.com/106961/81357517-bbdd0e80-9088-11ea-916a-94405b50b227.png">

**Comment by ebruchez** [comment]
We use `event('versions')` which only contains available versions.

- [ ] It would be nice if we could also indicate if the version is available or not in the dropdown.
