### ISSUE TITLE
Ajax requests missing value change events

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#4537]
While entering the app/form names quickly, typing "a", tab, "a", tab, I end up with the following, with the focus on the form title field:

<img width="749" alt="Screen Shot 2020-05-13 at 11 02 59 PM" src="https://user-images.githubusercontent.com/106961/81898634-ec7fe500-956d-11ea-8e48-2ff897d167a1.png">

I have 2 Ajax requests sent by the browser (see below). In the first the client tells the server the app name is "a" and that the form name field got the focus. Good. But in the second we just have events related to the title field. Some seem superfluous (why are we send the value, since I didn't change it? why that blur immediately followed by a focus?), but the main thing is that the client isn't telling the server about the form name value having changed to "a".

```xml
<!DOCTYPE xxf:event-request [<!ENTITY nbsp "&#160;">]>
<xxf:event-request xmlns:xxf="http://orbeon.org/oxf/xml/xforms">
        <xxf:uuid>1e437adeeef8c75b664ca48f797dc22931eb2367</xxf:uuid>
        <xxf:sequence>1</xxf:sequence>
        <xxf:action>
            <xxf:event name="xxforms-value" source-control-id="dialog-form-settings≡xf-1556≡xf-1759≡fb-app-name-input">
                <xxf:property name="value">a</xxf:property>
            </xxf:event>
            <xxf:event name="xforms-focus" source-control-id="dialog-form-settings≡xf-1556≡xf-1759≡fb-form-name-input"></xxf:event>
        </xxf:action>
</xxf:event-request>
<!DOCTYPE xxf:event-request [<!ENTITY nbsp "&#160;">]>
<xxf:event-request xmlns:xxf="http://orbeon.org/oxf/xml/xforms">
        <xxf:uuid>1e437adeeef8c75b664ca48f797dc22931eb2367</xxf:uuid>
        <xxf:sequence>2</xxf:sequence>
        <xxf:action>
            <xxf:event name="xxforms-blur" source-control-id="dialog-form-settings≡xf-1556≡xf-1759≡fb-title-input"></xxf:event>
            <xxf:event name="xforms-focus" source-control-id="dialog-form-settings≡xf-1556≡xf-1759≡fb-title-input"></xxf:event>
            <xxf:event name="xxforms-value" source-control-id="dialog-form-settings≡xf-1556≡xf-1759≡fb-title-input">
                <xxf:property name="value">Untitled Form</xxf:property>
            </xxf:event>
            <xxf:event name="DOMActivate" source-control-id="dialog-form-settings≡xf-1556≡xf-1759≡fb-title-input"></xxf:event>
        </xxf:action>
</xxf:event-request>
```

**Comment by ebruchez** [comment]
Curiously, right now, I don't reproduce this.

**Comment by avernet** [comment]
Me neither, and I tried maybe 30 times. Yesterday I reproduced it on my second try. (Bad) luck?

**Comment by ebruchez** [comment]
It happened to me a few times at least at some recent point.  Maybe it was due to 99043a8c4a92849a9a9622bab8931c83ba69b550. Let's keep an eye on it.

**Comment by ebruchez** [comment]
Ah now I can reproduce it by throttling the connection to "Slow 3G" in Chrome.

**Comment by avernet** [comment]
Good! (Better catch this earlier than later.)
