### ISSUE TITLE
JavaScript error related to state with Edge 18 in Form Builder

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#4540]
<img width="919" alt="Screen Shot 2020-05-15 at 8 13 08 AM" src="https://user-images.githubusercontent.com/105769/82066267-04498d00-9684-11ea-81b6-69775a72575a.png">

**Comment by avernet** [comment]
I am not reproducing the above error, however I have the seen the following in the console, even if this is seemed asymptomatic. The errors happened at different times.

    SCRIPT5007: SCRIPT5007: Unable to get property 'open' of undefined or null reference
    SCRIPT5007: SCRIPT5007: Unable to get property 'innerWidth' of undefined or null reference

**Comment by avernet** [comment]
I am not seeing any of those issues with the new Blink-based versions of Edge, so suggest that starting with 2020.1 we don't support the old versions of Edge for Form Builder.

**Comment by avernet** [comment]
Resolved: we will only support the latest version of Edge for Form Builder. Closing.
