### ISSUE TITLE
Presentation of Validation and Alerts tab

### ISSUE THREAD

**Issue by AddledMe** [orbeon/orbeon-forms#4551]
In version 2019.2.2 the Validation and Alerts tab in Control Settings are not presented correctly. Release notes don't seem to suggest this was intentional. 

[Optional suggestion: label the checkbox with text such as "Use default message."]

**In 2019.2.2:**
![Orbeon 2019 2 2 Test - Misaligned Validation](https://user-images.githubusercontent.com/25515537/82836642-bef33f80-9e7b-11ea-82e8-645d26abefe3.JPG)

**Compare 2019.1.0:**
![Orbeon 2019 1 0 - Aligned Validation](https://user-images.githubusercontent.com/25515537/82836791-1f827c80-9e7c-11ea-859e-f9242bba3038.jpg)

**Comment by ebruchez** [comment]
Thanks for reporting. I think that this is covered by #4523, which is fixed already. Closing this one as a duplicate.
