### ISSUE TITLE
Loading indicator not disappearing on back

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#4552]
Steps to reproduce:

1. Load the Form Builder summary page.
2. Click on a form to open it in Form Builder.
3. Hit back, you get back to the summary page, which works fine, but the loading indicator is incorrectly showing and doesn't seem to go away.

This isn't happening with version 2019.2.2 deployed on `demo.orbeon.com`.

**Comment by ebruchez** [comment]
Seems to be only with Safari. It works with Chrome and Firefox.

**Comment by ebruchez** [comment]
Actually I don't see this even on Safari with the dev tools open.

**Comment by ebruchez** [comment]
I see it with the dev tools open if I enable the cache.

Could it be related to the bfcache?

**Comment by ebruchez** [comment]
When we navigate, we have:

- Ajax request
    - shows indicator
- Ajax response processing
    - form  `submit()`
    - directly calls `LoadingIndicator.show()`
    - sets `loadingOtherPage = true`
    - then `hide()` is scheduled and gets to `0`, but doesn't actually hide because we have `loadingOtherPage == true`

The idea is probably that we want to keep the indicator as long as possible, and we don't care that it doesn't hide except when using the bfcache.

We never set `Globals.loadingOtherPage = false` except upon page load.

It's pretty messy.

We could use the `pageshow` event when `persisted == true` and, in this case, if the counter is `0`, hide it. Also set `Globals.loadingOtherPage = false`.

**Comment by ebruchez** [comment]
Note that the `freeze` and `resume` events mentioned [here](https://developers.google.com/web/updates/2018/07/page-lifecycle-api) don't appear to have made it into browser implementations.
