### ISSUE TITLE
Dynamic Dropdown Control with service search - not resolving references to other fields

### ISSUE THREAD

**Issue by mateuszkiec** [orbeon/orbeon-forms#4556]
Orbeon Forms version: 2019.2.2
[Dynamic_Dropdown_Control_fields_ref.zip](https://github.com/orbeon/orbeon-forms/files/4694723/Dynamic_Dropdown_Control_fields_ref.zip)

Error is in dynamic dropdown control: search option does not support multi-parameters (parameters depending on other fields - it was working correctly on autocomplete control). To reproduce error:

- dropdown has to be configured like: "With search": yes, "Service performs search": yes

- Resource URL should have parameter depending on other field (e.g.: User depends on Gender)

- Choose value in first field (e.g.: Gender)

- Search for values in Dynamic Dropdown (e.g.: does not resolves value of Gender field - resource request is sent with empty gender value).

 

Error: Resource request does not resolves value of depending fields (resource request contains empty values of depending fields).

**Comment by avernet** [comment]
@mateuszkiec I think this is the same as #4535, which we just fixed last week. I wanted to check that, but with your example, what should I enter in the first "Name" field for anything to show in the "User" dropdown? And then, I imagine that I should see a different result depending on whether I select "female" or "male" in the "Gender" dropdown, correct?

**Comment by mateuszkiec** [comment]
Name is not important leave it empty. After you select male or female in Gender field the Resource Request for user should contain additional query condition resulting in narrowing the list of users accordingly. As a result of the error empty value of gender is put in Request Query (empty value is ignored by server and list is not narrowed).

**Comment by mateuszkiec** [comment]
I think that fix implemented in issue #4535 is correct. After applying it to Orbeon 2019_2_2 CE version, I can't reproduce this issue :).

I will close current issue.
