### ISSUE TITLE
Actions Editor to support setting hint for control choices

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#4566]
Right now we can set the label and value, but not the hint. This RFE calls for also supporting the hint. We only want to show the additional text field for the hint if checkboxes or radio buttons are selected.

<img width="803" alt="Screen Shot 2020-06-11 at 4 46 39 PM" src="https://user-images.githubusercontent.com/106961/84449825-5b02a200-ac03-11ea-9fd5-d72e58c983b3.png">

[+1 from customer](https://3.basecamp.com/3600924/buckets/1966556/messages/2752149072)

**Comment by ebruchez** [comment]
The [`<fr:control-setitems>` action](https://doc.orbeon.com/form-builder/advanced/services-and-actions/actions-syntax#setting-the-choices-of-a-selection-control) should also be updated to take an additional `hint` attribute.
