### ISSUE TITLE
Error when switch a non repeatable library section to repeatable in a new form

### ISSUE THREAD

**Issue by brunobuzzi** [orbeon/orbeon-forms#4588]
http://discuss.orbeon.com/Repeatable-Section-but-not-repeatable-in-library-td4665303.html
Check:
![Orbeon-bug](https://user-images.githubusercontent.com/4719282/85614898-d1ef6000-b631-11ea-8c42-dc9426cbfcb1.gif)

**Comment by brunobuzzi** [comment]
Duplicated with #4599 
Fixed in the latest master branch
@ebruchez this is duplicated --> closed too

**Comment by ebruchez** [comment]
@brunobuzzi Sorry, I hadn't realized that you had entered an issue already.

**Comment by brunobuzzi** [comment]
Hi @ebruchez 
does the master branch has been deployed to https://demo.orbeon.com/ ?

Because the issue still happening. Tested today on Orbeon Demo.

The problem is the same of GIF above.

Also my local Orbeon (2020.1.202012300129) also has the same problem.

**Comment by avernet** [comment]
@brunobuzzi Not yet, but @ebruchez has that on his to do list ;). BTW you can see the version of Orbeon Forms by going to the Form Settings dialog, and then About this Form tab.
