### ISSUE TITLE
Angular component for form embedding

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#4617]
The component is to provide a higher level user experience compared to the JavaScript embedding API.

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/1956846/messages/4379370774)

**Comment by avernet** [comment]
We now have a prototype, used as:

```xml
<fr-form
    app="orbeon"
    form="controls"
    orbeonContext="/orbeon"></fr-form>
```

**Comment by obruchez** [comment]
See #6251 for the multiple forms embedding problem.
