### ISSUE TITLE
Control when and where the captcha is shown

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#4651]
Right now, when enabled, the captcha is always showing. This is not ideal for forms showing as a wizard, as in some of those cases it would only make sense to show the captcha on the last page of the wizard. This RFE calls for adding two properties:

- A first property will allow admins to define whether the captcha should be shown, for instance using the function `fr:is-wizard-last-page()` to only show it on the last page of the wizard.
- A second property will allow admin to determine whether the captcha is shown inside or outside of the wizard. In some cases, for instance when the captcha is only shown on the last page of the wizard, showing the captcha inside the wizard makes more sense.

[+1 from customer](https://3.basecamp.com/3600924/buckets/1966556/messages/2945911312)

**Comment by ebruchez** [comment]
For reference, doc is [here](https://doc.orbeon.com/configuration/properties/form-runner/form-runner-detail-page#showing-inside-the-wizard)
