### ISSUE TITLE
Click on Save while background `xforms-server` call in progress causes forever spinning

### ISSUE THREAD

**Issue by daniszabolcsatoll** [orbeon/orbeon-forms#4656]
See this video demonstrate:
https://drive.google.com/file/d/1AulmHpr4ptfX9bQ2uwRpi3eEixy7V1vG/view

fact: xforms-server http request goes in background as you click on elements.
problem: If you press SAVE while unfinished background xforms-server http request, the button will stuck in disabled spinning forever, but save request doesn't go out. The customer just wait, wait...

It could happens if use a big form or a slow internet (i use that in the video)

I was able to reproduce at orbeon demo site.

thank you in advance,

**Comment by ebruchez** [comment]
- [ ] check on 2020.1.4
- [ ] check on master (`-rebase`)

**Comment by avernet** [comment]
I checked this isn't happening with 2020.1.4 and with the latest code from `offline-support-1221-rebase`. So for now, I am closing this, but @daniszabolcsatoll, just let us know if it looks like I missed anything.

https://user-images.githubusercontent.com/106961/134953618-c46c644a-23ec-4fef-94f2-afcd614741ce.mp4
