### ISSUE TITLE
Consider dropping support for IE11

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#4674]
We probably won't do this in 2020, but 2021 is likely.

* Microsoft Team stops supporting IE11 on November 30, 2020
* Microsoft 365 stops supporting IE11 on August 17, 2021
* IE11 receives security updates as long as Windows 10 is supported
* [IE11 has a share at 2.61%](https://gs.statcounter.com/browser-market-share/desktop/worldwide)
* Application ending IE11 support
    * 2020-11-30 Microsoft Teams
    * 2021-08-17 Microsoft 365

**Comment by ebruchez** [comment]
Vue 3 [is dropping IE11](https://news.ycombinator.com/item?id=27140836).

**Comment by ebruchez** [comment]
IE11 share is now at 1.08%.

**Comment by avernet** [comment]
Resolution: we drop support for IE11 in 2022.1.

**Comment by ebruchez** [comment]
We will add this to the compatibility section of the release notes.
