### ISSUE TITLE
More than 128 role crashes the form reader

### ISSUE THREAD

**Issue by croo** [orbeon/orbeon-forms#4688]
If you use header authentication with either json credentials or header-roles/groups/username configuration, the number of roles orbeon can handle is (around) 128. More than that promtly crashes the form.

Reproducable on a newly downloaded orbeon, with the following config in properties-local.xml

```
<property
    as="xs:string"
    name="oxf.fr.authentication.method"
    value="header"/>

<property
    as="xs:string"
    name="oxf.fr.authentication.header.username"
    value="My-Username-Header"/>
<property
    as="xs:string"
    name="oxf.fr.authentication.header.group"
    value="My-Group-Header"/>
<property
    as="xs:string"
    name="oxf.fr.authentication.header.roles"
    value="My-Roles-Header"/> 
```

And with ModHeader browser addon put more than 128 role in "My-Roles-Header", seperated by | .

**Comment by avernet** [comment]
Can you tell us more about what the "crash" looks like? Are you getting an exception in the `orbeon.log`?

**Comment by avernet** [comment]
Closing, since we don't have more information about.
