### ISSUE TITLE
Unable to bind a repeated grid to data element with another namespace

### ISSUE THREAD

**Issue by Leo7k** [orbeon/orbeon-forms#4696]
I need to bind a repeated grid to data element with another namespace, but I am unable to do it.
I am getting the following error message

> There was an error during form publishing.

when trying to publish the following form:
[2.txt](https://github.com/orbeon/orbeon-forms/files/5428294/2.txt)

This happens because of repeated grid is binded to tns:Objects data element. After changing it from tns:Objects to Objects, it works fine ([1.txt](https://github.com/orbeon/orbeon-forms/files/5428293/1.txt)). But I _need_ to bind a repeated grid to tns:Objects data element.
I need a fix (or workaround) for this as soon as possible.

**Comment by avernet** [comment]
@Leo7k, I am sorry but at this point, binding to elements in a custom namespace isn't supported by Form Builder or Form Runner. In cases where you need more control over the XML data structure that contains the data entered by users, we recommend you use XSLT to transform the XML document produced by Form Builder / Form Runner into the document you need.
