### ISSUE TITLE
Labels for dropdowns "with search" are not tied to the dropdown

### ISSUE THREAD

**Issue by mateuszkiec** [orbeon/orbeon-forms#4713]
To reproduce create a Static dropdown with search, or Dynamic dropdown with search, and notice that a `<span>` is generated for the label (not a `<label for="">`), and that there is no element with a `aria-labelledby` pointing back to the that `<span>` (either of which would be fine, per WCAG).

<hr>

Original description from @mateuszkiec:

Label "Choose color" is simple <span> element. It should use <label for=""> statement like in any other controls. It is a WCAG error, and it breaks label convention commonly used in other orbeon controls.

Component used: Radio buttons. Control Appearance: with search.

[wcag_label_radiobuttons.zip](https://github.com/orbeon/orbeon-forms/files/5582712/wcag_label_radiobuttons.zip)

**Comment by avernet** [comment]
@mateuszkiec The main issue you reported with the dropdowns with search is now fixed, and a proper `<label for="…">` is generated. Thank you for letting us know about this! Regarding the radio buttons and checkboxes, the correct HTML is generated: the element around all the controls is marked with a `role`, e.g. `role="radiogroup"`, and it has an `aria-labeledby` pointing to the `id` on the element that contains the label.

<img width="1079" alt="2020-11-24 - Group pointing to the label" src="https://user-images.githubusercontent.com/106961/100189419-2462d000-2ea1-11eb-93fd-7247e769abcf.png">
