### ISSUE TITLE
 Multiple File Attachments to support constraints on files in Control Settings

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#4725]
In Control Settings - Validations and Alerts, in the Validation Type dropdown, instead of "Maximum Length" and "Minimum Length", we should have "Maximum Attachment Size" and "Supported File Types", as shown in the 1st screenshot below.

<img width="985" alt="image" src="https://user-images.githubusercontent.com/106961/102038740-e4468d00-3d7c-11eb-8392-af9b6c6e77ab.png">

**Comment by ebruchez** [comment]
Problem is we test on `anyURI` datatype for this. `fr:attachment[@multiple = true]` doesn't set this datatype, and so the constraints don't show in the dialog.

However, if an attachment constraint is present, it is used by the component. So we just need to updated the condition for what is an attachment control in the dialog.

Pushed a commit to test this.

- [ ] cp on master/2020.1-ce
- [ ] close when tested

**Comment by avernet** [comment]
The fix done by @ebruchez works, closing.
