### ISSUE TITLE
Error summary produces multiple elements with the same id

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#4782]
![image](https://user-images.githubusercontent.com/106961/108585535-d1f94a00-72fd-11eb-9583-c8ab61a4023f.png)

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/2192969/messages/3490765344)

**Comment by avernet** [comment]
This can be reproduced quite simply with the following:

```xml
<xh:html xmlns:xh="http://www.w3.org/1999/xhtml"
      xmlns:xf="http://www.w3.org/2002/xforms"
      xmlns:xxf="http://orbeon.org/oxf/xml/xforms"
      xmlns:ev="http://www.w3.org/2001/xml-events"
      xmlns:xs="http://www.w3.org/2001/XMLSchema"
      xmlns:fr="http://orbeon.org/oxf/xml/form-runner">
    <xh:head>
        <xf:model>
            <xf:instance>
                <_>
                    <iteration>1</iteration>
                    <iteration>2</iteration>
                </_>
            </xf:instance>
        </xf:model>
    </xh:head>
    <xh:body>
        <xf:repeat ref="iteration">
            <xf:trigger appearance="minimal">
                <xf:label>
                    <xh:span class="{.}">Click me</xh:span>
                </xf:label>
            </xf:trigger>
        </xf:repeat>
    </xh:body>
</xh:html>
```

This produces the following 2 triggers. Notice how the ids on the inner `<span>` are both `xf-7`. Those ids are produced because we have an attribute with an AVT, and it looks like in this case we don't property namespace the id. (Once we do, we should check that updates of the value are also done properly.)

```html
<span id="xf-5⊙1"
      class="xforms-control xforms-trigger xforms-trigger-appearance-minimal xforms-repeat-selected-item-1 xforms-update-full">
    <button id="xf-5≡≡c⊙1" class="btn-link">
        <span class="1" id="xf-7">Click me</span>
    </button>
</span>
<span id="xf-5⊙2" class="xforms-control xforms-trigger xforms-trigger-appearance-minimal xforms-update-full">
    <button id="xf-5≡≡c⊙2" class="btn-link">
        <span class="2" id="xf-7">Click me</span>
    </button>
</span>
```

**Comment by ebruchez** [comment]
I reproduce this. We have two implementations now:

1. the old one using `XFormsElementValue.getElementValue`
2. the new one using `XFormsStaticElementValue.getElementExpressionOrConstant`

Both add a prefix to the id, but no repeat suffix.

```scala
containerPrefix + currentAttributeValue
```

For the (obsolete) case of 1, we could use some context to add a suffix to the id.

But for the case of 2, the XPath expression is computed entirely statically. So we'd need to call a function to know the current repeat suffix. We could generate something like:

- if the expression is not within a repeat (statically), just add the prefixed id like now
- if the expression is within a repeat (statically), add an expression to compute the suffix, for example:
    ```scala
    xxf:repeat-suffix()
    ```
