### ISSUE TITLE
Date field to keep invalid valid values, instead of autocorrecting them

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#4794]
- *Current behavior* – Right now, when users tab out of the date field either the date in the field is valid, is made to be valid, or is blanked. Because we want to avoid blanking out the field, we're trying very hard to make what users type into something that is valid.
- *Problem* – For instance, if they type `13/1/2020`, we change it to `1/1/2020`. But this isn't necessarily what the user wanted, and this can be an accessibility problem as some users are likely not to notice that the value has been changed when they leave the field.
- *Suggested change* – Except for cases where we are unlikely to misinterpret the users' input (e.g. changing `today` into today's date), we want to keep the invalid dates entered by users as-is in the field, and mark the field as invalid.
- *Implementation* – In case of invalid input, the value in the form data will be blanked, as is the case now, but the value typed by users will be stored in an attribute, e.g. `invalid-input="13/1/2020"`, and the field marked as invalid.

[+1 from user](http://discuss.orbeon.com/Wrong-date-format-td4665705.html)

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/2016476/messages/3534191818)

**Comment by ebruchez** [comment]
The following scenario must also be handled:

- form data contains `xxx` for a date field (for example from a calculation/initial value)
- load the form
- the field initializes but immediately clears the value so the user never sees the invalid value

We'd like instead the incorrect value to show in the field.

See WIP in https://github.com/orbeon/orbeon-forms-pe/commit/eb9b83ed361fe0339c0583ad6fa49442d4697c5b

**Comment by ebruchez** [comment]
Identified the following case:

- date in data has invalid month or day, for example  `2021-11-31`
- on the server we validate this correctly (as invalid)
- value sent to client
- client uses crap algorithm and so this is considered valid on the client and then converts to `2021-12-01`

So I added one step of validation on the client to consider dates like `2021-11-31` as invalid. Next step is that we then clear the date picker, but that cause the value to blank too and then the server receives a blank date. So trying to find a way to fix that.

**Comment by ebruchez** [comment]
I managed to clear the date picker without sending an event upon initialization. The issue I have now is that when you open the date picker after that, it opens on a funny date. For example  with value `2021-11-33`, the date picker shows year 1933. This is better than clearing the value silently, though.

**Comment by ebruchez** [comment]
Some changes done for 2021.1, see above.

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/2192969/messages/3477658309)

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/23878674/messages/6416436396)

**Comment by ebruchez** [comment]
With 2022.1:

- "July 1 2020" does clear the field
- "8/3/12345" is truncated and seems to store 8/2/1234

**Comment by ebruchez** [comment]
See also what we did for #5534.

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/1966480/messages/7547078722#__recording_7755710818)

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/2192969/messages/7807543742)

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/1977373/messages/8052481253)

**Comment by ebruchez** [comment]
Curiously, I see in the code that we use `opts.forceParse = false` since 2022.1.

**Comment by ebruchez** [comment]
Upon `change` of value in the input field, we query `datePicker.getDate()`, which calls `this.dates` (an JS array of `Date`). If I enter "1/50/2024", that date is already "Sun Feb 18 2024 16:00:00 GMT-0800", so it was parsed with adjustments.

We should not ask the date picker for the date when the value of the field changes.

Interestingly, when selecting a date in the picker, the `change` event doesn't appear to be dispatched to the `input`, even though its value changes. How is that?

**Comment by ebruchez** [comment]
Quick brainstorming again. We'd like to do all of the above, ideally.

We also need to think about the following cases:

- storing ISO date entered by user, if UI format is not ISO
    - in this case, we should ideally mark the value as invalid, not store it, otherwise it will roundtrip to something different
- storing value with `T` for `dateTime`
    - if the user enters a value with `T`, we don't want that to pollute the `dateTime` value

Right now, neither Date nor Time have a local value in the XBL. But maybe we should consider doing that, especially for Date:

- local value
- copy value in/out as needed
- local constraint for date validity per format
    - can this work properly, in particular wrt Error Summary?
- if local invalid value
    - write special `invalid` token to external data, or `fr:invalid`, or `#INVALID`, or…
    - write invalid value as `fr:invalid-value` attribute
- if local valid value
    - write value to external data
    - remove `fr:invalid-value` attribute
- if external invalid value per token and attribute
    - read it to local data

Another solution might consist in not using an attribute, but in writing the invalid value escaped.

- for example
    - `invalid-2/50/2024`
    - or `fr:2/50/2024`
    - or fancier escaping
- possible issue reading currently invalid data?

Right now we think that the attribute solution would be cleaner.

**Comment by ebruchez** [comment]
- [ ] handle case where value from server is for example  `2023-02-29`: the client sees the pseudo-ISO date value

**Comment by ebruchez** [comment]
I think that right now, the only problematic case is the user entering an ISO date, which causes the roundtrip-style autocorrection. I think we can consider this a bug, but it is not high priority IMO compared with the other cases we have solved, as users are unlikely to enter ISO dates.

**Comment by avernet** [comment]
What if we just parsed valid ISO dates (just as we parse "today")? Wouldn't that solve the problematic case?

- `2025-01-06` ⇒ `1/6/2025` on tab out
- `2025-01-32` ⇒ `2025-01-32` on tab out

We want to avoid the risk of incorrectly interpreting the user's intent. However, a valid ISO date doesn't look like any other formatted date, so there is close to zero risk of misinterpreting a value entered by the user if it happens to be a valid ISO date. (Besides, currently, it will be interpreted as such later, typically when the data is reopened.)

**Comment by avernet** [comment]
We can ignore my last comment as the current implementation already does exactly what I was suggesting :).
