### ISSUE TITLE
Quick control search in Form Builder

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#4841]
When a form is large, and especially if it has many collapsed sections, it is hard to find a particular control. We need a search feature. It would work like this:

- keyboard shortcut (`/` or `⌘-J` or …) and search icon
- pops up a panel with a search field
- search returns controls/grids/sections by name
- options could allow searching controls by label, etc.
- selecting the search result (`enter`?) focuses on the control/grid/section and opens the related settings

**Comment by ebruchez** [comment]
- [ ] basic implementation
- [ ] option to directly open the Control/Container Settings (keep option "sticky" for session)
- [ ] option to search grids/sections
- [ ] option to search by control name
- [ ] P2: option to search others (actions/services?)

**Comment by ebruchez** [comment]
For "scroll Form Builder view to control", the JavaScript `scrollIntoView()` method works but it oftens scrolls in a funny way. For example if the control is already visible in the viewport, it will still scroll it, which is something we probably want to avoid. So we should implement our own algorithm.

**Comment by avernet** [comment]
@ebruchez Have you tried `scrollIntoView(false)`? The default value for the first parameter, `alignToTop`, is `true`, which could maybe explain the behavior you were seeing?

**Comment by ebruchez** [comment]
I haven't tried, but MDN says:

> If `false`, the bottom of the element will be aligned to the bottom of the visible area of the scrollable ancestor.

which doesn't look like what we'd like either. Instead I implemented custom logic depending on where the element is:

https://github.com/orbeon/orbeon-forms/blob/c2a46743f7bfbd8bd76a8343d169406f200515c3/form-builder/js/src/main/scala/org/orbeon/builder/FormBuilderPrivateAPI.scala#L56-L83

**Comment by ebruchez** [comment]
[Documented](https://doc.orbeon.com/form-builder/form-editor/quick-control-search)
