### ISSUE TITLE
Summary table to be full width

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#4855]
Unlike pages that show paragraphs of texts, where having a narrower layout can improve legibility, tables benefit less from a narrower layout, and I think we would better off having the summary page use whole page width, as is already the case for the Form Runner home page.

(In the future, we could let users choose, as does Roam; see screenshot below.)

<img width="449" alt="image" src="https://user-images.githubusercontent.com/106961/114962732-1ac21080-9e20-11eb-85c8-fcf1e7fb5f36.png">

[+1 from customer](https://3.basecamp.com/3600924/buckets/20062825/messages/3670232546)

**Comment by avernet** [comment]
@ebruchez Can we consider that this is done, and close this RFE?

**Comment by ebruchez** [comment]
Yes, in fact this was covered by #5228. Closing this as duplicate.
