### ISSUE TITLE
Support converting between data formats in the persistence proxy

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#4863]
Following #3110, #4804, and #4861.

With #4804 we added form definition conversion in the persistence proxy. This means we are pretty close from being able to do this for form data as well.

This requires retrieving the form definition, and for performance reasons we should also implement caching of the form definition.

With this, we can, instead of returning a 400, convert between data format when the `data-format-version` parameter is passed.

**Comment by avernet** [comment]
Duplicated of #4135
