### ISSUE TITLE
Dynamic dropdown without search empty in subsequent iterations of repeat

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#4868]
To reproduce, add a dynamic dropdown to a repeat grid, run the form, add iterations, and notice how the dropdown is empty in all the iterations except the first one. This doesn't happen if the dynamic dropdown is "with search".

[+1 from customer](https://3.basecamp.com/3600924/buckets/16915667/messages/3665921221)

**Comment by ebruchez** [comment]
Duplicate of #4945. Closing.
