### ISSUE TITLE
NPE in `LHHAElementVisitorListener` when called by `getStaticChildElementValue`

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#4870]
Following #4782.

We can't use `contextStack` in static mode.

[+1 from customer](https://3.basecamp.com/3600924/buckets/1956846/messages/3706959345)

Note that this code is not present on master (for the upcoming 2021.1).

**Comment by ebruchez** [comment]
Instatic mode (that is, the value doesn't depend on XPath), if we have (or generate) an `id` attribute, we consider the value constant. We would need to rewrite ids separately when we output the value  instead of using the XPath context.

**Comment by ebruchez** [comment]
- [ ] check how we do it on master now
- [ ] test Error Summary again

**Comment by avernet** [comment]
I checked @ebruchez cherry-picked the commit on `2020.1-pe` branch, and marked this as done for the 'Orbeon Forms 2020.1.3 project. Can this be closed, or is there still something left to do for some of the items mentioned above?
