### ISSUE TITLE
"Required item type of first operand" error in the logs

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#4877]
Full error:

```
Required item type of first operand of '/' is node(); supplied value has item type xs:string
```

Due to `<fr:grid ref="''">` in `view.xsl`. See comment on offline branch and find solution.

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/2167032/messages/2339159861)

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/1956846/messages/3758475757)
