### ISSUE TITLE
Don't package `orbeon-proxy-portlet.jar` inside the `orbeon.war`

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#4904]
It should only go in the `proxy-portlet.war`. Since the file isn't the same, this is also confusing to users, some of them mistakenly taking the `orbeon-proxy-portlet.jar` from the `orbeon.war` instead of the `proxy-portlet.war`, which then leads to `NoClassDefFoundError`.

[+1 from customer](https://3.basecamp.com/3600924/buckets/8287464/messages/3640073060)

**Comment by ebruchez** [comment]
We also don't need/want `orbeon-embedding.jar`.
