### ISSUE TITLE
Templates used in field labels are not expanded in emails using an All Value Controls

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#4905]
As a result, one would receive an email that could look as follows:

![image](https://user-images.githubusercontent.com/106961/119415881-549bf780-bca7-11eb-91f4-b9116531a6a0.png)

[+1 from customer](https://3.basecamp.com/3600924/buckets/6794635/messages/3770981332)

**Comment by ebruchez** [comment]
The process that prepares the email runs as a service, but it's a curious thing: it uses both the XML provided, but also the implicit in-scope document set by the caller of the service.

This means that we are able to directly query the labels without re-evaluating them.

**Comment by ebruchez** [comment]
Fix done on the offline branch.
