### ISSUE TITLE
`toString` in `scala.xml.Elem` not producing well-formed XML

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#4927]
In a case reported by a customer, the following error happened, but this bug could cause all kind of parsing error. It seems to happen when scala-xml serializes the value of an attribute that contains both single and double quotes. It decides to use a single quote for the attribute, but doesn't escape the single quotes in the value of the attribute.

    Fatal error: Element type "constraint" must be followed by either attribute specifications, ">" or "/>".

This problem is present in scala-xml 2.0.0-M1. They are now is a final version (2.0.0), which hopefully fixes this issue, but it is only published for Scala.js 1.5, and we are using Scala.js 0.6.2. The update to scala-xml 2.0.0-M1 was [done](https://github.com/orbeon/orbeon-forms-pe/commit/52daa6ff06dc8cebe70fc682a51ac0412406cbd1) in January 2020 and the commit just says "Bump scala-xml", so it doesn't look like this version bump was done to solve any problem in particular. So, for now, I am reverting to using scala-xml 1.2.0, which we were using before that.

[+1 from customer](https://3.basecamp.com/3600924/buckets/1966555/messages/3886762881)

**Comment by ebruchez** [comment]
With `scala-xml` 2.0.0 things appear to work as well with customer form.

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/7044591/messages/4081172492)
