### ISSUE TITLE
File scan API: ability to return specific error message, mediatype, filename

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#4960]
This would make sense.

[+1 from user](https://mail.google.com/mail/u/0/#inbox/FMfcgzGkZstnWMCwDgQSqLLwcsxDbdGf)

**Comment by ebruchez** [comment]
A similar request is to allow the API to return a new `Content-Type`.

**Comment by palimondo** [comment]
In the current API, which does not offer an explicit return value for the message, we have tried to propagate the error message from our `FileScanProvider` to the Orbeon by throwing a _runtime exception_, assuming that the exception message would be propagated to the user, but that did not work.

**Comment by ebruchez** [comment]
Changing this is a possibility. The question is whether we would want any exception messages propagated to the user, as there can be intentional and unintentional exceptions. One possibility would be to make messages part of the API by requiring exceptions to derive from a particular exception class, such as a `FileScanException`. Any other exception would still cause the generic error message to show.

**Comment by ebruchez** [comment]
The current form language should be passed so that the message can be return in that language.

**Comment by ebruchez** [comment]
Closing as subsumed by #4967.
