### ISSUE TITLE
File scan API: allow replacement of the file binary

### ISSUE THREAD

**Issue by palimondo** [orbeon/orbeon-forms#4962]
In [the comment ](https://github.com/orbeon/orbeon-forms/issues/4960#issuecomment-901371934)to #4960, Erik mentions the ability to change the `Content-Type`. In our use case, where we are integrating the OPSWAT Metadefender as the `FileScanProvider`. Their Deep CDR feature, can perform file sanitization, which produces new binary after the file scanning (eg. removing macros from Word documents). This can be even configured to perform file type conversions (eg. Word to PDF transformation).

Our current solution is to [upload the file](https://docs.opswat.com/mdcore/metadefender-core/ref#fileanalysissyncpost) to Metadefender during the file scan operation and then swapping the file binary for the [sanitized](https://docs.opswat.com/mdcore/metadefender-core/ref#sanitizedfile)/converted version in our custom persistence layer (based on the original file hash).

Maybe this use case scenario can be supported by an extension of the `FileScanProvider` API.

**Comment by palimondo** [comment]
I forgot to mention, one more thing that might be good to consider for a potential extension of the FileScan API. The file conversion process on Metadefender can be also configured to [rename the converted file](https://docs.opswat.com/mdcore/deep-cdr/setup-output-file-name). This is related to potentially converting the file type (`Content-type`).

**Comment by ebruchez** [comment]
So we'd have a requirement to support updating all of the following:

- mediatype (`Content-Type`)
- filename
- content

**Comment by ebruchez** [comment]
Closing as subsumed by #4967.
