### ISSUE TITLE
Form Runner `success-message()` and `error-message()` to support HTML

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#4964]
We should update the actions with an `html` or `is-html` or other parameter.

[+1 from customer](https://3.basecamp.com/3600924/buckets/4224335/messages/4066064082#__recording_4068931697)

**Comment by obruchez** [comment]
- [ ] doc

**Comment by ebruchez** [comment]
[Doc](https://doc.orbeon.com/form-runner/advanced/buttons-and-processes/actions-form-runner#success-message-and-error-message)
