### ISSUE TITLE
Fix build and merge offline and other branches

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#4971]
- [x] fix Proguard build
- [x] fix tests
- [x] check `println(s"xxxx $jsonString")`
- [x] merge Excel import/export feature
- [x] fix/reword commit messages especially those containing "xxx" and "TODO"
- [x] cherry-pick rebases on `pe` branch
- [x] figure out how to cherry-pick on `master` (CE) branch
    - [x] create catalog of existing differences between CE/PE (files, etc.)
    - [x] next step as needed (hopefully move towards a better solution)
- [x] review `2020.1-pe` branch for commits that are missing on `master`
- [x] review `wip-dependencies` to see if some fixes  need to be cherry-picked

**Comment by avernet** [comment]
> `fr:number`: `1.2` is invalid if grouping separator is `,` fails

This is now fixed on master, on `orbeon-forms` and `orbeon-forms-pe`. @ebruchez, I'll let you cherry-pick the [change](https://github.com/orbeon/orbeon-forms/commit/68b44d69ce5274e2bffea3d4e632d2ef5ace67f3) on `offline-support-1221-rebase`, if needed.

**Comment by ebruchez** [comment]
Tests status:

- local
    - all tests pass with `-J-Xmx4G` in `.sbtopts` when `OrbeonClientTest` is disabled
    - `OrbeonClientTest` either fails with "timeout expired" or hangs
- Travis CI
    - build gets stuck when `OrbeonClientTest` is disabled

**Comment by ebruchez** [comment]
I went through diffs between CE and PE as of the master branch. It is not ideal how we are handling this, of course.

Properties a better solution could have:

- differences are grouped together instead of spread around files
    - for example  they could be in one or more separate subprojects (`form-runner-pe`)
- it's ok if we have a few files with diffs, for example
    - property files
    - build files
    - one or two clear spots where, for example, specific components are registered
- database support
    - this needs to be modularized

**Comment by ebruchez** [comment]
Strategy for the `fr.persistence` changes:

- list features that warrant these changes (encryption, etc.)
- modularize on `-rebase` or PE `master` to have as much as possible separate files
    - 1 commit is common code
    - 1 commit is PE-only files
- on CE `master`
    - cp common code commit
    - create new CE-only files

**Comment by ebruchez** [comment]
Features under `fr.persistence`:

- encryption
- Oracle / DB2 / SQL Server
    - `Provider` has most diffs
    - but some code in `FlatView`

**Comment by ebruchez** [comment]
- [x] `FlatView`: move specific SQL to `Provider` and create PE provider functions
- [ ] `FlatView`: create CE provider functions

**Comment by ebruchez** [comment]
- modularize
    - `PersistenceProxyProcessor.proxyReEncryptStatus`
    - `CreateCols` for `id`
    - `FormRunnerHome.canReEncrypt`
- use new PE file
    - `Permissions`
    - `PersistenceProxyProcessor`
    - `Reindex`
    - `CreateUpdateDelete`
    - `CRUD`
    - `LockUnlock`
    - `Read`
    - `commonPart`
    - `SearchLogic`
    - `RelationalCommon`
    - `RelationalUtils`
    - `FormRunnerPersistence`
- `FieldEncryption`: adjust function params for CE

**Comment by ebruchez** [comment]
CE:

- [ ] update commit "For #4971: split out Form Runner embedding API (PE part)"

**Comment by ebruchez** [comment]
Files that remain different on PE and CE:

- Controls `form.xhtml`
- W9 `data.xml`
- `FormRunnerApp`: to register `xbl.HandwrittenSignature`
- `page-flow.xml`: reencrypt, schema
- `image-attachment.xbl`
- `FieldEncryption`
- `Provider`
- `SimpleDataMigrationTest`: disabled test on CE
- `OrbeonClientTest`: disabled test on CE
- `properties-base.xml`: `oxf.resources.versioned`
- `properties-form-builder.xml`: handwritten signature, Email menu, workflow menu
- `properties-form-runner.xml`: providers, autosave, PDF template/TIFF, lease
- `properties-internal.xml`
- `processors.xml`: reencrypt, XML Schema
- `home.xhtml`: reencrypt
- `README.md`
- build files
    - `build.sbt`: `CE` vs. `PE` string
    - `build.xml`: `CE` vs. `PE` string, `orbeon-src` (CHECK!), `test-db`, `proxy-portlet`, `orbeon-embedding`, 
    - `.travis.yml`: db stuff

**Comment by ebruchez** [comment]
It seems that he replication test now passes!

**Comment by ebruchez** [comment]
`wip-dependencies` handled. New branch `wip-1192-dependencies` created.
