### ISSUE TITLE
Update to `scalajs-dom` 2.8.0 or newer

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#5049]

**Comment by ebruchez** [comment]
Tried this but there is an issue: `scalajs-jquery` is not compiled against 2.0.0 so this doesn't compile. Specifically, `JQueryEventObject` causes problems. We'll need `scalajs-jquery` (or other) compiled against 2.0.0.

Work in progress on local `wip-5049-scalajs-dom-20` branch.

**Comment by ebruchez** [comment]
The `scalajs-jquery` we use (https://github.com/sjrd/scala-js-jquery/commits/master) is not really maintained anymore, and not even linked from the Scala.js site. Instead:

- https://github.com/jducoeur/jquery-facade: newer but no recent release
- https://github.com/UdashFramework/scala-js-jquery: appears up to date, with version 3.2.0 depending on `scalajs-dom` 2.0.0

**Comment by ebruchez** [comment]
See also #5433.

**Comment by ebruchez** [comment]
Not sure about the Udash version now as it hasn't been updated in a year.

**Comment by ebruchez** [comment]
There have been two releases in 2023: 3.2.0 and 3.3.0. JQuery doesn't change often and we are reducing our dependence on it anyway, so hopefully this should be fine.

**Comment by avernet** [comment]
+1 from me, to use `HTMLDialogElement`, already added in 2.3 (released in August 2022).

**Comment by ebruchez** [comment]
+1 again

**Comment by avernet** [comment]
I’ve started looking into this. Let’s see where it takes us! :)

**Comment by avernet** [comment]
- Test
    - [ ] Tooltip for radios/checkboxes
    - [ ] Fancy tree, in particular the listener on `fancytreeactivate`

**Comment by avernet** [comment]
The Select2 library does not emit standard DOM `change` events (see https://github.com/select2/select2/issues/1908) and instead only emits jQuery `change` events. Therefore, we will need to catch the jQuery event within our XBL component and dispatch a corresponding DOM event for `InitSupport.scala`.
