### ISSUE TITLE
Pick and implement solution for the new demo embedded database

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#5063]
With #4141 we deprecated eXist, but we don't have a replacement as of Orbeon Forms 2021.1.

Options:

1. ship with a pure-Java database like [H2](https://www.h2database.com/html/main.html)
2. use Docker to ship Orbeon Forms and a database (either MySQL or PostgreSQL)
3. ship with SQLite with https://github.com/xerial/sqlite-jdbc

Option 3 seems fairly attractive, and since we support already so many databases it shouldn't be hard to add support for SQLite.

**Comment by ebruchez** [comment]
Let's say we go with SQLite:

- [ ] make sure our SQL supports SQLite
- [ ] see how we can ship our schemas and data with SQLite
- [ ] remove eXist support

**Comment by ebruchez** [comment]
Our `postgresql-2019_1.sql` file runs fine in SQLite.

**Comment by ebruchez** [comment]
Gave this a quick try and I am getting a SQL error when publishing the form. Will have to look into it to see if it's indeed some SQL to fix or something else.

**Comment by ebruchez** [comment]
How I setup my datasource in server.xml:

```xml
                    <Resource
                        name="jdbc/sqlite"
                        driverClassName="org.sqlite.JDBC"

                        auth="Container"
                        type="javax.sql.DataSource"

                        initialSize="3"
                        maxTotal="10"
                        maxIdle="10"
                        maxWaitMillis="30000"

                        poolPreparedStatements="true"

                        testOnBorrow="true"
                        validationQuery="select 1"

                        username=""
                        password=""

                        url="jdbc:sqlite:/Users/Shared/orbeon.sqlite"/>
```

**Comment by ebruchez** [comment]
During our latest discussions, the question of the location of the database on disk arose.

The database could be:

- in the WAR file, as we did for eXist
- somewhere else

With the first option, Orbeon Forms can start and find the database immediately. However:

- it might not always be writeable, as it's in the WAR
- redeploying the WAR can erase it

Those are two issues we've had with our embedded eXist in the past.

The first option is the easiest to implement, of course.

If we were to opt for the second solution:

- the user/installer needs to provide a location for the database (via property)
- it would be good to be able to prompt the end user if no datasource is properly configured
- the sample database would have to be copied, either by hand by the user/installer, or automatically by Orbeon Forms if the destination is empty

For #5942, we are thinking about showing an application page if the password is missing/weak. We could use the opportunity to show information about the database as well, if not configured.

**Comment by ebruchez** [comment]
Also a note about introducing a fallback datasource.

We'd like to avoid requiring, for the demo database, that the user/installer setup a datasource in the app server, as that is sometimes a difficult step.

So example forms will point to the `sqlite` provider, associated with a `sqlite` datasource name.

If that datasource cannot be found via JNDI, we create a fallback datasource, determined by a configuration property, which can be present or not (and/or empty or not). That fallback datasource points to SQLite somehow. But its path might be missing. If missing, we will point to the database file within the WAR.

The user/installer could modify that property to specify a location on disk for the demo database.

Remains the question of whether we would copy that database in code, or let the user/installer do it.

**Comment by ebruchez** [comment]
We now have a new banner that shows at the top of every Form Runner page if there is an incomplete product configuration.

Right now, this only means that the main encryption password is too weak or not set.

This `configCheck()` is only run once per server start, lazily, when the first Form Runner page loads. Conceivably, we could also use this to check for an  incomplete database configuration.

The idea is that this would warn a tester/evaluator/installer, who then would look at the logs for the details, as we don't want to reveal the details of the configuration in that banner. Of course, people could get used to seeing that banner, but it is red, so hopefully it will cause some action to be taken.

**Comment by obruchez** [comment]
WAR file from Travis tested with Tomcat 9/10 and WildFly 26/27.

**Comment by obruchez** [comment]
Doc: https://doc.orbeon.com/installation#database-setup

**Comment by obruchez** [comment]
All changes cherry-picked in 2023.1 branches (PE/CE) as well.
