### ISSUE TITLE
New control for showing explanatory text (vs. using output control)

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#507]
Use case: show a block of explanatory text in a form. Right now the text output can be used as a workaround, but:

- Text has to be typed in a text field, which isn't appropriate for longer pieces of text, and it doesn't allow the text to be split in paragraphs.
- A useless element is generated in the XML data.

Instead:

- This control should not have a label or a hint.
- To modify, user should just be click in the cell and type.
- There should be a rich text option.

For now, we can use the [label of output control][1] as a workaround.

  [1]: http://wiki.orbeon.com/forms/doc/user-guide/form-builder-user-guide#TOC-Text-controls

**Comment by ebruchez** [comment]
Something came to mind today: does this control have a data holder and a bind? I assume so as this is the default behavior of the builder.

I think that ideally it should not have a holder unless a "Visibility" expression is set.

**Comment by acspike** [comment]
The merge of #2025 skipped changes in [grid.xbl](https://github.com/orbeon/orbeon-forms/pull/2025/files#diff-61f98068890199fd9988216d9a67558c). This causes the isHTML checkbox to be unchecked and all of the HTML tags to be stripped every time the control is interacted with.

**Comment by avernet** [comment]
@acspike Yes, that was intentional; next step is to use the TinyMCE, and not have a checkbox and mediatype attribute.

**Comment by acspike** [comment]
@ebruchez, I don't understand your comment concerning "data holder and bind" but today I set a visibility expression on an explanation control and nothing happened. How do I fix this?

**Comment by ebruchez** [comment]
@acspike I notice that the component doesn't have a binding with `xxbl:mode="binding"`. It should have one if this is to work.

**Comment by acspike** [comment]
And if I add that, it does work. Thanks.

**Comment by ajw625** [comment]
This control is exactly what we need. Our number one use case includes many large blocks of explanatory text just like this.

**Comment by avernet** [comment]
@ajw625 Cool, so that will be in 4.9, thanks to @acspike!
