### ISSUE TITLE
URL adds `&draft=true` when saving from`/new`

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#5099]
Regressed with #5066.

**Comment by ebruchez** [comment]
Issue is `isDraft` is a String:

```
ORBEON.fr.private.API.newToEdit(documentId, isDraft)
```

The Scala code expects a Boolean:

```scala
def newToEdit(documentId: String, isDraft: String): Unit
```

So the `if (isDraft)` is incorrect at runtime. This is caught with `fastOptJS`.

**Comment by ebruchez** [comment]
- [ ] update on 2021.1 and master

**Comment by avernet** [comment]
Commit on `2020.1-pe`: https://github.com/orbeon/orbeon-forms-pe/commit/0bbc1f7408cef1bfa6b3c28ea07907022300f421
