### ISSUE TITLE
"An error has occurred" dialog shows when going back to the summary page on Safari

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#5133]
On a summary page (e.g. Form Builder's), click on a form to open hit, once open go back, and notice the dialog. This works fine on Chrome.

<img width="956" alt="Screen Shot 2021-12-26 at 9 29 31 PM" src="https://user-images.githubusercontent.com/106961/147437762-5436f149-1f37-488e-8724-6ec96b815669.png">

**Comment by avernet** [comment]
This might be related to the Ajax request sent on click, which fails on Safari, with:

<img width="707" alt="Screen Shot 2021-12-26 at 9 32 57 PM" src="https://user-images.githubusercontent.com/106961/147437888-6baea797-cd87-4bd9-8ea8-12e17c33724b.png">

**Comment by avernet** [comment]
I suspect those are a red herring, as the same errors shows on `demo.orbeon.com`, but going back to the summary page doesn't produce the "An error has occurred" dialog.

**Comment by ebruchez** [comment]
Confirming that the error appears to happen on the Summary page shortly before navigating away to the Form Builder page.

**Comment by ebruchez** [comment]
Noting that when the browser cache is disabled, this doesn't happen.

Now I don't know if we can figure out why exactly the error happens.

However, this happens in a case where we normally retry the request later. However, with the page paused, I guess the retry won't happen as JavaScript execution will be stopped.

This said, it's weird to show an error to the user if there is a failure of the fetch API itself, when we are going to retry anyway.

Maybe we should not show an error dialog in this case. Or we should show it only after a number of retries.

Or we could specifically filter out this error and not show an error dialog in this case.

**Comment by avernet** [comment]
The following solves the problem, and if we don't find a better solution, I would suggest we go with this, at least for now:

Replace:
```xml
<xh:a href="{$current-document-href}">
    <xf:output value="$created"/>
</xh:a>
```

With:
```xml
<xf:trigger appearance="minimal">
    <xf:label ref="$created"/>
    <xf:load event="DOMActivate" resource="{$current-document-href}"/>
</xf:trigger>
```

We also need to change/add some CSS to get the minimal trigger to show like the anchor does now. And we can also move the event handler higher in the DOM to avoid code duplication.
