### ISSUE TITLE
Signature becomes smaller the second time the section is open

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#5149]
<img width="650" alt="Screen Shot 2021-12-31 at 10 17 36 AM" src="https://user-images.githubusercontent.com/105769/147835296-4addd9b5-da39-4b5f-b93f-1950464b0b25.png">

**Comment by ebruchez** [comment]
Confirming this was working with 2020.1.x.

**Comment by avernet** [comment]
Fixed in https://github.com/orbeon/orbeon-forms-pe/commit/ea3f929538e8c767abc9595e740ec640a54d86c9
