### ISSUE TITLE
IE11 unhappy about `this\u00f8`

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#5160]
In the following code, IE11 is having some trouble with the `this\u00f8`, complaining that "the use of a keyword for an identifier is invalid".

> this.eventName = $as_T($ps_Lorg_orbeon_xforms_AjaxEvent__checkArg__Lorg_orbeon_xforms_AjaxEvent__T__F0__s_reflect_ClassTag__O(this, "eventName", new $c_sjsr_AnonFunction0((function(this\u00f8) {

It seems to be produced based on the following:

```scala
val eventName: String =
  checkArg[String](
    "eventName",
    throw new IllegalArgumentException("eventName")
  )
```

The JavaScript has a total of 14 occurrences of `this\u00f8`. This problem only happens with `fastOpt`, and not with `fullOpt`, so we won't consider this is an issue, and I will close this right away, but wanted to have this here for future reference.

**Comment by ebruchez** [comment]
Yes I did notice this during 2021.1 testing in December. Agreed it's not a problem given the `fastOpt` AND IE11 combo.
