### ISSUE TITLE
Initial form data from POST or service must use simple data migration

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#5217]
Right now, such initial data is use as is.

But with [Simple data migration](https://doc.orbeon.com/form-runner/features/versioning#simple-data-migration), we have a way to:

- check for errors such as extra XML elements provided
- allow the caller to just pass the elements/values needed

Right now, Simple data migration is turned on for initial data but only if the form turns it on, which is unintended. We should always enable it, and probably at the `HolesOnly` level.

**Comment by ebruchez** [comment]
[Documented](https://doc.orbeon.com/configuration/properties/form-runner/form-runner-detail-page#initial-data-posted-to-the-new-form-page)

**Comment by avernet** [comment]
I changed the title of this issue to remove "or service ",  as this was implemented and documented as being done only for data POSTed to /new, but not for initial data loaded from a service.
