### ISSUE TITLE
HTTP Service Editor no longer shows response body

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#5224]
[+1 from customer](https://3.basecamp.com/3600924/buckets/16915667/messages/4599335198)

**Comment by avernet** [comment]
Can reproduce with GET on `http://httpbin.org/xml`.

**Comment by ebruchez** [comment]
Confirming that I do reproduce this.

**Comment by ebruchez** [comment]
What's happening here is that we have `replace="none"`.

- `handleSubmissionResult()`
- `replacer.replace()`
- an `Eval.later` to dispatch `XFormsSubmitDoneEvent` is returned
- `connectionResult.close()`
- after all is done, we call `submitDoneOrErrorEval.value` which, of course, doesn't find the stream open anymore

In short, calling `event('response-body')` upon `xforms-submit-done` for a submission with `replace="none"` fails.

**Comment by ebruchez** [comment]
The correct sequence is to call `connectionResult.close()` only after submission events have been dispatched.

**Comment by ebruchez** [comment]
- [ ] test that we now close the connection correctly
- [ ] in `XFormsModelSubmission` review `try`/`catch` for logging
- [ ] in replacers, consider returning `ReplaceResult.Error` instead of throwing
- [ ] consider refactoring many functions to separate `object`

**Comment by ebruchez** [comment]
Fixed on 2021.1-pe but reopening until the leftover refactoring tasks are completed.
