### ISSUE TITLE
Update function to access the value of a control within a section template

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#5246]
For #2471 we implemented a `$library-name` parameter for the `fr:control-string-value()` and `fr:control-typed-value()` functions. The choice of a "library name" parameter was done because this was originally intended to be used for cross-section communication "from the inside", where there was no knowledge of the enclosing section name in the destination form (#5005).

However, this function was not used by the implementation of #5005, but the function was made available and documented anyway.

Discussing this with @avernet, we are not 100% satisfied about the choice or "library name" parameter as this doesn't allow supporting scenarios where we include the same session twice, for example:

- Shipping Address
- Billing Address

We could work around with `fr:control-typed-value()`, which returns all values, and use the nth value, but it's not great.

So we are thinking about using an argument which identifies the enclosing form *section name* in which to search for the control.

We could:

- update this function in place (2021.1.2 or later) as it's new and probably hasn't seen any use yet to changing the meaning of the 3rd parameter
- OR add a 4th parameter
- OR create a new function

Now if we use a section name, we should also handle renaming of the call when the section is renamed. We do this for variable references already. Here we should do something similar:

- analyze the formula/expression to find if there is a call to `fr:control-string-value()` or `fr:control-typed-value()`
- check if the 3rd parameter is present and matches the section name to rename
- if so do a replacement in the formula

(It remains a heuristic, but it's probably ok.)

**Comment by ebruchez** [comment]
- [ ] update/implement function
- [ ] control renaming in Form Builder
- [ ] update doc
- [ ] tests

**Comment by ebruchez** [comment]
We still need to decide whether it ever makes sense to want to use this and pass a library name.

I am thinking of the scenario where a section would like to obtain the value of a control within the same library. For example, using templates, it's possible to use the value of a control as part of the label of another control. If you do this between for example two library sections, and insert the two sections in a form, this won't work, and there we are back to the scenario where we don't know the name of the enclosing section but we know of course the name of the library.

In fact, I tested that scenario, and using the `library` parameter it works. So I conclude that we should still keep the ability to pass a library name.

Ways to keep the same function:

- add a parameter for the section name (the library name is ignored if empty)
- use a map to simulate named parameters

**Comment by avernet** [comment]
Attempting an analogy to programming languages (prepare for failure!), let's try to look at section templates like classes, and libraries like… libraries defining classes (i.e. jars providing classes that a developer can use), and forms like users of those libraries:

1. If, as a user of a library, I am creating an instance of a class, say `val mary = new Employee`, it makes sense to have a way to access an attribute of that object (`mary.company`), and this is what this RFE was originally calling for. This part looks kosher to me.
2. If I am a library author, and provide a class `Employee` as well as a class `Company`, I could imagine a language that would allow me to access from the code of `Employee` all the other instances of `Company` that the user created. I'm sure people out there will find a use for this, but this looks a bit iffy to me. For this, I would prefer to have a way for the users of the library to connect instances, i.e. `val acme = new Company; val mary = new Employee(companyName = acme.name)`, and this is a mechanism we have already talked about (https://github.com/orbeon/orbeon-forms/issues/3008#issuecomment-262038117).

Does 2 seem wrongheaded? If not, does it seem too idealistic (aka hard to implement)?

**Comment by ebruchez** [comment]
RESOLUTION:

1. Library name doesn't need to be publicly exposed/documented. Use internal function.
2. `$foo` notation in library form are translated to calls to function using library name.
3. We update public functions to use section name rather than library name.

**Comment by ebruchez** [comment]
Right now, in `form-to-xbl.xsl`, we add the `library-name` to `fr-set-service-value-action` and to `controlMatchesNameAndLibrary()` (for the `<xbl:handler>`.

Where should be place further `library-name` attributes, if any, to pass to `replaceVarReferencesWithFunctionCalls()` when building the form? Maybe we should just pass a tunnel parameter.

**Comment by ebruchez** [comment]
[Updated functions doc](https://doc.orbeon.com/xforms/xpath/extension-functions/extension-form-runner#fr-control-string-value)

**Comment by ebruchez** [comment]
See "For #2471: frf:controlVariableValue()/fr:control-string-value() with library/section arguments" test, which got updated to use section names.

**Comment by ebruchez** [comment]
On the 2021.1 branch we don't need to handle renaming, as renaming within functions wasn't a feature of that release.

**Comment by ebruchez** [comment]
Added a [clarification section](https://doc.orbeon.com/form-builder/formulas#resolution-of-repeated-controls) in the doc about the variable notation and what it does.

**Comment by ebruchez** [comment]
At least do "control renaming" point above.

**Comment by ebruchez** [comment]
For renaming:

- `fbf:renameControlIfNeeded()` is called by `fb:dialog-container-settings`
- this calls `renameControlReferences()`
- which calls `renameNodeContent()` and then `replaceSingleVarReference()` in various places

The issue is that here we don't want  to replace a variable reference, but a function parameter. Do we have other code that does that?

**Comment by ebruchez** [comment]
We don't appear to have that. So we need to:

- compile expression (like for variable replacement)
- check that the `fr:control-string-value()` or `fr:control-typed-value()` is present with 3 parameters
- if so, check that the 3rd parameter is a literal matching `oldName`
- if so, do a literal replacement in the function
