### ISSUE TITLE
Add a search functionality to the Forms/Admin page

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#5274]
[+1 from customer](https://3.basecamp.com/3600924/buckets/18358270/messages/4742391614)

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/23878674/messages/5546067650)

**Comment by ebruchez** [comment]
The Form Metadata API doesn't do paging yet (#5493), but it can filter by app/form names. That should be used if filtering by app/form.

**Comment by ebruchez** [comment]
+1 for going to Form Builder Forms page with `orbeon` app name.

Possibility for URL parameters:

```
?fr-search-app=orbeon
```

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/29305475/messages/6659347800).

**Comment by ebruchez** [comment]
See also #2547.

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/3237397/messages/7274433717)

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/18358270/messages/7380526105)

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/7993860/card_tables/cards/7115923956)

**Comment by ebruchez** [comment]
After discussion, we are leaning towards doing the following:

- implement search at the Form Metadata API level (vs. in the UI)
- implement sorting as well
- implement paging as well (currently done in UI)
- implement merging of providers (currently done in API) and joining of local vs. remote (currently done in UI) at API level
    - so we can do this in Scala
    - optimizations (streaming) are easier
        - if only 1 provider/no remote, performance can also be better (less to read from database)
- UI no longer does paging and joining

This is the "maximalist" option, but it would have lots of positive benefits.

**Comment by ebruchez** [comment]
If we go with the API route:

- [ ] define `/form` API for search, sort, paging, passing info about remote
- [ ] TODO

**Comment by obruchez** [comment]
- [ ] fix tests in CE
- [ ] doc
    - [ ] API
    - [ ] UI

**Comment by avernet** [comment]
A possible unintended consequence of the work done for this #5274 is that, for the forms metadata API, the proxy:

- Before: was passing the `all-versions="true|false"` parameter.
- Now: never passes that parameter. Instead, it expects the implementation to return all versions and handles the filtering itself if it received `all-versions="false"` or did not receive `all-versions` at all.

The documentation states that if an implementation's API does not receive the `all-versions` parameter, it should only return the latest version (defaulting to `false`). This means the change is neither backward compatible nor consistent with what we say in the documentation.

[+1 from customer](https://3.basecamp.com/3600924/buckets/1956846/messages/9662307431)

**Comment by avernet** [comment]
Resolution: Change the proxy to pass the `all-versions` parameter. This will restore the behavior we had before, and be more efficient in case we only need the latest version. Created #7565 to track this.
