### ISSUE TITLE
Email addresses to support including a personal name

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#5313]
Email addresses used by Form Runner to send emails currently can only be raw email addresses. However, we'd like them to include a personal name, so that the From, To, and other addresses can for example  show "John Doe" instead of "jdoe".

However, in `email-form.xsl`, we split email addresses naively on spaces and commas. This means that "John Doe <jdoe@example.org>" won't be processed properly.

**Comment by ebruchez** [comment]
We should not parse in `email-form.xsl` but let `EmailProcessor.scala` handle the email addresses parsing, as `InternetAddress` supports those formats already, as specified in [RFC #822](https://www.ietf.org/rfc/rfc822.txt).

**Comment by ebruchez** [comment]
- [ ] doc

**Comment by ebruchez** [comment]
Documented:

- [Format of email addresses](https://doc.orbeon.com/configuration/properties/form-runner/form-runner-detail-page/form-runner-email#format-of-email-addresses)
- [Basic Settings](https://doc.orbeon.com/form-builder/form-editor/control-settings#basic-settings)

**Comment by avernet** [comment]
@ebruchez This part looks a bit strange; maybe we should say in which version it changed, as done for the property. Also, if not already done, this is something to include in the compatibility section for 2021.1.4. (And we'll then know who amongst customers uses spaces to separate email addresses!)

![IMG_42F04016036E-1](https://user-images.githubusercontent.com/106961/166839288-81b756b2-3836-4c6d-827b-3a2072764548.jpeg)

**Comment by ebruchez** [comment]
@avernet Following discussion, it turns out we don't need to break backward compatibility. We can (and already do!) parse emails in non-strict mode which allows space-separated simple emails. Email addresses with names, on the other hand, need to be comma-separated.
