### ISSUE TITLE
Use `fr:is-embedded()` to hide navigations buttons in embedded modes

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#5323]

**Comment by ebruchez** [comment]
Reopening following discussion.

**Comment by ebruchez** [comment]
Discussion was that the function would take an optional token parameter.

- P1
  - `portlet`
- P2
  - `java` or `java-api`
  - `javascript` or `javascript-api`


Reason for this is to disable navigation buttons (Review, Summary, Home).

**Comment by avernet** [comment]
Change `not(fr:is-embedded('app'))` to `not(fr:is-browser-environment())`

**Comment by ebruchez** [comment]
Navigation buttons (`review`, `summary`, `home`, and the planned `landing` and possibly `forms`/`admin`) are supported when the form is not embedded, obviously, but also in the Form Runner proxy portlet.

The `pdf` and `tiff` buttons should work also when embedding with the Java and JavaScript API (but see #5355).

**Comment by ebruchez** [comment]
Verified it works with a build with the Java and JavaScript embedding APIs.

**Comment by ebruchez** [comment]
Verified that we see the navigation buttons with the proxy portlet in Liferay with 2021.1.4.
