### ISSUE TITLE
`fr:username()` and `fr:user-group()` returning an empty string instead of an empty sequence

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#5363]
The offline code looks correct, but in `org/orbeon/saxon/function/request.scala`, we have `Username.evaluateItem` returning a `StringValue`, which means that `exists(fr:username())` always returns false.

[+1 from customer](https://3.basecamp.com/3600924/buckets/2192969/messages/4828764131)

**Comment by avernet** [comment]
For customers using `xxf:non-blank()` or `xxf:is-blank()`, the code will behave the same after we fix this.

<img width="917" alt="CleanShot 2022-06-17 at 17 56 26@2x" src="https://user-images.githubusercontent.com/106961/174416285-8eb774c6-8ba2-41e5-ae98-cfbc86039aea.png">

**Comment by ebruchez** [comment]
This impacts the following functions:

- `document-id()`
- `form-title()`
- `workflow-stage-value()`
- `username()`
- `user-group()`
- `wizard-current-page-name()`

The reason this fix works is that:

- before, we had a conversion from `String` to `StringValue` which returned an empty `StringValue` for a `null` `String` (via Saxon `makeStringValue()`
- after, we have our own conversion from `Option[String]` to `StringValue` which returns `null` for a `None`, that is, the empty sequence

Now documented the incompatibility [here](https://doc.orbeon.com/release-notes/orbeon-forms-2022.1#return-value-of-fr-workflow-stage-value-and-other-functions).
