### ISSUE TITLE
Export services to be exposed as pages

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#5382]
We currently have services to export:

1. A form definition being edited in Form Builder
2. A published form definition
3. Form data

In each case, the export can be done in XML or Excel format. This RFE calls for having pages, in addition to services, allowing users to directly access this functionality. As far as permissions and security is concerned, for the three items mentioned above:

1. Exporting a form definition being edited in Form Builder is only allowed if the user is able to edit the corresponding form in Form Builder.
2. Exporting a published form definition is only allowed if the user has access to the admin capabilities for that form on the Form Runner homepage.
3. Exporting form data is only allowed if the user has access to that form data in view mode, and if this feature is enabled through a property. The latter is needed for two reasons: (a) this gives users visibility on how data is stored (i.e. values instead of labels for selection items, and potentially more for custom XBL controls), (b) the data will contain, and must contain based on the requirements for this feature, the values of fields that are not necessarily shown to users. (Such a property is not needed for items one and two above.)

[+1 from customer](https://3.basecamp.com/3600924/buckets/5085006/messages/3866580659)

**Comment by ebruchez** [comment]
Point 3 is the priority for customer. Example of current service URL for point 3:

```
/fr/service/acme/sales/export/1234?export-initialize-form=true&language=en
```

We want this to be available as:

```
/fr/acme/sales/export/1234?export-initialize-form=true&language=en
```

In `excel-export-with-data.xpl`, we have 2 cases:

1. `export-initialize-form=true`, which causes the form to run
    - this will check permissions
2. the other case, which doesn't run the form, and (probably) does not check permissions

- [ ] changes to `page-flow.xml`
- [ ] check permissions in case 2 above
- [ ] add property to enable export as "page" for point 3

**Comment by ebruchez** [comment]
Was going to say that the hardest part is checking permissions when we don't run the form. But we already have `readFormDataIfDocumentIdPresentAndAuthorized()`. This does part of what's in `persistence-model.xml`.

Q: Is that enough, or do we also need to check any permissions when the data is `POST`ed to the page or 
when no data is required?

**Comment by ebruchez** [comment]
Mmh, `readFormDataIfDocumentIdPresentAndAuthorized()` only checks for `edit`. It's called both for import and export. That seems incorrect: we need to pass whether we want to check for `edit` or for `view`.

**Comment by ebruchez** [comment]
Correcting comment above: this is only used for import, when specifying a document id, to check whether we are allowed to edit the document. The `edit` mode translates to checking the `update` permission.

So here we need, when using a page, to check the `view` mode.

- [ ] make sure we don't mix up the `import` page and the `import` "mode" used for the import service (?)

**Comment by ebruchez** [comment]
See also  #3493 for the opposite requirement for PDF.

**Comment by ebruchez** [comment]
Things to test:

- anonymous user
    -  can export form data for form without permissions
    -  can export form data for form with permissions but Anyone can read
    -  cannot export form data for form with permissions but not Anyone can read
- logged in user
    - same as above
    - with owner can Read
        - cannot export data if not owner
        - can export data if owner
    - with role
        - cannot export data if doesn't have role
        - can export data if has role

**Comment by ebruchez** [comment]
For reference:

- PDF/TIFF always runs the form, which means that `persistence-model.xml` runs and checks permissions
- Excel/XML exports may or may not run the form
    - when they do (`?export-initialize-form=true`), same case as PDF/TIFF
    - when they don't, we run custom code to check permissions

- [ ] add to test plan
- [ ] complete testing
- [ ] consider refactoring `persistence-model.xml` initialization

**Comment by ebruchez** [comment]
For reference, the relational persistence implementation returns an `Orbeon-Operations` header for `GET` or `HEAD` of data:

- by calling `PermissionsAuthorization.authorizedOperations()`
    - uses `readFormPermissions()` to obtain the form definition permissions, or properties
    - uses the `Credentials` of the service user
    - uses `CheckWithDataUser` with user information coming from the data
- response
   - if `Read` is not allowed by that, throw a 403
   - else return an `Orbeon-Operations` header with the operations allowed

When that is the case, the client (detail page) trusts the list of operations returned and doesn't do any permissions processing besides checking the operations against the current mode.

This only applies to cases where data is read from the persistence layer, which excludes the `new` mode,

**Comment by ebruchez** [comment]
When on the Detail page, the "Excel Export" button runs `open-rendered-format()`, with the current form data `POST`ed. Before these changes, it called the `/fr/service` path. What should it do now? Does it matter, since it is internal? In this case, the export is enabled by the presence of the "Excel Export" button.

**Comment by ebruchez** [comment]
[Documented](https://doc.orbeon.com/form-runner/link-embed/linking)
