### ISSUE TITLE
Can't set value of number field with documented public API

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#5383]
Doing the following, per the [doc](https://doc.orbeon.com/form-runner/api/other-apis/form-runner-javascript-api#setting-a-controls-value) has no effect.

```javascript
ORBEON.xforms.Document.setValue(
    ORBEON.fr.API.findControlsByName('my-number')[0],
    42
)
```

This sends the following, but the server doesn't set the value of the bound element to the value provided. Since the XBL has the `binding value` modes, the server supporting this seems reasonable to me, and would allow support for this use case.

```xml
<xxf:event name="xxforms-value" source-control-id="section-1-section≡grid-1-grid≡my-number-control">
    <xxf:property name="value">42</xxf:property>
</xxf:event>
```

[+1 from customer](https://3.basecamp.com/3600924/buckets/15921610/messages/5140249123)

**Comment by ebruchez** [comment]
When the user changes the value of a number field, the following is sent to the server:

```xml
<xxf:event name="xxforms-value" source-control-id="fr-view-component≡typed-controls-section≡grid-3-grid≡number-control">
    <xxf:property name="value">{"displayValue":"299792459","editValue":"299792459","decimalSeparator":"."}</xxf:property>
</xxf:event>
```

The value of the `value` property is a serialization. This is controlled, in `number.xbl`, with `xxbl:deserialize-external-value`.

On the other hand, `Document.setValue()` directly dispatches an event without asking the client-side component to serialize the value.

I'd say that the value on the wire should always be in the same format. This means that `Document.setValue()` should somehow ask the client-side component for the serialized value.

**Comment by ebruchez** [comment]
The problem is that right now, the companion object doesn't expose an entry point that takes a "user value", whatever that is, and then uses it to serialize it. We'd probably need to add that to the API.

**Comment by ebruchez** [comment]
In `xforms.js`, `setCurrentValue()` can be called as a result of a value coming from:

- the server, which can be "serialized"
- or from the `Document.setValue()` API, where we don't want it to be

So we need a way to differentiate, either:

- using a different function
- or by passing an extra parameter

**Comment by ebruchez** [comment]
Quick brainstorming with @avernet:

- we cannot avoid adding method or parameter, so do that
- as P2, protocol client → server should not pass JSON ideally, as only the `editValue` is passed; but this involves `ServerValueStore` which we need to figure out

**Comment by ebruchez** [comment]
[Documented](https://doc.orbeon.com/form-runner/api/other-apis/form-runner-javascript-api#setting-a-controls-value)
