### ISSUE TITLE
Easy navigation between sections for easy renaming, validations etc.

### ISSUE THREAD

**Issue by AreejK28** [orbeon/orbeon-forms#5393]

**Comment by ebruchez** [comment]
I assume that you mean in Form Builder?

**Comment by AreejK28** [comment]
Hi Erik,

Yes that is what I meant :)

**Comment by ebruchez** [comment]
Thanks. We think that Form Builder does need some improved navigation, in particular from the keyboard. You can already navigate between controls with the left/right cursor keys. It would be nice to be able to also jump to sections, quickly edit a label and commit the change, etc.

**Comment by ebruchez** [comment]
Since we have #4609, I am closing this and adding suggestions to that other, more general issue.
