### ISSUE TITLE
Lease "Show in read-only mode" can't be used when embedding

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#5403]
This is because the button causes navigation. We'd need to either be able to navigate or, easier, to hide or configure the button.

[+1 from customer](https://3.basecamp.com/3600924/buckets/7545500/messages/5217057376)

**Comment by ebruchez** [comment]
In fact for #5323 we recently disabled the lease feature when enabled.

So this would call for:

- [ ] re-allowing the lease feature when embedding
- [x] making the "Show in read-only mode" process configurable
- [ ] allowing hiding the "Show in read-only mode" button

**Comment by avernet** [comment]
Fixed by https://github.com/orbeon/orbeon-forms-pe/commit/2065d132d10d18c7405f80754ba112b36338141d.

**Comment by ebruchez** [comment]
Also cherry-picked the configurable process commit to 2021.1-pe.
