### ISSUE TITLE
Slow response in HTTPService/Action loading dropdown control

### ISSUE THREAD

**Issue by cc-cmarher** [orbeon/orbeon-forms#5444]
We have a HTTP Service/Action that read a REST API and in the Service Response Actions we use "Set Control Choises" to fill a dropdown control. The REST API response is relative big (aprox 9000+ items) but the response takes a short time (700ms). However, the control takes a long time to populate (aprox. 2 minutes). This delay is unacceptable.
If we put several "Service Response Actions/Set Control Choises" in the same Action to fill multiple controls, the time increases arithmetically.

Can we optimize this procedure?

Version: Orbeon Forms 2021.1.3 PE

**Comment by orbeon** [comment]
Hi Carlos,

Have you already looked into using a dropdown with search, hooked up to a
service that does the search (see link below)? This would avoid having to
load 9000+ items, and instead the service would be called as the user types
in the field to provide the most relevant items; it would most likely also
provide a better guy than a drop down with 9000+ items.

https://doc.orbeon.com/form-runner/component/static-dynamic-dropdown

This being said, populating a dropdown with 9000 items really shouldn't
take 2 minutes. If you really need to go for this solution, would you be
able to share with us a minimal example that we can run locally that shows
this performance problem?

-Alex

**Comment by cc-cmarher** [comment]
We are currently working with dynamic dropdown with search but our web service has a variable parameter in the url and we do not know if it's posible to do it with the control.

For example: https://www.mydomain.com/api/$user/list?query={$fr-search-value}

$user is a variable stored in a form control

**Comment by cc-cmarher** [comment]
[test_orbeon.zip](https://github.com/orbeon/orbeon-forms/files/9582813/test_orbeon.zip)

Our web service return a response like the file attached

**Comment by avernet** [comment]
@cc-cmarher, ok, could I ask you to create a thread about this on the Orbeon Forms "group" on Google Groups (see [Community](https://www.orbeon.com/community))? This is because we only use this Issues section to track verified bugs or request for enhancements, and I can then follow-up on that thread. And of course, just let us know if Google Groups is causing you any trouble.
