### ISSUE TITLE
Performing Authentication in a Web Service

### ISSUE THREAD

**Issue by cc-cmarher** [orbeon/orbeon-forms#5450]
We would like to know if there is any way to authenticate a web service either from a dynamic type control or using the HTTP Service/Action.

We need to add a JWT Bearer in the Header of every request.

**Comment by avernet** [comment]
@cc-cmarher I'm sorry for the trouble, but as mentioned on #5444, could I'll ask you to repost this on the Google Groups, so we can keep this Issues section just about bugs and request for enhancements.
