### ISSUE TITLE
Ability for form author to reset the value of a Yes/No Answer

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#5479]
Should form authors click on the Yes, or the No radio button, and later on prefer to have neither one selected, they will need to either delete and recreate the control, or edit the source of the form definition, neither of which is convenient.

This calls for providing form authors with a better a way to reset the value of a Yes/No Answer.

- Implementation
  - Inline "clear" button, just in Form Builder, under the Yes/No radios
  - Done with `fr:keep-if-design-time="true"` in `yesno-input.xbl`

- We also thought of the following alternative, but the above is preferred (just keeping this here for reference)
      - Using a custom editor
          - with button "Clear value" (disabled if the value is already empty)
          - with 3 radio buttons: no selection, yes, no
      - In the Formulas tab, under Initial Value, have Static / Formula radios, the Static case being new and allowing form author to clear the value; this would apply to all controls
          - Drawbacks
              - Discoverability maybe worse than if using a custom editor?
              - Makes it easier for form author to enter a out-of-bound value

[+1 from customer](https://3.basecamp.com/3600924/buckets/18358270/messages/5405532463)

**Comment by obruchez** [comment]
Implemented, but we'll need to discuss the look and feel of the "Clear" button.

**Comment by obruchez** [comment]
A review of the look and feel will be done by @ebruchez.

**Comment by avernet** [comment]
- [ ] @ebruchez: L&F
