### ISSUE TITLE
Form metadata API: support paging

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#5493]
The [Form metadata API](https://doc.orbeon.com/form-runner/api/persistence/forms-metadata) currently doesn't support paging, which means that the Home/Admin page loads all forms in memory, which makes the page slow.

There are other uses of the API as well.

**Comment by ebruchez** [comment]
+1 from customer

**Comment by ebruchez** [comment]
The API, implemented in `PersistenceProxyProcessor`, returns data from all configured providers. `home.xhtml` and `landing.xhtml` do client-side sorting. The relational implementation doesn't do any sorting at that level.

In general, there is only one provider configured, but there *can* be multiple. Also, `home.xhtml` merges results from local and remote entries.

Could we:

- let the database do the sorting
- optimize paging when there is only one provider
- read all in memory and merge (in Scala) when there is more than one provider
- also merge local/remote entries using the same code

- [ ] move the relational implementation from `form.xpl` to native so we can reuse more code
- [ ] consider how to handle paging given the above

**Comment by obruchez** [comment]
- [ ] doc (API)
