### ISSUE TITLE
Form Builder summary field search for app, form… doing exact instead of substring match

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#5499]
[+1 from customer](https://3.basecamp.com/3600924/buckets/14122811/messages/5452578057)

**Comment by ebruchez** [comment]
I checked that right now, we produce `match="exact"` for the Form Builder app and form input fields/dropdowns.

We only want that when we show dropdowns with lists of app/form names. But when we have fields, we want `match="substring"`.

- App name shows as field when `$has-fb-roles-for-all-apps`
- Form name: shows as field when `$has-fb-roles-for-all-apps or $current-app/form[@name = '*']` 

We should use the same logic to update `match` to `substring`.

This said, if I try to do that, I notice a different behavior with `form-builder-permissions.xml`:

- without any `<role>` element
- with `<role name="*" app="*" form="*"/>`

**Comment by ebruchez** [comment]
Also noting that the Form Title and Form Description do an exact match, which is incorrect.
