### ISSUE TITLE
Add language selector to relevant tabs of the Control Settings

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#5500]
It would make sense in the tabs where form authors can enter localizable text, including Validations and Alerts, Label, Hint, and Help Message.

[+1 from customer](https://3.basecamp.com/3600924/buckets/18345583/messages/5457619460)

**Comment by obruchez** [comment]
- [ ] add support for optional elements in setControlLhhValuesForAllLangs
- [ ] doc
