### ISSUE TITLE
Add more logging for two-pass submission issue

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#5502]
[+1 from customer](https://3.basecamp.com/3600924/buckets/2016476/messages/4166764027#__recording_5457498997)

**Comment by ebruchez** [comment]
Let's review what happens in `XFormsServer` if "handling NOP response for submission" is output. Note that we don't even know if that's truly related to the issue.

- means `xmlReceiverOpt == None` / `isAjaxRequest == false`
     - means this was a second pass
- means `containingDocument.getReplaceAllEval == None`
- means block returns `Success(None)`
- later we hit `case Success(Success(None)) =>`
    - when this happens we don't do anything

It might be that the issue is that we have `containingDocument.getReplaceAllEval == None`. How can that happen? This is set only in one place, with `BaseSubmission.submitEval()`, when `p2.isAsynchronous && p.isDeferredSubmissionSecondPass`. This is called:

- from `CacheableSubmission`, which doesn't apply to `replace="all"`
- from `RegularSubmission`

We don't use `mode="asynchronous"` in this case, so we'd expect it to be `false` and exclusive with `p.isDeferredSubmissionSecondPass`, so it's fine here.

So either:

- `submitEval()` is not called
- or it gets cleared

This gets cleared in `clearClientState()`, which is called:

- upon `afterInitialResponse()`
- upon `afterUpdateResponse()`

The call to `getReplaceAllEval()` is wrapped in `beforeUpdateResponse()/afterUpdateResponse()`, and the value obtained from within, so it shouldn't be cleared there.

**Comment by ebruchez** [comment]
Added some debug on the `2021.1-pe` branch.

**Comment by avernet** [comment]
Commit where the debug was added: https://github.com/orbeon/orbeon-forms-pe/commit/8e6bf70eef69651b1f75ff70b034dcb3cd40773d.
