### ISSUE TITLE
PDF shows cells on the same line

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#5510]
Consider this form ([source](https://github.com/orbeon/orbeon-forms/files/9890806/form.txt)):

<img width="958" alt="Screenshot 2022-10-28 at 10 47 50 AM" src="https://user-images.githubusercontent.com/106961/198702139-4f919153-620c-4104-bc66-e93957b635f2.png">

With 2021.1, the PDF looks as follows, which is correct:

<img width="751" alt="Screenshot 2022-10-28 at 10 59 05 AM" src="https://user-images.githubusercontent.com/106961/198702204-021336ed-8610-4da6-b14a-8aff8176df44.png">

With the latest code, all cell are shown on the same line:

<img width="597" alt="Screenshot 2022-10-28 at 10 48 18 AM" src="https://user-images.githubusercontent.com/106961/198702275-0ea090bf-08b2-41d4-8677-1035b7e5eb79.png">

**Comment by ebruchez** [comment]
Works now, not sure what changed but we have the updated PDF renderer in place:

<img width="798" alt="image" src="https://user-images.githubusercontent.com/105769/205779133-4b718e25-bc78-4521-a34e-df2713740052.png">

**Comment by ebruchez** [comment]
Could also have been due to the new CSS grids configuration.
