### ISSUE TITLE
Outside of Form Runner, `fr:number` not initialized, not storing new value in data

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#5533]
With the example below, the field shows empty when the form is loaded, and changing the value of the field doesn't updated the data.

[+1 from user](https://groups.google.com/g/orbeon/c/Ex880YIuZxA)

```xml
<xh:html xmlns:xh="http://www.w3.org/1999/xhtml"
      xmlns:xf="http://www.w3.org/2002/xforms"
      xmlns:xxf="http://orbeon.org/oxf/xml/xforms"
      xmlns:fr="http://orbeon.org/oxf/xml/form-runner">
    <xh:head>
        <xf:model xxf:function-library="org.orbeon.oxf.fr.library.FormRunnerFunctionLibrary">
            <xf:instance>
                <_>42</_>
            </xf:instance>
        </xf:model>
    </xh:head>
    <xh:body>
        <fr:number ref=".">
            <xf:label>fr:number:</xf:label>
        </fr:number>
        <xf:output value=".">
            <xf:label>Value in data:</xf:label>
        </xf:output>
    </xh:body>
</xh:html>
```

**Comment by ebruchez** [comment]
Reasons:

- call to `fr:component-param-value()` in `xxbl:format`, `xxbl:serialize-external-value`, `xxbl:deserialize-external-value`
    - similar issue to `fr:date`
- call to `fr:mode()` and `fr:component-param-value()` in body
    - should be fixable with `fr:keep-if-function-available="fr:mode"` and `fr:keep-if-function-unavailable="fr:mode"`

**Comment by ebruchez** [comment]
See #5568.

**Comment by ebruchez** [comment]
This, by the way, was probably not supported with 2021.1, and possibly even earlier releases.

**Comment by avernet** [comment]
Works fine in the following test case: [view.txt](https://github.com/orbeon/orbeon-forms/files/10925251/view.txt). Closing.
