### ISSUE TITLE
FB: "New" from Form Builder causes error

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#5572]
See screenshot.

<img width="542" alt="Screenshot 2022-12-14 at 3 45 05 PM" src="https://user-images.githubusercontent.com/105769/207739305-7bc856c1-531e-41dd-8050-7aca07238b05.png">

**Comment by ebruchez** [comment]
Reproducible. Error happens in `handleDeleteRepeatElements()` with:

- `deleteId: "dialog-form-settings≡xf-1693≡xf-1935"`
- `count: 6`
- `parentIndexes: "" `

At some point, `lastNodeToDelete` is `null`, and so `lastNodeToDelete.previousSibling` crashes.

Is the markup to remove in the UI somehow incorrect? Or something else?

**Comment by ebruchez** [comment]
Next steps:

- [ ] trace `StateHandling.initializeState()`

**Comment by ebruchez** [comment]
I still reproduce the above 100% locally, with or without the Dev Tools open.

**Comment by ebruchez** [comment]
So the page navigates to `/new`, but then we get:

```
state found, assuming back/forward/navigate, requesting all events
```

which is not right. We are hitting the `None/Some` case, which means that:

1. We are not finding the `varStateOpt`, which is good and expected since we are navigate to a different page
2. But we are finding `dom.window.history.state`

**Comment by ebruchez** [comment]
The way we navigate is with `window.location.href = "/orbeon-forms-pe/fr/orbeon/builder/new"`. We do this when processing the Ajax response. WHATWG [says](https://html.spec.whatwg.org/multipage/browsing-the-web.html#beginning-navigation), which is new to me:


> If any of the following are true:
> 
> - url [equals](https://url.spec.whatwg.org/#concept-url-equals) navigable's [active document](https://html.spec.whatwg.org/multipage/document-sequences.html#nav-document)'s [URL](https://dom.spec.whatwg.org/#concept-document-url);
> - url's [scheme](https://url.spec.whatwg.org/#concept-url-scheme) is "[javascript](https://html.spec.whatwg.org/multipage/browsing-the-web.html#the-javascript:-url-special-case)"; or
> - navigable's [active document](https://html.spec.whatwg.org/multipage/document-sequences.html#nav-document)'s [is initial about:blank](https://html.spec.whatwg.org/multipage/dom.html#is-initial-about:blank) is true
>
> then set historyHandling to "[replace](https://html.spec.whatwg.org/multipage/browsing-the-web.html#hh-replace)".

So we are getting a `replace`, which explains why the state is found and is that of the "previous" `/new` document.

So now the question is:

- should we attempt to push a new history entry instead?
- or should we instead accept the replacement of the history entry, but compare the UUIDs and consider the state not found?

**Comment by ebruchez** [comment]
The `formId` is the same (`xforms-form`), but we don't try to discriminate by `uuid`:

```json
{
    "xforms-form": "{\"uuid\":\"a3d7138bcdd4603aa3b92878e291e5a49c8c6828\",\"sequence\":7}"
}
```

**Comment by ebruchez** [comment]
Fixing this using option 2, I still get the original when doing a proper back. So there might be another issue. But at least now we are not breaking simple navigation with `new`.

**Comment by ebruchez** [comment]
Trying to figure out what is causing funny back/forward behavior.

I note that with Chrome, it appears our Form Runner pages are not bfcache-enabled, because an `unload` handler is detected. This apparently is added by YUI in YAHOO.util.Event`!

**Comment by ebruchez** [comment]
- [ ] create separate bug for "back to Form Builder" issue

**Comment by ebruchez** [comment]
Unsure if this happened with 2021.1.x, but the code hasn't changed, so cherry-picking that on the 2021.1-pe branch as well.

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/16915667/messages/5817718399)
