### ISSUE TITLE
Error migrating email templates in customer form

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#5597]
This happens because there is a template parameter that is "conflicting" in the subject and the body. The migration code creates a new name, I think, but then forgets about the parameters that don't conflict, and then when the template must be filled, some parameters are missing.

- [x] fix
- [x] unit test

[+1 from customer](https://3.basecamp.com/3600924/buckets/7993860/messages/5685043792)

**Comment by avernet** [comment]
Fixed in https://github.com/orbeon/orbeon-forms-pe/commit/c048341c71b4fb2d20f2da26741e4a3cb8e58225.
Unit test in https://github.com/orbeon/orbeon-forms-pe/commit/215f37b9caadba0910ddf2643fd395f4e394701c.
