### ISSUE TITLE
Possible issue with email of selected attachments

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#5603]
Try to reproduce with 2021.1 and 2022.1 with:

```xml
<property
    as="xs:string"
    name="oxf.fr.email.attach-files.*.*"
    value="selected"/>
```

[+1 from customer](https://3.basecamp.com/3600924/buckets/7993860/messages/5685043792#__recording_5687131274)

**Comment by avernet** [comment]
Fixed in https://github.com/orbeon/orbeon-forms-pe/commit/2ff0bb71acd0cbd641902abf939c1b566483cb3f.
