### ISSUE TITLE
JavaScript error when login page detected

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#5638]
This regressed in [this commit](https://github.com/orbeon/orbeon-forms/commit/ae899c14728ac9c4bf5201602dc171301bccb784), when JavaScript was rewritten in Scala.js. We have this since 2019.2, so potentially this could have last worked in 2019.1.x.

[+1 from user](https://groups.google.com/g/orbeon/c/_j7NaRhgAFE)

**Comment by ebruchez** [comment]
Noting that @avernet also cherry-picked this on `2019.2-pe`.

**Comment by ebruchez** [comment]
Also cherry-picked this on `2020.1-pe`.
