### ISSUE TITLE
Improve performance of publish and Form Runner Forms page

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#5689]
- Situation
    - In Form Builder, on publish, before showing the dialog, we run a single query
    - The query retrieves information about the published versions of this form
    - Locally, with MySQL, that query takes 4.3 seconds, with 1313 versions
        - Yes, 1313 might be a lot, but still, 4.3 seconds for this query is a LOT
- Analysis
    - The inner query take 13 ms
    - It is joined with `orbeon_form_definition`, which has 1628 rows
    - I wouldn't expect joining 2 tables of respectively 1313 and 1628 rows would take 4.3 s
- Finding
    - Hard coding the app/form when known
        - Right now we join the app/form of the outer with the inner query, even when the app/form name a known
        - If instead we select for that known app/form in the outer query the time goes down from 4.3 s to 45 ms
        - Unfortunately, this doesn't solve the more general case of the Form Runner Forms page, where the app/form name isn't
    - Join order
        - Joining on `last_modified_time` first improves the time from 4.3 s to 2.9 s
        - Most likely because that time is more "unique" in the table
    - Index to facilitate the join
        - Creating an index on `app, form, form_version, last_modified_time` brings down the time from 4.3 to 54 ms
        - Now we're talking!
- Next
    - [x] Write and test `orbeon_form_definition_i2` on all the databases

**Comment by ebruchez** [comment]
+1 from me!

**Comment by ebruchez** [comment]
Maybe some of this could be looked at in the context of/after #5274. Also, once we have paging at the API level, will this make a difference?

**Comment by ebruchez** [comment]
Just I noticed this index is only present in `mysql-2019_1.sql`. It would be good to get closure on this.

**Comment by ebruchez** [comment]
Only indexes, no code, should be fairly easy.

**Comment by avernet** [comment]
- [ ] Once the test pass on PE, sync the SQL on CE, make sure the DDL tests pass on CE
