### ISSUE TITLE
Upgrade to Font Awesome 6

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#5702]
- benefits: newest version with more icons
- drawbacks: style of newer free icons is "solid" (no free "light")

**Comment by ebruchez** [comment]
- [ ] see if better icon for top right Landing icon
- [ ] icon "zoom" in Form Builder no longer originates from the center of the icon

**Comment by avernet** [comment]
I am not suggesting that we change, but, for reference, I find the [Feather](https://feathericons.com/) set of icons really nice, and it's fully open source, but with a more limited number of icons.

**Comment by ebruchez** [comment]
Closing, open new bugs if issues are found.
