### ISSUE TITLE
Occasional blank page after click on "Review"

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#5719]
To reproduce:

- Load a form with a review button.
- In the DevTools, in the Network tab, add some throttling, e.g. Fast 3G.
- Quickly click a few times on the review button.

The problem is that when we get the POST, we retrieve from the delayed events from the containing document, and remove those events from the containing document. So the second time we get that POST, we don't find those delayed events that we need to run in the containing document, and we are unable to process that second request.

The server must be able to handle getting the same request two or more times in a row. It must answer with the same response every time (as it cannot assume that the client received the previous answers), and if creating the answer must have a side effect, the server needs to be able to produce that same answer without creating that side effect again (e.g. by caching the response the first time it is generated, and "replaying it" on subsequent requests).

[+1 from customer](https://3.basecamp.com/3600924/buckets/2016476/messages/4166764027)
[+1 from customer](https://3.basecamp.com/3600924/buckets/2192969/messages/5784795025)

**Comment by ebruchez** [comment]
Might have started happening with #4386.

Possibilities:

- keep server events and just replay them if a second request comes in
    - are they small? can we just keep them until the next-next operation on the document?
- keep response for a while, like we do for Fetch responses
- prevent the user from clicking on some buttons twice (#2514)

**Comment by ebruchez** [comment]
The `DelayedEvent` we create for two-pass submissions is has `eventName = "xxforms-submit"` and `time = None`.

When an incoming request comes with `isAjaxRequest == false` (so the second pass of the submission), we only process the events (well, it should be a single one!) with `time == None`. All other events are remaining in the queue. So only that single two-pass `xxforms-submit` is processed and removed from the queue.

If we keep the event around to handle this scenario, things might work in most cases, except that this will cause the associated `xf:submission` to run twice. This is not correct as that might cause multiple undesired service calls (like saving twice, sending twice, etc.). So I don't think we should do option 1 above.

**Comment by ebruchez** [comment]
Option 3 should be done in any case at some point.

But how can we implement option 2? And would it solve the problem?

Indeed, I am not sure what exactly is happening in the "double-click" scenario, but let's try to figure it out. The network tab in Chrome shows:

- `DOMActivate` sent in first XHR request (response doesn't show, but must contain `xxf:submission`)
- `DOMActivate` sent in second XHR  request (response doesn't show, but must contain `xxf:submission`)
- form `POST`, which ends up canceled
- form `POST`, which "succeeds", but has zero content and `Content-Length: 0` (per Chrome)

The exact reason for that order of events is not exactly clear. XHR requests are sequential, which means that the response of one must be processed before sending the next one.

- the response of the first XHR calls `submit()`
- but presumably this processing of `submit()` is async in the browser, so…
- the second XHR request is sent
- its XHR response is received
- a new `submit()` performed, which, on the client, cancels the first one
- however the server has received the first `POST`, processes it, removes the event, fails to write the response entirely
- then the server receives the second `POST`, and is forced to return blank content

What should happen to fix this, even if we allow double-clicks on buttons (see option 3)?

**Comment by ebruchez** [comment]
For reference, right now, we have the following process with a two-pass submission on the server:

- first pass
    - we first do everything, including preparing the data, up to the point where we are ready to send it
    - however, we do not send it, and we throw away the prepared data
    - instead, we return an event to the client, telling it to do a client-side `POST` (with `submit()`)
- second pass
    - the `POST` is received by the server
    - we again prepare the data
    - we are supposed to have no side-effects on the document
    - we then create an `Eval.later` to execute the request
    - we exit the lock on the document in `XFormsServer`
    - we then perform the actual connection and return the result to the client

This is problematic in a few ways, including:

- this current issue
- #936/#2795

**Comment by ebruchez** [comment]
Allowing double-clicks, the idea is that to work correctly, the submission on the server might take place twice, while not showing a white resultg page. This is:

- ok in the case of, say, a navigation to a `view` page
- but not ok in the case of form data being sent to a third-party service for submission, returning a confirmation page

But this would be the "correct" behavior if we allow double-clicks and have no other mechanism to prevent multiple submissions.

What would happen if, in `processDueDelayedEvents()`, we only extracted the *first* event with `time.isEmpty`?

- the second event, if present, would stay in the queue
- so if there is a second `POST` coming out of order (as above), it would still find an event
- but if, later, the is a browser back and a different `POST` there is a risk the incorrect `xxforms-submit` could run, right?

For correctness, the `POST` should contain information allowing matching with the specific event.

**Comment by ebruchez** [comment]
Doing more testing, it seems that there is only *one* `DelayedEvent` in the queue. So processing just one, as suggested above, doesn't solve the problem.

**Comment by ebruchez** [comment]
I realize that I don't understand what's happening on the server. The issue with the double-click is reproducible. But the explanation is unclear:

- the `POST` can only come after processing at least one XHR response
- so there is at least one `xxforms-submit` event on the server, and it is read
- but a second `POST`, due to double-click, should also come as a result of a second XHR response
- so the second `POST` should find the `xxforms-submit`event added by the second XHR request

So next step:

- [ ] log sequence on the server in the above scenario

**Comment by ebruchez** [comment]
Findings:

- server gets XHR 1
    - runs submission phase 1 as expected
    - adds `xxforms-submit` event
- server gets XHR 2
    - *doesn't* run submission phase 1
    -  because "another submission requiring a second pass already exists"
    - so doesn't add second `xxforms-submit` event!
- server gets `POST` 1
    - removes one event and tries to do submission phase 2
    - but doesn't complete successfully, probably
- server gets `POST` 2
    - doesn't find event
    - so we get "NOP response"

**Comment by ebruchez** [comment]
We check for "another submission requiring a second pass already exists" presumably because  at some point we assumed that it only made sense to have one two-pass submission at a "given time".

What would happen if we "simply" turned off that theck?

Say we have:

- two-pass submission to produce a PDF in another window
- followed by two-pass submission to navigate to the `view` page

This arguably should work. If we have, however:

- two-pass submission to navigate to the `view` page
- followed by, again, by two-pass submission to navigate to the `view` page

If the first one succeeds, then the browser will navigate, and a second `submit()` on the client will either not have a chance to work, or if navigation hasn't yet happened it will cancel the first one.

One question is: what happens if we have two scheduled second passes as `xxforms-submit` on the server, but only one `POST` ever arrives? Can we clean-up the second `xxforms-submit`?

It would be good if we could match a `POST` with a given `xxforms-submit`. Then we could also expire old `xxforms-submit` events if any.

**Comment by ebruchez** [comment]
To implement matching:

- assign opaque id to `DelayedEvent` with `time == None`
- add id to response element, for example `submission-id="12345"`
- when doing the `POST`, add `$submission-id` hidden field
- server then receives the id and uses it for matching the event on the server
    - selects `xxforms-submit` event that matches
    - if none, then it is an error

**Comment by ebruchez** [comment]
Tried out on 2021.1-pe branch and the fix works there. Tested on 2022.1-pe branch, but found (possibly unrelated) issue #5835.

**Comment by ebruchez** [comment]
Noting that we fixed the issue we could reproduce here, that is the "double-click with slow network" issue. There could be other cases where Form Runner produces a blank page, but hopefully not.
