### ISSUE TITLE
Ability to set the `relevant` and `readonly` of iterations in repeated grids and repeated sections

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#5724]
In one use case the form author desires to hide rows of a repeated grid depending on who the user is, e.g. based on their role, but of course those rows should stay in the data.

As a workaround, a form author can edit the source of the form, find the `xf:bind` that corresponds to the iteration, and add an attribute like `relevant="starts-with(first-name, 'M')"`, in this example to only show the rows where the first name starts with the letter "M".

[+1 from customer](https://3.basecamp.com/3600924/buckets/16915667/messages/5860726173)

**Comment by ebruchez** [comment]
It should be easy to add a UI for this.

**Comment by ebruchez** [comment]
The following might even work:

```xml
relevant="starts-with($first-name, 'M')"
```

**Comment by ebruchez** [comment]
+1 from customer

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/5085006/messages/7203995834)

**Comment by avernet** [comment]
New UI:

![Screenshot 2024-03-25 at 11 56 43 AM](https://github.com/orbeon/orbeon-forms/assets/106961/10e762f4-a54d-4255-bd40-f1952c60e0d9)

**Comment by obruchez** [comment]
Doc: https://doc.orbeon.com/form-builder/form-editor/repeat-settings#visibility-and-read-only-formulas
