### ISSUE TITLE
Ability to customize, in Form Builder, the "add another line" link, for minimal repeated grids

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#5742]
This is not unlike #3911, but for repeated grids instead of repeated sections.

[+1 from customer](https://3.basecamp.com/3600924/buckets/2016476/messages/6011691267)

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/23878674/messages/4755672540#__recording_6061870322)

**Comment by ebruchez** [comment]
Also consider making the "Remove" button configurable, for example  "Remove Passenger". This is good for screen readers.

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/10984927/messages/6281750534)

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/7545500/messages/6609436166)
