### ISSUE TITLE
Readonly grid shows incorrectly

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#5743]
Compare how it shows when readonly (first screenshot below) versus not readonly (second screenshot below). 

<img width="950" alt="Screenshot 2023-04-04 at 1 24 15 PM" src="https://user-images.githubusercontent.com/106961/229911986-045b7099-2127-4299-bcb1-e41f23d55fca.png">
<img width="960" alt="Screenshot 2023-04-04 at 1 24 40 PM" src="https://user-images.githubusercontent.com/106961/229912081-ad2895b7-bb0e-4ee7-970d-ea5d7fe69f29.png">

**Comment by jmalyik** [comment]
Hello! Do you have any progress in this? We bumped into the same problem.

**Comment by ebruchez** [comment]
@jmalyik We plan to address this for Orbeon Forms 2022.1.4. Soon!

**Comment by ebruchez** [comment]
Also, this is curious, as the [Appearances of Orbeon Forms Repeated Grids](https://demo.orbeon.com/demo/fr/orbeon/repeated-grids/new?form-version=1) doesn't have this problem.

**Comment by ebruchez** [comment]
We can now reproduce the issue.

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/24212679/messages/6159653594)
