### ISSUE TITLE
Support `save then email` for users without the `read` permission

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#5768]
If a user can `create` but not `read`, and we want to have a process that runs `email` and `save`, they must be run in that order. If we run `save` first, the paths to the files will be changed from pointing to temporary files to pointing to the persistence, and then `email` will fail trying to read the files from the persistence because the user doesn't have `read` permission. Using `email then save` works, but it's not unreasonable to want to have `save then email` to make sure the data is saved before an email is sent.

Possible solutions:

- Have `email` pass some sort of encrypted message to the persistence proxy, telling it not to check permissions, since it "knows" that even if sending an email causes a read, it doesn't correspond to the reads we want to protect.
- Have `save` copy the temp path to an attribute `fr:tmp-path="…"`, which doesn't get saved, but stays in the live data, and have `email` use that in place of the path in the element(s) when sending the email.

[+1 from customer](https://3.basecamp.com/3600924/buckets/7993860/messages/6046331817)

**Comment by ebruchez** [comment]
So `save()` would always add `fr:tmp-path` on attachment elements in the live data. But when should these attributes be removed?

In general, `fr:*` elements and attributes are pruned as follows:

- `send()`
    - use `prune-metadata` parameter if present
    - default
        - `data-format-version = "edge"`: defaults to `false`
        - else defaults to `true`
    - `nonrelevant`
        - if legacy `prune` parameter is explicit, then `keep` if `false`, `remove` otherwise
        - else use `nonrelevant` parameter
        - else defaults to `remove`
    - so by default, `fr:*` elements and attributes are pruned, and non-elements are removed
- `save()`
    - use `prune-metadata` parameter if present
    - else defaults to `false`
    - so by default, `fr:*` elements and attributes are preserved, including `fr:relevant` attributes

Now, with the suggested `fr:tmp-path` attribute, we should ideally not send or save them under any circumstance.

**Comment by ebruchez** [comment]
- mode change: preserve everything including `fr:tmp-path`
- `save()` and `send()`: always prune `fr:tmp-path`, no matter what the other settings are

But `changeMode()`, which must preserve everything, uses `trySendImpl()`.

**Comment by ebruchez** [comment]
- `changeMode()` doesn't necessarily pass `data-format-version = "edge"`
- so we need an extra parameter

**Comment by ebruchez** [comment]
- [x] `email-form.xsl` must use `fr:tmp-file` when present and non-blank
- [x] `fr:tmp-file` must be pruned with `send()` and `save()`
- [x] `save()` must add `fr:tmp-file` as needed
- [ ] `xf:output` for download/image must use `fr:tmp-file` when needed
- [ ] clarify lifecycle of `fr:tmp-file` attribute
    - [ ] clearing value should remove the attribute (`xf:upload`?)
        - but this is a structural change, annoying; or just clear attribute value?
    - [ ] `fr:control-clear` in particular must remove the attribute
    - [ ] if the value is blank, but `fr:tmp-file` is not blank, it shouldn't be used
    - [ ] if attribute is present consider updating instead of recreating it (avoid structural change)

**Comment by ebruchez** [comment]
There are questions related to the lifecycle of the attribute. Right now:

- Form Runner `save()` adds it
- `xf:output` and `email-form.xsl` use it

But we need to remove/clear attribute when needed as well. Since adding the attribute is a Form Runner job, and at the XForms level we only read it, we could do remove/clear at the Form Runner level:

- right now, only `fr:attachment` and `fr:wpaint` use `xf:upload`
- all the following must remove/clear attribute
    - [ ] new upload from UI
    - [ ] clear upload from UI
    - [ ] `fr:control-setvalue`/`fr:control-clear`
    - [ ] legacy action response
    - [ ] anything else?

**Comment by ebruchez** [comment]
This issue also addresses the following related issues:

- Attachment doesn't show/download after save
- Image Attachment doesn't show in PDF after save
