### ISSUE TITLE
Ability to use variable references in service URL AVT

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#5782]
I don't think this is supported yet, looking at the code. Needed:

- [x] call to `frf:replaceVarReferencesWithFunctionCalls()`
- [x] renaming in Form Builder

See `actions.xsl`.

**Comment by avernet** [comment]
[+1 from discuss](http://discuss.orbeon.com/Calling-a-Service-td4660424.html) from duplicate #2384.

**Comment by obruchez** [comment]
- [ ] doc
