### ISSUE TITLE
Short section labels for wizard

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#5795]
As a Form Builder, I want to be able to designate a "short label" for sections so that forms presented in wizard view provide a better user experience.

Suggested location for new feature:

- The availability of the new feature should probably be located in the Label tab of the Section/Grid Settings dialog.

Suggested design/options:

- Change "Label" to "Full Label", "Display Label" or other.
- Add new label field called "Short Label", "Navigation Label", or other.
- Add an additional "Use HTML" checkbox for the new label field.
- Align "Use HTML" checkboxes with field labels so association is stronger.

Suggested behaviours:

- If a "Navigation Label" is blank (null), Orbeon uses the "Full Label" for wizard navigation.
- Both Labels can use Template Parameters.
- They can both use the same set of templates (no need to duplicate the Template Parameters part of the UI)

[+1 from customer](https://3.basecamp.com/3600924/buckets/4224335/documents/3610449223)

**Comment by ebruchez** [comment]
One question is about how the wizard can get the value of the short label. For the label proper, the wizard uses the `xxf:label()` function. But there is is no equivalent function for the short label.

`controls.xsl` replaces:

```xml
<xf:label ref="...">
    <fr:param>
        ...
    </fr:param>
</xf:label>
```

with a simple:

```xml
<xf:label ref="..."/>
```

where the `ref` has been replaced with an expression that evaluates the template.

The same is done with `<fr:short-label>`, except that `<fr:section>` will not automatically interpret that element.

Note that `fr:iteration-label` and `fr:add-iteration-label` are handled by `fr:repeater`, which is used by `fr:section`.

Here, we should have `fr:section` handle `fr:short-label`. What does handle mean? The section will not display it. Instead, it will expose an `<xf:output>` in the outer scope with a known id and the value. Inspired by `fr:repeater`:

```xml
<xsl:for-each select="fr:short-label[1]">
    <xf:output
        id="{concat($root/@id, '-short-label')}"
        value="{@ref}"
        xxbl:scope="outer">
        <xsl:copy-of select="@mediatype"/>
    </xf:output>
</xsl:for-each>
```

Then `fr:wizard` can use `xxf:value()` to get the value of that control by id. See in `fr:wizard` the handling of `section-label-expr`. For a section id `foo`, the id of the control will be `foo-short-label`.

**Comment by obruchez** [comment]
As discussed, I've explored the idea of using a hidden field (`<fr:hidden>`) instead of a hidden output (`<xf:output class ="xforms-hidden">`) to store the value of the short label, but I can't seem to make section.xbl produce one. Actually, I'm not sure it even makes sense (i.e. an XBL component producing other controls).

**Comment by obruchez** [comment]
Trying another way, I've also found that template parameters don't work with short labels.

**Comment by obruchez** [comment]
> Trying another way, I've also found that template parameters don't work with short labels.

This was just a missing namespace in section.xbl (now fixed).

**Comment by avernet** [comment]
[Documented](https://doc.orbeon.com/form-builder/form-editor/section-settings#label-help-message-and-short-labels) by @obruchez
