### ISSUE TITLE
Add suggestion of variable names in all formulas

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#5798]
Started implementation using https://github.com/github/text-expander-element. This is a big usability improvement for formulas so we should finish this!

Remaining tasks:

- [x] +renamed, -original names in dialog when renaming
- [x] fix: open dialog, completion ok; close, reopen, no completion
    - might need to change `text-expander-element` to improve component lifecycle
- [x] menu entries should show control labels as well (we control the content, could also add icons, etc.)
- [x] upgrade to latest version (2.8.0)
- [x] ~~consider backporting to 2022.1.x~~
    - this will be in 2024.1
- [x] add `xpath-completion` appearance to all formula fields
    - [x] Email Settings
    - [x] Actions
        - [x] condition
        - [x] itemset: do we support `$`
    - [x] Dynamic Dropdown
    - [x] other control editors?
- [x] fix menu in dialog that appears behind the area
    - need to change `text-expander-element` to add optional `container` element?
- [x] add hint/help icon to all formulas
    - did 4 formulas in Control Settings, will have to do more later, (#4098)

**Comment by ebruchez** [comment]
We were also discussing with @avernet about whether we could add completion for function names. This is a little harder as there is no obvious trigger key (for variables, it is `$`), and the GitHub component expects to have a starting character followed by a word. We could define a special character, like `#`, or `?`, which would start function completion. This would have to be documented/hinted as it's not discoverable - although, to be fair, variables completion is not very discoverable either. So add hint/help icon to all formulas!

**Comment by ebruchez** [comment]
RESOLVED: complete for 2023.1. Maybe @obruchez can work on it.

**Comment by avernet** [comment]
I'm pushed the fix so the completion menu doesn't get truncated (after a valiant [fight](https://www.youtube.com/watch?v=WAvchbP2kXM) with nvm, bass, fisher… the kind of stuff you get for switching to fish). It may or may not also solve the problem for the help bubbles, which I don't see (@ebruchez did you push them?).
