### ISSUE TITLE
Add `<fr:control-setsize>` to the Action Syntax

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#5817]
The element for a Single File Attachment looks like:

```xml
<my-file filename="" mediatype="" size=""/>
```

In the action syntax, we have actions to set the `filename`, the `mediatype`, but not the `size`, i.e. the third action below does not exist. This issue calls for adding one.

```xml
<fr:control-setfilename  control="my-file" value="…"/>
<fr:control-setmediatype control="my-file" value="…"/>
<fr:control-setsize      control="my-file" value="…"/>
```

**Comment by ebruchez** [comment]
([Doc](https://doc.orbeon.com/form-builder/advanced/services-and-actions/actions-syntax#setting-the-size-of-an-attachment-control))
