### ISSUE TITLE
Support AVTs in `oxf.fr.persistence.filesystem.directory` property

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#5831]
This is an improvement after #4146.

We have 2 use cases in mind, and in both of these the AVT would use the [`environment-variable()` function](https://doc.orbeon.com/xforms/xpath/standard-functions#environment-variable).

- For the tests, to be able to point to a temporary directory setup with an environment variable, as the temporary directory is typically different on Linux/macOS (`/tmp`) and Windows.
- For production, so the same properties can be used in different environments in which the temp directory might be different

**Comment by ebruchez** [comment]
Implementation hints to follow what's done in `PDFTemplateProcessor`:

- use `XPathCache.evaluateAsAvt`
- use `FunctionLibrary.instance` 
- there is no clear XPath context to provide, so
    - try passing `null` (for the empty sequence)
    - if that doesn't work pass an empty XPath `StringValue`

**Comment by avernet** [comment]
- [ ] Make it so `environment-variable()` can be called from AVT in `oxf.fr.persistence.filesystem.directory` specificallty without having to enable `oxf.xpath.environment-variable.enabled`

**Comment by ebruchez** [comment]
Following today's discussion:

- [ ] hookup in the function library a version of `environment-variable()` that doesn't check for the property to enable it
    - this is desirable since otherwise you need to enable environment variable support globally just to have a way to configure your base directory using an environment variable
    - in fact could this be the case for the `PipelineFunctionLibrary` in general, as that function is not accessible through user-defined forms?
