### ISSUE TITLE
Allow form authors to specify success and error messages in Form Builder

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#5833]
The [`success-message()` action](https://doc.orbeon.com/form-runner/advanced/buttons-and-processes/actions-form-runner#success-message-and-error-message) can either take:

- A resource name, as in `success-message(resource = "save-success")` or `success-message(resource = "email-success")`
- An actual message, as in `success-message(message = "All is good")`

When `resource` is used, the corresponding name under `detail.messages` is looked up, e.g. `detail.messages.save-success`, and as is the case for all resources, this can be [overridden by setting a property](https://doc.orbeon.com/configuration/properties/form-runner#overriding-resources), e.g. by setting the value of the `oxf.fr.resource.*.*.en.detail.messages.save-success` property.

This RFE calls for adding a UI to Form Builder to enable form authors to define their own resource → message, with the message being localizable. This is not unlike the Edit Choices dialog (with the Edit Choices' value corresponding to the resource, and the Edit Choices' label corresponding to the message).

<img width="358" alt="Screenshot 2023-05-25 at 10 50 25 AM" src="https://github.com/orbeon/orbeon-forms/assets/106961/44979242-48ec-44bf-b17a-6c234f630a1f">

For the resource, instead of just having a text field, we're thinking of using a Dropdown with "Other" (`<fr:open-select1>`), pre-populated with the resources used by calls to `success-message()` and `error-message()` that are provided in processes coming out-of-the-box.

Where the added UI will be placed is TBD; maybe we can just add it to the Form Options tab of the Form Settings dialog.

[+1 from customer](https://3.basecamp.com/3600924/buckets/4224335/documents/4538214999)

**Comment by obruchez** [comment]
- [ ] doc

**Comment by obruchez** [comment]
Fixed case where metadata/resources is missing.

**Comment by obruchez** [comment]
- [ ] fix tests

**Comment by obruchez** [comment]
- [ ] add template

**Comment by ebruchez** [comment]
- [ ] show an initial empty line when opening the dialog initially (same as "add template" above?)
- [ ] show readonly language in column even if there is only one language

**Comment by ebruchez** [comment]
[Doc](https://doc.orbeon.com/form-builder/advanced/messages)
