### ISSUE TITLE
Bulk update from the summary page

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#5836]
This calls for allowing users to update certain form fields in bulk, from the summary page. This is not unlike what can be found in GitHub Issues, which allows certain fields of the issues to be updated directly from the Issues page.

[+1 from customer](https://3.basecamp.com/3600924/buckets/7993860/messages/6178039850)

*2023-05-29 @avernet What follows is mostly obsolete; instead see [comment](https://github.com/orbeon/orbeon-forms/issues/5836#issuecomment-1567796690).*

Some thoughts:

- UI
    - For selection control
        - Drop-up button, along with the other buttons, with label such as "Set status"
        - When clicked, shows the possible options
        - The button is enabled when 1 or more rows are selected
- How the modifications are done
    - Options
        - 1. Through the CRUD API, reading the data, changing the value, and writing the data back
        - 2. Running a process on each document
    - Option 1 is more efficient, option 2 is more precise as far as permissions go
    - With option 2, updates can fail for certain documents, and we might want to report that, e.g. "5 out of 7 documents updated"
- Permissions: whether a certain user can perform the update
    - Options
        - 1. Driven by permissions on the form itself
            - This sounds like it would be the most "precise" and "simplest" way to do it.
            - The result can be different for each row, but also for each value to be set.
            - This means we wouldn't realistically be able to determine ahead of time if a certain row can be updated
        - 2. Controlled by a setting on the form
            - Controls settings: add a checkbox to allow this, then an optional field to enter the required role

**Comment by ebruchez** [comment]
A few more thoughts, comparing the *viewing* and *updating* scenarios.

For viewing data on the Summary page, there are currently two conditions:

- the field ("column" in the Summary page) has "Show in Summary" checked
- the document ("row" in the Summary page) has the `read` permission
    - Q: What if it only has the `delete` permission? Check!

However, still for viewing, we do not check whether the field to show might have been non-relevant when the form was saved, or whether if the current user was viewing the data, the field would be non-relevant - and the two relevance values might be different, for example  if the data was saved by user A and see in the Summary page by user B, or if there are more complex conditions in place (dependent on URL parameters, headers, workflow stage, current time, etc.). In other words, viewing a value in the Summary page is not exactly the same as saying that the value would be visible in the form if the user was actually opening the form and viewing the data (or updating it).

(This said, we *could* hide fields that had `fr:relevant="false"` upon saving, or simply not index that data if it has `fr:relevant="false"` upon saving.)

Similarly, for updating values, if we want to be exact, that is do *as if* the user was opening the form data and entering a value, there are no shortcuts to actually running the form in `edit` mode.

As noted above, this would be costly. But in the same way that we don't do that for viewing the values, we probably don't need to do that for updating the values, although this could be an option implemented later.

So in this simple version, a field would be updatable if:

- the field ("column" in the Summary page) has "Allow updating in Summary" checked
- the document ("row" in the Summary page) has the `update` permission
    - This information is already returned by the search API so it's easy to access.

**Comment by avernet** [comment]
Resolutions:

- Values are updated by the summary page with the REST API (instead of running forms in the background).
- Form authors must be able to restrict who can set values, at least on a per-role basis.

The implementation has 3 parts:

1. The summary page UI, allowing users to select which field they want to update, and with what value.
    - For this, we have a more GitHub-like UI in mind, but given time constraints, will implement this later.
    - For now, we're thinking of just extending the current field search UI, renaming "Show Options" into "Show Search Options", and "Hide Options" to "Hide Search Options", and adding a button "Show Bulk Edit", which shows a section very similar to the one we have for search, but with an additional "Set" button. When the section is shown, the button becomes "Hide Bulk Edit". Which fields are shown is driven by a checkbox "Show in bulk edit" shown in the Control Settings (see below).   In this UI, for now, we only need to support selection controls.
    <img width="671" alt="Screenshot 2023-05-29 at 10 37 41 PM" src="https://github.com/orbeon/orbeon-forms/assets/106961/6389f7e2-e076-40b5-97c3-c63709780ac9">
2. The summary page logic that uses the REST API, and that, for each selected row, retrieves the data (GET), sets the field to the required value (for this, we need to find the XPath pointing to the element corresponding to a certain field, and we have logic along those lines used for Search, which we might be able to leverage), and saves the data (PUT).
3. A new checkbox in the Control Settings dialog, "Show in bulk edit"
    <img width="487" alt="Screenshot 2023-05-29 at 10 49 36 PM" src="https://github.com/orbeon/orbeon-forms/assets/106961/7e322275-584e-4be1-9c27-656da218267e">

How to restrict who can perform a bulk edit, if enabled in Control Settings, is yet to be determined. Two possible options are:

- On a per-control basis, so in Control Settings, when "Show in the bulk edit" is checked, form authors can specify which roles can perform that operation. Benefit: different fields can have different role requirements.
- Through the Permissions dialog, with a new column "bulk edit". Benefit: more in line with the Wei permissions work now, provides more granularity at the entire form level (owner, group…).

**Comment by avernet** [comment]
In this comment I'll cover the scope of the permissions functionality. I'll cover the implementation in the following comment.

In Control Settings, for each of the checkboxes "Show on Summary page", "Show in Search", and "Show in Bulk edit", when the checkbox is checked, next to it we show a "Restrict to role" checkbox, which if clicked shows a required text field allowing form authors to type a role.

<img width="543" alt="Screenshot 2023-06-01 at 12 05 07 PM" src="https://github.com/orbeon/orbeon-forms/assets/106961/5f264fc5-84f3-4376-b25a-9cd73822fbe1">

If the "Restrict to role" checkbox is checked, then the summary page provides the corresponding functionality only if the user has the specified role. For instance, if a role is required for "Show on Summary page" and the user doesn't have that role, then the corresponding column won't show on the summary page.

- TBD
    - [ ] "Show on Summary page" isn't very accurate anymore. Here is a suggestion. All three checkboxes are for the summary page. We could maybe use a fieldset or similar, that contains the three checkboxes, with label "Summary page", and rename the first one to "Show in table", and "Allow search", "Allow bulk edit".
- Possible future improvements
    - Support for multiple roles (if we add this, is it a `or` or `and` between the roles?)

**Comment by avernet** [comment]
Currently, when a checkbox is checked, we add a class on the control, for instance `class="fr-summary"`. With this change, since we also need to store the roles, this calls for moving the state of the checkboxes and the roles to the form metadata, stored in the `fr-form-metadata` instance. We add a new section `<summary>` for this, inside `<metadata>`, which could look like:

```xml
<summary>
    <field name="approved">
        <read/>
        <write require-role="manager"/>
    </field>
</summary>
```

In this case, the field named `approved` shows in the table to all users, but only users with the role `manager` are allowed to bulk update it. (In the future, as mentioned above, we might want to support multiple roles, but it is unclear if we want an `or`, `and`, or both type of logic. So for now we just keep the name `require-role` in the metadata.)

Storing this information in the metadata rather than on the controls allows for more flexibility, and we did the same change recently for email, but this also means that:

- Forms need to be upgraded when opened in Form Builder (see `annotate-migrate.xsl`).
- At runtime, the summary page still needs to support the legacy format, as we might have forms published with a previous version that still have the information on the controls.
- [ ] Section templates support
    - This is P2, in the sense that we can have a MVP without this, but we want to have this before closing this issue, hence adding a checkbox above so we don't forget about it.
    - On publish, we create an XBL component for the section template, inside which we already put an `fr-form-metadata` instance for the email functionality. We will want that metadata to also have the `<summary>`.
    - In the summary page, we need to not only check the metadata for the form itself, but also the metadata for the inline XBL corresponding section templates. Luckily, we already have code doing exactly that for email, which we should be able to reuse.

**Comment by obruchez** [comment]
Some tasks left to do after the first commit:

- [ ] Remove require-role attribute if empty
- [ ] Forms need to be upgraded when opened in Form Builder
- [ ] Look and feel: align role checkboxes/fields in control dialog
- [ ] Look and feel: bulk edit section
- [ ] When forms are all deselected, the bulk edit section should be closed
- [ ] Error reporting when updating the controls
- [ ] Adapt example forms (bookself, etc.)
- [ ] Add tests to IndexTest
- [ ] Simplify the code in `dialog-control-settings.xbl`(e.g. duplicated code with `fr-summary-show/search/edit`)

**Comment by avernet** [comment]
P2 (i.e. after form migration):

- [ ] I would suggest we don't disable "Show Bulk Edit", and instead disable the "Apply" buttons. This as I found it counterintuitive that you would need to select one or more row before being able to open "Show Bulk Edit". (However, once open, it stays open even if you deselect rows.)

**Comment by avernet** [comment]
- [ ] Support other control types, in addition to the selection controls, supporting at least the controls that don't pose any particular difficulty to implement, maybe at parity with the controls supported by search
- [ ] Avoid having a situation where clicking on Show Bulk edit shows an empty section (as shown below); in such a case, we should either hide or disable the Show Bulk edit button (hide benefit: why show a UI element that we know users won't be able to use; disable benefit: making users aware that this feature exists)
    ![screencast](https://github.com/orbeon/orbeon-forms/assets/106961/c12457ba-fcb8-4edc-99d3-b30539006159)
- [ ] When both the search fields and the bulk edit fields are shown, it isn't clear which is which; we could add a title inside each section (see how fieldset/legend are rendered in Form Builder), or when users open one section automatically close the other section
    <img width="1070" alt="Screenshot 2023-06-08 at 11 45 36 PM" src="https://github.com/orbeon/orbeon-forms/assets/106961/8c427377-dc8b-496b-a9dc-dfa9cb75ee8e">

**Comment by obruchez** [comment]
Re. the bulk edit empty section: "Show Bulk Edit" is already disabled when no control is marked as "Show in bulk edit". I guess you had an unsupported control marked as "Show in bulk edit". This actually can happen with search options as well (see video). This will be less problematic when bulk edit supports all controls that are supported by search. The question is: should we do anything about unsupported controls (for both search and bulk edit)?

<img width="1319" alt="Screenshot 2023-06-09 at 15 00 36" src="https://github.com/orbeon/orbeon-forms/assets/1003397/cde422db-04f5-410e-9ff7-a80a7ab146d6">

https://github.com/orbeon/orbeon-forms/assets/1003397/f8c30e19-370b-499f-a828-8ac0b9090db0

**Comment by obruchez** [comment]
- [ ] doc

**Comment by ebruchez** [comment]
[Doc](https://doc.orbeon.com/form-runner/features/summary-page#bulk-edit)
