### ISSUE TITLE
PDF table of contents to include repeated sections titles

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#5855]
[+1 from customer](https://3.basecamp.com/3600924/buckets/5085006/messages/5612475978)

**Comment by avernet** [comment]
Result with Traveler Form:

<img width="1024" alt="Screenshot 2023-07-04 at 6 05 59 PM" src="https://github.com/orbeon/orbeon-forms/assets/106961/76959bc4-329e-408e-a2c8-2a5231f09fa8">

**Comment by avernet** [comment]
Result with [test form](https://github.com/orbeon/orbeon-forms/files/11952932/form.txt):

<img width="961" alt="Screenshot 2023-07-04 at 6 07 36 PM" src="https://github.com/orbeon/orbeon-forms/assets/106961/a3a74ba5-daa0-4f12-a0d6-e2a0df5f171f">
