### ISSUE TITLE
Special characters not showing in PDF

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#5881]
To reproduce, create a new form, type "≤" in the value of the field, click on the arrow next to the Test button, then Test PDF. In the generated PDF, the character "#" shows instead of "≤", and we can see the following error in the log, despite that file seemingly being in the correct location. I can reproduce this was 2022.1.4.

> XHTMLToPDFProcessor - Failed to load font by path: `/apps/fr/print/Inter-Medium.ttf` specified with property `oxf.fr.pdf.font.resource.inter`

<img width="747" alt="Screenshot 2023-06-29 at 6 26 50 PM" src="https://github.com/orbeon/orbeon-forms/assets/106961/9ed9441f-a86e-4e88-85fc-a02d7d7adf75">

[+1 from customer](https://3.basecamp.com/3600924/buckets/5085006/messages/6127006150)

**Comment by ebruchez** [comment]
For reference, see also [this doc](https://github.com/danfickle/openhtmltopdf/wiki/Fonts) from `openhtmltopdf`.

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/18345583/messages/6253766811)
