### ISSUE TITLE
Automatic PDF generation can be extremely slow on large forms

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#5888]
[+1 from customer](https://3.basecamp.com/3600924/buckets/7993860/messages/6286435915)

**Comment by ebruchez** [comment]
Possible [+1 from customer](https://3.basecamp.com/3600924/buckets/5085006/messages/6373981778)

**Comment by ebruchez** [comment]
@avernet implemented a fix. Not sure why the issue is not closed.

**Comment by ebruchez** [comment]
Once satisfied:

- [ ] cherry-pick on CE `master`
- [ ] close issue
