### ISSUE TITLE
Session heartbeat request sent too frequently

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#5889]
We are sending a session heartbeat every `0.8*sessionLength/10`. For a 1 hour session, this means that we send that request every 4.8 minutes, which isn't too much of a problem, but it creates lots of events for shorter sessions, for instance one every 0.8*600/10 = 48 seconds with a 10 minute session.

[+1 from customer](https://3.basecamp.com/3600924/buckets/7993860/messages/6305620377)

**Comment by ebruchez** [comment]
Noting that this was also released with 2022.1.5.
