### ISSUE TITLE
Date picker navigation is not read by NVDA

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#5906]
- form with date field
- tab to calendar icon, enter
- date picker opens
- cursor keys navigate calendar, but NVDA only lists "blank"
- first date selected by enter is read
- but if trying a second time, date is not read

To try/check:

- VoiceOver
- check [Bootstrap Datepicker](https://bootstrap-datepicker.readthedocs.io/en/latest/): supports any of this out of the box?
    - if so and works, see if we need to upgrade Bootstrap Datepicker

[+1 from customer](https://3.basecamp.com/3600924/buckets/1956846/messages/6307235213#__recording_6359892208)

**Comment by avernet** [comment]
We are using bootstrap-datepicker 1.8.0, and their latest version is 1.10.0, released in May of this year, but I do not see any accessibility improvements in either [1.9.0](https://github.com/uxsolutions/bootstrap-datepicker/compare/v1.8.0...v1.9.0) or [1.10.0](https://github.com/uxsolutions/bootstrap-datepicker/compare/v1.9.0...v1.10.0), and it does not look like any work has been done on https://github.com/uxsolutions/bootstrap-datepicker/issues/811. So it looks like we could either:

1. Take on the task of fixing https://github.com/uxsolutions/bootstrap-datepicker/issues/811 ourselves.
2. Switch to another date picker that has better accessibility support.
3. Use the built-in HTML date picker.

As I recall, when we implemented the current `date.xbl` using the bootstrap date picker back in 2018 (#3657), the desktop version of Chrome had only embryonic support for `<input type="date">`, while the desktop version of Safari was already decent. Now, all modern desktop browsers seem to provide an acceptable date picker (see the screenshot on [this blog post](https://webcache.googleusercontent.com/search?q=cache:7Bf4H6mIpXcJ:https://developer.chrome.com/blog/show-picker/&cd=10&hl=en&ct=clnk&gl=us)), so I am leaning towards option 3.

**Comment by avernet** [comment]
Closing this through #5956.
