### ISSUE TITLE
Possible incorrect email template conversion

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#5923]
[This form](https://3.basecamp.com/3600924/buckets/7449965/messages/6341965617#__recording_6423067437) includes the following:

```xml
<parameters>
    <param type="AllControlValuesParam(all)">
        <name>all</name>
    </param>
</parameters>
```

`AllControlValuesParam(all)` is not correct. It should be `AllControlValuesParam`.

**Comment by ebruchez** [comment]
I am not sure how this got generated in the first place, but it shouldn't be. In the meanwhile, I am adding a temporary test to handle this case at runtime.

**Comment by ebruchez** [comment]
This is the real cause of #5900.

**Comment by ebruchez** [comment]
Workaround is on 2022.1-pe and master.

**Comment by avernet** [comment]
Fixed by https://github.com/orbeon/orbeon-forms-pe/commit/9fa2f3cf774ac5c9387cd8b2245d52e4cc2978ce.
