### ISSUE TITLE
Form Builder: search by form name yields unexpected results

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#5928]
<img width="388" alt="image" src="https://github.com/orbeon/orbeon-forms/assets/105769/19e6abbc-fa2f-4247-9ac4-5959afb4b01d">

[+1 from customer](https://mail.google.com/mail/u/0/#inbox/FMfcgzGtwWGdzDrshhHxcMbrLwSvXTDw)

**Comment by ebruchez** [comment]
Issue is that we use `LIKE`, where `_` represents a character, and `%` represents zero, one, or multiple characters.

We should either:

- escape `_` and `%` (and also `\`)
- use something other than `LIKE`, for example `INSTR(value, 'foobar') > 0`

**Comment by avernet** [comment]
On case-sensitivity, for Oracle and SQL Server, we use `contains()`, which depends on collation. By default it will be case-sensitive on Oracle, case-insensitive on SQL Server. For MySQL, we use `LIKE`, which is case-insensitive. On PostgreSQL, `LIKE` is case-sensitive, and we use `ILIKE`, which is not. So we want the search to be case-insensitive, for backward compatibility, and consistency with what we do for most other databases. `instr()` uses the collation on the column, which we set explicitly to `utf8mb4_unicode_ci`, so it will be case-insensitive, so from that perspective we are good using `instr()`.

The performance of `instr()` and `like` seems similar, so going with `instr()`, which avoids the character replacements.

**Comment by ebruchez** [comment]
- [ ] check other users of `LIKE`

**Comment by avernet** [comment]
- [ ] @obruchez Write unit test (`SearchTest.scala`): do a basic test searching for a string containing an underscore with the (1) full-text search and the structured text (2) substring, (3) exact, and (4) token matches

**Comment by ebruchez** [comment]
I cherry-picked @obruchez's latest commits on 2022.1-pe.

**Comment by obruchez** [comment]
- [ ] fix free text test in `SearchTest` for SQL Server (index is not updated right away - waiting e.g. 10 seconds fixes the problem, but we should probably test that we have the expected result _eventually_)

**Comment by obruchez** [comment]
- [ ] fix  2022.1-pe tests
- [ ] fix 2022.1.5-pe-elca tests
- [ ] fix tag-release-2022.1.5-pe tests

**Comment by obruchez** [comment]
#5981 has been created for further investigations (more special characters, etc.).
