### ISSUE TITLE
Automatically visit changed visible fields

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#5934]
We do not show an alert for invalid fields if they are not visited, to avoid having forms show lots of errors as soon as they load, and instead show the alert for a field right after the user has interacted with that field, i.e. "visited" it. This makes sense for fields that users typically "interact" with, such as typing a value into the field. However, they are unlikely to visit read-only fields, and as a result, alerts for those fields are not displayed until later, typically when users try to save or submit the form. Therefore, this RFE requires that alerts for read-only fields be displayed even if they are not visited.

Since this is a new behavior, for backwards compatibility, we would like to make this new behavior the default for new forms only, and keep the old behavior as the default for old forms, while letting users choose which behavior they prefer in all cases.

[+1 from customer](https://3.basecamp.com/3600924/buckets/1966718/messages/6472620749)

**Comment by ebruchez** [comment]
We could mark the control visited if its value changes.

Q: Should this apply to all controls, such as Text Input?

**Comment by ebruchez** [comment]
Notes:

- OP regards a readonly control
- but also applies to Calculated Value control

Q: What if the value that changes is further in a wizard in validated mode? Probably don't want to show the error then. So additional constraint would be that the field is `visible`.

**Comment by ebruchez** [comment]
RESOLUTION:

- [ ] implement simple solution
- [ ] temporarily put feature behind flag, and off by default
- [ ] for 2023.1, turn on by default if all is good

**Comment by ebruchez** [comment]
Q: Can we implement this in "user mode", that is, using an event handler for `xforms-value-changed`?

**Comment by ebruchez** [comment]
Decided to do this in semi-user mode, in the Error Summary.

**Comment by ebruchez** [comment]
To enable this with 2022.1.5 PE, set:

```xml
<property
    as="xs:boolean"
    name="oxf.xforms.xbl.fr.error-summary.visit-value-changed"
    value="true"/>
```
