### ISSUE TITLE
Disable external entities

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#5944]
On https://demo.orbeon.com/demo/sandbox-transformations/xpath/, using the input document `<!DOCTYPE data [<!ENTITY xxe SYSTEM"file:///etc/passwd">]><data>&xxe;</data>` and the XPath expression `/*` shows us the contents of the file `/etc/passwd`, which is not desirable. This should not happen according to #3468. Is it only happening here because of something special we are doing in this sandbox example? If so, we can close this issue since we just removed the sandbox examples (#5943).

Thanks to Sonny of watchTowr https://watchtowr.com/ for the report.

**Comment by ebruchez** [comment]
Closing, as we have removed the sandboxes.
