### ISSUE TITLE
Cannot edit alert messages in Validations and Alerts tab

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#5945]
This happens in 2021.1.9, but not in 2022.1.4.

[+1 from customer](https://3.basecamp.com/3600924/buckets/7545500/messages/6491073242)

**Comment by ebruchez** [comment]
- [ ] @ebruchez to repro
- [ ] fix

**Comment by ebruchez** [comment]
I reproduce this.

The XHR response doesn't tell the client to change the readonliness of the field. So it could be:

- the client doesn't tell the server correctly about the checkbox value
- the server doesn't handle the MIP correctly
- anything else?

**Comment by ebruchez** [comment]
Client sends to the server a `true` value even when the checkbox is deselected:

```xml
<xxf:event name="xxforms-value" source-control-id="dialog-control-settings≡fb-tabbable≡validations-grid≡xf-3003⊙3">
    <xxf:property name="value">true</xxf:property>
</xxf:event>
```

**Comment by ebruchez** [comment]
This regressed with #5651, which was 2021.1-pe only. It changes the order of tests in `Controls.getCurrentValue()`.

**Comment by ebruchez** [comment]
Mmh, actually maybe some earlier issue.

**Comment by ebruchez** [comment]
Was #5651, but a second clean-up commit that was wrong!
