### ISSUE TITLE
Video component

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#5946]
This RFE is for providing a new video component that allows form authors to upload a video, and users editing or viewing the form to see the video. To play the video, we want to use a `<video>'; if it helps, see what Basecamp does when attaching a video to a message.

First, we can make the video component behave very much like the static image component, except that it plays a video instead of displaying an image. This means that the video will be stored in the data. The path will be to published form attachments, e.g. `/fr/service/persistence/crud/your-app/your-form/form/123.bin`, so we won't have a copy of the video for each form data, but having this path in the data is not very useful. Once we have a working MVP, we can look into storing this file elsewhere, such as in the form resources, as is done by the Explanatory Text control for the text shown to users.

[+1 from customer](https://3.basecamp.com/3600924/buckets/18358270/messages/4874276212)

**Comment by avernet** [comment]
Based on today's discussion:

- [ ] Also support `Range` for `file://`, i.e. to be able to play a video in Form Builder right after it is uploaded.
- [ ] Support for PostgreSQL
    - Have PostgreSQL specific code in `Provider.scala`.
    - Write a test (most likely `RestApiTest`).

**Comment by obruchez** [comment]
- [ ] support for other databases (`partialBinary`/`binarySize` in `Provider.scala`)
- [ ] tests (`RestApiTest`)
- [ ] doc

**Comment by obruchez** [comment]
Oracle is now supported, but currently the attachments can only be read 2000 bytes at a time (see #5978).

**Comment by ebruchez** [comment]
[Doc]((https://doc.orbeon.com/form-builder/advanced/email-settings#usage)
