### ISSUE TITLE
`content.css` pollutes top-level page

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#5962]
This happens since we switching to using the `inline` mode for TinyMCE (#5441).

[+1 from customer](https://3.basecamp.com/3600924/buckets/14122811/messages/6519681209)

**Comment by ebruchez** [comment]
@avernet I don't see this on the 2022.1-pe branch.

**Comment by avernet** [comment]
@ebruchez Ah, good catch, forgot to push; now done.
