### ISSUE TITLE
JavaScript error in Form Builder when copying a Formatted Text Area

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#5963]
This happens when doing the copy while the menu is displayed. Somehow I don't get the error when I just move it. Below, I first try to move it from left to right, which works fine, but then I get the error when copying from right to left. This is with the latest code on the `2022.1-pe` branch.

![screencast](https://github.com/orbeon/orbeon-forms/assets/106961/8788cbe5-d23a-4689-b490-da749e760428)

**Comment by ebruchez** [comment]
Trying to follow the steps, but I can't reproduce this one.

**Comment by avernet** [comment]
I just tried it and I can still reproduce it. A few things to keep in mind:

- Use a 2022.1 build from Travis, just to be sure.
- Click inside the text area to show the toolbar before doing the shift & drag with the 4-direction icon to make a copy to the next cell.
    - No problem if you do a move instead of a copy (no shift)
    - No problem if the toolbar doesn't show when you copy

**Comment by ebruchez** [comment]
- [ ] try with touchpad instead of mouse
- [ ] try with CI build

**Comment by ebruchez** [comment]
I reproduce this now on the 2022.1-pe branch, with the mouse and trackpad, but not on master.

**Comment by ebruchez** [comment]
The event originates in `TinyMCECompanion`:

- `blur` event
- `clientToServer()`
- `DocumentAPI.setValue()`
- `Controls.setCurrentValue()`
- `AjaxFieldChangeTracker.hasChangedIdsRequest()`
- form not found

The element is detached from the dom (no `form` or `body` ancestor), so the call fails.

On `master, I don't see significant changes to `AjaxFieldChangeTracker`, `setCurrentValue()`, or `TinyMCECompanion` that can explain this. However, if the control is detached and the `blur `event is somehow received, `TinyMCECompanion` should call `DocumentAPI.setValue()` and the rest. So we can fix things this way.
