### ISSUE TITLE
Formatted Text Area toolbar not displayed when first in form

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#5965]
When you first enter the form, the textarea gets the focus, but the toolbar doesn't appear. It also doesn't show when you tab out of the textarea and back into it. It only appears when you click in the text area if it doesn't already have the focus.

![screencast](https://github.com/orbeon/orbeon-forms/assets/106961/b4cf7cc8-85dd-4298-acb3-9c1bb56a3649)

**Comment by ebruchez** [comment]
Can't reproduce on demo or master.

**Comment by avernet** [comment]
Closing, can't reproduce as well :).
