### ISSUE TITLE
Workflow stage is lost when going to the view page

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#5984]
[+1 from customer](https://3.basecamp.com/3600924/buckets/7993860/messages/6535571830)

**Comment by ebruchez** [comment]
We have parameters that we now pass between modes differently, in particular for the token see #5437. There is a TODO there to (re)check how we do this. Not sure how it is done now on 2022.1.

**Comment by ebruchez** [comment]
When implementing #5437, we improved the preservation of permission operations (`read`, `update`, etc.) between mode changes (`new` → `view`, `edit` → `view`, etc.), by encrypting the operations and passing them internally as a URL parameter, then decrypting them on the other side (to prevent injection).

The handling of the workflow stage should be identical.

Note that the changes for #5437 are on 2023.1 only and not on 2022.1.
