### ISSUE TITLE
When the itemset changes, always send the current value, even if it is unchanged

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#5986]
Right now, the server doesn't "resend" the value of a selection control to the browser if the itemset has changed but the current value hasn't. Instead, we should resend the value because the value used by the client is a position in the itemset that may have changed if the itemset changed. Of course, it would be fine not to resend the current value if we know that the position of the current value in the itemset hasn't changed.

A result of the current behavior is that the control may display an empty or incorrect value as a result of the itemset changing, even if the current value is still in the itemset.

**Comment by avernet** [comment]
The logic in `mustOutputAjaxValueChange' looks correct to me (i.e. based on external values), except that `getExternalValue' returns the previous external value. It seems that the itemset change didn't cause the external value to be re-evaluated.

**Comment by ebruchez** [comment]
See also #3038.
