### ISSUE TITLE
"Show on Summary page" / "Restrict to role" to support multiple roles with and/or logic

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#5994]
- This is a follow-up to #5836.
- UI
    - When "Restrict to role" is checked, the usual buttons to add more roles are displayed next to the text box.
        <img width="304" alt="image" src="https://github.com/orbeon/orbeon-forms/assets/106961/5172d435-789e-4989-b232-1291607b7e97">
    - If more than one role is added, we'll show the text "User must have Any/All of the following roles" above the text fields, where Any/All is a drop-down menu with these two choices.
- Form Definition
    - Currently, the following is added inside the control:
        ```XML
        <fr:index
            <fr:summary-search require-role="xxx"/>.
        </fr:index>
        ```
    - Just an idea, not part of the "spec": a simple, backward-compatible extension would be to keep `require-role="aaa"` when there is one role, and where there are multiple, use the attributes `require-role-any-of="aaa bbb"` or `require-role-all-of="aaa bbb"` (we already use an `any-of` attribute for permissions). We could go for something that allows nesting and/or, but I'm not sure we'll need this in the near enough future that it's worth paying the implementation price now.
- Finally, the summary page needs to reflect the new information.

Current dialog:

<img width="990" alt="image" src="https://github.com/orbeon/orbeon-forms/assets/106961/6d30666a-c0a3-441f-aaf1-52087f28b543">

**Comment by obruchez** [comment]
UI's proposal from @avernet:

<img width="614" alt="Screenshot 2023-09-29 at 18 20 34" src="https://github.com/orbeon/orbeon-forms/assets/1003397/91c4a2cb-0948-469b-aa9b-fd06d7058113">

Depending on the initial value found in the form, we will either display:

- a checkbox: "Show in summary page"
- a dropdown: Don't show on summary page / Show on summary page / Show search only / Show column only

- [ ] adapt the UI

**Comment by obruchez** [comment]
- [ ] adapt the form format

Current:

```
<fr:index>
  <fr:summary-show require-role="..."/>
  <fr:summary-search require-role="..."/>
  <fr:summary-edit require-role="..."/>
</fr:index>
<fr:encrypt/>
```

After:

```
<fr:index>
  <fr:show-in-summary search=”true=default” column=“true=default” require-role="...">
  <fr:allow-bulk-edit require-role="..."/>
</fr:index>
<fr:encrypt/>
```

This will allow us to move away from the "Show search only" and "Show column only" options, which we don't want to have.

**Comment by obruchez** [comment]
- [ ] doc

**Comment by ebruchez** [comment]
[Doc](https://doc.orbeon.com/form-builder/form-editor/control-settings#basic-settings)
