### ISSUE TITLE
Improve US Address section template

### ISSUE THREAD

**Issue by obruchez** [orbeon/orbeon-forms#5997]
While implementing #5083, it appeared that the fields in the current US Address template cannot be all associated with autocomplete values.

- "Zip": `postal-code`
- "State": `address-level1`
- "City": `address-level2`
- "Apt/Suite": `address-line2` (?)
- "Street Number" and "Street Name" would need to be associated with `address-line1` (as a single field)

**Comment by ebruchez** [comment]
Done as part of #5495.
