### ISSUE TITLE
FB: Support colspan

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#600]
FB currently supports rowspan only.

**Comment by avernet** [comment]
[+1 from community](https://twitter.com/therampop/status/588770971890266112)

**Comment by avernet** [comment]
[+1 from customer](https://basecamp.com/1721271/projects/8966776/messages/44665606)

**Comment by ebruchez** [comment]
[+1 from evaluator](https://mail.google.com/mail/u/0/#inbox/14e7553141c64ab1)

**Comment by avernet** [comment]
[+1 from customer](https://basecamp.com/1721271/projects/4157621/messages/45163499)

**Comment by ebruchez** [comment]
- update server-side algorithms
- need expand/reduce icons
  - issue: enough space for icons?

**Comment by acspike** [comment]
There are a few different places where it might be helpful to have an popup icon panel (adding collapse operations, moving XCV operations closer to the cells for usability sake, and reordering grids). I should take a screen shot of the popup icon panels in MS Word as an example.

**Comment by ebruchez** [comment]
@acspike Agreed. Please send the screenshot!

**Comment by acspike** [comment]
The "mini toolbar" isn't available in Office for Mac, but there is a single button panel that displays afer a paste operation.

As it appears:
![screen shot 2015-07-23 at 5 39 10 am](https://cloud.githubusercontent.com/assets/114363/8848641/69389e18-30fe-11e5-9bf8-f8ff02b2308b.png)

On mouse over:
![screen shot 2015-07-23 at 5 40 59 am](https://cloud.githubusercontent.com/assets/114363/8848643/6d38f59e-30fe-11e5-8a40-883968f2cc08.png)

After activation:
![screen shot 2015-07-23 at 5 41 07 am](https://cloud.githubusercontent.com/assets/114363/8848646/70113d1c-30fe-11e5-966d-b03ad254ae83.png)

**Comment by avernet** [comment]
@acspike Yes, the "mini toolbar" is quite inline with what we had mind, showing on mouseover (like the current icons), so just one click is needed to select an option, minimal pointer movement is needed, and more "tools" can be made to fit there (e.g. cut/copy/paste). Thank you for sharing those screenshots.

**Comment by ebruchez** [comment]
What it takes:

- [ ] easy: in `fb-grid-cell-icons`, rename `fb-expand-trigger` to `fb-expand-down- trigger` and `fb-shrink-trigger` to `fb-shrink-up-trigger` (also rename `fbf:expandCell()` and `fbf:shrinkCell()`
- [ ] add 2 buttons to `fb-grid-cell-icons`: `fb-expand-right-trigger` and `fb-shrink-left-trigger` and associated functions
- [ ] implement algorithm for expanding right / shrinking left
- [ ] hard: implement new UI for cell buttons

**Comment by ebruchez** [comment]
Next step is to design the new UI for cell/control properties. Do we do something like the "mini-toolbar" above? Or do we want something showing up around the grid cell?

**Comment by ebruchez** [comment]
+1 from me today.

**Comment by ebruchez** [comment]
Unfortunately we have to push this one again too.

**Comment by ebruchez** [comment]
With recent changes for #3105, we have adjusted the PDF layout to support manual `colspan` in `fr:grid`.

**Comment by ebruchez** [comment]
[+1 from customer](https://mail.google.com/mail/u/0/#inbox/15add1be74ff8a4e)

**Comment by ebruchez** [comment]
Closing this as it is subsumed by #2738.
