### ISSUE TITLE
Mode "Allow bulk edit" inside "Show on Summary page"

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#6010]
Currently, when can control whether the search field and column for a control are displayed independently of a user's ability to perform a bulk edit for that control. This allows a form author to enable bulk edits for a control while hiding the values for that control, which is a bit unusual. If there are restrictions on which users can see the value for a given control, those restrictions will most likely need to be copied for the bulk edit. To resolve this, this RFE includes the three changes described in the following diagram.

![image](https://github.com/orbeon/orbeon-forms/assets/106961/a6aa35e8-6109-408c-b06a-ff529cb5e186)

**Comment by obruchez** [comment]
- [ ] doc (screenshots)
- [ ] backport
