### ISSUE TITLE
Summary page field search to show values in dropdown for controls without static items

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#6014]
On the summary page, for the field search, for selection controls, unless the itemset is static, we currently show an empty dropdown. Instead, this RFE calls for showing all possible values for the control, based on existing data the user has access to. We see this as a way to solve #3371 in cases where values and labels are the same (and still as an improvement over an empty dropdown in cases where values and labels are not the same).

The UI we have in the Form Builder Control Settings remains unchanged. The Summary page will determine, for selection controls, whether it can find the itemset in the form definition. If it cannot, it will tell the search API to also return all the possible values for that control. In turn, the search API will find those values using a SQL query similar to the one used to return the rows shown on the summary page, except it will do `DISTINCT` for the relevant control, and won't limit the number of rows returned to the page size. We might need to run such a query for each control for which we need to have all the distinct values.

[+1 from customer](https://3.basecamp.com/3600924/buckets/7993860/messages/6614251938)

**Comment by ebruchez** [comment]
For reference, we discussed that there could be two ways of selecting the list of items for a given form control.

There are two possibilities:

1. get the list of values independently from search criteria
2. get the list of values depending on search criteria

The second option is not always desirable, probably. But in some cases it could be. For example, filter first on a list of states, then filter on the list of zip codes for that state (or state and city). The benefit is that the list of possible items is more manageable and relevant in that case.

In any case, we'd want to select only items used for data that the user has access to. So we can't simply just get the same list of distinct values independently from the user.

**Comment by obruchez** [comment]
- [ ] fix test failing with Oracle, SQLserver, and DB2

**Comment by ebruchez** [comment]
[Doc](https://doc.orbeon.com/form-runner/features/summary-page#dynamic-dropdowns)
