### ISSUE TITLE
Option for landing, forms, and admin pages to link to summary page without form version

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#6017]
If we disable the version selector on the Form Runner summary page by setting `oxf.fr.summary.show-version-selector.*.*` to `false`, the page will show data across form versions. However, when we navigate to a summary page from the pages listed below, we have code that adds a `?form-version=` parameter, and when such a parameter is present, the summary page shows only data for the specific version, even if it doesn't show the version selector.

- The forms page (`/fr/forms`) or the admin page (`/fr/admin`), both implemented by `fr/home/home.xhtml`. For the relevant code in `home.xhtml`, search for `name="link"`.
- The landing page (`/fr/`), `landing.xhtml`, where we have code from the form/admin page that is duplicated (search for `form-version=`), first in the demo forms card, second in the published forms cards.

This RFE calls for having a configuration that can be set so that links in the forms, admin, and landing pages don't include the `form-version=` request parameter.

[+1 from customer](https://3.basecamp.com/3600924/buckets/29305475/messages/6636541290)

**Comment by avernet** [comment]
How would we configure this?

- Two properties:
    - `oxf.fr.landing.link-to-summary.include-form-version` and
    - oxf.fr.home.link-to-summary.include-form-version
- A single property: But what name to use? I don't think we have an existing property that applies to both the forms/admin and the landing pages.
- Have the value of `oxf.fr.summary.show-version-selector.*.*` affect the links on these 3 pages.

**Comment by ebruchez** [comment]
Issue: the Admin page lists published forms by version, and would still have to pass the version number in the URL.

**Comment by avernet** [comment]
Resolution: if `oxf.fr.summary.show-version-selector.*.*` is set to `false`, the forms and the landing page will not include the `form-version=`, but the admin page will, because it has one row per version.

**Comment by obruchez** [comment]
- [ ] doc

**Comment by obruchez** [comment]
Note: `/new` without `form-version=` will use the latest version of the form, so not including the parameter in that case is fine as well.

**Comment by ebruchez** [comment]
[Doc](https://doc.orbeon.com/form-runner/component/video)
