### ISSUE TITLE
Zip export: include workflow stage and other metadata if needed

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#6023]
Important add-on to #779 as implemented so far.

Right now, this is not done. But it is important to export at least the stage.

Currently, we set:

- `setCreationTime()`
- `setLastModifiedTime()`

Two options for storing extra information:

- using `setExtra()`
- using a metadata file, for example, alongside `data.xml`, add `metadata.xml`

**Comment by ebruchez** [comment]
- [ ] workflow stage
- [ ] check all metadata columns: group name, etc. ideally all must be included somehow

**Comment by obruchez** [comment]
Questions: should we do the same for form definitions and attachments as well? e.g. to export `last_modified_by` for form definitions?

**Comment by obruchez** [comment]
List of columns in the database:

- common columns
  - `created`
  - `last_modified_time`
  - `last_modified_by`
  - `app`
  - `form`
  - `form_version`
  - `deleted`
  - `xml` / `file_content`
- form data / data attachments:
  - `username`
  - `groupname`
  - `organization_id`
  - `document_id`
  - `draft`
- form data only
  - `stage`
- form definition
  - `form_metadata`
- attachments only
  - `file_name`

**Comment by obruchez** [comment]
@ebruchez: let me know if the following format/schema looks reasonable:

```
<?xml version="1.0" encoding="UTF-8"?>

<metadata>
    <created-by username="username-column" groupname="groupname-column"/>
    <last-modified-by username="last-modified-by-column"/>
    <workflow-stage>test-123</workflow-stage>
    <organization-levels>
        <organization-level>Test organization</organization-level>
    </organization-levels>
</metadata>

```

**Comment by ebruchez** [comment]
@obruchez that seems reasonable to me.
