### ISSUE TITLE
Email Settings support for custom email headers, value provided by a formula

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#6036]
Right now, in the Email Settings dialog, we have the ability to set the value of a predefined list of "roles" (e.g. Recipient) to the value of a control, as shown in the screenshot below.

![Screenshot 2023-10-30 at 8 50 36 PM](https://github.com/orbeon/orbeon-forms/assets/106961/f758e072-7650-43e3-8000-13281bf2b119)

This RFE is about adding support for custom email headers to that list. The list of possible headers is defined by admins through a property, `oxf.fb.email.custom-headers`, where the value is a space-separated list of custom headers, such as `X-SMTPAPI X-Priority`. These entries are added to the dropdown.

Also, after this RFE is implemented, form authors will be able to specify the value of any of these "roles" (except "Include attachment" and "Exclude from all fields"), as a static value (e.g., form author enters the sender's email address), and as a formula, as shown in the diagram below.

![image](https://github.com/orbeon/orbeon-forms/assets/106961/1a4a9b37-afc7-451a-9388-7834c554e679)

At the implementation level, `email-form.xpl` doesn't run the form, it just gets the form definition and form data. However, when this process runs, the form is running, so we have the ability to ask questions of the live form. And we already have `metadata:findAllControlsWithValues()` called from `email-form.xsl` that does this. So here we would use a similar mechanism to evaluate XPath expressions in the context of the form, so that we can support functions like `fr:workflow-stage()`.

We should also look into using a similar mechanism to evaluate template parameters, so that their formula is also evaluated in the context of the live form, and can use Form Runner functions, for example. But that is beyond the scope of this RFE.

**Comment by obruchez** [comment]
- [ ] fix test (migration from 2022 metadata)
- [ ] prevent edition of attachment controls if All/None
- [ ] support for orbeon/library
- [ ] backport to 2022
- [ ] backport to CE
- [ ] doc

**Comment by avernet** [comment]
When using the formula `fr:workflow-stage-value()`, when the email is being sent, I am getting the following error:

    XPath syntax error at char 25 in {fr:workflow-stage-value()}:
    Cannot find a matching 0-argument function named
    {http://orbeon.org/oxf/xml/form-runner}workflow-stage-value()

**Comment by obruchez** [comment]
It seems to work on master ("fr:workflow-stage-value()" in custom header "Formula" value). I will investigate.

**Comment by obruchez** [comment]
Indeed, it works in master, but not in the 2022 branch.

**Comment by obruchez** [comment]
Fixed by partial cherry pick from #6048 commit.
