### ISSUE TITLE
Automatic hint for max file size and supported file formats

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#6037]
This is a subset of #2833 specifically for attachment controls, to provide an optional automatic hint to users about file size or supported file format restrictions that the form author may have set.

[+1 from customer](https://3.basecamp.com/3600924/buckets/2016476/messages/3667264943)

**Comment by avernet** [comment]
Commits implementing this reference #2833.

**Comment by ebruchez** [comment]
[Doc](https://doc.orbeon.com/form-builder/form-editor/control-settings#automatic-hints)
