### ISSUE TITLE
Only send email from specific template when formula evaluates to true

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#6048]
This RFE calls for adding an optional "Consider this template when formula evaluates to true" to templates.

- Form Builder Email Settings dialog
    - Under the template name, add a checkbox with the label mentioned above (feel free to find a better label!).
    - If checked, a text field for entering the formulas will be enabled and the value will be validated as a formula.
    - Decide how to store this information in the form definition.
- email-form.xsl
    - If a formula is provided for a given template, evaluate it, and if false, exclude that template.

[+1 from customer](https://3.basecamp.com/3600924/buckets/4224335/documents/6433382249)

**Comment by obruchez** [comment]
- [ ] doc

**Comment by ebruchez** [comment]
@obruchez if this is done you can close it.
