### ISSUE TITLE
Summary page to support search by created, last modified, created by, last modified by, and workflow stage

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#6073]
- UI
    - Dates: as done by Google Drive
        - Dropdown with Any time (default), Today, Yesterday, Last 7 days, Last 30 days, Last 90 days, Custom…
        - When users choose "Custom…", two dates files show for "After date" and "Before date" (only one of the 2 value is required)
    - Users and workflow stage: dropdown with search
- Implementation
    - To populate the users and workflow stage dropdowns, we'll do an enhancements at the API level similar to the one done to have dropdowns based on index controls, except this won't do a distinct on `orbeon_i_control_text`, but directly on columns of `orbeon_i_current`

[+1 from customer](https://3.basecamp.com/3600924/buckets/7993860/card_tables/cards/6641745665)

**Comment by obruchez** [comment]
Note: next logical feature would be to be able to sort by those columns.

**Comment by obruchez** [comment]
- [ ] doc
- [ ] fix tests in customer branch (seems to fail with PostgreSQL)

**Comment by obruchez** [comment]
https://doc.orbeon.com/form-runner/api/persistence/search#metadata-queries
