### ISSUE TITLE
`.map` request removes credentials from session with ModHeader

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#6080]
-  enable header auth
- pass credentials headers
- make sure credentials are not "sticky"
- open Chrome dev tools
- load page
- error upon 1st Ajax request

This is because  the browser requests a `.map` file for the CSS (which neither the console nor the Network tab show!). Using the ModHeader extension, the credentials header is not passed in this case, causing the removal of the credentials as if the user had logged out.

**Comment by ebruchez** [comment]
When credential headers are not sticky, which is the default:

```xml
<property 
    as="xs:boolean"
    name="oxf.fr.authentication.header.sticky" 
    value="false"/>
```

we have code that removes credentials if they are missing.

However, we should probably not do this for requests to resources, especially for `.map`.

**Comment by avernet** [comment]
Yes, a "known" pitfall:
https://3.basecamp.com/3600924/buckets/1978393/messages/3141362366#__recording_3528420337
