### ISSUE TITLE
"Form Builder Forms" don't show on landing page out of the box

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#6097]
<img width="1272" alt="landing" src="https://github.com/orbeon/orbeon-forms/assets/105769/d4465111-ad6f-4803-bd63-c1fd4f946d9d">

**Comment by ebruchez** [comment]
If I create a form and I save it, it then appears in the list. Could it be that the sample forms are not imported as Form Builder data?

**Comment by ebruchez** [comment]
Also, no form data shows in the Summary pages out of the box. I suspect that this is because  the index tables are not populated, @obruchez.

**Comment by obruchez** [comment]
The `import-sample-data-into-sqlite.sc` script is indeed incomplete. I've included a complete SQLite database directly in the repository. It is now copied into the WAR instead of the file produced by the script.

**Comment by ebruchez** [comment]
I cherry-picked on 2023.1-pe, and unfortunately the Landing page doesn't load properly. I haven't yet looked into it.
<img width="965" alt="image" src="https://github.com/orbeon/orbeon-forms/assets/105769/ab8e2c0a-c6fc-40ca-9c3a-fd6e111b2c34">

**Comment by obruchez** [comment]
The `cp` command in `build.sbt` fails on Travis:

`cp: cannot create regular file 'orbeon-war/jvm/target/webapp/WEB-INF/orbeon-demo.sqlite': No such file or directory`

**Comment by obruchez** [comment]
Latest Travis builds in 2023.1-pe/2023.1-ce branches should be fine.

**Comment by ebruchez** [comment]
Works now, thanks @obruchez !
