### ISSUE TITLE
Generate proper SQLite demo database during build step

### ISSUE THREAD

**Issue by obruchez** [orbeon/orbeon-forms#6104]
Following #5063, an SQLite demo database was generated during the build, but was missing entries in the `orbeon_i_control_text` and `orbeon_i_current` tables.

Following #6097, the SQLite demo database is now simply copied from `data/orbeon-demo.sqlite` to `orbeon-war/jvm/target/webapp/WEB-INF/orbeon-demo.sqlite`, but `orbeon-demo.sqlite` has to be manually updated and committed, for example by:

- running `import-sample-data-into-sqlite.sc` without the `importData` phase
- running Orbeon Forms
- running `import-sample-data-into-demo.sc` using `crudEndPoint = "http://localhost:8080/orbeon/fr/service/persistence/crud/"` 
- copying `orbeon-war/jvm/target/webapp/WEB-INF/orbeon-demo.sqlite` (about 8-9 MB) to `data/orbeon-demo.sqlite`

**Comment by ebruchez** [comment]
Discussed:

- sbt task, for example `createDemoSqliteDb`
- can an sbt task depend on a build module that just got compiled?
- issue: Orbeon Forms properties are global; sbt passes `-D`s to the test runner, and its resource manager is initialized with that; the `createDemoSqliteDb` would need different properties, or some other way to configure the provider (we want the Sqlite provider used to store the demo forms)

**Comment by obruchez** [comment]
- [ ] check that the file is generated correctly on Travis

**Comment by obruchez** [comment]
Note: `Files.walk` doesn't return files in the same order depending on the filesystem/OS. On macOS, the returned files include form definitions before form data, by chance. This is not the case on Travis (i.e. Xenial). I guess the same problem would occur in the `import-sample-data-into-demo.sc` script if run on another platform.

**Comment by obruchez** [comment]
The generation of the SQLite file works on Travis, but we get the following warning/error in the logs:

```
     [exec] [error] WARNING: An illegal reflective access operation has occurred
     [exec] [error] WARNING: Illegal reflective access by scala.reflect.package$ (file:/home/travis/.sbt/boot/scala-2.12.18/lib/scala-library.jar) to method sun.net.www.protocol.jar.JarURLConnection$JarURLInputStream.close()
     [exec] [error] WARNING: Please consider reporting this to the maintainers of scala.reflect.package$
     [exec] [error] WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
     [exec] [error] WARNING: All illegal access operations will be denied in a future release
```

I don't seem to have this problem on my machine (macOS, with Java openjdk  11 or 17). Is this caused by the use of BellSoft Java 11.0.15.1 on Travis?

This seems to have something to do with `useAndClose` (which takes a `closable: T` with `T <: {def close(): Unit}`).

This might be linked to this bug as well (opened since 2018): https://github.com/scala/bug/issues/11368

**Comment by obruchez** [comment]
`--illegal-access=permit` is not supported anymore in Java 17.

**Comment by obruchez** [comment]
This is where the problematic call happens:

```
[error] WARNING: Illegal reflective access by scala.reflect.package$ (file:/Users/olivierbruchez/.sbt/boot/scala-2.12.18/lib/scala-library.jar) to method sun.net.www.protocol.jar.JarURLConnection$JarURLInputStream.close()
[error] 	at scala.reflect.package$.ensureAccessible(package.scala:65)
[error] 	at scala.runtime.ScalaRunTime$.ensureAccessible(ScalaRunTime.scala:162)
[error] 	at org.orbeon.io.IOUtils$.reflMethod$Method1(IOUtils.scala:66)
[error] 	at org.orbeon.io.IOUtils$.$anonfun$useAndClose$1(IOUtils.scala:66)
[error] 	at org.orbeon.io.IOUtils$.runQuietly(IOUtils.scala:71)
[error] 	at org.orbeon.io.IOUtils$.useAndClose(IOUtils.scala:66)
[error] 	at org.orbeon.xforms.XFormsCrossPlatformSupport$.readTinyTreeFromUrl(XFormsCrossPlatformSupport.scala:234)
[error] 	at org.orbeon.oxf.fr.FormRunnerResourcesOps.$anonfun$resourcesInstanceDocFromUrlOpt$3(FormRunnerResourcesOps.scala:68)
[error] 	at scala.Option.map(Option.scala:230)
[error] 	at org.orbeon.oxf.fr.FormRunnerResourcesOps.resourcesInstanceDocFromUrlOpt(FormRunnerResourcesOps.scala:68)
[error] 	at org.orbeon.oxf.fr.FormRunnerResourcesOps.$anonfun$findResourceHoldersWithLangUseDoc$1(FormRunnerResourcesOps.scala:45)
[error] 	at scala.Option.orElse(Option.scala:447)
[error] 	at org.orbeon.oxf.fr.FormRunnerResourcesOps.findResourceHoldersWithLangUseDoc(FormRunnerResourcesOps.scala:45)
[error] 	at org.orbeon.oxf.fr.FormRunnerResourcesOps.findResourceHoldersWithLangUseDoc$(FormRunnerResourcesOps.scala:43)
[error] 	at org.orbeon.oxf.fr.FormRunnerResourcesOps$.findResourceHoldersWithLangUseDoc(FormRunnerResourcesOps.scala:72)
[error] 	at org.orbeon.oxf.fr.FormRunnerControlOps.$anonfun$searchControlBindPathHoldersInDoc$6(FormRunnerControlOps.scala:352)
[error] 	at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:935)
[error] 	at scala.collection.immutable.List.foreach(List.scala:431)
[error] 	at scala.collection.TraversableLike$WithFilter.map(TraversableLike.scala:934)
[error] 	at org.orbeon.oxf.fr.FormRunnerControlOps.$anonfun$searchControlBindPathHoldersInDoc$4(FormRunnerControlOps.scala:351)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:366)
[error] 	at org.orbeon.oxf.fr.FormRunnerControlOps.$anonfun$searchControlBindPathHoldersInDoc$3(FormRunnerControlOps.scala:350)
[error] 	at scala.collection.immutable.List.flatMap(List.scala:366)
[error] 	at org.orbeon.oxf.fr.FormRunnerControlOps.$anonfun$searchControlBindPathHoldersInDoc$2(FormRunnerControlOps.scala:349)
[error] 	at scala.collection.TraversableLike$WithFilter.$anonfun$flatMap$2(TraversableLike.scala:966)
[error] 	at scala.collection.immutable.List.foreach(List.scala:431)
[error] 	at scala.collection.TraversableLike$WithFilter.flatMap(TraversableLike.scala:965)
[error] 	at org.orbeon.oxf.fr.FormRunnerControlOps.searchControlBindPathHoldersInDoc(FormRunnerControlOps.scala:347)
[error] 	at org.orbeon.oxf.fr.FormRunnerControlOps.searchControlBindPathHoldersInDoc$(FormRunnerControlOps.scala:340)
[error] 	at org.orbeon.oxf.fr.FormRunner$.searchControlBindPathHoldersInDoc(FormRunner.scala:4)
[error] 	at org.orbeon.oxf.fr.FormRunnerControlOps.searchControlsTopLevelOnly(FormRunnerControlOps.scala:294)
[error] 	at org.orbeon.oxf.fr.FormRunnerControlOps.searchControlsTopLevelOnly$(FormRunnerControlOps.scala:289)
```

**Comment by avernet** [comment]
> `--illegal-access=permit` is not supported anymore in Java 17. `--illegal-access=deny` will remove the warnings, but prevent the actual calls to `close()`, which is not very problematic for some code called once during the build.

@obruchez With Java 17 I am seeing the following error message. Are you saying that this parameter was needed if compiling with versions of Java < 17?

> [error] OpenJDK 64-Bit Server VM warning: Ignoring option --illegal-access=deny; support was removed in 17.0

**Comment by obruchez** [comment]
Some more context:

- "From Java 9, the `--illegal-access=permit` is the default mode"
- "In Java 16, the `--illegal-access=deny` becomes the default mode"
- "Since Java 17, the `--illegal-access` option is entirely removed"

In Travis, Java 11 is used, so, by default, the illegal access caused by `close()` is allowed, but some warnings are displayed in the build logs, which are displayed as errors, in red. This is why I introduced the `--illegal-access=deny` option, which should not be present in Java 17.

- [ ] check if possible to have different `javaOptions` for `demoSqliteDatabase` depending on the Java version
