### ISSUE TITLE
"_.isUndefined is not a function" when testing with Subject7

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#6126]
Our code in `xforms.js` identifies the `_` defined on line 2378 of [VM325.txt](https://github.com/orbeon/orbeon-forms/files/13834331/VM325.txt), which I suspect has been injected by Subject7. This injection seems to override the Underscore.js library.

One solution is to modify `underscore.min.js` so that `_` is defined not on the global object, but on `ORBEON`. Subsequently, we would update our code in `xforms.js` to use `ORBEON._` instead of just `_`. Alternatively, we could remove all instances of `_` from our code. However, this approach requires more extensive changes (46 instances in `xforms.js`) and is potentially riskier.

[+1 from customer](https://mail.google.com/mail/u/0/#inbox/FMfcgzGwJcXsSPGfktKDWbgmvmBnPgKn)

**Comment by ebruchez** [comment]
At some point we do want to remove that library entirely (#5436).

**Comment by avernet** [comment]
Changed the project version from 2022.1.6 to 2022.17, as the additional fix made by Erik on 2024-02-28 was implemented after version 2022.1.6 was released.

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/22184491/messages/7231981404)
