### ISSUE TITLE
Allow custom model variables references in formulas

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#6145]
In Control Settings in particular we check formulas that reference variables, and we prevent saving the formula if it is referencing a non-existing variable.

However, some users set custom variables, in particular in the model:

```xml
<xf:model id="fr-form-model" xxf:expose-xpath-types="true">
    <xf:var name="foo" value="xxx"/>
    <xf:var name="bar" value="xxx"/>
```

This RFE is about allowing user variables defined this way to be referenced by formulas without errors.

One issue is that of scoping: model variables are visible from MIP formulas. However, they are not visible to view formulas.

Later, we could even officialize this with a UI to set such global variables.

[+1 from customer](https://3.basecamp.com/3600924/buckets/3237397/messages/6921018845#__recording_6925043799)

**Comment by avernet** [comment]
[+1 from customer](https://groups.google.com/g/orbeon/c/4Gk_Uxt9Ckw)
