### ISSUE TITLE
Null context when adding `save` to Form Builder's `publish`

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#6148]
To reproduce, edit `properties-form-builder.xml`, locate the `oxf.fr.detail.process.publish.orbeon.builder` property, and add `save then` at the beginning of the process. Then, load Form Builder and hit Publish. This will result in a `NullPointerException` with the following message.

> Cannot invoke "org.orbeon.oxf.xforms.function.CommonFunctionSupport$Context.container()" because the return value of "org.orbeon.oxf.xforms.function.XFormsFunction$.context()" is null

Generally, this isn't necessary since we save on publish, but it used to work with 2022.1. This suggests there might be a problem that could occur in other cases.

[+1 from customer](https://3.basecamp.com/3600924/buckets/25378200/messages/5874387778)

**Comment by ebruchez** [comment]
What happens:

- `processCompletedAsynchronousSubmissions()`
- runs continuation of async
- `runProcess()`
- `tryShowDialog()`
- `evaluateValueTemplate()`
    - `XPath.functionContext.orNull`
    - which is `null`

In other words, `ProcessInterpreter` runs XPath expressions by passing as `functionContext` the in-scope `XPath.functionContext`, which would work if the process is called from XPath, but here it isn't.
