### ISSUE TITLE
`oxf.fb.tinymce.config` not used by the editors in dialogs

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#6160]
For instance, in the case of an Explanatory Text, it is displayed for the editor during inline text editing, but not when the editor is used in the Control Settings under the Explanatory Text tab. Additionally, it does not appear when editing a control label or hint in Control Settings, nor when modifying the body of an email in the Email Settings.

[+1 from customer](https://3.basecamp.com/3600924/buckets/16915667/messages/6965007323)

**Comment by ebruchez** [comment]
This is addressed with #6225.
