### ISSUE TITLE
JavaScript Embedding API: no error when trying to embed a non-existing form

### ISSUE THREAD

**Issue by obruchez** [orbeon/orbeon-forms#6195]
`embedForm` doesn't return any error when trying to load a non-existing form, either via `catch` or via `onRejected`.

The following will be displayed, though:

```
Orbeon Forms - Page Not Found
We are sorry, but the resource you have requested is not available on this server.
```

In that case, to embed another form, `destroyForm` will have to be called explicitly before the next `embedForm`.

**Comment by ebruchez** [comment]
Findings:

- for some reason, the code path is different with `orbeon-embeddable=true`
    - `/fr/orbeon/xxx/new` returns 404
    - `/fr/orbeon/xxx/new?orbeon-embeddable=true` returns 200
- if `config.cacheUseLocalCache == true` in `HttpSerializerBase`, then 200 is sent
    - the PFC correctly sets 404
    - then `HttpSerializerBase` sets a default 200
    - but then, while it should set again a 404, it doesn't, due to the broken caching mechanism kicking in

**Comment by ebruchez** [comment]
Possibilities:

- fix caching to take processing instruction into account
- disable caching if previously a non-success status code was set on the response

**Comment by obruchez** [comment]
I still see this problem on master. When embedding a non-existing form:

- We go through `PageFlowControllerProcessor.start`
  - `route.process` fails with `HttpStatusCodeException(404)``
  - `ServletExternalContext.setStatus` is called with 404
- Later, we go through `HttpSerializerBase.start`
  - In the `if (externalContext != null)` block, we call `response.setStatus(config.statusCode)` with  `config.statusCode` = 200, which overwrites the previous status code (404)

**Comment by ebruchez** [comment]
Fix is incomplete. It handles disabling the caching when the PFC already sets a non-success status code, but it doesn't handle properly the main case.

**Comment by obruchez** [comment]
I've also integrated the changes in 2022.1-pe. Feel free to revert if needed.
