### ISSUE TITLE
`AjaxEventQueue` can get blocked when a response arrives for a form that has been removed

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#6200]
To reproduce:

- Publish [this form](https://github.com/orbeon/orbeon-forms/files/14365285/form.txt), which includes a button named `sleep-button`. This button, upon being clicked, calls a service that sleeps for 2 seconds. The HTML below embeds the form, clicks the button, then after 1 second removes the form, and embeds it again.
- Then click on the button, and notice that no event is sent to the server.

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Embedding</title>
    <script
        type="text/javascript"
        src="http://localhost:8080/orbeon/xforms-server/baseline.js?updates=fr"></script>
    <script type="text/javascript">

        function embedForm() {
            return ORBEON.fr.API.embedForm(
                document.getElementById("my-container"),
                "http://localhost:8080/orbeon",
                "a",
                "a",
                "new"
            );
        }

        document.addEventListener("DOMContentLoaded", () => {
            embedForm().then((form) => {
                console.log("click on the sleep button");
                ORBEON.fr.API.findControlsByName("sleep-button")[0].querySelector("button").click();
                setTimeout(() => {
                    console.log("remove content of `my-container`");
                    document.getElementById("my-container").innerHTML = "";
                    setTimeout(() => {
                        console.log("embed form again");
                        embedForm();
                    }, 2000);
                }, 1000);
            });
        });
    </script>
</head>
<body>
    <div id="my-container"></div>
</body>
</html>
```

[+1 from customer](https://3.basecamp.com/3600924/buckets/1956846/messages/6497107553)

**Comment by ebruchez** [comment]
@avernet didn't you implement a fix for this? If so, can this be cherry-picked and closed?

**Comment by avernet** [comment]
@ebruchez Will do: I was waiting for a confirmation from the customer that this also solves their problem before cherry picking the commit on all branches. We've now received that confirmation, so I'll go ahead with the cherry picking.
