### ISSUE TITLE
Support serving files with the `xml` extension

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#6214]
We already support `json`, and serving a static XML file can be useful for testing (mocking a GET service) or even in production for populating a dropdown. In the latter case, we should note that the file will be publicly available, so this assumes that the list of possible labels and values doesn't need to remain private.

**Comment by avernet** [comment]
> My projects have *.xml pages that are generated from XPL pipelines. These pipelines no longer function as it appears that Orbeon is trying to deliver a static XML file from the app's filesystem.

Hi Ethan, good to hear from you. You’re saying that you have HTTP requests to Orbeon Forms with paths like `/path/to/something.xml`, which you map to pipelines in your page flow, but now Orbeon Forms is instead trying to serve the file `something.xml`, expecting to find it in the resources. Is that correct?

If so, you’ll need to remove the `xml|` that was added with [this change](https://github.com/orbeon/orbeon-forms/commit/810c84f2f114ec76a3f99404ec9e9dfa9c424973). Would that solve the problem for you?

**Comment by ewg118** [comment]
Yes, that is what I mean. Strangely enough, there was no page-flow.xml in `WEB-INF/resources` upon deployment of orbeon into Tomcat's webapps. I copied an older file I used in the previous installation of orbeon, which already had a similar line:

`<files path="(?!/([^/]+)/service/).+\.(gif|css|pdf|js|coffee|map|png|jpg|htc|ico|swf|html|htm|txt|svg|otf)"/>`

I added `|kml` to the files path attribute to see if it would break my KML XPL serializations by fetching a static KML file from the filesystem, but it had no effect.

Is this page-flow.xml supposed to be located in WEB-INF/resources? Is there some reason that page-flow.xml at this location would be ignored? I verified my page-flow.xml file is owned and readable by tomcat.

**Comment by avernet** [comment]
> Is this page-flow.xml supposed to be located in WEB-INF/resources? Is there some reason that page-flow.xml at this location would be ignored? I verified my page-flow.xml file is owned and readable by tomcat.

The `page-flow.xml` file is located inside `WEB-INF/lib/orbeon-core.jar` because it is rarely modified. Instead of using one from a previous version of Orbeon Forms, I recommend extracting it from that jar file, copying it to `WEB-INF/resources`, and then applying your changes to the copy.

For safety, I recommend repeating this process whenever you upgrade Orbeon Forms, in case there are changes to the default `page-flow.xml`.

**Comment by ewg118** [comment]
OK, so I extracted `page-flow.xml` from `WEB-INF/lib/orbeon-core.jar` and removed the xml extension from the path attribute. It's not having an effect on my pipelines that deliver XML. Is it possible the orbeon-core.jar is simply overriding the page-flow I've put into `WEB-INF/resources`? Should I insert my change back into the jar file?

**Comment by avernet** [comment]
The version in `WEB-INF/resources` takes precedence over the one in the JAR files. This is defined in your `web.xml`, where the `WebAppResourceManagerFactory` should have a priority number lower than that of `ClassLoaderResourceManagerFactory`.  

You might try adding a syntax error to your `page-flow.xml`, such as a `<` character where it doesn't belong, to check if the file is actually being read.

**Comment by ewg118** [comment]
I put a syntax error into my page-flow.xml, and it didn't result in an Orbeon error, so it appears that it is not being read.

Here are the first few params of my `web.xml`. Is this what I should expect:

```
<context-param>
        <param-name>oxf.resources.factory</param-name>
        <param-value>org.orbeon.oxf.resources.PriorityResourceManagerFactory</param-value>
    </context-param>
    <!--Web application resource manager for resources-->
    <context-param>
        <param-name>oxf.resources.priority.2</param-name>
        <param-value>org.orbeon.oxf.resources.WebAppResourceManagerFactory</param-value>
    </context-param>
    <context-param>
        <param-name>oxf.resources.priority.2.oxf.resources.webapp.rootdir</param-name>
        <param-value>/WEB-INF/resources</param-value>
    </context-param>
    <!--Classloader resource manager-->
    <context-param>
        <param-name>oxf.resources.priority.6</param-name>
        <param-value>org.orbeon.oxf.resources.ClassLoaderResourceManagerFactory</param-value>
    </context-param>
```

**Comment by avernet** [comment]
What you have in your `web.xml` looks correct, so I'm not sure why your `WEB-INF/resources/page-flow.xml` isn't being recognized. Are changes to other files you've customized under `WEB-INF/resources` being applied? You could also try updating the `page-flow.xml` in the `orbeon-core.jar` file, though that shouldn't be necessary.

**Comment by avernet** [comment]
Strange indeed. Have you also tried adding a syntax error to the `page-flow.xml` you put directly in your `orbeon-core.jar`, to check if that file is being read?
