### ISSUE TITLE
FormRunnerPersistence.getProviders returns "mysql" even when non-MySQL provider is configured

### ISSUE THREAD

**Issue by obruchez** [orbeon/orbeon-forms#6228]
For example in the context of tests, if `ProvidersTestedAutomatically = List(Provider.PostgreSQL)`:

`getProviders` is called with :
 - `appOpt     = Some("postgresql")`
 - `formOpt    = None`
 - `formOrData = Form`

So: `propertyName = "oxf.fr.persistence.provider.postgresql.*.form"`.

`propertiesMatch` is called with:
 - `name           = "oxf.fr.persistence.provider.postgresql.*.form"`
 - `matchWildcards = true`

It returns the following properties:
- `oxf.fr.persistence.provider.postgresql.*.*` (= `"postgresql"`)
- `oxf.fr.persistence.provider.*.*.*` (= `"mysql"`)

`oxf.fr.persistence.provider.postgresql.*.*` is defined in `src/test/resources/config/properties-local.xml `.

`oxf.fr.persistence.provider.*.*.*` is defined in `src/test/resources/ops/unit-tests/properties.xml`.

We expect `oxf.fr.persistence.provider.postgresql.*.*` to override `oxf.fr.persistence.provider.*.*.*`.

**Comment by ebruchez** [comment]
- [ ] create test for `getProviders()`
- [ ] fix bug

**Comment by ebruchez** [comment]
`propertiesStartsWith()`:

- returns all properties with the given prefix
- doesn't care about the precedence of returned properties: it just returns all found matches
- `matchWildcards` controls whether we allow returning properties that contain `*`
- but passing `*` in the search property will match any existing token, whether `matchWildcards` is `true` or `false`

**Comment by ebruchez** [comment]
The reasons we have `getProviders()`:

- find all providers that can store *data* for
    - reindex
    - reencrypt
- find all published *form* metadata for
    - all forms for all apps: probably ok
    - all forms for a given app: failing case as per above
    - a specific app/form: special case, will return a single provider

In the failing case, we need to exclude the "weaker" properties.

Now, there are questions! Say you have:

- `oxf.fr.persistence.provider.foo.*.*` = `p1`
- `oxf.fr.persistence.provider.foo.bar.*` = `p2`
- `oxf.fr.persistence.provider.foo.*.form` = `p3`

Now, we as for `foo`/`bar`/`form`. What property should match? Right now, just getting a property returns `p2`. We go from left to right. Presumably `getProviders()` should behave the same.

**Comment by ebruchez** [comment]
Fixed with 27ca4a50eb2e37b41aa965a699a739036d4bfe69.
