### ISSUE TITLE
`ORBEON.fr.API.wizard.focus()` to support the `lax` and `strict` modes

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#6240]
See the ``<!-- TODO: Support `lax` and `strict` modes. -->`` in `wizard.xbl`.

[+1 from customer](https://3.basecamp.com/3600924/buckets/36258888/messages/7091167121)

**Comment by ebruchez** [comment]
Simply enabling the focus logic on a control in a non-available section focuses on that control and section. So we cannot just use that naive approach. Instead, we must check whether the section is available.

**Comment by ebruchez** [comment]
- [ ] test
- [ ] doc

**Comment by ebruchez** [comment]
[Documented](https://doc.orbeon.com/form-runner/api/other-apis/form-runner-javascript-api#focusing-on-a-control)
