### ISSUE TITLE
Type with custom error message must not store `xs:string`

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#6252]
We currently store:

```
 <xf:type id="validation-1-validation">xs:string</xf:type>
```

Note the `xs:string` content.

We use a nested element so that we can have an `id`, thus allowing linking the validation with a specific alert.

However, when we use an attribute `type="..."`, we omit the attribute when it is an `xs:string`.

I thought that there was no difference when we assigned an `xs:string` type vs. no type, but there is a difference:  in case of atomization, an `xs:string` has that specific type, and will cause an error for example  with `sum()` if a numeric or date time is expected, while an untyped value will be cast.

In any case, for consistency, we should not assign an `xs:string` type.

- [x] don't write `xs:string`, instead use an empty element
- [ ] consider removing `xs:string` value when compiling form

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/26376073/messages/7251024885)
