### ISSUE TITLE
JavaScript error when going to "All Form Controls" review page

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#6256]
- go to https://demo.orbeon.com/demo/fr/orbeon/controls/new
- navigate to Review
- see JavaScript error

**Comment by ebruchez** [comment]
Error:

```
java.lang.IllegalArgumentException: For input string: ""
```

On this line:

https://github.com/orbeon/orbeon-forms/blob/97251cdb0ff4a813720a8c914490c2d466fe8d32/form-runner-web/src/main/scala/org/orbeon/xbl/Select1Search.scala#L214

**Comment by ebruchez** [comment]
Usually in static readonly mode, we don't need to run most of the component's JavaScript.

**Comment by avernet** [comment]
This occurs with the `databound-select1-search.xbl`. XBL components receive the `xforms-readonly` class but not the `xforms-static` class. It would be beneficial if they did, as it would simplify detecting when we are in the static-readonly case.
