### ISSUE TITLE
XBL components support for `aria-invalid` and `aria-required`

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#6279]
We automatically add `aria-labelledby`, `aria-describedby`, and `aria-errormessage` on the element the XBL points to with `xxbl:label-for`, but we don't have a similar mechanism for the XForms/XBL engine to add and maintain `aria-invalid` and `aria-required`.

[+1 from customer](https://3.basecamp.com/3600924/buckets/1956846/messages/7175826989)

**Comment by ebruchez** [comment]
One difference is that the other attributes are generated once and then remain unchanged.

In the case of `aria-invalid` and `aria-required`, we must add them and remove them dynamically as conditions change.

For this purpose, we must:

- output the attributes when producing markup
- send updates to the client when those change

**Comment by ebruchez** [comment]
Use case: `fr:date` when using the native date picker. This might also apply to the non-native case, as in both cases we use an `xh:input` with `xxf:control="true"` within the XBL component, and the distinction between native/non-native is done in JavaScript.
