### ISSUE TITLE
Ability to set column width in grids and repeats

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#628]
Form Builder currently doesn't support setting the width of a column in a grid or repeat, and this isn't something that can be done in a portable way with CSS.

The following can be used with IE9+ and other browsers to set the width of the first column in a repeat. In Form Builder, in the Grid Settings, assign a CSS class to the grid, e.g. `products`. Then, edit the source of the form, and add the following after the `<xh:title>…</xh:title>`:

``` xml
<xh:style>
    .products tr > :nth-child(2) { width: 80% }
</xh:style>
```

However, it has the following drawbacks:
- Doesn't work with IE8.
- Doesn't show in Form Builder.
- Relies on knowing that Form Runner adds one first column, which may change at some point in the future.

**Comment by avernet** [comment]
[+1 from interested party](https://mail.google.com/mail/u/0/#inbox/14d0b9c0518dd802)

**Comment by ebruchez** [comment]
Closing as WONTFIX as this is obsolete and we now have the 12-column layout.
