### ISSUE TITLE
Configuration banner shows for custom persistence provider

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#6300]
The reason is that we check all active providers, then make sure that there is a datasource configured for that provider.
However, an external provider, only identified by URI with `oxf.fr.persistence.my-provider.uri`, should not have its datasource checked.

So somehow we must exclude such external providers.

[+1 from customer](https://3.basecamp.com/3600924/buckets/1979712/messages/7017727617#__recording_7269834277)

**Comment by ebruchez** [comment]
We could consider that providers with an absolute URL are external and should not be datasource-checked.

Or we could consider that providers that match known internal URLs are internal and should be datasource-checked.

**Comment by avernet** [comment]
> We could consider that providers with an absolute URL are external and should not be datasource-checked.

@ebruchez Wouldn't this technique fail to exclude the `filesystem` provider, which doesn't have a data source?

**Comment by ebruchez** [comment]
We don't really have a `filesystem` provider: we have it only for attachments, the configuration property for that looks different:

```
oxf.fr.persistence.provider.*.&.*.attachments
```

**Comment by avernet** [comment]
Try adding the property. That provider will end up in `activeInternalProviders`, and then in `problematicDataSources` since it doesn't have a datasource.

    <property as="xs:string" name="oxf.fr.persistence.provider.*.*.*.attachments" value="filesystem"/>

**Comment by ebruchez** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/18358270/messages/7366631062#__recording_7423574002) for a related issue where the `filesystem` provider causes the banner to snow.

**Comment by ebruchez** [comment]
New fix, with more unit tests!
