### ISSUE TITLE
Number and currency don't support minimal labels

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#6304]
Similar to #3233, which is for the "with character counter" appearance.

[+1 from customer](https://3.basecamp.com/3600924/buckets/36258888/messages/7373591185)

**Comment by avernet** [comment]
Could this be supported by the XForms engine? If the XBL has `xxbl:mode="lhha"` and `xxbl:label-for="html-input"`, and the element with the id `html-input` is an `<xh:input>`, which is the case here, couldn't the XForms engine place and maintain the label in the `placeholder` attribute of that input?

**Comment by ebruchez** [comment]
This seems doable, but consider this:

- it's not best practice to not have a label at all outside of the field, but we already have this option for text fields/text areas
- the placeholder should contain either the label or the hint, as configured for text fields/text areas
