### ISSUE TITLE
"Dropdown with Other" truncates entries in Number field settings

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#6308]
<img width="556" alt="image" src="https://github.com/orbeon/orbeon-forms/assets/105769/7f81df2c-90cf-4307-b4cc-411559b9ebe9">

See also #6233.

**Comment by avernet** [comment]
Curiously, I am not getting the same results locally:

![Screenshot 2024-05-10 at 8 43 49 AM](https://github.com/orbeon/orbeon-forms/assets/106961/9e743960-9bb2-46b5-b903-9efaa6a559c4)
