### ISSUE TITLE
XForms servlet filter stopped working in 2023.1

### ISSUE THREAD

**Issue by obruchez** [orbeon/orbeon-forms#6325]
The XForms servlet filter stopped working in 2023.1.

**Comment by ykowalewski** [comment]
@obruchez see https://3.basecamp.com/3600924/buckets/7545500/messages/7079702132 
Is this the same issue? If yes, it was soleved in 2023.1.1

**Comment by obruchez** [comment]
- [ ] doc
- [ ] test with Jakarta (e.g. WilldFly)

**Comment by obruchez** [comment]
> @obruchez see https://3.basecamp.com/3600924/buckets/7545500/messages/7079702132 Is this the same issue? If yes, it was soleved in 2023.1.1

Thanks for mentioning this. This was yet another problem, unfortunately.

**Comment by ykowalewski** [comment]
Will be that fix added to ver 2023.1.3?
