### ISSUE TITLE
TOC section stays highlighted

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#6336]
1. Load http://localhost:8080/orbeon/fr/orbeon/controls/new?fr-wizard-page=utility-controls.
2. In the TOC, click on Typed Controls.
3. ⇒ Notice that both Utility Controls and Typed Controls are highlighted, while we'd expect only Typed Controls to be.

![Screenshot 2024-05-21 at 7 08 03 PM](https://github.com/orbeon/orbeon-forms/assets/106961/f09d0382-0f8a-4687-a106-e6e8c9b72b65)

**Comment by ebruchez** [comment]
Reproduced. This only happens if you start with an initial wizard page specified on the URL.

**Comment by ebruchez** [comment]
This doesn't happen on master.

**Comment by ebruchez** [comment]
However, I think that @avernet you reproduced that on master?

**Comment by ebruchez** [comment]
This happens on demo with 2023.1.2.

**Comment by avernet** [comment]
> However, I think that @avernet you reproduced that on master?

I reproduce this with the latest code we have on `2023.1-pe` (so to be clear, not on `master`).

**Comment by ebruchez** [comment]
The wizard debugger and the wizard instances appear the same in both cases.

**Comment by ebruchez** [comment]
Fixed on 2023.1.x and 2022.1.x branches. This didn't happen on master (for 2024.1.x) as the code had been moved to Scala and refactored, and in the process addressed this bug alreeady.
