### ISSUE TITLE
`fr:run-process-by-name()` isn't sync anymore

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#6342]
What brought our attention to this was that when publishing from Form Builder, we used to save then publish, but now saving happens in parallel to publishing. This is done in `builder/form/model.xml`. When we get the `fb-publish-form` event, first `fr:run-process-by-name('oxf.fr.detail.process', 'save')` runs, then `<xf:send submission="fb-publish-submission">`. These two operations run in parallel because `fr:run-process-by-name()` is now asynchronous.

Instead of running the `save` process directly, we considered running another process that runs `save` then dispatches an event back to the model. When we get that event, we would run `<xf:send submission="fb-publish-submission">`. The problem is that we need context. We could save it in an instance, as we don't expect multiple publish operations to run concurrently, but this adds complexity.

We would also need to do something similar in other places (and there may be more):

- When changing the app/form name ("Save as") and updating the URL before the document is saved.
- In the Excel and XML exports.
- When duplicating the form.
- When running `before-publish` before publishing.

I'd like to avoid adding complexity in multiple places, making the code more error-prone and harder to maintain:

-  I've thought of whether we could deprecate `fr:run-process-by-name()` and replace it with an XForms action. This action, similar to `<xf:send>`, would be asynchronous but behave synchronously. But what would that action be? We wouldn't want to use `<xxf:run-process-by-name>` because processes are at the Form Runner level.
- Instead, could this be achieved at the `<xf:action type="xpath">` level? For example, checking if the expression returns a future, and if so, running the subsequent actions only after the future is resolved. If we can do this, we'll avoid changing our XForms code, potential issues with customers using `fr:run-process-by-name()`, and this mechanism might be useful in the future when calling other async functions.

[+1 from customer](https://3.basecamp.com/3600924/buckets/1966555/messages/7435251119)

**Comment by ebruchez** [comment]
We discussed a few options:

- moving the XForms code to a simple process
    - however we are missing some facilities for example  to dispatch a `send()` with properties
- moving the XForms code to the action syntax
    - similar thing, and then we would need to make sure the embedded action syntax is processed in Form Builder, etc.
- moving the XForms code to Scala

The last option is the one we are following.  But for this to work, we need to change the implementation of `runProcess()`to return a `Future` or `IO`.

```scala
def runProcess(scope: String, process: String, initialTry: Try[Any] = Success(())): Either[Try[Any], IO[Any]]
```

This in turn means making changes to the `AsynchronousSubmissionManager`.
