### ISSUE TITLE
Selected radio button and checkboxes are not showing in high contrast

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#6350]
<img width="288" alt="Screenshot 2024-04-15 at 10 46 49 PM" src="https://github.com/orbeon/orbeon-forms/assets/106961/55d4ee69-f972-4102-9821-7a7cc1c301b3">

[+1 from customer](https://3.basecamp.com/3600924/buckets/1956846/messages/7175826989)

**Comment by ebruchez** [comment]
Solution: we include the fancy styling of the buttons only when prefers-contrast is either `no-preference` or `less`. The standard buttons styling will be used otherwise.

**Comment by ebruchez** [comment]
- [ ] cp on 2022.1-pe
