### ISSUE TITLE
Missing license statement in two files

### ISSUE THREAD

**Issue by willebra** [orbeon/orbeon-forms#6354]
The following files:

[src/main/java/org/orbeon/oxf/servicedirectory/ServiceDefinition.java](https://github.com/orbeon/orbeon-forms/blob/master/src/main/java/org/orbeon/oxf/servicedirectory/ServiceDirectory.java)
src/main/java/org/orbeon/oxf/util/JMSUtils.java (<-- seems to be from some older snapshot)

contain a copyright statement
`/*
 * Copyright 1998-2002, Orbeon, Inc.
 * All Rights Reserved
 *
 * This is unpublished proprietary source code of Orbeon, Inc. The
 * copyright notice above does not evidence any actual or intended
 * publication of such source code.
 */`

Is this outdated? If yes, could it be udated to LGPL-2.1-or-later license?

**Comment by ebruchez** [comment]
Indeed these are obsolete files. We have now removed ServiceDefinition.java as well. Hopefully that is enough?

**Comment by willebra** [comment]
Thanks for the info & change.
