### ISSUE TITLE
Horizontal scrollbar in toolbox when version dropdown displayed

### ISSUE THREAD

**Issue by obruchez** [orbeon/orbeon-forms#6358]
The toolbox becomes a bit too wide when the version dropdown is displayed:
<img width="216" alt="with" src="https://github.com/orbeon/orbeon-forms/assets/1003397/cf04f9e9-ba16-4cf4-a189-15c446230239">
Versus:
<img width="217" alt="without" src="https://github.com/orbeon/orbeon-forms/assets/1003397/4da8b50c-a381-4fcd-ac48-1a5f333f98fc">
On macOS, this will become more obvious if "Show scroll bars" is set to "Always".

**Comment by avernet** [comment]
This is also happening in 2022.1.7 and 2023.1.2. Cherry picked this change on the relevant branches.
