### ISSUE TITLE
Control label editor sometimes appears below the control

### ISSUE THREAD

**Issue by obruchez** [orbeon/orbeon-forms#6384]
https://github.com/orbeon/orbeon-forms/assets/1003397/4520f234-9d1d-45e0-ad3b-703931b13644

**Comment by obruchez** [comment]
This happens in master (2024.1), as well as in 2023.1.

**Comment by obruchez** [comment]
A more minimal example to reproduce the problem:

- insert a repeated grid
- add an "Image annotation" in the first row of the repeated grid
- adding a second control in the second row of the repeated grid

**Comment by avernet** [comment]
I am also reproducing this on 2022.1.
