### ISSUE TITLE
Automatic PDF to produce put produced CSS first, so it can be overridden

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#6402]
Use case: customer wanting to override `@top-left`, putting their own logo.

[+1 from customer](https://3.basecamp.com/3600924/buckets/7545500/messages/7547050268)

**Comment by ebruchez** [comment]
[Added an entry about this in the compatibility notes for 2024](https://doc.orbeon.com/release-notes/orbeon-forms-2024.1#pdf-header-footer-configuration)

**Comment by ebruchez** [comment]
[Also mention this in the PDF-specific CSS section](https://doc.orbeon.com/form-runner/styling/automatic-pdf#pdf-specific-css)
