### ISSUE TITLE
JavaScript error when Dynamic dropdown with search becomes non-relevant

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#6446]
In `Select1Search.scala`, `updateOpenSelection`, called from `init`, is invoked when the `data-is-open-selection` attribute is empty, instead of containing the expected boolean value.

The `init` function is called when the control becomes non-relevant, which is unexpected. This occurs when the client-side code executes `<xxf:blur control-id="section-1-section≡grid-1-grid≡country-control"/>`, which happens last, and in doing so, we attempt to initialize the companion object. See the [response](https://github.com/user-attachments/files/16646482/response.txt).

I believe the server shouldn't be sending such an event to a control after informing the client that the control is no longer relevant. This needs to be discussed.

To reproduce, publish [this form](https://github.com/user-attachments/files/16646480/form.txt) and select the first country from the dropdown.

[+1 from customer](https://3.basecamp.com/3600924/buckets/36258888/messages/7704225640#__recording_7720577934)

**Comment by ebruchez** [comment]
Control was just marked non-relevant, but we get:

- check why we get `<xxf:init>` in response
- check why we get `<xxf:blur` in response

**Comment by ebruchez** [comment]
`<xxf:init relevant="false">` is dispatched when the control becomes non-relevant, and this will call `destroy()` on the component. So in spite of the confusing element name, this is correct.
