### ISSUE TITLE
ORBEON.fr.FormRunnerOffline is undefined - FormRunner Javascript API

### ISSUE THREAD

**Issue by Dajcok** [orbeon/orbeon-forms#6448]
Hello,

I'm trying to display forms at my own frontend and the best API to use in my case is the Javascript FormRunner API, especially the FormRunnerOffline API. I was following the docs [here](https://doc.orbeon.com/form-runner/link-embed/offline-embedding-api) but it doesn't mention how to properly import the FormRunnerOffline API. In the docs it looks like it's accessible from the global orbeon object which is bind to window when importing using: `<script type="text/javascript" src="/orbeon/xforms-server/baseline.js?updates=fr"></script>` as described [here](https://doc.orbeon.com/form-runner/link-embed/javascript-api). 

The problem is that there is no FormRunnerOffline property accessible from `ORBEON.fr` context (see image).
![image](https://github.com/user-attachments/assets/daa0c4eb-0ce6-4468-94b8-c3ecf758481c)

I was wondering that maybe the `update` query in the URL needs to be set to specific value so it's loaded but I couldn't find anything on this topic anywhere. As the documentation is not clear enough can you please clarify how am I supposed to load the FormRunnerOffline API ?

**Comment by ebruchez** [comment]
Hi, for questions, we recommend using [Google Groups](https://groups.google.com/g/orbeon). This said, the following will load the offline API:

```html
<script src="/xforms-server/baseline.js?updates=offline" defer="defer"/>
```

Same for the CSS:

```html
<link rel="stylesheet" href="/xforms-server/baseline.css?updates=offline"/>
```

I hope this helps.

**Comment by Dajcok** [comment]
Hi, thanks for response. I will definitely post these kind of questions to the Google group in the future. 

To be honest the URL `orbeon/xforms-server/baseline.js?updates=offline` doesn't work as expected and I still can't access the FormRunnerOffline API. When I try to load it like this it doesn't even include the `fr` object. 

It's very important for me to load the FormRunnerOffline api. Can you please check it if it works for you ?

**Comment by ebruchez** [comment]
Are you using the PE or CE version? The offline API is not available on the CE version.
