### ISSUE TITLE
Chained service calls possibly causing connection pool starvation

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#6466]
Let's say an external request A opens a database connection, calls a service, and closes the connection. The service, run by the internal request B, opens a connection, does something, and closes the connection.

Assume the pool allows for 2 connections (`maxActive="2"`), and 2 A requests (A1 and A2) are started simultaneously. Both A1 and A2 manage to obtain a connection before calling the service. As a result, both B1 and B2 will be blocked waiting for a connection from the pool, resulting in a deadlock. This deadlock can only be resolved at the cost of one or more A requests failing (e.g., due to a timeout).

We can prevent this from happening by either:

- Ensuring we close all connections before calling services. We have already made changes to that effect in the past, but this is difficult to guarantee. The challenge lies in identifying all possible cases.
- Setting `maxActive` on the connection pool to be at least a factor of the `maxThreads` on the `Connector`. The factor is the maximum depth of service calls, e.g., 2 with the above example (A → B), 3 if we have A → B → C, and so on.

Q: Are we saving attachments in parallel? If so, the factor would depend on the number of files, thus not statically bounded. Could we then limit the number of attachments processed in parallel to achieve a bounded factor?

[+1 from customer](https://3.basecamp.com/3600924/buckets/5085006/messages/7597657107)

**Comment by avernet** [comment]
Based on https://github.com/orbeon/orbeon-forms-pe/blob/2022.1.5-pe-elca/form-runner/shared/src/main/scala/org/orbeon/oxf/fr/FormRunnerPersistence.scala, in `trySaveAllAttachments` we use `TryUtils.sequenceLazy`, which processes the `attachmentsWithHolder` sequence, suggesting that it's performing a sequential, lazy evaluation of the attachments, rather than processing them in parallel.

**Comment by ebruchez** [comment]
My understanding is that, as of 2023.1, saving attachments and data entirely remains sequential, even through we use FS2. Concurrency is explicit with FS2, not implicit by default.

**Comment by ebruchez** [comment]
Also, as discussed, we should have very few, if at all, remaining cases where we might get a connection, call another connection-requiring service, and then release the original connection. The Form Runner persistency proxy performs service calls which should all just use a single database connection (in the case of the relational provider).

**Comment by ebruchez** [comment]
We have identified, with 2022.1, a case like this:

- `Read` gets a connection with `RelationalUtils.withConnection()`
- within this, calls `RelationalUtils.readFormPermissions()`
    - this calls an internal service
    - this calls `getConnection()`

With a connection pool of, say, 10 connections, this is less likely to happen, but it can still happen if there are 10 callers.

**Comment by ebruchez** [comment]
The specific case above cannot happen with 2023.1, where we don't nest connections this way.
