### ISSUE TITLE
Form Builder unresponsive after "Undeclared variable in XPath expression"

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#6517]
- Import [form.txt](https://github.com/user-attachments/files/17106792/form.txt).
- Open the Control Settings for the 3rd control, Databound with search.
- Set Open selection to Formula, type `$is-open`.
- Apply ⇒ "Undeclared variable in XPath expression: $is-open".

**Comment by ebruchez** [comment]
In `annotate-design-time.xsl`, we handle specifically `fr:section/(@open | @readonly | @page-size)`, for example, in addition to MIPs. The attributes are moved to the `fb:` namespace. We should do something similar here. In addition, the control editor should use the `fb:` namespace when reading/updating attributes.

**Comment by ebruchez** [comment]
We can also check within the component itself whether we are at design-time when calling `fr:component-param-value('selection')`. Could we also make a static determination? That is, if literally `true`, when we are open, but if an AVT, then "maybe" or "closed"?
