### ISSUE TITLE
Documentation signature error

### ISSUE THREAD

**Issue by lwassermann** [orbeon/orbeon-forms#6539]
In the `fr:run-process()`-documentation[1], the signature is the `run-process-by-name` action. The actual function seems to accept an eval-string as a second argument, I assume (from the example).

[1] https://doc.orbeon.com/xforms/xpath/extension-functions/extension-form-runner#fr-run-process

**Comment by avernet** [comment]
@lwassermann, fixed! And thanks for letting us know about this.
