### ISSUE TITLE
Save operation completes before all files are uploaded in Multiple File Attachments control

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#6548]
To reproduce:

- In Form Builder, create a form with a Multiple File Attachments control and publish it.
- Open `/new`, attach several files, and click Save while the files are still uploading (network throttling helps).
- Once the upload is complete, reload the page.

Result:

- Observed: only some of the uploaded files have been saved.
- Expected: the save operation should wait for all files to finish uploading before saving the data.

[+1 from customer](https://3.basecamp.com/3600924/buckets/5085006/messages/7862188533)

**Comment by ebruchez** [comment]
Right now, the XFCD keeps a `pendingUploads` set . This is:

- added to when getting `xxforms-upload-start`
-removed from when
    - getting `xxforms-upload-cancel|done|error` 
    - the control is destroyed
- checked with the `pending-uploads` action

Now, in the case of a multiple file upload, each upload is sent separately on the client. We have a `processFileList()` function  
based on `Future` which sends each file at at time using `addFile()`.

So it is possible that the `save-final()` process, which uses the `pending-uploads`, catches `pendingUploads` just at a time between two uploads of a multiple-upload sequence. Ideally, this shouldn't happen, and `save-final()` should not be allowed to proceed.

Note that this could also happen in even with separate upload controls. So the client should somehow be able to tell the server whether there are pending uploads on the client.

**Comment by ebruchez** [comment]
The client keeps a pending uploads queue in `UploaderClient`. Sequence of events:

- upload(s) triggered
- client sends `xxforms-upload-start`
- client initiates background file upload
- when done
    - server
        - responds with "server events" containing `xxforms-upload-done` or `xxforms-upload-error`
    - client
        - sends back to server `xxforms-upload-done` or `xxforms-upload-error` (within "server events")
        - if there was an error in the background file upload, client sends `xxforms-upload-error` explicitly
        - in case of successful upload, client continues with remaining events in pending uploads queue

One difficulty is to make sure the client and the server are synchronized. You don't want, for example, the client to tell the server that 3 uploads are expected, 1 upload completes, the client somehow is interrupted, and the server forever expects 2 more uploads, while the client no longer knows about it.

Adding files to the queue, even though it is based on `Future`, allows, at least in "online" mode, to fill the pending uploads queue as uploads are added. So at the end of an upload, we know if there are pending uploads on the client. Could we, at the same time we send `xxforms-upload-done` or `xxforms-upload-error` to the server, send a new `xxforms-upload-start` just before that?

Q: What happens with `xxforms-upload-start`/`xxforms-upload-done` in the case of multiple file uploads? Are they dispatched to the same XForms control, or different ones?

**Comment by ebruchez** [comment]
So, `attachment.xbl` has a single `xf:upload`, which uploads to the local instance. Upon `xxforms-upload-done`, it copies over the the data as appropriate.

So, in the case of a multiple attachments control, it doesn't quite make sense from a sequence point of view to dispatch `xxforms-upload-start` before `xxforms-upload-done` or `xxforms-upload-error `, does it? We'd like the `start`/`done|error` to be paired. In addition, the id will be added to the list of pending uploads, and the subsequent `done|error` will remove it. So It think that option will not work.

**Comment by ebruchez** [comment]
One option I considered was that `xxforms-upload-done` could contain a flag saying "another upload will come soon for this control". But this is not easy:

- the client would know about this
- but the servers sends an encrypted `xxforms-upload-done`, so the client cannot amend it

But the following might work:

- add a new `xxforms-upload-queued` event when something is added to the client queue
- the server `pendingUploads` would keep a count of queued uploads, not just a flag
- `xxforms-upload-start` would no longer update `pendingUploads`
- `xxforms-upload-done|error` would decrement `pendingUploads`

**Comment by ebruchez** [comment]
Looking at why the issue could occur in the first place before we implement changes, I indeed easily reproduced the problem. Observing the logs, I see that the client, between the two uploads, sends:

```xml
<xxf:event-request xmlns:xxf="http://orbeon.org/oxf/xml/xforms">
        <xxf:uuid>f286144590eed8d35bf2d76384d5196e77d2b91e</xxf:uuid>
        <xxf:sequence>7</xxf:sequence>
        <xxf:action>
            <xxf:event name="xxforms-upload-progress" source-control-id="section-1-section≡grid-1-grid≡control-2-control≡xf-upload"></xxf:event>
            <xxf:event name="xxforms-upload-start" source-control-id="section-1-section≡grid-1-grid≡control-2-control≡xf-upload"></xxf:event>
            <xxf:event name="xxforms-server-events">
                <xxf:property name="value">...</xxf:property>
            </xxf:event>
        </xxf:action>
</xxf:event-request>
```

So the `start` comes before the server events, which contain the `done`. And the server processes them in that order.

This explains that, but it is puzzling, because  the client does:

- `AjaxServer.handleResponseDom()`, which dispatches the server events
- `continueWithRemainingEvents()`, which dispatches the `start`

**Comment by ebruchez** [comment]
The reason for this is that we use `setTimeout()` to fire the server events. So they are queued after `start`.

**Comment by ebruchez** [comment]
I haven't pushed the new `xxforms-upload-queued` event, only the fix for the order of `start` and `done` events. The `queue` event could make this a little more reliable, preventing unlikely cases where the server could think that there are no more uploads. The `queue` could be used on the server to show to the user the number of pending uploads, which could be interesting.
