### ISSUE TITLE
`xxf:get-session-attribute()` to support returning a Java object

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#6564]
This could be useful, for instance, to retrieve a bearer token stored by Keycloak in the session.

    ksc:getTokenString(xxf:get-session-attribute('org.keycloak.KeycloakSecurityContext'))

**Comment by ebruchez** [comment]
- [ ] test method call similar to above

**Comment by ebruchez** [comment]
Tested with:

```scala
case class MyTest(value: String)

req.setAttribute("my-attribute", MyTest("my-value"))
```

```xpath
my-test:value(xxf:get-request-attribute('my-attribute'))
```

**Comment by ebruchez** [comment]
Add test.
