### ISSUE TITLE
Remote Server Credentials dialog on Forms Admin: fix Cancel button behavior 

### ISSUE THREAD

**Issue by obruchez** [orbeon/orbeon-forms#6567]
If two remote servers are defined in the properties (say "Test 1" and "Test 2"):

- When going to the Forms Admin page for the first time: the credentials dialog is displayed. If "Cancel" is clicked, an empty list of forms will be displayed, with "Test 1" being selected as the active remote server. This is confusing.
- When switching from "Test 1" (after credentials have been successfully entered) to "Test 2": if "Cancel" is clicked, the current list of forms is displayed (i.e. not updated) and "Test 2" is selected as the active remote server.

In the second case, the "Test 1" remote server should be displayed as being active, not "Test 2".

**Comment by obruchez** [comment]
What's the expected behavior in the first case? Should we even be allowed to click "Cancel"?

**Comment by ebruchez** [comment]
In the first case, the list of local forms be displayed. This was the case before.  That is, if we fail to authenticate with a remote server, we still want to show the local forms.
