### ISSUE TITLE
Information density setting in Form Settings

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#6581]
We could just have 3 levels, names tbd Roomy, Comfortable, Compact.

**Comment by ebruchez** [comment]
- UI in Form Builder in Form Settings (View Options)
- should probably also apply to PDF
- at runtime (and design-time?) setting should put a CSS class somewhere
- new CSS needed to adjust the margins (no padding!)

**Comment by obruchez** [comment]
- [ ] Form Options: 2 appearance settings -> Appearance tab
- [ ] Wizard Options -> Wizard
- [ ] PDF Options -> PDF
- [ ] View Options -> Appearance
- [ ] Simple Data Migration + Grid Tab Order -> 2nd row
- [ ] Use automatic hints -> with 3 attachments settings (+ uppercase)
- [ ] check French translations
- [ ] adapt dialog width
- [ ] PDF
- [ ] design time
- [ ] sizes: 4px/4px (= default/compact) + 0.5em/1em (comfortable) + 1em/2em (roomy)
- [ ] CSS class density-* -> fr-density-*

**Comment by obruchez** [comment]
- [ ] try and reduce/suppress padding in Form Builder (if possible)
- [ ] doc

**Comment by obruchez** [comment]
Layout on repeated-grids demo form is completely broken.

- [ ] check why
