### ISSUE TITLE
Property to disable the keyboard shortcuts hints

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#6605]
- This would only disable the hints shown in Form Builder and Form Runner, not the shortcuts themselves.
- We could also consider a form setting for this, though it isn’t necessary.

[+1 from customer](https://3.basecamp.com/3600924/buckets/36258888/messages/7483582797)

**Comment by ebruchez** [comment]
This property could place a CSS class on the top-level, as we do for other configurations, and then CSS would take care of hiding the hints.

**Comment by avernet** [comment]
- [x] [Doc](https://doc.orbeon.com/form-builder/form-editor/keyboard-shortcuts#discoverability)
