### ISSUE TITLE
Max aggregate file size not enforced when uploading multiple files

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#6606]
To reproduce:

- Create a 5MB file using the command `dd if=/dev/zero of=5mb-1.bin bs=1M count=5`.
- Copy it to create `5mb-2.bin`.
- Add the property `<property as="xs:string" name="oxf.fr.detail.attachment.max-size-aggregate-per-form.*.*" value="6000000"/>`.
- Create and publish a form with a Multiple File Attachments control.
- Upload `5mb-1.bin`, followed by `5mb-2.bin`. The second upload will not go through, and a dialog will display the reason for the failure.
- Remove `5mb-1.bin` and upload both files simultaneously. Both files will be attached without any errors.

[+1 from customer](https://3.basecamp.com/3600924/buckets/2192969/messages/7978876986)

**Comment by ebruchez** [comment]
Confirming the problem. In `UploadCheckerLogic`, we call `currentUploadSizeAggregateForForm`, which:

- when the two files are attached together, returns `6000000` for max allowed size
- but when the are attached one after the other, returns `6000000` first, and then `757120`
 
This means simply that `currentUploadSizeAggregateForForm` is not up to date when we upload files together.

This makes sense, as the flow in the failing case is:

- upload comes in, checks limits
- when done, respond with `xxforms-upload-done`, check the upload queue, and starts second upload
- `xxforms-upload-done` is sent back to server, which updates the form

It seems that the second upload reaches the server before the previous `xxforms-upload-done` has done its job.

**Comment by ebruchez** [comment]
Possible solutions:

- force the sequencing, meaning that the response from `xxforms-upload-done` would trigger the continuation of the upload queue
    - benefit: implements the logical sequencing one might expect
    - drawback: probably harder to implement and requiring more changes
- check limits upon receiving `xxforms-upload-done` as well
    - drawback: attaching a large number of files could lead to delay before the uploads are rejected
    - benefit: easier to implement

**Comment by ebruchez** [comment]
- [ ] fix issue where I am not getting an explicit message if I upload a single file that goes over the limit

**Comment by ebruchez** [comment]
The last problem occurs because the two uploads happen very quickly, and each does:

- `setUploadProgress()`

using the same session key, because the two uploads pertain to the same form control.

When the first error occurs, `removeUploadProgress()` is called, and so the second error event no longer finds the details in the session.

**Comment by ebruchez** [comment]
Seems that the merge on 2022.1-pe is not exactly obvious.

**Comment by ebruchez** [comment]
Managed to cherry-pick on 2022.1-pe and it seems to work. One difference is that, contrary to the doc, the `oxf.fr.detail.attachment.max-size-aggregate-per-form` was not supported in 2022.1, even though the general feature was introduced with 2017.1. But it works if you set the limit in the Form Builder UI.
