### ISSUE TITLE
Form shown after pasting source, but after saving and reloading, form shows empty in Form Builder

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#6607]
Use the form linked from this [message](https://3.basecamp.com/3600924/buckets/1966555/messages/7983823896).

**Comment by ebruchez** [comment]
Error in logs in `theme-plain.xsl`:

```
Cannot output a namespace node for the default namespace when the element is in no namespace
```

**Comment by ebruchez** [comment]
Issue was due to elements named `<property>` in the source:

```xml
<xh:body>
    <property as="xs:integer" name="oxf.fr.summary.page-size.*.*" value="10"/>
```

and:

```xml
        </fr:view>
        <property as="xs:integer" name="oxf.xforms.xbl.fr.error-summary.page-size" value="10"/>
    </xh:body>
</xh:html>
```

These elements are not allowed.

**Comment by ebruchez** [comment]
So closing, I don't think we need to take particular action here, except that we should validate form definitions in general.
