### ISSUE TITLE
Screen readers announce Font Awesome's Unicode characters

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#6624]
Font Awesome works by using CSS to insert special characters (like `\f056`) that get displayed as icons through a custom font file. While this works visually, screen readers try to read these special characters out loud, creating confusion. Adding `aria-hidden="true"` tells screen readers to ignore these decorative characters.

[+1 from customer](https://3.basecamp.com/3600924/buckets/2192969/messages/7997907419)

**Comment by avernet** [comment]
Resolution: programmatically add the `aria-hidden="true"` (if not already present) in the handlers, for the label updates, etc.

**Comment by ebruchez** [comment]
There are a few places where we output HTML:

- handlers
    - when producing the original page
    - when doing "full updates" via XHR
- updates to LHHA and output fields with `mediatype="text/html"

We could hook-up a transformation in those cases, see:

- `XHTMLElementHandler`
- `streamHTMLFragment()`

**Comment by ebruchez** [comment]
Example of issue with the new `aria-hidden="true"`:

<img width="624" alt="image" src="https://github.com/user-attachments/assets/aeaabc1d-3830-452b-b2c9-e686686d8f58">

**Comment by ebruchez** [comment]
The status icons are not read by VoiceOver.
