### ISSUE TITLE
No success or error message when encountering issue saving with custom provider

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#6639]
To reproduce:

- `gh gist clone 3c72973b745b73ecb30af487bc82cdea 6639`
- `cd 6639`
- `docker compose up -d`
- http://localhost:8080/orbeon/fr/orbeon/bookshelf/new
- Enter a title and an author, hit Save
- ⇒ No success or error message shows

[+1 from customer](https://3.basecamp.com/3600924/buckets/2016476/messages/8049045978)

**Comment by ebruchez** [comment]
I reproduce this. I see that the persistence proxy returns the error correctly, and that the `ProcessInterpreter` obtains the error as well. The issue appears to be in running the process continuation.

**Comment by ebruchez** [comment]
Interestingly, we process this:

```
(nop then new-to-edit then success-message("save-success") recover error-message("database-error"))
```

This decomposes into a `(expr, rest)`, where `rest` is `Nil`. This later causes the code not to execute `rest`.

But removing parentheses:

```
nop then new-to-edit then success-message("save-success") recover error-message("database-error")
```

returns a different `(expr, rest)` tuple, with `rest` being non-empty.

**Comment by ebruchez** [comment]
- [ ] fix
- [ ] test

**Comment by ebruchez** [comment]
Assuming `continue-with-failure` is an action that fails:

    continue-with-failure then (a then b recover c)

produces a result different from:

    continue-with-failure then a then b recover c

This is by design. Parentheses create groups or blocks.
