### ISSUE TITLE
XPath functions to access FR mode and roles

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#664]
Right now, we use `$fr-roles` and `$fr-mode`. This is not ideal as the variables need to be properly scoped to work.

We should consider using functions instead, for example:
- `fr:user-roles()`
- `fr:mode()`

**Comment by avernet** [comment]
Those functions have been implemented and [documented](https://doc.orbeon.com/xforms/xpath/extension-form-runner.html) for a little while now. Closing.
