### ISSUE TITLE
Using a variable in Custom CSS classes AVT crashes Form Builder

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#6648]
Create a new form, add a text field, and name it `a`. Under "Custom CSS classes," write `{$a}`, then click Apply. As a result, Form Builder becomes unresponsive, and the log shows an exception: "Undeclared variable in XPath expression: $a".

There are two problems here. First, and more critically, Form Builder should not crash even when referencing an invalid variable. Second, valid variables should function correctly.

**Comment by avernet** [comment]
For 2023.1.6, we at least went to fix the crash.

- [ ] If we don't also implement the support for variables, check if they work in 2024.1, and if they don't create a new issue.

**Comment by ebruchez** [comment]
XSLT attempts to interpret the AVT, causing the error.

**Comment by avernet** [comment]
Removing all classes just because some use an AVT referring to a control value feels a bit like throwing the baby out with the bathwater. Could we maybe just annotate the classes that contain AVTs for better backward compatibility?
