### ISSUE TITLE
Better `Accept` headers in requests by the proxy to implementations of the persistence API

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#6651]
To reproduce, I’m running `mitmproxy -p 8081 --mode reverse:http://localhost:8080`. I also set the property `<property as="xs:anyURI" name="oxf.fr.persistence.mysql.uri" value="http://host.docker.internal:8081/orbeon/fr/service/mysql"/>` so that requests to the implementation of the persistence API for MySQL go through the proxy. 

Once this is in place, create a form in Form Builder, add an Image Attachment control, publish the form, open the new page, attach an image, save, reload the page, and check the headers on the request for the image sent to the implementation of the persistence API (see below for what I am observing, which differs from the `Accept` header sent by the browser). It seems like it would make more sense to either omit the `Accept` header or use one with the value `*/*`.

![Headers sent by the proxy](https://github.com/user-attachments/assets/c0c2e4f5-800e-400d-9376-3cd047a096b0)

This issue is specific to requests made for the Image Attachment control, but we might also want to see what we are doing for other requests made by the proxy to the implementation of the persistence API.

This issue arose while investigating a problem [reported by a customer](https://3.basecamp.com/3600924/buckets/1977270/messages/8056026858), but it is distinct from their specific problem.

**Comment by ebruchez** [comment]
- call to `SubmissionUtils.clientHeadersToForward()`
    - takes the headers that we used to load the page
    - and forwards `"user-agent", "accept"`

This is why we are getting this `Accept` header. It doesn't make sense, though!

In short, I don't think that we should "forward" (kind of) that `Accept` header. It serves no purpose, on the contrary. The persistence layer doesn't implement content-negotiation anyway: it is supposed to just return the resource requested.

**Comment by ebruchez** [comment]
The `User-Agent` is ok to be forwarded, maybe? We also forward these in `EchoSubmission.connect()` (doesn't matter much here) and `RegularSubmission.connect()`.
