### ISSUE TITLE
Source code for "org.orbeon" %%% "xerces" % "2.11.0.11-SNAPSHOT" is not committed

### ISSUE THREAD

**Issue by Saadati** [orbeon/orbeon-forms#6663]
Hello everyone and thank you for your attention.
When compiling with Scala 13, I unfortunately encountered the lack of published code for other dependencies.

**Comment by ebruchez** [comment]
The code of Xerces you are referring to is in https://github.com/orbeon/xerces-xml. This is a port of Xerces to Scala for runnin Orbeon Forms in the JavaScript environment. It's marked as SNAPSHOT for lack of a better release, but indeed it has been pretty stable so we could move to a final version number.

**Comment by Saadati** [comment]
> The code of Xerces you are referring to is in https://github.com/orbeon/xerces-xml. This is a port of Xerces to Scala for running Orbeon Forms in the JavaScript environment. It's marked as SNAPSHOT for lack of a better release, but indeed it has been pretty stable so we could move to a final version number.

But the sources of this version is much older than the code used in the new versions.
The changes have not been committed for a long time and only its package has been placed in the library folder for Scala 12.

**Comment by ebruchez** [comment]
> But the sources of this version is much older than the code used in the new versions.
> The changes have not been committed for a long time and only its package has been placed in the library folder for Scala 12.

What do you mean by "the library folder for Scala 12"? Which file(s) are you referring to? What are "the new versions"? Please be specific.

**Comment by Saadati** [comment]
> > But the sources of this version is much older than the code used in the new versions.
> > The changes have not been committed for a long time and only its package has been placed in the library folder for Scala 12.
> 
> What do you mean by "the library folder for Scala 12"? Which file(s) are you referring to? What are "the new versions"? Please be specific.

Sources of xerces-2.12-orbeon.jar in lib folder is missing

**Comment by ebruchez** [comment]
Got it. See this:

https://github.com/orbeon/xerces2-j/commits/Xerces-J_2_12_0-orbeon

**Comment by ebruchez** [comment]
See also  https://github.com/orbeon/orbeon-forms/issues/4139#issuecomment-517490523

**Comment by Saadati** [comment]
> Got it. See this:
> 
> https://github.com/orbeon/xerces2-j/commits/Xerces-J_2_12_0-orbeon

Thank you very much. I was wrong.
I didn't know the relation between these two (https://github.com/orbeon/xerces2-j/commits/Xerces-J_2_12_0-orbeon,  https://github.com/orbeon/xerces-xml).
But still, the repository https://github.com/orbeon/xerces-xml is not the latest version (2.11.0.11-SNAPSHOT) used in orbeon and is older.

**Comment by ebruchez** [comment]
No problem.

The repository https://github.com/orbeon/xerces-xml is up to date for the JS version of Xerces we are usinng.
