### ISSUE TITLE
File upload progress bar not showing progress with large files

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#6666]
Reproducing this issue on both the demo server and locally. Strangely, the progress bar updates correctly when uploading a 1 MB file with throttling set to Slow 4G, but it does not move when uploading a 95 MB file, whether without throttling on the demo server or with throttling set to Fast 4G locally.

- 1MB file: `dd if=/dev/zero of=1mb_file bs=1m count=1`
- 95 MB file: `dd if=/dev/zero of=100mb_file bs=1m count=95`

[+1 from customer](https://3.basecamp.com/3600924/buckets/5085006/messages/8097523492)

**Comment by ebruchez** [comment]
With the 100 MB file, we are getting update requests with the size uploaded, and it correctly increases.

```xml
<xxf:event-response xmlns:xxf="http://orbeon.org/oxf/xml/xforms">
  <xxf:action>
    <xxf:control-values>
      <xxf:control id="section-1-section≡grid-1-grid≡control-1-control≡xf-upload"
                   progress-state="started"
                   progress-received="6110847"
                   progress-expected="99615109"/>
    </xxf:control-values>
  </xxf:action>
</xxf:event-response>
```
