### ISSUE TITLE
Dynamic Dropdown (`fr:databound-select1`, `databound-select1.xbl`) shows empty

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#6667]
Add a Dynamic Dropdown to a form, test. By default, it should show a list of countries, but the dropdown is empty.

[+1 from customer](https://3.basecamp.com/3600924/buckets/17077193/messages/8088147557)

**Comment by avernet** [comment]
[+1 from customer](https://3.basecamp.com/3600924/buckets/18345583/messages/4832256872)

**Comment by ebruchez** [comment]
Workaround for #6443 forgot to include `xxbl:scope="outer"`.
