### ISSUE TITLE
"Cannot read properties of null (reading 'classList')" while removing iteration

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#6679]
I can reproduce this in 2023.1.5.2 (on demo) and on master.

https://github.com/user-attachments/assets/d2836b6a-202e-461a-8a97-3a282f9f9356

**Comment by ebruchez** [comment]
Curiously I don't repro this on master.I'll try with the next 2023.1 build.

**Comment by ebruchez** [comment]
With a build, it happens if I add, remove, then add, and remove a second time.

**Comment by ebruchez** [comment]
This is similar to #6446, but that fix is present on 2023.1-pe.

**Comment by ebruchez** [comment]
I reproduce on `master` too with the XForms Inspector disabled.

**Comment by ebruchez** [comment]
I commited a fix so that the server doesn't tell the client to focus on the field if not relevant and visible. But somehow the server believes that a non-relevant/removed field has focus, which is a problem.
