### ISSUE TITLE
Safari: confirmation dialog background is partially transparent

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#6686]
<img width="556" alt="image" src="https://github.com/user-attachments/assets/bfdcd105-68c6-4fad-98b8-724d7a978bf2" />

**Comment by ebruchez** [comment]
This affects all dialogs, including in Form Builder, so it's important to fix it.

**Comment by avernet** [comment]
Reopening as the fix is causing issues on Chrome with the dialog's background coverage.
