### ISSUE TITLE
Consider using Bootstrap's grid to implement fr:grid

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#70]
With [Bootstrap](http://twitter.github.com/bootstrap/), we could get rid of tables (which bother some customers, for ideological or accessibility reasons) and provide a responsive design that works better on mobile devices.

**Comment by ebruchez** [comment]
We might not absolutely need to move to Bootstrap 3.

**Comment by johnhwhite** [comment]
I agree, it's not necessary to get to Bootstrap 3 to do responsive. And I like the idea of just using tables for grids with rowspan.

**Comment by avernet** [comment]
Isn't necessary, or even help, for responsive design (#2146), so not planning this for 4.10.

**Comment by ebruchez** [comment]
Won't fix, closing.
