### ISSUE TITLE
Support minimizing the "above the baseline" JavaScript files

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#841]
Right now we only minify the "below the baseline" JavaScript files, and link to the JavaScript files and their corresponding minified version is "hardcoded" in [`XFormsFeatures.java`](https://github.com/orbeon/orbeon-forms/blob/master/src/java/org/orbeon/oxf/xforms/processor/XFormsFeatures.java).

**Comment by ebruchez** [comment]
Marking as duplicate of #2328.
