### ISSUE TITLE
`label` for boolean field shows before the `input`

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#854]
As in the following screenshot, from `http://localhost:8080/orbeon/fr/orbeon/controls/new`. But WCAG 2.0 wants to see the [label after the input][1]. I am not sure what is the best way to solve this.

![Screen Shot 2013-02-27 at 5 30 35 PM](https://f.cloud.github.com/assets/106961/203766/4830c3bc-8147-11e2-8b37-8be173e4f148.png)

  [1]: http://www.w3.org/TR/WCAG20-TECHS/H44.html

**Comment by ebruchez** [comment]
@avernet entered a newer bug for this, #2218. Closing this one as duplicate.
