### ISSUE TITLE
3 issues with Fields Date control

### ISSUE THREAD

**Issue by apergy** [orbeon/orbeon-forms#912]
There are a number of small bugs with the following control:
![Screen Shot 2013-04-02 at 15 06 59](https://f.cloud.github.com/assets/864846/328584/a11e7dd6-9b9e-11e2-928d-73cf57ba4715.png)

1. A user must click directly on the image, otherwise the control text inputs are not correctly filled.
    * If you click outside the calendar image, it still appears - but incorrectly fills a single text input with a full date string - strangely, in the format configured.
2. When in IE8 - selecting a date causes a JS error (Placeholder.js - ln 29 chr 12)
3. When configuring Orbeon for UK date formats, it ignores the format set:
    * ```<property as="xs:string" name="oxf.xforms.format.input.date" value="[D01]/[M01]/[Y]"/>```
    * Retains the American default format

**Comment by ebruchez** [comment]
- Issue 1 above: appears fixed now. See also #2628.
- Issue 2 above: probably fixed now, and anyway IE8 is on the wane.

.So closing this.
