### ISSUE TITLE
Ability to reorder roles in the permissions dialog

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#918]
Currently, the permission dialog doesn't enable form authors to easily change the order of roles. When done, order should of course be kept as well (issue #917).

![Screen Shot 2013-04-05 at 10 32 10 AM](https://f.cloud.github.com/assets/106961/345099/c5bb85ba-9e16-11e2-8438-9aa340f22563.png)

**Comment by ebruchez** [comment]
Couldn't stand it anymore so just did it by switching to the standard `fr:grid` component.

![](http://doc.orbeon.com/form-builder/images/permissions-dialog.png)
