### ISSUE TITLE
Better way to control buttons visibility/readonlyness

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#940]
The buttons could have an associated XPath expression or function to determine this.

See also #935, #937, #938.

**Comment by acspike** [comment]
[From Twitter](https://twitter.com/orbeon/status/569636982210498560)

Can you give any additional pointers to how this could be implemented?

**Comment by avernet** [comment]
@acspike We're looking into it, and will most likely follow-up here with more details on how this could be implemented.

**Comment by ebruchez** [comment]
Suggestions from @avernet:

- "once we can use XPath to determine whether to show a button, you'll also be able to check on the page mode (new, edit, ...)"
- "get rid of the `oxf.fr.detail.buttons.view.*.*` property, which does something similar to what you need, just for view page"

**Comment by ebruchez** [comment]
What we have right now related to buttons:

- `oxf.fr.detail.buttons.*.*`: list of buttons to show on detail page
- `oxf.fr.detail.buttons.view.*.*`: list of buttons to show on detail page in view mode
- `oxf.fr.detail.buttons.inner.*.*`: list of buttons to show on detail page inside wizard
- `oxf.fr.resource.*.*.$lang.buttons.$name`: set/override button label
- `oxf.fr.detail.process.$name.*.*`: associate a process to a button

We would like to add:

- a way to control whether the button is visible or not
- maybe: a way to control whether the button is enabled or not

**Comment by ebruchez** [comment]
Tasks:

- [ ] update `fr:process-button` (or callers?) to use `visible` property
- [ ] update PDF button
- [ ] change `fr:process-button` uses of `ref` to use the `visible` property
- [ ] check `inner` works too
- [ ] doc
  - [ ] new properties
  - [ ] deprecate use of `view` property

*NOTE: We might not do `enabled` right now.*

**Comment by acspike** [comment]
#1619 seems related also.

**Comment by ebruchez** [comment]
@acspike Yes, #1619 could also be addressed by fixing #940 and having XPath functions to get the current permissions. #940 seems a bit more general.

**Comment by acspike** [comment]
Where in the source would most of this work happen? I'm thinking `src/resources/apps/fr/components/` but where else?

Do the properties (e.g. `oxf.fr.detail.buttons.visible.*.*`) need to include a button name also?

**Comment by ebruchez** [comment]
@acspike Possibly within `process-button.xbl`. We have to be able to say which button is affected, so yes, good point, a button name is needed too!

**Comment by acspike** [comment]
What's the actual mechanism by which buttons should be hidden or disabled (i.e. how would it look in the code)?

**Comment by ebruchez** [comment]
For visibility, there is the good old trick of writing things like:

```xml
<fr:process-button ref=".[XPath condition here]">
```

In [`view.xsl`](https://github.com/orbeon/orbeon-forms/blob/1050b4c6eedb0cf94a3052de098e22c6816ac38c/src/resources/apps/fr/components/view.xsl#L634) there is already some crazy logic to make the button point to one or another node.

**Comment by acspike** [comment]
So visibility needs to be controlled from the caller? Is it possible from inside process-button.xbl?

When I tried `<xf:trigger ref="false()">` in process-button.xbl it appeard to disable the buttons. Does that make sense? Is there a better way?

**Comment by ebruchez** [comment]
I think it would be slightly better if `fr:process-button` handles its own visibility. On the other hand, that means `fr:process-button` would still be a little bit alive even when not shown: it would be a relevant control hiding its own content. But that's probably not be a real issue.

**Comment by avernet** [comment]
This would be useful for the wizard mode, where in certain cases, it would be preferable not to show certain buttons, e.g. *Submit*, until users went through all the steps.

[+1 from community](http://discuss.orbeon.com/disable-control-button-td4659813.html)

**Comment by acspike** [comment]
Make that +2. This came up in an internal discussion yesterday.

**Comment by avernet** [comment]
[+1 from community](http://discuss.orbeon.com/disable-control-button-td4659813.html#a4659948)

**Comment by bsdang** [comment]
+1

**Comment by avernet** [comment]
[+1 from community](http://stackoverflow.com/questions/35058268/is-it-possible-in-orben-to-hide-or-disable-the-send-button-until-a-form-is-fin) so we can hide or disabled the Send button until the last step of the wizard

**Comment by theelectricwiz** [comment]
[+1](http://blog.orbeon.com/2006/05/xforms-tip-enabling-and-disabling-your_23.html#comment-2495542898)

**Comment by jorgehortelano** [comment]
In Orbeon version 2016.1, in the [documentation page](http://blog.orbeon.com/2016/04/orbeon-forms-20161.html) is written:

> Wizard improvements. The wizard's table of contents indicates pages with errors more clearly. In validated mode, pages which cannot be navigated to are also indicated better. **Last but not least, in validated mode, Save, Submit, Send, and other buttons which appear within the wizard only show when the user reaches the last page of the wizard**. Finally, we made a few cosmetic improvements as well.

That it means that this is already solved?

**Comment by ebruchez** [comment]
@jorgehortelano Unfortunately not, it's only a very narrow aspect of showing/hiding buttons in the context of the wizard. The more general mechanism remains to be implemented.

**Comment by jorgehortelano** [comment]
Ok, we will wait for it.

**Comment by ebruchez** [comment]
For reference, the improvement mentioned in the release notes is covered by #2253.

**Comment by ebruchez** [comment]
We probably do not need to control the visibility by inner vs. not inner (and we are not sure we want to keep the distinction between the two buttons locations anyway). So we would have:

- `oxf.fr.detail.button.$name.visible.*.*`
- `oxf.fr.detail.button.$name.enabled.*.*`

**Comment by ebruchez** [comment]
- [ ] doc
- [ ] if possible, migrate custom, hardcoded visibility rules to using new properties

**Comment by ebruchez** [comment]
[Documented](http://doc.orbeon.com/configuration/properties/form-runner.html#hiding-and-disabling-buttons)

**Comment by aquilesgeo** [comment]
Exist some method to make a manual submit()
I have a toolbar in frame A, and the form in frame B, so, I need set a submit button in the frame A, and make the Orbeon.something.submit() to the frame B. Is possible?

**Comment by avernet** [comment]
@aquilesgeo I imagine you could, in your own JavaScript running in frame A, call [`click()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/click) on the button part of a form produced by Orbeon Forms in frame B. And note that there is nothing specific to Orbeon Forms in this. Also, for this to work, you'll need both frames to be loaded from the same server.
