### ISSUE TITLE
Wizard: errors in section template not highlighted in TOC

### ISSUE THREAD

**Issue by avernet** [orbeon/orbeon-forms#943]
- add `<property as="xs:string"  name="oxf.fr.detail.view.appearance.*.*" value="wizard"/>`
- FB: create form with section template with required field
- FR: load new page, hit save, section with error isn't highlighted in the TOC

![Screen Shot 2013-04-16 at 12 42 52 PM](https://f.cloud.github.com/assets/106961/387956/e1132b96-a6cd-11e2-8099-d6abc15de264.png)

**Comment by ebruchez** [comment]
Fixed with #2066. We now use the error summary's knowledge of invalid sections to highlight them in the wizard.
