### ISSUE TITLE
FB: Ability to set size of grid columns individually

### ISSUE THREAD

**Issue by ebruchez** [orbeon/orbeon-forms#991]
Ideally, via grabbing column separators.

**Comment by ebruchez** [comment]
[+1 from evaluator](https://mail.google.com/mail/u/0/#inbox/15add1be74ff8a4e)

**Comment by ebruchez** [comment]
Or, see if 12-column layout would solve this too (#2738_.

**Comment by avernet** [comment]
Closing, as we've implemented the 12-column layout (#2738) in 2017.2.
